### ISSUE TITLE
Unable to launch using shortcut with the new stub exe

### ISSUE THREAD

**Issue by headswe** [Squirrel/Squirrel.Windows#1008]
C:\Users\XXX\AppData\Local\MyApp\MyApp.exe fails to launch and does not do anything.

The app can be launched fine via its original exe file under C:\Users\XXX\AppData\Local\MyApp\app-1.0.0

**Comment by steel9** [comment]
I think this is because the DLL files for the application are located in the "app-1.0.0" folder, but when the application launches from the "MyApp" folder, it can't find the DLL files and crashes.
