### ISSUE TITLE
Installation folder uniqueness

### ISSUE THREAD

**Issue by Slion** [Squirrel/Squirrel.Windows#1021]
Squirrel uses the [NuGet package metadata Id](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/nuget-package-metadata.md) to define the installation folder which looks like: `%LocalAppData%\MyAppId`

However it would be nice to have a scheme closer to ClickOnce which looks like:
`%LocalAppData%\MyCompany\MyAppId`

**Comment by paulcbetts** [comment]
Why?

**Comment by Slion** [comment]
To avoid path conflicts. There are a lot of apps and folders being installed in %LocalAppData% these days. 
It's just a neat way to organize your deployments which should reduce risks of path conflicts without resorting to UIDs as folder names. You may argue that one could happen company name to the app id but sub-folders are nicer. It's convenient to have all your company's apps installed below the same folder.

**Comment by paulcbetts** [comment]
I don't think we're going to do this, sorry.

**Comment by Slion** [comment]
Too bad. Is the app id used for anything else than defining the installation folder?

**Comment by Slion** [comment]
It's also most certainly trivial to implement without breaking the current behavior. Just check if a 'CompanyName' or 'ParentDirectory' metadata is present and use it if any.
