### ISSUE TITLE
0-bytes executable stub created at install time (i.e. broken shortcuts)

### ISSUE THREAD

**Issue by christianrondeau** [Squirrel/Squirrel.Windows#1026]
I am using Squirrel 1.6.0 (same issue with 1.5.2) in GoToWindow (see https://github.com/christianrondeau/GoToWindow/releases/tag/v0.7.0 to see for yourself).

The software installs and launches correctly, but the links in the Start menu and the Desktop are broken. The executable stub (GoToWindow.exe) actually exists, but it's a zero-bytes file. It doesn't seem to be in the .msi if I unzip it. My GoToWindow.exe is a wpf application and I confirmed it's using subsystem 2:

    > dumpbin.exe -headers GoToWindow.exe | grep subsystem
    6.00 subsystem version
    2 subsystem (Windows GUI)

I'm invoking There are no errors in the build log, nor in the install log. It appears fine in Program Files. I'm executing it like this: `&($Squirrel) -g $SetupLoadingGif --releasify $NuPkgPath -i $SetupIcon -baseUrl https://github.com/christianrondeau/GoToWindow/releases/download/v$Version/`

You can try the software here: https://github.com/christianrondeau/GoToWindow/releases/tag/v0.7.0
You can look at the build script here: https://github.com/christianrondeau/GoToWindow/blob/master/Build.ps1
You can look at the nuspec here: https://github.com/christianrondeau/GoToWindow/blob/master/GoToWindow.nuspec
Or simply clone and run Build.ps1 and see for yourself: https://github.com/christianrondeau/GoToWindow

I'm simply unable to build an update. Any clue on where to go next? Is there a secret log somewhere I'm missing, or something I *can* do wrong that would silently generate a zero-byte executable? I really tried :|

**Comment by paulcbetts** [comment]
Hm, maybe a bug with rcedit or WriteZipToFile? Also, are you possibly using some AV solution that sucks?

**Comment by christianrondeau** [comment]
You were right, it seems the Avast anti-virus hooked into the build process and screwed up the generated file.

Even though that solves it for me, a small sanity check (i.e. confirm that the file exists and is not a zero-sized file) would be helpful if me (or someone else) gets the same thing. When I tested the package before deploying it, I verified the install, played with the program and uninstalled it. I did not check desktop icons :| That's easy to overlook.

And if the file is missing, you could suggest "Your AV sucks. Disable it temporarily, or install another" :)

**Comment by paulcbetts** [comment]
I would take that PR but the problem is that AV doesn't do anything predictable or repeatable, it is constantly changing and breaking random things in random ways
