### ISSUE TITLE
Restrict updates on metered connections

### ISSUE THREAD

**Issue by MatthewSteeples** [Squirrel/Squirrel.Windows#1029]
Is it possible to restrict the download of updates over metered connections? I believe there are APIs for getting this information through C++, but I don't know whether this ties in with wanting to keep the installer logic simple

**Comment by paulcbetts** [comment]
Your app decides when updates are downloaded, just check for metered connections before you run the update

**Comment by MatthewSteeples** [comment]
That makes sense I suppose, I was just hoping as a user I could override that
