### ISSUE TITLE
My setup.exe begins to be a threat for Windows Deffender

### ISSUE THREAD

**Issue by LightCZ** [Squirrel/Squirrel.Windows#1036]
Suddenly when I release new version of our application Windows Defender and suddenly even Kaspersky begins to mark this as a threat and wont allow users to download setup.exe. Immediately it is deleted.

When you try to download app.x.x.x.FULL or app.x.x.x.DELTA files also produced with squirell  or even source nuget package it works flawlessly and there is no AntiVirus messages.

So this has to be something in squirell way of making installler. We were using unsigned version - we already ordered a certificate for future signing. 

Is there some kind of temporary workaround for this?

Ok this started to be a huge problem suddenly. I even tried uploading nupkg (source of squirrel framework) to virustotal and even this nupkg is marked as a threat with some antiviruses:

Results can be seen here:
https://www.virustotal.com/en/file/cbecc0bd8b1ed0eb2a46727ea1e22ab91621326057e0f141007ab04a660925e9/analysis/1496180648/

**Comment by shiftkey** [comment]
> Is there some kind of temporary workaround for this?

Not without disabling the AntiVirus software.

I've had several incidents over the years where AV products generate false positives for things for components that previously passed and users end up reporting it to us. We generally have to chase the AV companies for more information and ultimately updating their AV detection closes out the false positives, but it's annoying for users who have to wait for it to be resolved.

I uploaded the latest Squirrel.Windows zip to VirusTotal again to see what it looks like today and it still has two AV products which claim to find issues with it:

https://www.virustotal.com/gui/file/64a61fea22f9780fdbc834aa0a593305b171f6682fc340cdb25d11edb0c81b1c/detection

This is all really beyond the project's control, but if someone spots something malicious in the bits distributed by Squirrel I'd love to hear about it.
