### ISSUE TITLE
.NET 4.7 Compattableity

### ISSUE THREAD

**Issue by flaxj** [Squirrel/Squirrel.Windows#1040]
Is Squirrel compactable with the latest .NET Framework (.NET 4.7)?

**Comment by lukeskinner** [comment]
You can use Squirrel with .NET 4.7. But it is not able to install .NET 4.7 automatically when you run the installer. 

You will need to manually install .NET 4.7 first on each machine or wait until someone submits a PR which updates https://github.com/Squirrel/Squirrel.Windows/pull/940 with 4.7 support.

**Comment by Thieum** [comment]
fixed by #1055
