### ISSUE TITLE
Scoped npm packages are not working as @ is read as %40

### ISSUE THREAD

**Issue by robertohuertasm** [Squirrel/Squirrel.Windows#1044]
I've upgraded to the latest version but unfortunately is making all my projects crash due to some failure when dealing with `@` characters in folders.

I suspect it has to do with some escaping and unescaping features being removed in `ReleasePackage.cs` but I'm not sure of it. I'm digging into it but this is really a big issue as everybody using scoped packages is going to be unable to use the generated application.

The installer gets generated but when you try to run the `.exe` you'll get warned that some packages are missing.

Take a look at the `node_modules` inside the `setup.exe`

![image](https://cloud.githubusercontent.com/assets/696981/26827739/da5f5dbc-4abe-11e7-9d32-0d593ac00d39.png)

I can confirm that the package is being correctly generated before using the installer.

**Comment by paulcbetts** [comment]
Thanks for the report, I'll be having a look at this tomorrow

**Comment by robertohuertasm** [comment]
You're welcome @paulcbetts. For what I've been able to see [this commit introduced the issue](https://github.com/Squirrel/Squirrel.Windows/commit/2c35a79abbc4a7a9f5aebbb843b281adeab42166#diff-2637002ddbb1dfa2c58f1536d1caff6eR182).

For some reason, it seems that you decided to get rid of the functionality unescaping the entries of the nuget package entries.

**Comment by paulcbetts** [comment]
@robertohuertasm Yeah, so the plan was that because we weren't using NuGet for any zipping/unzipping at all, we could just ditch this whole plan and not escape / unescape anything
