### ISSUE TITLE
Stub executable not copied to root directory after fresh install

### ISSUE THREAD

**Issue by peters** [Squirrel/Squirrel.Windows#1045]
Upon a fresh install stub executable is not copied to application root directory.

Repro:

1. Use latest 1.7.0 version.
2. Install any type of squirrel application, e.g a `sample` application.
3. Stub executable is present in `%LOCALAPPDATA%\sampleapp\app-X.X.X\sample_ExecutionStub.exe`
4. Stub executable **is not** present in `%LOCALAPPDATA%\sampleapp\sample.exe`

This is bad because we rely on the stub executable being present in the root folder in order to avoid Windows firewall prompt every time an application is updated.

The reason being that all our shortcuts point to the stub executable in order to avoid `Windows firewall` issue after an application is updated.

**Comment by paulcbetts** [comment]
Thanks for the report, I'll have a look at this tomorrow

**Comment by bennor** [comment]
Thanks for fixing this. Started using Squirrel in anger this week and thought it was something I was doing wrong. 🥇

**Comment by paulcbetts** [comment]
sry sry computers are hard

**Comment by bennor** [comment]
I'm just glad the problem wasn't me being too dumb to use Squirrel 😂

**Comment by peters** [comment]
@paulcbetts Works like a charm :)
