### ISSUE TITLE
Squirrel lunching all executables after install

### ISSUE THREAD

**Issue by GorelH** [Squirrel/Squirrel.Windows#1046]
Our app have multiples exe, with main exe to be lunched and create shortcut point to.
But squirrel is lunching all the exe at once after install.
Is there a way to specify a main exe to be lunched ??
Im using latest release 1.7.0
Thanks

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md
