### ISSUE TITLE
Update to a specific version number with Squirrel 1.5.2?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1058]
Hello,

We're using Squirrel 1.5.2 and we want our application to update up to a specific version number. For example, in our releases folder we have packages (full & delta) for 1.0.0, 1.0.1, 1.0.2, and 1.0.3 updates. Is there any way we can force Squirrel to update up to 1.0.1 although we have 1.0.2 and 1.0.3 updates uploaded to our releases folder?

Thanks in advance.

Sissi Konsta

**Comment by paulcbetts** [comment]
@SissiKonsta 

1. Download RELEASES yourself in your own code
2. Filter out the entries you don't like, then save it to a temp folder
3. Download all of the files in the RELEASES file to the same temp folder
4. Point Squirrel to that folder

**Comment by SissiKonsta** [comment]
@paulcbetts first of all thank you for your reply. I just wanted to clarify some things. Let me give you an example. Let's say that in our releases folder we have packages (full & delta) for 1.0.0, 1.0.1, 1.0.2, 1.0.3, and 1.0.4 updates and we have installed version 1.0.1. We want to go to  update 1.0.3. So, according to what you wrote above, we need to edit the RELEASES file so that the last entry is for update 1.0.3. Do we need to have entries for both full and delta packages in the RELEASES file? And what about the files we have to download? Should we download both full and deltas? Finally, in the RELEASES file we have entries for older versions too. Do we also have to download the files for older versions in the temp folder?

**Comment by SissiKonsta** [comment]
@paulcbetts is there any update regarding my questions above? Thanks.

**Comment by paulcbetts** [comment]
Just have a single entry, the full package
