### ISSUE TITLE
Found a Bug in Squirrel.exe, maybe ;)

### ISSUE THREAD

**Issue by hs-hub-world** [Squirrel/Squirrel.Windows#1063]
Looks like when there are more than one  .EXE file's in the Nuget Package (*.nupkg) the squirrel.exe  --releasify will not iterate through the correct .EXE files and it will replicate the single .EXE based on the total number of .exe files are in the package. See attached image. Notice the size.  Both "ExectionStub.exe" are the same size. And obviously, the file size does not seem to match for any of the .EXE files...

(Squirrel.Windows Version: 1.7.5)

![image](https://user-images.githubusercontent.com/20629911/27249471-3c5ca920-52cb-11e7-8665-27f9270e4016.png)

**Comment by paulcbetts** [comment]
Nope, this is correct. The execution stub isn't a copy of your executable, it's a stub, that forwards to the correct version of the executable.
