### ISSUE TITLE
SquirrelSetup.log not being created/updated

### ISSUE THREAD

**Issue by guyfletch** [Squirrel/Squirrel.Windows#1070]
On both squirrel.windows.1.6.0 I'm running squirrel --releasify and getting nothing in SquirrelSetup.log.

This may be linked to the fact Squirrel isn't creating a .exe file, but I can't tell because it fails silently.

**Comment by Thieum** [comment]
@guyfletch is it an issue you are still experiencing with the latest version of Squirrel?

**Comment by guyfletch** [comment]
Not currently using squirrel, so I don't know.

**Comment by Thieum** [comment]
@shiftkey this can be closed.
