### ISSUE TITLE
--checkInstall aborting an installation when application is not actually installed

### ISSUE THREAD

**Issue by leekevinyg** [Squirrel/Squirrel.Windows#1077]
It looks like `--checkInstall` will check for the directory `%LocalAppData%\PKGID` and abort an installation if the directory is there. However, since local app data isn't removed on uninstall, this can result in an installation not running if a user has previously uninstalled the app. Is this expected?

**Comment by paulcbetts** [comment]
Yes, this is how machine-wide install tells whether an individual user didn't want the app. If this didn't happen, then whenever a user on a machine-wide install removed the app, they would immediately get it reinstalled on next boot
