### ISSUE TITLE
App using Squirrel installer randomly disappear from Windows 7 machines

### ISSUE THREAD

**Issue by spagetthicoder** [Squirrel/Squirrel.Windows#1079]
We are using Squirrel installers for a customer app and the application randomly disappear from the user machines without anyone initiating Uninstall. Everything is being removed - App, Desktop Shortcut and Uninstaller from Programs&Features. There is no Firewall/Malware/AV tools which are recognizing the app as unwanted software and therefore removing it. 

Follow up question - Is there plan for implementing "Are you sure you want to remove this application?" dialog box when someone tries to uninstall the app from Programs&Features?

**Comment by hs-hub-world** [comment]
Are you installing use the Setup.exe or the MSI -?

Squrrel will not randomly uninstall your app.  Something else is uninstalled your app.  I would suggest that you review Windows Event Viewer, also in your app use the 'OnAppUninstall' event to write a log somewhere so you can get little more information when/why it's happening. 
 Could it be MS Windows Security running in the background, especially if it's windows 10.
 Could be something in windows Task Scheduler -?

**Comment by swirly** [comment]
You certainly are in a production environment with roaming profiles
roaming profiles are kept on the server
local part of profile is usually deleted after some period of inactivity of a user on the computer
As squirrel installs the program in the local Appdata, it is clearly deleted by the system
This is normal behavior on a well managed widows network environment. 
Squirrel installer is just made for personnal user but behaves very badly on managed networks

**Comment by paulcbetts** [comment]
> This is normal behavior on a well managed widows network environment.

Uhhhh I worked for Microsoft and my machines were managed by MSIT, undoubtedly the most well-managed Windows network environment in the world, and they for sure didn't randomly delete %LocalAppData%

**Comment by swirly** [comment]
@paulcbetts you were working on a one station/one person basis undoubtly. On a large network were there are many people (100+) using the same computer, local profile are to be deleted with the delprof Microsoft provided tool in order not to leave local datas too long on computer.
So, only roaming profil is conserved (that's what roaming profile is made for)
University and College don't have the same kind of needs nor the same management as Industry do.

**Comment by paulcbetts** [comment]
If you're installing to these kinds of machines, the MSI file that Squirrel generates will work much better then, even if you're clearing LocalAppData, the app will reinstall itself as users log in.

**Comment by swirly** [comment]
No. 
On those kind of machines, Squireel install the app in each profil. In a room for free use, in a few day, 100 students may use the machine. For atom for exemple, 300M are installed in local profil for each student. With old disk, can be quite long. 
With 100+ student, you use 30G for only ONE application, that install for each student. If you have two or three squirrel based application in a university (atom and github desktop for example), disk are full just with those application and startup is very long.
Not having a system wide installer is a major limitation for this kind of environment. Not to say it make the use of such application impossible.
I personnaly had to create a custom installer for Atom in a college but did not make so for the other applications. So they're not used.
