### ISSUE TITLE
How to uninstall a Squirrel application programmatically without using Squirrel dlls?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1083]
Hello,

I want to uninstall a Squirrel application without using Squirrel dlls. Basically, what I am trying to do is exactly what the right click -> Uninstall does in Programs and Features. Is this possible? If yes, how can I do that?

Thanks.

**Comment by hs-hub-world** [comment]
If I understand your question correctly you simply want to uninstall your application without using Squrrel or Add Remove Programs. 


You may use Powershell to query Registry to locate the uninstall command and execute it that way.  This probably would be the prefered method. you can easily integrate this in a C# if you want or batch file.

	$uninstallcommand=$(Get-ItemProperty HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\"<YOUR APP NAME>").QuietUninstallString

	Invoke-Expression "& $uninstallcommand"

**Comment by paulcbetts** [comment]
`%LocalAppData%\YOURAPP\Update.exe --uninstall .`
