### ISSUE TITLE
Is squirrel for me?

### ISSUE THREAD

**Issue by jdc20181** [Squirrel/Squirrel.Windows#1092]
I have been forced to find another installer solution, and I am having a hard time. I have used installshield for a long time, and the UI, and ease of deployment made it a great solution. I can not use the standard installer with VS it will not work with my app, saying things that are required aren't there for it to run. Meaning that the standard installer just isn't for me. 

Anyways, can someone explain this more to me, and if its ideal?

**Comment by hs-hub-world** [comment]
Watch this video:
https://channel9.msdn.com/Events/dotnetConf/2015/Squirrel-for-Windows-installing-NET-apps-the-way-it-should-be

Search for examples on google.

**Comment by jdc20181** [comment]
Couldn't find any examples, will keep looking.

**Comment by hs-hub-world** [comment]
Here you go:
http://developingdane.blogspot.com/2015/10/clickonce-squirrel-and-nuts.html
https://madstt.dk/squirrel-the-basic/

**Comment by jdc20181** [comment]
The links you provided is about as useful as wix documentation. No thanks, I will keep looking.

**Comment by hs-hub-world** [comment]
Here is a full sample application, does this help -?
https://github.com/DaneVinson/Nuts

**Comment by jdc20181** [comment]
Short answer no. Again, about as useful as Wix Documentation not impressed.

**Comment by lukeskinner** [comment]
I assume you've looked at the wiki? It covers what squirrel can do and then has separate pages about individual features. 

[Index of wiki](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/readme.md)

99% of the info I've ever needed has been from the wiki.
