### ISSUE TITLE
Installation with --silent and --machine

### ISSUE THREAD

**Issue by thismark1227** [Squirrel/Squirrel.Windows#1096]
Hi all,

I am new on Squirrel and used on WPF Product. My purpose is installing my application to all users and silently.

On Packaging, i disable msi installer.
`PM> Squirrel --releasify MyApp.1.0.0.nupkg --no-msi`

It is working fine separately.
`C:\Setup.exe --machine` **OR** `C:\Setup.exe --silent`

When i ran this,
`C:\Setup.exe --machine --silent`
It installed on %LocalAppData% and install silently.

Is there are any ways to install for all users and silently. Thanks.

**Comment by ralsu091** [comment]
You need to generate the MSI and run it. See here: https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/docs/using/machine-wide-installs.md

**Comment by thismark1227** [comment]
Thanks Ralsu,

I tried, it works. However, I would like to keep the publisher name and software name. Is it possible to configure it on MSI Installer?

Thanks.

**Comment by ralsu091** [comment]
@thismark1227 No problem! What publisher name and software name are you referring to? 
Do you have a screenshot?

**Comment by thismark1227** [comment]
@ralsu091 thank you for your reply, i tried to change the software name but not working.
![image](https://user-images.githubusercontent.com/5283565/28255435-654de480-6ae9-11e7-882a-3deb7c222e89.png)

And the MSI installed on C:\Program Files (x86)\Installer and named XXX.exe (XXX is the Id) which is another installer.

**Comment by ralsu091** [comment]
@thismark1227 Here is a link to the wiki which describes how Squirrel names things https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/naming.md

**Comment by thismark1227** [comment]
@ralsu091 Thank you!
