### ISSUE TITLE
Installation Should ask for some settings rather than assumptions

### ISSUE THREAD

**Issue by GeorgeWL** [Squirrel/Squirrel.Windows#1097]
For e.g.

[X] Add Shortcut to Desktop

Many users prefer a clean desktop and to have the shortcuts in the start bar.

[X] Installation location

Many users have multiple drives

Can't think of anything else atm.

**Comment by hs-hub-world** [comment]
I don't think ClickOnce asks for any settings either. The idea of this program is to deploy as quickly and as silently as possible. I am 100% sure %localappdata% path will always be there. No matter what their local drive letter is. And this program is designed specifically for non-admin execution. If you are trying to install system drivers or service this setup will not work for you, you can implement your own scripts around it but that is not the goal here with this app. 

Thanks
H

**Comment by paulcbetts** [comment]
Sorry! The single purpose of a Squirrel Setup.exe is to run your app, it will never ever do anything to get in the way of getting your app running on your users' computers as fast as absolutely possible.

**Comment by GeorgeWL** [comment]
But what of the default behaviour of making an assumption that every user wants a desktop shortcut?

There must be some way around that?

**Comment by paulcbetts** [comment]
@GeorgeWL This isn't a Squirrel.Windows forced behavior, this is entirely under the control of the developer who wrote the application

**Comment by GeorgeWL** [comment]
ah, they pointed me here from https://github.com/desktop/desktop/issues/2242 @paulcbetts 

Specifically
>As an aside, Desktop uses a library called [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows) to install itself. Getting a PR merged there would allow us to take advantage of it in this project.
