### ISSUE TITLE
Creating diffs for some files fails

### ISSUE THREAD

**Issue by joshaber** [Squirrel/Squirrel.Windows#1101]
This might be a relatively recently introduced bug.

We're trying to enable delta updates for GitHub Desktop (https://github.com/desktop/desktop/pull/2239). With Squirrel.Windows 1.5.2, it works. With Squirrel.Windows 1.7.6, an exception is thrown creating deltas for _some_ files:

```
DeltaPackageBuilder: We really couldn't create a delta for package.json: System.DivideByZeroException: Attempted to divide by zero.
   at Squirrel.Bsdiff.BinaryPatchUtility.Create(Byte[] oldData, Byte[] newData, Stream output)
   at Squirrel.DeltaPackageBuilder.createDeltaForSingleFile(FileInfo targetFile, DirectoryInfo workingDirectory, Dictionary`2 baseFileListing)
```

@Keboo mentioned hitting this same bug in https://github.com/Squirrel/Squirrel.Windows/pull/1087.

**Comment by paulcbetts** [comment]
I think we're just gonna revert all of these bsdiff changes, they're breaking stuff

**Comment by Thieum** [comment]
@joshaber are you still experiencing this issue with the latest version of Squirrel?

**Comment by shiftkey** [comment]
I'm tracking https://github.com/desktop/desktop/issues/5197 to upgrade our version of `electron-winstaller` (that uses Squirrel) and I'll report back if we still see this issue later on.
