### ISSUE TITLE
How to keep specific number of installed versions with Squirrel 1.7.5?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1107]
Hello,

We updated from Squirrel 1.5.2 to Squirrel 1.7.5 and now the installed versions for our application are more than 2. For example, we're installing version 1.0.0 and we make an update 1.0.1. The new update is being installed and now in the application's AppData folder we have 2 folders: app-1.0.0 and app-1.0.1. If we make another update, after the installation we have 3 folders in the application's AppData folder: app-1.0.0, app-1.0.1, and app-1.0.2 and so on. How can we say to Squirrel to keep a specific number of installed versions or to remove older ones?

Thanks.

**Comment by paulcbetts** [comment]
The number was upped to three to prevent a race condition - if you issue too many updates in a short timeframe (or if the user leaves the app running for a long time), you could end up removing yourself. If you end up with a *bunch* of older ones, please reopen this

**Comment by SissiKonsta** [comment]
@paulcbetts thanks for the quick reply. One last question: is there a way so that we set this number in our code?

**Comment by paulcbetts** [comment]
No, it's hard-coded at the moment

**Comment by SissiKonsta** [comment]
Ok. Thanks again.

**Comment by SissiKonsta** [comment]
Hello @paulcbetts. As you told me, I made a bunch of updates, 5 in the number, and it seems that I have 5 folders in the application's AppData folder instead of 3 as you've said yesterday. Why is this happening?

**Comment by ralsu091** [comment]
@SissiKonsta 
1- Use the latest Squirrel package (1.7.7)
2- Delete the content of C:\Users\YOUR_USERNAME\AppData\Local\SquirrelTemp
3- Release a new update to you app.
4- Update your app.
5- Verify that you only have to versions of your app.

**Comment by SissiKonsta** [comment]
@ralsu091 first of all thank you for your reply. 

It's necessary for me to use Squirrel 1.7.5 because otherwise my application does not work properly. So, is there anything I can do to keep only 2 or 3 folders in the application's AppData folder without changing Squirrel version?

**Comment by ralsu091** [comment]
@SissiKonsta This issue was fixed in 1.7.6 (https://github.com/Squirrel/Squirrel.Windows/issues/1024)
Perhaps you have to update the latest and try to figure out why your app is not working properly.

Thanks!
