### ISSUE TITLE
AVG detects trojan horse in signed setup.exe

### ISSUE THREAD

**Issue by rvoisin** [Squirrel/Squirrel.Windows#1113]
Latest release of squirrel.windows (1.7.7), AVG Cloudcare is the AV. 
Detects as 'Trojan horse SCGeneric4.BPUH'

Setup.exe is signed with a Digicert Code signing-key (not EV if that matters).

Helping me out prevents me from having to revert back to clickonce, nobody wants that.

**Comment by paulcbetts** [comment]
All we can do is recommend you report this as a false positive or uninstall AVG, sorry :(
