### ISSUE TITLE
NuGet global package cache support

### ISSUE THREAD

**Issue by mkosieradzki** [Squirrel/Squirrel.Windows#1114]
Hi,

I am trying to integrate squirrel with the new project system and I am having some problems:

I basically would like to have something like this:
MyExecutable.nupkg
MyLib1.nupkg
MyLib2.nupkg

Where none of this packages contains framework assemblies or 3rd party libraries, but they all depend on those libraries.

I would like to releasify MyExecutable.nupkg and I would expect Squirrel to find:
MyExecutable.nupkg in local folder
MyLib1.nupkg in local folder
MyLib2.nupkg in local folder
all 3rd party and framework dependencies in `$HOME\.nuget\packages` cache (which has a non-flat structure)

Does this make any sense?

**Comment by Thieum** [comment]
@mkosieradzki Squirrel only uses nupkg for the packaging capacity (zip file + metadata), not the overall architecture of nuget. Isolating dependencies would make everything far more complex for not much advantages (the delta compression already omits dependencies that didn't change)
It would be a mess to mix regular nuget nupkg with nupkg used by squirrel, as they have not the same usage.
