### ISSUE TITLE
Is it possible to add additional files to Setup.exe and/or create multiple Setup.exes?

### ISSUE THREAD

**Issue by bennor** [Squirrel/Squirrel.Windows#1117]
Here's the problem: I have an app that needs to point to one of 3 API instances (potentially more to come). I'd like to avoid making this user configurable, because it's potentially confusing to the user, and I don't want 3am phone calls if they screw it up.

The way I see it, I have these options:

1. Compile the API url setting into the app and releasify 3 times.
1. Add a configuration file that ships with the app and releasify 3 times.
1. Submit a PR that adds the ability for Releasify to create multiple `setup.exe` files (and MSIs, if necessary) that package a configuration file directly in each `setup.exe`. This would work because once this URL is set, it never needs to change. The different APIs are for a few clients of ours that have isolated instances of our app.

The first two of those I can do right now without too much effort, but they mean I'm building 3 copies of the app to change a URL. 

Does this sound like something you'd accept a PR for? Or can you think of any other way round this dilemma?

**Comment by paulcbetts** [comment]
You probably should do #2. Reason being is, what update URL are you gonna point these three different apps to? Since you only changed the initial installer, your config file is going to be only in v1 of your app, all the updates will have the wrong config file.

I assume this is for like, multiple clients yeah? Can you get the FQDN of their machine then use that to decide which API endpoint to use?

**Comment by bennor** [comment]
Looked at IP and FQDN resolution, but one of the clients with their own instance is a franchise and we're not dealing with the most tech savvy people so it might not be worth it.

I think #1 or #2 may be best though.

My thinking was that extra files in the installer would wind up one level up with update.exe, but it's probably a lot of work for no real benefit and you're right - the ability to change the url would be beneficial.

On another note, I'm pulling release files back from the S3 bucket before building with deltas. Do I actually need any more than the last full nupkg and the releases file?

**Comment by paulcbetts** [comment]
> Do I actually need any more than the last full nupkg and the releases file?

Nope

**Comment by paulcbetts** [comment]
The SyncReleases tool will do all the pulling for you, use it in a CI environment before you Releasify

**Comment by bennor** [comment]
Oh wow. Could have saved myself some time if I'd just RTFM.

Thanks!
