### ISSUE TITLE
squirrel 1.7.6  depend vs version?

### ISSUE THREAD

**Issue by liseen315** [Squirrel/Squirrel.Windows#1118]
i'm a newer for electron and i use windows-installer depend squirrel.windows. i see window-installer update squirrel.window to 1.7.6 but my project dist delta file so large.

i now vs studio 2015 for my develop project should i update vs studio to 2017?

sorry , my english so pool thankyou!

**Comment by paulcbetts** [comment]
If you use electron, you don't need to worry about VS. If your Delta files are large, rename them to zip, extract them, then use a tool like WinDirStat to see what is taking up space. Hope that helps!
