### ISSUE TITLE
Which .NET version do I need to reinstall to fix a broken SquirrelSetup?

### ISSUE THREAD

**Issue by ophilbinbriscoe** [Squirrel/Squirrel.Windows#1126]
An Atlassian team member recommended I re-install .NET in order to fix issues that SquirrelSetup was encountering while attempting to install SourceTree.

I have over a dozen versions/variants of .NET installed. I don't even know if uninstalling all of them is something I can do without breaking my OS and tons of apps? I've reached out to Atlassian on two occasions asking if they could specify which version/variant SquirrelSetup is using and have not heard anything back so I've come here as a last resort.

**Comment by paulcbetts** [comment]
Installing .Net 4.7 should cover you. Hope that helps.
