### ISSUE TITLE
.NET Error when running updater

### ISSUE THREAD

**Issue by Andrew-Archon** [Squirrel/Squirrel.Windows#1127]
I work for a company that uses Squirrel updater with our program.

I am trying to help a user who is seeing this .NET error come up when Updater.exe is running:

> ************** Exception Text ************** 
> System.InvalidCastException: Unable to cast COM object of type 'Microsoft.WindowsAPICodePack.Taskbar.CTaskbarList' to interface type 'Microsoft.WindowsAPICodePack.Taskbar.ITaskbarList4'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{C43DC798-95D1-4BEA-9030-BB99E2983A1A}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)). 
> at Microsoft.WindowsAPICodePack.Taskbar.TaskbarList.get_Instance() 
> at Squirrel.Update.AnimatedGifWindow.<>c__DisplayClass2_1.<ShowWindow>b__4(Object o, EventArgs e) 
> at System.Windows.Forms.Timer.OnTick(EventArgs e) 
> at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m) 
> at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

He has tried reinstalling our program, reinstalling .NET 4.5.2, running the .NET repair tool, and clicking continue in the error window, and it's not working.

I can't find any information about Microsoft.WindowsAPICodePack.Taskbar.CTaskbarList on google.

**Comment by paulcbetts** [comment]
This person should reinstall Windows, this means that one of Explorer's COM interfaces is somehow missing :(
