### ISSUE TITLE
Can't install various Squirrel based packages in enterprise windows

### ISSUE THREAD

**Issue by dcollis** [Squirrel/Squirrel.Windows#1128]
I am unable to install various applications that use Squirrel such as SourceTree and the GitHub client within our network.

I am prevented because we are using Windows Software Restriction Policies (https://technet.microsoft.com/en-us/library/hh831534(v=ws.11).aspx) to whitelist apps by certificate (or if necessary by location). This technology is similar to AppLocker (https://technet.microsoft.com/en-us/library/dd759117(v=ws.11).aspx - which is only available with Enterprise windows).

The peculiar bit is that running as Domain Admin is not a work around. Normally we allow a Domain Admin to do whatever they want despite the restriction policies, but for whatever reason this doesn't work for the Squirrel based installers.

For what it's worth, we have a diverse network with 100s of users running many different kinds of applications that have required a variety of workarounds over time, but we've never encountered one that couldn't be installed by elevating to Domain Admin. It seems that the installer starts but then loses the admin credentials because maybe it launches something after start as the currently logged in user?

We also like to use auto-deployment tools within our network (e.g. PDQ deploy), but I am unsure how to package an application that uses Squirrel like a more normal installation that a deployment tool can understand.

Finally, like a lot of organisations we don't want apps in AppData. Is there a way around this as well?

Thanks,
David

**Comment by ralsu091** [comment]
Unfortunately, if you don't want apps in AppData, then Squirrel cannot help you. The whole point of Squirrel is to install and update apps without requiring Elevation.

You can read more about how Squirrel installs and update apps here:
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/4-installing.md
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-process.md

**Comment by dcollis** [comment]
Sorry, that was a little misleading. We can run apps out of appdata as long as they are properly signed and whitelisted (though we prefer not to). So, for something like SourceTree or GitHub clients, we would be able to whitelist the cert of the exe that it runs under (I would presume).

The earlier part of my described issue relating to the installer itself is the important part:
The issue in this case is that we can't even install these apps as a domain admin on a users PC. Policy is preventing installation and I don't see an easy way of telling Windows that it is safe without whitelisting a lot of paths, which doesn't sound like the right approach to me.
It is something very particular to the Squirrel installer that is causing the problem, as elevating to Domain Admin on the users PC to perform the installation doesn't seem to work to avoid the AppLocker/Software Restriction Policies. I presume because a later part of the install then uses the logged in users credentials or something?
It looks like it does something with the c:\ProgramData folder as part of the early install process (before it starts writing into appdata).

Other people have mentioned this with regard to building an installer, but I don't see many talking about using installers created by others:
https://github.com/Squirrel/Squirrel.Windows/issues/843
https://github.com/Squirrel/Squirrel.Windows/issues/322 (this link mentions a workaround, but the link is dead)

On my separate point about deployment/appdata installs:
The point of these Microsoft technologies (AppLocker/Software Restriction Policy) is that you can whitelist apps that run on your network.
This combined with deployment tools mean that we never have to visit a users PC to install software, we just choose the app, choose the PC and click "deploy". A user can even install apps themselves through a company website that lists apps they can have.
We are able to wrap up just about every other installer out there that we've tried so far, but we aren't sure what we should do with Squirrel based installers. I suspect if we can solve the issue described above, it would solve this issue too.

**Comment by paulcbetts** [comment]
Squirrel usually generates an MSI file that can be used for exactly what you want, you should ask the vendor to publish this file.

**Comment by dcollis** [comment]
I couldn't see this for GitHub Desktop Client or SourceTree on the vendor websites, but I'll certainly ask, thanks.

It's worth noting that Software Restriction Policies are not just a big company thing, it's common to a lot of even small businesses that are using it as a way to prevent malware (particularly ransomware) infecting their machines. 

Perhaps you could help me try and diagnose why Squirrel installers get blocked by it? Perhaps I can find a way to whitelist it.
Are there steps to the installer that aren't described here: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/4-installing.md.
Does it perhaps try and copy something to a temp location first and try and then run something from there before installing to the locations mentioned?
What could be the reason for the next step of the installation losing the elevated credentials given to it by "run as administrator"?

**Comment by shiftkey** [comment]
@dcollis here is the MSI for GitHub Desktop: https://help.github.com/desktop-beta/guides/getting-started-with-github-desktop/about-the-github-desktop-windows-installer-package/

**Comment by dcollis** [comment]
Sorry, seems I'm a bit blind! Many thanks for that.

**Comment by paulcbetts** [comment]
> Perhaps you could help me try and diagnose why Squirrel installers get blocked by it? Perhaps I can find a way to whitelist it.

I would try to whitelist the certificate that the installer is signed with

> What could be the reason for the next step of the installation losing the elevated credentials given to it by "run as administrator"?

Squirrel does this by design, because it intentionally does _not_ want to be running under an elevated user, because then any files it writes can't be updated.

**Comment by dcollis** [comment]
I was just trying the installer cert whitelisting - i'm waiting for it to propagate to my machine at the moment. We normally whitelist the app rather than the installer, but in Squirrel's case I think this makes sense. I think as long as what it then launches under the non-elevated user is signed too, it will be fine. Will post back when I know.

**Comment by dcollis** [comment]
Sorry for slow reply, it wasn't as straightforward as I thought it would be and I haven't had time to look into it properly until now.

Certificate whitelisting has been partially successful for these 2 particular installers. I suspect it will work for most applications when Software Restrictions are in place. The GitHub app seems to be working now. SourceTree might with a bit of help from Atlassian.

The key is to check your event log for errors since a lot of the time the installer does nothing but hang when it tries to launch another exe with a different signature.

GitHub - I was able to install, but then the installer/application froze after the login step. The Squirrel Log showed no errors, and I tried it several times, with no change. Then suddenly on my 4th relaunch, everything seemed to work. The last line in the log before the "freeze" each time was "Program: Fetching update information, downloading from...blah". So, maybe something unrelated to the install and to do with the corporate proxy. Since it's now progressed beyond this point, I don't have a good answer.
Unfortunately, the app itself didn't work because git.exe was signed with a different cert. After whitelisting this as well, it seems to be working, until I found another exe signed with yet another cert. One more added to the white list and it seems to work.

SourceTree - this installer works initially, but coincidentally also gets stuck at the login stage, but for different reasons. This time it's because it's installer is trying to launch another exe that isn't signed at all (st-askpass-gcmpassthrough.exe). So, I'll ask Atlassian about this.

I'd say it's fair to say that this isn't Squirrel's fault, but I thought I would post in case others find their way back here.

**Comment by shiftkey** [comment]
> GitHub - I was able to install, but then the installer/application froze after the login step. The Squirrel Log showed no errors, and I tried it several times, with no change. Then suddenly on my 4th relaunch, everything seemed to work. The last line in the log before the "freeze" each time was "Program: Fetching update information, downloading from...blah". So, maybe something unrelated to the install and to do with the corporate proxy. 

If you can reproduce this please open an issue over on https://github.com/desktop/desktop - I'd love to understand more about this "freeze" as I think the Squirrel log message is a red herring.

**Comment by esQmo** [comment]
Having the same issue trying to install SourceTree or the GitHub desktop client! Getting "The update has crashed. on Windows 7 SP1. 

![image](https://user-images.githubusercontent.com/10319812/44124597-f2a3a078-a025-11e8-8d48-c2c849dcc757.png)

**Comment by esQmo** [comment]
![image](https://user-images.githubusercontent.com/10319812/44124659-35e6934a-a026-11e8-9e16-6a447bf12cbe.png)

**Comment by shiftkey** [comment]
@esQmo can you share what's in the file that "Open Setup Log" launches?

**Comment by paulcbetts** [comment]
@esQmo This is not an appropriate venue for user support, and you are making wild assumptions about whether your problem is the same as this one, please Email SourceTree for help.
