### ISSUE TITLE
Not buildable stage of product

### ISSUE THREAD

**Issue by vano101** [Squirrel/Squirrel.Windows#1133]
Hello
Is it even possible to compile run this product?
There is missing Core.vcxproj file. Is it possible to build without Core file? How much stub code should be removed in order to run this product?
Also, recommendation from README.md does work.
.\.NuGet\NuGet.exe restore 
command gets
Unable to find version '2.0.0' of package 'xunit.runners'.
Is there used xunit.runners actually?
Thanks.

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/docs/contributing/building-squirrel.md

**Comment by paulcbetts** [comment]
```sh
git submodule update --init --recursive       ## THIS IS THE PART YOU PROBABLY FORGOT
```
