### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fmeffert** [Squirrel/Squirrel.Windows#1140]
I saw a similar request in issue #1021

Our use case is as follows:
- Installation via Squirrel works wonderfully
- After installation we have to allow firewall exceptions to several executables in the install folder. This requires elevated privileges so we do it manually (one reason we chose Squirrel is that we did not need to elevate to install).
- Once we have everything set up, upgrading or downgrading makes us manually add exceptions for the same executables again, because the installation path has changed, again needing to elevate.

- This is for several dozen systems (luckily only internal) which do not have elevated privileges for the default industrial user accounts, so an admin needs to be present for each upgrade/installation to re-enter the firewall exceptions.

I do use the UpdateManager/Squirrel events functionality, so I could likely do some manual code to rename folders, then update shortcuts and settings to reflect the new location, but it would be wonderful if we could specify (via a command line option for ```squirrel --releasify``` maybe?) that the final folder name stays constant (i.e. instead of ```app-7.2.0``` it would just be ```app```).

Just a suggestion, might be useful for others

**Comment by paulcbetts** [comment]
Keeping executables in separate folders is necessary to be able to do upgrades without reboots, I think that Squirrel is probably not a good installer for this use-case, sorry.
