### ISSUE TITLE
Unity3D

### ISSUE THREAD

**Issue by imZEH** [Squirrel/Squirrel.Windows#1142]
Is it possible to use Squirrel as an installer and Update manager for Unity built application? 

Thank you

#newbieHERE

**Comment by fr4gles** [comment]
According to what I know about unity - it produces EXE file with data folder (correct me if i wrong) so you can easily use squirrel to produce install&update package. 

I advise you to get through wiki https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/readme.md before you create one to get started ;)

**Comment by imZEH** [comment]
The docs is using Visual studio to build the files. Is it possible to build outside the VS ?

Thanks for the response.

**Comment by fr4gles** [comment]
Thats right - you need to produce your files with Unity3D https://docs.unity3d.com/Manual/PublishingBuilds.html

**Comment by imZEH** [comment]
Ok thank you :)

**Comment by paulcbetts** [comment]
This will probably work though if you have trouble with delta packages because the file sizes are too big you probably need to disable them.
