### ISSUE TITLE
1.7.8 Update.exe does not work properly

### ISSUE THREAD

**Issue by gobne** [Squirrel/Squirrel.Windows#1144]
Hi, i'm developing a Qt app and using squirrel for relese/update process.

When my program calls: "Update.exe --checkForUpdate=/*some URL*/"

if there is a space in the update.exe path, Squirrel gives me an error on the --checkForUpdates option.

For example:
C:\Users\Name\appdata\Local\MyProgram\Update.exe --checkForUpdate=/*some URL*/  //WORKS WELL.

C:\Users\Name Surname\appdata\Local\MyProgram\Update.exe --checkForUpdate=/*some URL*/  //DOES NOT WORK

How can I resolve this kind of problem?
Thank you

**Comment by paulcbetts** [comment]
How about a call stack?

**Comment by Inzanit** [comment]
Looks like this has been abandoned, or at least not followed up. @gobne ? Maybe could be closed for the author to reopen if they have follow up info @shiftkey

**Comment by shiftkey** [comment]
Closing this out as it doesn't have enough information to investigate.

@gobne please open a new issue with more information if you'd like us to investigate further.
