### ISSUE TITLE
Taskbar icon during setup is the default .net icon

### ISSUE THREAD

**Issue by o11ie** [Squirrel/Squirrel.Windows#1146]
If _setup.exe_ is the output from the squirrel **releasify** command.

The _setup.exe_ file has been customised to include the desired icon.

However, while setup runs, the taskbar icon is the default .net winforms icon.

Is there a way to prevent the taskbar icon appearing or replace the icon with a custom icon?

**Comment by kjpacheco** [comment]
The icon in the taskbar is set in your code. 
In your solution, right click on your solution>Properties>Application.  In there, you will see a block for 'Resources' where you can specify your icon image.

**Comment by fr4gles** [comment]
o11ie is right. I faced same behaviour and it does nothing in common with application icon couse it is ok. Just setup icon during install is default winforms app icon.

**Comment by kjpacheco** [comment]
Sorry, I guess I misunderstood which icons we were talking about.
I haven't figured out how to change the setup.exe icon. For my project, I don't have a need to alter it from the default.  Once everything is installed, custom icon for my application.exe is there

**Comment by o11ie** [comment]
Thanks for the comments. I'm still having this issue though. Will I have to dig into the Squirrel source code to fix this? Functionally everything is perfect. It's just that professional touch that is missing.

**Comment by teh173** [comment]
I also see this issue. It looks like animated GIF window is showing this icon even though I don't have a GIF setup.

**Comment by o11ie** [comment]
Hi thanks for everyone's comments corroberating my issue. Does anyone know of a fix or work around, yet? Do these sorts of issue ever get added to the backlog?

**Comment by jonoomph** [comment]
Hello! Any updates on this? ... or known workarounds?

**Comment by Tobias-B-Besemer** [comment]
I found the following issue in the latest Atom and Git installer. Guess is (still) the same issue. Using Win7.

![2019-11-11 21_12_33-](https://user-images.githubusercontent.com/11881073/68686589-22ff8780-056c-11ea-8f9b-6db255e40c34.jpg)

![2019-11-08 03_31_07-](https://user-images.githubusercontent.com/11881073/68686608-2b57c280-056c-11ea-95cf-961e9b33df69.jpg)
