### ISSUE TITLE
Desktop App Converter Compatablity for Squirrel

### ISSUE THREAD

**Issue by flaxj** [Squirrel/Squirrel.Windows#1147]
Are Apps build in Squirrel are compatible with the Desktop App Converter?

**Comment by fr4gles** [comment]
What do you mean by "compatible"?

**Comment by flaxj** [comment]
Like having your setup file that is build using Squirrel put into the Desktop App Converter and having it turn into a Appx file with no problems.

**Comment by paulcbetts** [comment]
I believe that works, yes. You only have to run it once, then you can use the output as a "template" and just drop new versions of your app in

**Comment by paulcbetts** [comment]
__
