### ISSUE TITLE
Newbie unable to get started

### ISSUE THREAD

**Issue by JohnStodden** [Squirrel/Squirrel.Windows#1149]
I would like to explore using Squirrel to install winforms apps instead of Clickonce.  But I cannot get to base 1!
1.  The "Getting Started" tutorial documentation says this code should be added to program.cs:

using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
{
    await mgr.UpdateApp();
}

But this fails because await expects async processing.
So I got round this, and placed squirrel.exe in the bin directory as recommended, changing its name to update.exe

2.  then the program fails because it expects a releases file in the releases directory.  There is no explanation of how I create such a file.

Come on Squirrel!  This tutorial is meant to get newbies started!!

**Comment by fr4gles** [comment]
I don't understand why you stop on first point in Getting Started Guide ;) Please check https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/readme.md other points - you will get it.

Wiki is as-is - you can always provide PR fixing it ;)

**Comment by JohnStodden** [comment]
Thanks for the pointer, but I think you miss my point.  A getting-started guide should surely be designed for users who are new to github and squirrel.  To find code that does not work in the very first step of the getting-started guide does not inspire confidence.

**Comment by fr4gles** [comment]
Ok. So for now get through wiki page and point out what else could be mentioned and fixed. I assume that someone will PR this.

**Comment by dePoPo** [comment]
John, you are correct that you cannot use the tutorial's syntax this isnt possible in the startup environment of a standard winforms app

```
            using (var mgr = new UpdateManager(@"...")) {
                await mgr.UpdateApp();
            }
```

I'd suggest using something like;

```
            using (var mgr = new UpdateManager(@"...")) {
               Task t = mgr.UpdateApp();
                t.Wait();
            }
```

Which will have the update still run as a seperate task (which seems to be the intention of the original code), and simply waits for it to complete.
Which will still run the updates and wait for completion, which seems to be the intention of the original code.

**Comment by shiftkey** [comment]
Closing this out because it's not quite clear to me what should change, but suggestions to the current docs can be made here: https://github.com/Squirrel/Squirrel.Windows/tree/master/docs
