### ISSUE TITLE
How to display warning if app is already installed?

### ISSUE THREAD

**Issue by poma** [Squirrel/Squirrel.Windows#1152]
If user runs setup.exe with already installed app, I want to display a message that it will nuke his current settings with an option to cancel setup. Is this possible?

Some users think that setup *is* the app and run it every time and then wonder why their settings don't persist.

**Comment by paulcbetts** [comment]
Why not just move the settings into `%AppData%`\YourApp instead of `%LocalAppData%`?

**Comment by fr4gles** [comment]
Hi.
I see two options:
1. Use https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md
2. Or Just move settings else where.

**Comment by poma** [comment]
Good idea! I'll move it to roaming data.

**Comment by paulcbetts** [comment]
Incidentally, one of my goals of Squirrel, was that it installed _so fast_, and so unobtrusively, that you _could_ use Setup.exe as an app shortcut and it worked just as well :)
