### ISSUE TITLE
No obvious way to change configuration depending on where Squirrel folder is hosted

### ISSUE THREAD

**Issue by konste** [Squirrel/Squirrel.Windows#1169]
When Squirrel app is installed it normally uses config file to read the URL to check for updates. That works if config file is fully known at build time,  but if we don't know upfront where RELEASES file and Setup file are going to be hosted (or there are multiple locations) we cannot adjust that config file during deployment as it is buried deep inside the MSI and Setup.EXE, which are produced by the build process.

Is there any mechanism or hook which can be used to adjust application config file during deployment as it is the case for all web apps?

Thank you beforehand!
Konstantin

**Comment by paulcbetts** [comment]
> When Squirrel app is installed it normally uses config file to read the URL to check for updates

Are you maybe confusing Squirrel with ClickOnce? Squirrel uses a parameter to control where it checks for updates, there is no static config file that describes where updates are located. You can come up with any mechanism you want to decide where updates go

**Comment by konste** [comment]
@paulcbetts Thank you for speedy response!
Let me ask differently though - I have one Squirrel package to be hosted on two different hosts. What can I do to that package at deployment time so that after it is installed it could tell which host it was downloaded from? I could not find any example or hint how to achieve that.

**Comment by paulcbetts** [comment]
Squirrel doesn't have any kind of feature for that, how to solve this depends on your situation - the most straightforward one is to:

1. Build your app
1. Create two copies of the `Release` directory, "ReleaseHostA" and "ReleaseHostB"
1. Copy a config file into both the directories with the URL you want to update from
1. Run Releasify on both
