### ISSUE TITLE
Can packages install/update packages be pulled from NuGet Server?

### ISSUE THREAD

**Issue by mhsimkin** [Squirrel/Squirrel.Windows#1174]
I could not find an answer to this in the documentation.  We have a internal NuGet server (ProGet).  Can Squirrel use a NuGet feed to find the packages for installation/update?

thanks

**Comment by CalvinSlusarski** [comment]
Bump. I have the same question.

**Comment by lukeskinner** [comment]
I don't think so. You can point Squirrel to a folder, URL or GitHub. 

When you point to a folder/URL it will expect a RELEASES file to be in the root of that folder/URL. If you point Squirrel at your NuGet server it's not going to have this file there.

What's the benefit of storing them in your NuGet server? You can't really use these Squirrel packages in your code, they are just for updates. NuGet servers generally have problems with response times after they're not used for a while, so trying to use it with Squirrel may cause slowdowns even if it did support it.

**Comment by Thieum** [comment]
@shiftkey can be closed. Nuget server is out of scope as a release source.
