### ISSUE TITLE
Question: Origin of C++ unzip code

### ISSUE THREAD

**Issue by wjk** [Squirrel/Squirrel.Windows#1178]
The issue title really says it all. I'm looking for a simple, C/C++-based, Win32-compatible library for creating, editing, and extracting zip archives. The [`unzip.h`](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Setup/unzip.h) code looks about right, but it can only extract zipfiles, not create them. From looking at the code I can tell that there is a companion library that creates the zipfiles, but I have not been able to find it on GitHub. Could anyone please give me a pointer as to where I might be able to find that code? Thanks!

**Comment by fr4gles** [comment]
I'm pretty sure that there are two zip processes in squirrel flow. 
First is controlled by nuget.exe (creates nupkg - full and delta packages - to handle update process). 
Second - creates full install exe file by calling exe "writeziptoexe.exe"... and I assume that zip file (which is used as a source for that operation)  is created by 7z - i've seen the 7z.exe next to update.exe in tools folder (downloaded by nuget.exe).

**Comment by lukeskinner** [comment]
This is a guess but I found this by searching for similar comments to the ones found in unzip.h.

https://github.com/stepmania/stepmania/blob/master/src/CreateZip.h - another comment in here points to https://www.codeproject.com/Articles/7530/Zip-Utils-clean-elegant-simple-C-Win.

**Comment by paulcbetts** [comment]
I believe @lukeskinner is correct, it was definitely from CodeProject.
