### ISSUE TITLE
Custom control over which shortcuts get generated on install

### ISSUE THREAD

**Issue by IntegerMan** [Squirrel/Squirrel.Windows#1179]
We have a scenario where we have an app being deployed alongside another executable that it relies on. Only the main exe is user-facing but Squirrel generates shortcuts for all executables it finds in the .nupkg. Is there any way for us to control this either via .nuspec or squirrel releasify? The presence of the secondary executable is confusing to the end users and mildly annoying.

**Comment by paulcbetts** [comment]
Please read the documentation about Squirrel Hooks

**Comment by IntegerMan** [comment]
Cool. So, the UX for that would be -> User installs the app, but doesn't get any shortcuts for it, they can navigate into their users folder and find the application and launch it and at that point it'll create shortcuts as needed. A definite snag for us would be the requirement of knowing the UpdateURL at application startup. For us, that's not known until the user configures the application and authenticates with their particular server location. Still, it's nice to know there's an option.

I don't suppose we could create an UpdateManager with a dummy URL for this purpose, could we?

For anyone else confused about Squirrel Hooks, I believe Paul is referring to [Custom Squirrel Events](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md).

**Comment by paulcbetts** [comment]
> Cool. So, the UX for that would be -> User installs the app, but doesn't get any shortcuts for it, they can navigate into their users folder and find the application and launch it and at that point it'll create shortcuts as needed. 

Squirrel will launch your app on install and run the install hook. Set up the shortcuts there, the user doesn't have to do any of this

> A definite snag for us would be the requirement of knowing the UpdateURL at application startup. For us, that's not known until the user configures the application and authenticates with their particular server location.

You don't have to know this at app startup

**Comment by IntegerMan** [comment]
Great. I'll give this block of code a try, then:

`      using (var mgr = new UpdateManager("We don't need a path"))
      {
        SquirrelAwareApp.HandleEvents(
          onInitialInstall: v => mgr.CreateShortcutForThisExe(),
          onAppUpdate: v => mgr.CreateShortcutForThisExe(),
          onAppUninstall: v => mgr.RemoveShortcutForThisExe());
      }
`

It might be a good change to make an overload of the `UpdateManager` constructor that doesn't require a URL or marks the URL as optional and defaulting to null if it's not really required.

**Comment by paulcbetts** [comment]
Yeah, the whole C# API kind of needs a rework at this point, thanks for the feedback
