### ISSUE TITLE
.net installer should appear more integrated with the installer.  

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#118]
As an end user I would be a bit confused with the .net install, because it starts very nicely with a great new would you like to install this dialog, and then displays a progress bar and then completely disappears for some (LONG) time. Then eventually the.net framework installer appears. Once the framework installer exits it takes some time before my application gets installed. I am running under a HyperV virtual machine, which might be slower than a real one though

**Comment by shiftkey** [comment]
I'm going to close this out as it's a very old issue with not much to work with.

@stefanolson feel free to open a fresh issue with more information if you're still seeing this.
