### ISSUE TITLE
Add .NET 4.7.1 as an option for the required .NET framework version

### ISSUE THREAD

**Issue by MarcusSpecht** [Squirrel/Squirrel.Windows#1180]
It’s included in the Windows 10 Fall Creators Update. .NET Framework 4.7.1 is also available on Windows 7+ and Windows Server 2008 R2+.  We’ve added support for targeting the .NET Framework 4.7.1 in Visual Studio 2017 15.5.

Release Announcement
[Announcing the .NET Framework 4.7.1](https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/)

Similar to previous Issue/Pull Request:
[Add .NET 4.7 as an option for the required .NET framework version](https://github.com/Squirrel/Squirrel.Windows/pull/1055)

Especially interesting is the support for .NET Standard 2.0 and compiler features.

I'll try to do it und create a pull request.

@lukeskinner 
Last time you did the update. Any advise?

**Comment by lukeskinner** [comment]
Using the last pull request for reference - https://github.com/Squirrel/Squirrel.Windows/pull/1055/files:
1.  src/Setup/FxHelper.cpp - copy/paste the net47 changes in the diff and change to net471
For the line below, the number comes from https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#net_b
```static const int fx47ReleaseVersion = 460798; // Minimum version for .NET 4.7```
So for 4.7.1 it should be:
```static const int fx471ReleaseVersion = 461308; // Minimum version for .NET 4.7.1```

2. src/Setup/FxHelper.h - a new net471 option needs to be added

3. src/Setup/Setup.rc - There is a direct download URL for .NET 4.7 Web installer in this file. This needs to be updated to point to the .NET 4.7.1 direct download link (the .NET 4.6 download url points to 4.6.2 so might as well be consistent). 
```IDS_FXDOWNLOADURL47		"http://go.microsoft.com/fwlink/?LinkId=825298"```
The updated link is going to be the hardest part to find I think. If you look at the release announcement link you reference, the download link for the web installer is http://go.microsoft.com/fwlink/?LinkId=852095. This link goes to a web page where you have to start the download manually which isn't what we want. I ended up guessing the number in the URL for .NET 4.7 after a lot of trail and error - there's bound to be a better way I just haven't found it.

4.  src/Setup/resource.h - no changes needed that I can see

**Comment by Thieum** [comment]
For the URL, you can check the chocolatey package here: https://chocolatey.org/packages/dotnet4.7.1
They are using this url for the install: https://download.microsoft.com/download/9/E/6/9E63300C-0941-4B45-A0EC-0008F96DD480/NDP471-KB4033342-x86-x64-AllOS-ENU.exe

**Comment by genyx** [comment]
After following all these steps and compiling the Setup project i end up with a new Setup.exe. But how do i get it into my new first-installation setup files?

**Comment by ZirconLabs** [comment]
I found the needed link and applied the changes. My company needs this since our software targets 4.7.1 (needs .NET Standard 2.0 support).

**Comment by Thieum** [comment]
can be closed, as it is fixed by #1284
