### ISSUE TITLE
constraint: DeltaCompressionDotNet (>= 1.1.0 && < 2.0.0) for squirrel.windows 1.7.8

### ISSUE THREAD

**Issue by braegelno5** [Squirrel/Squirrel.Windows#1181]
I get an error if i will update OpenLiveWriter to 'DeltaCompressionDotNet 2.0.0':

Unable to resolve dependencies. 'DeltaCompressionDotNet 2.0.0' is not compatible with 'squirrel.windows 1.7.8 constraint: DeltaCompressionDotNet (>= 1.1.0 && < 2.0.0)'.

In the Squirrel.nuspec i found: id="DeltaCompressionDotNet" version="[1.1,2.0)" defined, that's why i get the above error message.

Is it possible to change to version="[1.1,2.0]"?

**Comment by muffmolch** [comment]
+1

**Comment by yarseyah** [comment]
+1

**Comment by Thieum** [comment]
@shiftkey can be closed in favor of #897
