### ISSUE TITLE
Unable to install Wire Desktop Client on Windows 7 machine

### ISSUE THREAD

**Issue by Gryfin92** [Squirrel/Squirrel.Windows#1184]
Hey guys, 

i'm using Windows 7 with SP1. I tried to install Wire for Windows, but i got an error. 

"WireSetup.exe" says:

> Installation has failed.
> There was an error while installing the application. 
> Check the setup log for mor informations and contact the author.

> 2017-10-28 18:24:59> Unhandled exception: System.BadImageFormatException: Die Datei oder Assembly "WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Im Modul wurde ein Assemblymanifest erwartet.
> Dateiname: "WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"
>    bei Squirrel.Update.Program.executeCommandLine(String[] args)
>    bei Squirrel.Update.Program.main(String[] args)
> 
> WRN: Protokollierung der Assemblybindung ist AUS.
> Sie können die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.
> Hinweis: Die Protokollierung der Assemblybindungsfehler führt zu einer gewissen Leistungseinbuße.
> Sie können dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.

In German means this that a file or dependency was not found.
I does not found a HKLM registry entry in regedit.

Anyone who can help me?

Excuse my bad english, but i hope you understand my problem. 

Kind regards

**Comment by paulcbetts** [comment]
Hi, we're not Wire customer support, we can't really help you with applications. That being said, this looks like your .NET Framework installation is broken, so you probably need to reinstall or repair it.
