### ISSUE TITLE
Cant install whatsapp: javascript error

### ISSUE THREAD

**Issue by sachin4simon** [Squirrel/Squirrel.Windows#1185]
![java script error 1](https://user-images.githubusercontent.com/33248743/32213580-d723f72e-be41-11e7-852c-62d2c85a99f3.jpg)
![java script error 2](https://user-images.githubusercontent.com/33248743/32213581-d78a33fe-be41-11e7-84fc-f30669e25b48.jpg)
when i opened whatsapp i got this error so i unstalled whatsapp and tried to reinstall it. while installing im getting this error. i dont know what to do. whatsapp was working fine earlier.im using windows 8.1. 
**Please help me**

**Comment by MarshallOfSound** [comment]
This is not WhatsApp support, you should ask them for help not us 😄

**Comment by paulcbetts** [comment]
@sachin4simon Try deleting `C:\Users\HP PC\AppData\Local\WhatsApp`, rebooting your computer, then trying again. Also, what @MarshallOfSound said :)
