### ISSUE TITLE
How to resolve ambiguity when nuget package contains multiple executable files?

### ISSUE THREAD

**Issue by jonny-novikov** [Squirrel/Squirrel.Windows#1186]
When I releasify my application, pre-packed nupkg contains main exe file and additional exe tools but desktop shortcut is created for the tool instead of main exe.

Is there any way to explicit set main executable file?

**Comment by paulcbetts** [comment]
Read about Squirrel Events :)  https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md

**Comment by jonny-novikov** [comment]
@paulcbetts Thank you for provided link!
