### ISSUE TITLE
Machine-wide install doesn't work after manual install+uninstall

### ISSUE THREAD

**Issue by janih78** [Squirrel/Squirrel.Windows#1191]
Reproduce steps:
- Install application using setup.exe
- Uninstall application
- Uninstall leaves (intentionally) the application folder in place with .dead and update.exe files
- Now install application using setup.msi
- Reboot
- Check the application folder and you can see that the application is not installed
- Remove application folder
- Reboot
- Now application gets installed

Conclusion: Even an empty application folder prevents machine-wide installations.

**Comment by robinwassen** [comment]
Any high level recommendations on the approach that should be taken to solve this? 

Because this is a problem that IT-administrators frequently bump into when they explore the packaging before deploying it using SCCM.

**Comment by paulcbetts** [comment]
Delete the folder if it exists. This behavior is by-design, or else individual users wouldn't be able to uninstall the app on a machine-wide install, and it'd come back every reboot
