### ISSUE TITLE
Where does squirrel actually install to?

### ISSUE THREAD

**Issue by TonyValenti** [Squirrel/Squirrel.Windows#1192]
Hi All,
I'm confused by something I'm seeing with Squirrel.
Where does it install my app to?  I see copies of my app in both of these places:
C:\Users\kwieneke\AppData\Local\AlphaDrive\
C:\ProgramData\kwieneke\AlphaDrive

And I'm not sure why.  I've always seen it in the C:\Users... location but today, for the first time, I noticed it installing to Program Data.

Thoughts?

**Comment by vadi2** [comment]
Maybe you ran the `.msi` installer?
