### ISSUE TITLE
Show License Agreement to User

### ISSUE THREAD

**Issue by andylhansen** [Squirrel/Squirrel.Windows#1193]
Is there a way to configure squirrel to show a license agreement to a user when they install my application?

**Comment by lukeskinner** [comment]
https://github.com/Squirrel/Squirrel.Windows/issues/636

**Comment by DamianSuess** [comment]
The current method is to hook into the SquirrelAwareApp.HandleEvents, onInitialInstall.

See:
[custom-squirrel-events.md](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md)
