### ISSUE TITLE
Not creating temporary directories to extract nupkg files to

### ISSUE THREAD

**Issue by markgillnz** [Squirrel/Squirrel.Windows#1197]
I am getting the following error when using Squirrel.Windows to extract existing nupkg files to the SQUIRREL_TEMP directory.

> Utility: Failed to extract file E:\a1\EMRC-ELECTRON99-BW\dist\squirrel-windows-ia32\EMRConnect-1.5.0-full.nupkg to E:\SquirrelTemp\tempa  The system cannot find the file specified

Why doesn't the tempa folder get created by Squirrel.Windows automatically? Even if I manually add the folder it complains about folder tempb not existing.

I have SQUIRREL_TEMP set to E:\SquirrelTemp and am using version 1.7.8 via electron-builder version 19.45.1.

Full stacktrace:
`
07-Nov-2017 10:56:07 | 2017-11-06T21:56:07.622Z electron-builder Executing C:\Users\build\AppData\Local\Temp\electron-builder-cache\Squirrel.Windows\Squirrel.Windows-1.7.8\WriteZipToSetup.exe --copy-stub-resources E:\a1\EMRC-ELECTRON99-BW\dist\win-ia32-unpacked\EMR Connect.exe C:\Users\build\AppData\Local\Temp\temp-files-hLra1Q\1-stub.exe
-- | --
07-Nov-2017 10:57:04 | 2017-11-06T21:57:04.895Z electron-builder Executing C:\Users\build\AppData\Local\Temp\electron-builder-cache\Squirrel.Windows\Squirrel.Windows-1.7.8\Update.com --releasify E:\a1\EMRC-ELECTRON99-BW\dist\squirrel-windows-ia32\emrc-desktop-app-1.5.1-full.nupkg --releaseDir E:\a1\EMRC-ELECTRON99-BW\dist\squirrel-windows-ia32
07-Nov-2017 10:57:05 | 2017-11-06T21:57:05.519Z electron-builder Async task error: Error: Exit code: 4294967295. Command failed: C:\Users\build\AppData\Local\Temp\electron-builder-cache\Squirrel.Windows\Squirrel.Windows-1.7.8\Update.com --releasify E:\a1\EMRC-ELECTRON99-BW\dist\squirrel-windows-ia32\emrc-desktop-app-1.5.1-full.nupkg --releaseDir E:\a1\EMRC-ELECTRON99-BW\dist\squirrel-windows-ia32
07-Nov-2017 10:57:05 | 2017-11-07 10:57:05> Utility: Failed to extract file E:\a1\EMRC-ELECTRON99-BW\dist\squirrel-windows-ia32\EMRConnect-1.5.0-full.nupkg to E:\SquirrelTemp\tempa
07-Nov-2017 10:57:05 | The system cannot find the file specified
07-Nov-2017 10:57:05 | 2017-11-07 10:57:05> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
07-Nov-2017 10:57:05 | at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
07-Nov-2017 10:57:05 | at System.Diagnostics.Process.Start()
07-Nov-2017 10:57:05 | at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
07-Nov-2017 10:57:05 | at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
07-Nov-2017 10:57:05 | --- End of stack trace from previous location where exception was thrown ---
07-Nov-2017 10:57:05 | at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
07-Nov-2017 10:57:05 | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
07-Nov-2017 10:57:05 | at Squirrel.Utility.<ExtractZipToDirectory>d__22.MoveNext()
07-Nov-2017 10:57:05 | --- End of inner exception stack trace ---
07-Nov-2017 10:57:05 | at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
07-Nov-2017 10:57:05 | at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
07-Nov-2017 10:57:05 | at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
07-Nov-2017 10:57:05 | at Squirrel.Update.Program.ReleasifyElectron(String package, String targetDir, String baseUrl)
07-Nov-2017 10:57:05 | at Squirrel.Update.Program.executeCommandLine(String[] args)
07-Nov-2017 10:57:05 | at Squirrel.Update.Program.main(String[] args)
07-Nov-2017 10:57:05 | ---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
07-Nov-2017 10:57:05 | at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
07-Nov-2017 10:57:05 | at System.Diagnostics.Process.Start()
07-Nov-2017 10:57:05 | at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
07-Nov-2017 10:57:05 | at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
07-Nov-2017 10:57:05 | --- End of stack trace from previous location where exception was thrown ---
07-Nov-2017 10:57:05 | at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
07-Nov-2017 10:57:05 | at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
07-Nov-2017 10:57:05 | at Squirrel.Utility.<ExtractZipToDirectory>d__22.MoveNext()<---
`

**Comment by paulcbetts** [comment]
electron-builder has forked Squirrel and so you should take support to them
