### ISSUE TITLE
How to autoupdate my WPF app from GitHub repository, and what data should be stored on GitHub?

### ISSUE THREAD

**Issue by AndrijMoroziuk** [Squirrel/Squirrel.Windows#1198]
I am using Squirrel.Windows to create instalation and autoupdating for my WPF applicaition. I'm checking updates on GitHub using next code:

    using (var mgr = UpdateManager.GitHubUpdateManager("https://github.com/MyName/MyRepo")) 
    {
              var updResult = await mgr.Result.UpdateApp();
              this._viewModel.Error = $"Current version: {mgr.Result.CurrentlyInstalledVersion()}. Update version: { updResult?.Version.ToString() ?? "No update"}";
    }

But when app run this code:
    var updResult = await mgr.Result.UpdateApp();
I got error: "The request was aborted: The connection was closed unexpectedly."

What content should be on my GitHub repository so that the app can get updates from it?
Maybe can someone give me working example?

**Comment by patriksvensson** [comment]
@AndrijMoroziuk Did you find a solution to this?
