### ISSUE TITLE
Is re-running Setup again a safe way to upgrade?

### ISSUE THREAD

**Issue by vadi2** [Squirrel/Squirrel.Windows#1200]
I have my own code for checking updates and UI for downloading them already in-place. Is it safe for me to just run the new `setup.exe` as an "upgrade"?

**Comment by paulcbetts** [comment]
No, Squirrel used to do this, but the problem is that many people are running Setup again because their installation is broken or doesn't work somehow, so we changed it to erase and reinstall the version contained in Setup.

**Comment by vadi2** [comment]
So it sounds like for my automated, silent installer running `setup.exe` again is OK? Or do I have to let Squirrel do the updating and build infrastructure around the download progress tracking.

**Comment by paulcbetts** [comment]
@vadi2 If you want an automated silent installer, you should use the MSI file, it'll do the Right Thing and be easy to deploy with Group Policy tools
