### ISSUE TITLE
[Feature request] SHA256 support in UpdateManager

### ISSUE THREAD

**Issue by shlteater** [Squirrel/Squirrel.Windows#1205]
I've read the doc at https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-manager.md and realized the ReleaseEntry only supports SHA1.

`
public interface ReleaseEntry
{
    public string SHA1;
    public string Filename;
    public long Filesize;
    public bool IsDelta;
}
`

Since SHA1 is not secure enough and not recommended now, can Squirrel support SHA256 in UpdateManager?

**Comment by paulcbetts** [comment]
Squirrel is not using SHA1 for cryptography purposes, but integrity checking purposes
