### ISSUE TITLE
update.zip contains Trojan

### ISSUE THREAD

**Issue by yushihan** [Squirrel/Squirrel.Windows#1211]
The update.zip stored in Squirrel.Windows-master\src\Setup is flagged as trojan by 7 AV tools according to VirusTotal: https://www.virustotal.com/#/file/c1172519c6b17577f91a1d074b6223e59c240ccb708e911e5cab303e365fdade/detection

Please review and confirm if it is a false positive.

**Comment by paulcbetts** [comment]
It's a false positive. All of these are "heuristics" aka it noticed that we download and install software.
