### ISSUE TITLE
Auto install .Net Framework failed

### ISSUE THREAD

**Issue by luogxsysu** [Squirrel/Squirrel.Windows#1212]
After run the setup exe on win7，I got Install .Net 4.5 tips. 

But when I click the install button, it always return 
"Failed to install the .NET Framework, try installing the latest version manually"?
How can i avoid this error?

**Comment by paulcbetts** [comment]
> try installing the latest version manually

**Comment by luogxsysu** [comment]
What is failing and why? @paulcbetts
