### ISSUE TITLE
RELEASES file and AWS

### ISSUE THREAD

**Issue by patriksvensson** [Squirrel/Squirrel.Windows#1213]
I just started looking at Squirrel as way of auto updating an application I'm building.

Is there a way of telling relasify to get the existing `RELEASES` file from the AWS bucket? Right now I end up with a new `RELEASES` file containing a single release.

Not sure if I've misunderstood something or if this is the way it's supposed to work.

**Comment by patriksvensson** [comment]
I'm stupid. I just realized I need to download all files specified in the RELEASES file from AWS before building the installer.

Closing this issue.

**Comment by paulcbetts** [comment]
@patriksvensson This is what the SyncReleases tool does!

**Comment by patriksvensson** [comment]
@paulcbetts Ah, I've completely missed that and wrote my own script to download them. Will use the SyncReleases tool instead. Thanks!
