### ISSUE TITLE
Switching code signing cert? 

### ISSUE THREAD

**Issue by tom-james-watson** [Squirrel/Squirrel.Windows#1214]
The certificate authority that I used to purchase my previous code signing certificate is closing down, so I will need to purchase my next certificate from a different authority. 

If an application receives an auto-update that is signed with a different certificate to the one the original app was signed with, does it matter?

Thanks!

**Comment by stajs** [comment]
Good question, I'm curious also. Perhaps you could do an early-test with a self-signed cert?

**Comment by MarshallOfSound** [comment]
Windows doesn't care, it will work fine if you switch certs

**Comment by paulcbetts** [comment]
It might give you problems with SmartScreen for awhile, but it generally shouldn't cause issues. Squirrel.Windows trusts HTTPS to verify that you downloaded The Thing You Thought You Did, it doesn't use code signing.
