### ISSUE TITLE
Problem when updated from Squirrel 1.2.8 to 1.7.8 - Shortcut

### ISSUE THREAD

**Issue by Samircj** [Squirrel/Squirrel.Windows#1215]
Hi guys,

I've done some research and found some open issues about Execution_Stub, I've tried the workaround proposed. It din't work for me.

Here is a brief of my case:

Upgraded from:
   - App version 1.2.0
   - Squirrel 1.2.8
   - Squirrel.Windows for releasefy 1.4.3

To
   - App version 1.3.0
   - Squirrel 1.7.8
   - Squirrel.Windows for releasefy 1.4.3

Result:
   - Shortcut are created pointing to Update.exe, cause "file not found"
   - No Execution_Stub were created

I need to build new version of my App 1.4.0 but I'm facing some problems.
   - Squirrel 1.7.8
   - Updated Squirrel.Windows for releasefy to 1.7.8

Result:
   - Shortcut were created pointing to my App.exe (Stub) - Causing App Force close
   - NO App_ExecutionStub.exe were created

Could you please describe some workaround for this scenario? I can provide some screenshots for you better understand. 

p.s. The App is in production and users are facing shortcut issues.

Please, bear with my english.

**Comment by williamyuzhang** [comment]
I have the same issue with squirrel 1.7.9.0.    the shortcut just could not use the right version of app.exe and even windows tried to fix it and use the old version of app.exe instead of the newer one. 

Anyone has any idea about how to fix it or workaround for it?

thanks,
William

**Comment by lukeskinner** [comment]
This is likely the same problem as https://github.com/Squirrel/Squirrel.Windows/issues/1075.

**Comment by williamyuzhang** [comment]
Thanks, lukeskinner! 

I finally found solution for my issue.  It caused by the package tool **Auto.Squirrel** which could not generate the MyApp_ExecutionStub.exe file in the nuget package.  and the missing stub.exe file caused the shortcut function broken.

Anyway, Auto.Squirrel has bug.

**Comment by dtomovdimitrov** [comment]
> I finally found solution for my issue. It caused by the package tool Auto.Squirrel which could not generate the MyApp_ExecutionStub.exe file in the nuget package. and the missing stub.exe file caused the shortcut function broken.
>
>Anyway, Auto.Squirrel has bug.

Could you share your solution? I have the exact same problem and it drove me crazy until I found that it was caused by Auto.Squirrel.

**Comment by Thieum** [comment]
@shiftkey [auto.squirrel](https://github.com/tenacious/Auto.Squirrel) is not something we support here. I think this can be closed.
