### ISSUE TITLE
Expected Update Behaviors

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1218]
New to Squirrel (thanks!) and trying to get a better understanding of the update experience.

Currently it appears my users will have to run the application twice to get the latest version (unless they happen to have it running at the very moment of my publish, which of course can't be counted on).

I briefly became excited when I saw this command syntax at the Shortcuts section:

`C:\Users\kbailey\AppData\Local\MyApp\Update.exe --processStart MyApp.exe`
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/install-process.md#desktop--windows-start-shortcuts

This seems to indicate that `Update.exe` runs first and pulls down the latest version before running the application itself. I briefly became excited when I saw this, as it promised to alleviate my 'running twice' concern.

Alas, it was not to be. MyApp, when run under this construct, still displayed v1.0.1, even though I'd already published v1.0.2. I had to run MyApp again a second time in order to get the update.

That said, I had to manually edit the shortcut to even get that  syntax at all. Upon running `Setup.exe` for the first time (v1.0.0), the shortcut was created with a direct path to the executable. `Update.exe` appears to be ignored, at least as far as creation of the desktop shortcut goes.

Is something malfunctioning here? By specifying `Update.exe`, the documentation leaves us with the impression that an update check is supposed to occur _before_ the app is run. Nevertheless, my own shortcut didn't get that syntax in any case.

So two questions:

1. Isn't `Update.exe` supposed to behave as I've described, and download the latest?
2. Is there a way to customize these shortcuts? (Assuming I can get `Update.exe` to actually perform an update)

**Comment by paulcbetts** [comment]
> Isn't Update.exe supposed to behave as I've described, and download the latest?

Nope. You're also using an old version of Squirrel.Windows if it's creating shortcuts to Update.exe. Updates happen when *your program asks for it*, not at a time that Squirrel decides. To do that, your program has to run!

> Is there a way to customize these shortcuts? (Assuming I can get Update.exe to actually perform an update)

No, this is a workaround for pinning and shortcuts being broken on updates.

**Comment by InteXX** [comment]
My, that was fast! It's good to know you're sitting and waiting in case I might write in  :-)

Ah then...  the documentation is referring to an older construct—yes?
