### ISSUE TITLE
Test and Prod System of the same App on one PC

### ISSUE THREAD

**Issue by simader** [Squirrel/Squirrel.Windows#1220]
This is more a question than an issue.
For testing purpose we need to install on the same machine and users twice the same App. Once for Testsystem und and then for Production. 

I currently use VSTS Build and than Release Management where all the Squirrel magic happens. 
I would like to push first the Test-Update and when our customers verify its, we push the same build-output to the Prod System. 

I tried with 2 different .nuspec files, however they always overwrite each other.

Does anybody have a suggestion for me?
Thanks in advance

**Comment by ralsu091** [comment]
You will have to make sure the Id of the two versions are unique in your nuspec files.

**Comment by paulcbetts** [comment]
It's not ideal depending on how big your test pool is, but you can

1. Install the test version
2. `./lib/net45/myapp.exe --squirrel-uninstall 1.2.3`
3. Move your test version to another folder
4. `./lib/net45/myapp.exe --squirrel-install 1.2.3` to recreate the shortcuts
5. Install the prod version

Now both versions are installed at the same time and will get updates

**Comment by Thieum** [comment]
@simader did the suggestion in https://github.com/Squirrel/Squirrel.Windows/issues/1220#issuecomment-355356244 helped you? If so, you can close the issue.

**Comment by simader** [comment]
Hi, I made for my a different workaround. I made two build definitions and on the Test-Build it renames my the ApplicationName and adds -TEST to it. Then i have 2 .nuspec files for updating.
