### ISSUE TITLE
Generting new releases

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1221]
Does Releasify need _all_ prior versions in order to build a new release, or will it work when it has only the most recent version?

**Comment by paulcbetts** [comment]
Only the previous version. Use the `SyncReleases` tool in your CI process to do the work of copying it down from your update server

**Comment by InteXX** [comment]
That sounds like a pretty good tool. I'll have a look.

Any documentation for it?

**Comment by InteXX** [comment]
Also: do you ever eat or sleep?

**Comment by paulcbetts** [comment]
lol I just happened to see this message
