### ISSUE TITLE
Error running SyncReleases

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1222]
SyncReleases is writing this text to the error stream:

`Attempting to sync URL as remote RELEASES folder`

...which is turn is causing my build to fail.

Please advise.

> Found SyncReleases installation. Using D:\Agent\_work\29\s\packages\squirrel.windows.1.7.8\tools\SyncReleases.exe
Attempting to sync URL as remote RELEASES folder
Trying to download RELEASES index from http://[REDACTED].blob.core.windows.net/myapp/RELEASES
Downloading release from http://[REDACTED].blob.core.windows.net/myapp/MyApp-2017.1228.30-full.nupkg
Process completed with exit code 0 and had 1 error(s) written to the error stream.

**Comment by InteXX** [comment]
I attempted to submit a PR to address this, but I received a 403 in VS 2017. Not sure how to proceed.

**Comment by paulcbetts** [comment]
This is not an error in SyncReleases, this is a problem with your build system that decides all output to STDERR should be a failing result. If the exit code is 0 that means that SyncReleases worked correctly

**Comment by InteXX** [comment]
@paulcbetts 

> This is not an error in SyncReleases, this is a problem with your build system

TFS 2018

**Comment by InteXX** [comment]
I discovered this setting in the PowerShell build task:

![image](https://user-images.githubusercontent.com/10966749/34456873-e1d28222-ed4d-11e7-82c7-92ac358a1f91.png)

**Comment by InteXX** [comment]
@paulcbetts 

I'd like to take this up again with you.

I disagree that it's not an error in SyncReleases. I believe it is. The first try/catch, for when the sync is run against a non-GitHub repository, doesn't represent a true error condition. Squirrel supports using repositories other than GitHub, e.g. S3, Azure, etc. (thank you for this, BTW), so when one of these others is used the process shouldn't write to STDERR.

STDOUT will be just fine under this scenario.

Luckily, the TFS PowerShell build step provides us a workaround for this with the setting to not fail the build on STDERR writes. However, the Azure PowerShell build step doesn't. It's not possible to overcome the problem when using that important build step, other than forking this repo and working independently of your considerable expertise in the subject matter. (Unless there's a way I'm not aware of to swallow that STDERR write in PowerShell.)

Do you see a use case that requires writing to STDERR on the first exception (non-GitHub repository)?

**Comment by InteXX** [comment]
@paulcbetts 

I found a workaround in PowerShell:

`&$SyncReleases -u $PublicRepository -r $TargetDirectory 2> $ErrorLog`

However, this swallows _all_ STDERR output, which is probably not healthy. I stand by my arguments above.

Thoughts?

**Comment by paulcbetts** [comment]
I think you should rely on the exit code for seeing if SyncReleases succeeds :)

**Comment by InteXX** [comment]
Aha. That's what I'll do then. Thanks.

**Comment by InteXX** [comment]
> Aha. That's what I'll do then. Thanks.

But I still stand behind my arguments ;-)
