### ISSUE TITLE
Query - Deploying data files (SQLite)

### ISSUE THREAD

**Issue by jamithiran** [Squirrel/Squirrel.Windows#1223]
Hello, I'm exploring Squirrel.Windows as an alternate to Click-Once. After running through multiple forums and documentation am unclear how the data files are handled. 

I have couple of SQLite files (one with static data and another that will be for storing user data). Currently, they are in a folder named DB at the same level as App (contains all my release App.exe and dll-s). I also have another folder named Input containing static data. 

I understand that the DB & Input folders will have to be moved inside lib/net45. Hope this is the right way to do it? 

I intend to keep my user data SQLite file same in all the releases so that client does not lose the data. I guess this is how Click-Once processes it.  What happens to my data files during a version update in Squirrel.Windows in similar scenario or there any better practices?

Thanks for your time. Cheers

**Comment by Thieum** [comment]
@jamithiran Did you consider creating the sqlite files on app startup if they are not already there (in a separate folder than install folder) instead of shipping them? It would separate your concerns, and leave you more freedom when having to handle schema updates, data migration, etc.

**Comment by Thieum** [comment]
@shiftkey duplicate from #47
