### ISSUE TITLE
Squirrel hangs during releasify

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1228]
I'm running this command:

    D:\Agent\_work\29\s\packages\squirrel.windows.1.7.8\tools\Squirrel.exe --releasify D:\Agent\_work\29\a\MyApp.2017.1231.12.nupkg -r D:\Agent\_work\29\s\Releases

...and `Squirrel.exe` is silently hanging during delta creation.

Here're the files in `D:\Agent\_work\29\a`:

> MyApp-2017.1228.30-full.nupkg
MyApp.2017.1231.12.nupkg
RELEASES

...and the contents of my `RELEASES` file:

    A5AED38AF7E991A8110D078B5924EBB3712E925E MyApp-2017.1228.16-full.nupkg 2061624
    72EDCFAA45F8CDA7378217E66E1A4631A15D4FCF MyApp-2017.1228.17-delta.nupkg 9945
    B6279094F4F5A22DC04F534926251509B736D810 MyApp-2017.1228.17-full.nupkg 2061625
    CF3CBFE3970A6DBC6B6B1649B0E122C96DA06BE5 MyApp-2017.1228.25-delta.nupkg 10053
    715516C5DB3886CD90587225D7D429AFF6DD5D4F MyApp-2017.1228.25-full.nupkg 2061632
    C0F9C4027A2AD8CC5D838296A769C6E95849C3D6 MyApp-2017.1228.26-delta.nupkg 9944
    C20C42C7B96CDAE58DF35642DF8FBB9DDC84D050 MyApp-2017.1228.26-full.nupkg 2061632
    FF2D3F1811AD7B04B5F4E07EAB8D5B2BC814F2AE MyApp-2017.1228.28-delta.nupkg 10508
    9009D5327765BF8AA5861D452C725809EC9B8991 MyApp-2017.1228.28-full.nupkg 2061632
    06AA9DC216D64873CF1CFDAAE65A8EC4F2E26687 MyApp-2017.1228.29-delta.nupkg 9945
    571C52ECDB739BEFBA961B7EC14B9CFF9BD86587 MyApp-2017.1228.29-full.nupkg 2061634
    B33B046B6EE34267125489BF5BCD982649EE220D MyApp-2017.1228.30-delta.nupkg 9952
    A23FF451EA19A3F10C363D2B44F16FE08991D451 MyApp-2017.1228.30-full.nupkg 2061634

These files are then created in `D:\Agent\_work\29\s\Releases`:

> MyApp-2017.1231.12-full.nupkg
RELEASES
Setup.exe
Setup.msi

...but no delta/full releases are created for the update from `2017.1228.30` to `2017.1231.12`. `Squirrel.exe` hangs at this point. I have to press `Ctrl+C` to cancel it.

Here is the TFS build step command that's creating `MyApp.2017.1231.12.nupkg`:

    D:\Agent\_work\_tool\NuGet\4.5.0\x64\nuget.exe pack D:\Agent\_work\29\s\MyApp\MyApp.nuspec -NonInteractive -OutputDirectory D:\Agent\_work\29\a -Properties Configuration=release -version 2017.1231.12 -Verbosity Detailed

...and here is my NuSpec file:

    <?xml version="1.0"?>
    <package >
      <metadata>
        <id>MyApp</id>
        <version>$version$</version>
        <title>MyApp</title>
        <authors>InteXX</authors>
        <owners>InteXX</owners>
        <requireLicenseAcceptance>false</requireLicenseAcceptance>
        <description>Squirrel deployment prototype</description>
        <releaseNotes>Test release.</releaseNotes>
        <copyright>Copyright © 2017</copyright>
      </metadata>
      <files>
        <file src="bin\Release\*.dll" target="lib\net45\"></file>
        <file src="bin\Release\*.exe" target="lib\net45\" exclude="**\*.vshost.exe"></file>
        <file src="bin\Release\*.config" target="lib\net45\"></file>
      </files>
    </package>

Am I missing something?

**Comment by paulcbetts** [comment]
Dunno, I would get a crash dump of the hanging process then get a call stack. It's stuck at the scene of the crime, so easy!

**Comment by InteXX** [comment]
Sounds sexy. Know how to get there?

**Comment by paulcbetts** [comment]
Remote into the machine, run Task Manager => Processes tab => Squirrel.exe => Right click, "Create Crash Dump"

**Comment by InteXX** [comment]
Got it. Funny thing is, Squirrel exits early on, leaving the command prompt still hanging.

Odd.

**Comment by InteXX** [comment]
The dump has no exception information. Is that what we're looking for?

**Comment by InteXX** [comment]
Here's the symptom: `Squirrel.exe` exits immediately after creating the NuGet package, RELEASES file, `Setup.exe` and `Setup.msi`—and not the delta, as described—but then leaves the command prompt hanging.

Thus it's not possible to capture anything meaningful in a crash dump.

This is really strange. Do you have any ideas?

**Comment by paulcbetts** [comment]
I would get the log file SquirrelSetup.log, it's next to wherever Squirrel.exe is

**Comment by InteXX** [comment]
Hm, not much there:

    2018-01-05 15:05:59> Program: Starting Squirrel Updater: --releasify D:\Agent\_work\29\a\MyApp.2017.1231.12.nupkg -r D:\Agent\_work\29\s\Releases
    2018-01-05 15:05:59> Program: Bootstrapper EXE found at:D:\Agent\_work\29\s\packages\squirrel.windows.1.7.8\tools\Setup.exe
    2018-01-05 15:05:59> Program: Creating release package: D:\Agent\_work\29\s\Releases\MyApp.2017.1231.12.nupkg
    2018-01-05 15:05:59> ReleasePackage: Creating release package: D:\Agent\_work\29\s\Releases\MyApp.2017.1231.12.nupkg => D:\Agent\_work\29\s\Releases\MyApp-2017.1231.12-full.nupkg
    2018-01-05 15:06:00> ReleasePackage: Extracting dependent packages: []
    2018-01-05 15:06:00> ReleasePackage: Removing unnecessary data
    2018-01-05 15:06:02> Program: Building embedded zip file for Setup.exe

**Comment by paulcbetts** [comment]
Seems like this is succeeding, I think you probably need to review the PowerShell script that's driving the build

**Comment by InteXX** [comment]
I agree...  and I've already found one significant problem.

I'm running `--releasify` on this single package:

`D:\Agent\_work\29\a\MyApp.2017.1231.12.nupkg`

...and the latest public release prior to `2017.1231.12` (`MyApp-2017.1228.30-full.nupkg`) is sitting alongside that package in the same directory.

However, `Squirrel.exe`'s working directory when I do so is this:

`D:\Agent\_work\29\s`

...which means it's building the next release here:

`D:\Agent\_work\29\s\Releases`

The problem is that `Squirrel.exe` isn't seeing the older package sitting here:

`D:\Agent\_work\29\a`

So I've gone back to an earlier method that was working: I was running `--releasify` against all packages in `D:\Agent\_work\29\a`.

That was working before, but suddenly now I'm getting this error:

> System.InvalidOperationException: Source sequence doesn't contain any elements.

This occurs when I run `--releasify` against a package that `Squirrel.exe` created previously.

I'm working on tracking this one down now.

**Comment by InteXX** [comment]
The solution to this issue can be found here, #1229.
