### ISSUE TITLE
Icon support

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#123]
A user has created some icons on the task bar themselves. What I noticed is that the icon points to the executable (original version) and will never be updated. Is there a way to specify a custom icon that will be used instead and will be put in the root of the folder (next to update.exe)?

Otherwise I think it would be a good idea to use the icon of the nuspec for this to use a logo (and store it version independent).

**Comment by TyBarthel** [comment]
@GeertvanHorrik Were you able to work around this?  I'm running into the same issue where the icon that gets pinned in the start menu points at the version folder at the time of pinning (i.e. %USERPROFILE%\AppData\Local\<app name>\app-15.0.11\<app name>.exe).  

Then a few updates later, the path no longer is valid so an icon doesn't show up.

**Comment by GeertvanHorrik** [comment]
No. I think the latest version always points to update.exe. So if you ensure that update.exe has an icon, it should work (but to be honest, I am a few versions behind running my own branch).

I hope to get back on the main track if @paulcbetts is open to adding the release date (as a non-breaking change) to the RELEASES file (as a PR of course).

**Comment by TyBarthel** [comment]
Yeah, the shortcut points to update.exe, but (Win 7) if you view the properties of the shortcut and click "Change Icon" it's pointed to the executed of the application located in a version directory.

Currently I am a few versions behind, 1.0.2.

**Comment by SlavaChristin** [comment]
Got the issue as well. 
Shortcuts points to AppData\Local\<AppName>\<AppName>.exe
After clicking on shortcut looks like another process is created
 AppData\Local\<AppName>\app-<AppVersion>\<AppName>.exe

User then pins this process and after upgrade it becomes invalid. 

Are there any PRs created for that or workarounds exist?

**Comment by SlavaChristin** [comment]
Is that possible to update pins as well as desktop shortcuts ?

**Comment by Thieum** [comment]
@shiftkey fixed by #604, this can be closed.
