### ISSUE TITLE
Getting error using Squirrel.Windows

### ISSUE THREAD

**Issue by sharadverma810** [Squirrel/Squirrel.Windows#1230]
Hi,
i want to use squirrell for windows application deployment.i have visual studio 2013 and using operating system windows8.1.
when i execute PM> Install-Package Squirrel.Windows comand on NuGet console i got some dependancy error.how i can use 
Nuget package explorer and prerequisite for it.

**Comment by avinash0** [comment]
I am also facing the same issue. Is there any update on this. Have you sorted this issue.

**Comment by paulcbetts** [comment]
Not actionable

**Comment by sharadverma810** [comment]
Ok, then please let me know at least prerequisite to install Squirrel.Windows nu-get package with visual studio 2013 and Windows 8.1, because i not able to do that yet! please help.
