### ISSUE TITLE
Can we push the application updates for app developed with WinJs?

### ISSUE THREAD

**Issue by avinash0** [Squirrel/Squirrel.Windows#1232]
Its not an issue but I have one query. Please help.
I have checked the getting-started guide. There is mentioned to create Program.cs and Properties\AssemblyInfo.cs files. It seems that this library is used for .net applications. Can we use this for the distribution and code push for the desktop applications developed in WinJs?

**Comment by paulcbetts** [comment]
Nope, sorry! Desktop apps only.

**Comment by avinash0** [comment]
My application is also desktop application build with cordova and WinJs. I just want to confirm that is this support for this. or only for the .Net based applications?

**Comment by paulcbetts** [comment]
If your app is a Desktop-based app (i.e. the thing you get at the end of the day is an EXE), you can use Squirrel.Windows, it doesn't have to be a .NET app. However, if your app is Store-based (the result is an AppX Package), Squirrel.Windows won't work.

**Comment by avinash0** [comment]
Thanks for clarification. Your prompt response is highly appreciated.
