### ISSUE TITLE
Persistent Mutex leak after UpdateManager disposal

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1235]
Thank you for the recent update.

I'm using `Topshelf.Squirrel.Updater`, found [here](https://github.com/Nonobis/Topshelf.Squirrel.Updater). When I pressed Ctrl+C to exit the console app in Debug mode—a Topshelf convention—Squirrel intercepted the exit and threw a general exception with a message similar to this:

> UpdateManager must be disposed

Pressing Ctrl+C a second time fully exited the app.

I updated the `RepeatedTimeUpdater` class in the `Topshelf.Squirrel.Updater` assembly with this code:

    ~RepeatedTimeUpdater()
    {
      updateManager.Dispose();
    }

This time Squirrel threw a different exception from `SingleGlobalInstance`:

> Leaked a Mutex!

Presently I can no longer reproduce the original 'undisposed' exception. Even after I revert to the original `Topshelf.Squirrel.Updater`—without the destructor and `Dispose()` call—I still get the `AbandonedMutexException` every time I exit during Debug.

I'd like to avoid memory leaks, for obvious reasons.

Please advise.

**Comment by paulcbetts** [comment]
This error is trying to tell you something important - you're in the middle of an update, and you're exiting the app! That's Not Good. You need to defer exiting until the update completes.

**Comment by InteXX** [comment]
@paulcbetts 

TNG&trade;...  yes, I agree.

Funny thing is, though—I'm not installing an update. `UpdateManager` is finished doing its checking, and there's nothing left for it to do. I'm closing down the app (e.g. stopping the service).

I've got my code set to check for updates every 15 seconds (at least during testing). Are you saying that my Ctrl+C keypress (or service stop) shouldn't happen during an update check cycle? If so, is there a way to determine if that cycle is active?

Also: what about the abandoned mutex? There doesn't seem to be any escaping that to get back to the original 'undisposed' exception.

**Comment by paulcbetts** [comment]
>  If so, is there a way to determine whether there's an active cycle?

Usually you shouldn't hold around UpdateManager instances, create it, use it to Do A Thing, then destroy it (i.e. in a `using` block). That way you know when updates are running, solely because the task is still running.

> Are you saying that my Ctrl+C keypress (or service stop) shouldn't happen during an update check cycle?

Yeah! You could do something like, create a single `Task.Run` that has a loop:

```
var quitTokenSource = new CancellationTokenSource();

var updaterTask = Task.Run(() => {
while(cts.Token.IsCancellationRequested) {
   await doTheCheckForUpdates();   
   await Task.Delay(15 minutes, cts.Token);
});

// later when you want to exit
void CtrlCWasPressed() {
  quitTokenSource.Cancel();
  updaterTask.Wait();
}
```

> Also: what about the abandoned mutex? There doesn't seem to be any escaping that to get back to the original 'undisposed' exception.

I wouldn't try to do any of these finalizer tricks.

**Comment by InteXX** [comment]
@paulcbetts 

> I wouldn't try to do any of these finalizer tricks.

You've got no argument from me there! But even after I pulled the destructor (and deleted the `%LocalAppData%\.squirrel-lock-*` file) I keep getting the `AbandonedMutexException`. I can't get back to the original 'undisposed' exception so I can work on applying your suggested changes.

**Comment by InteXX** [comment]
@paulcbetts — I'm able to get back to the 'undisposed' exception by running this as a service under LocalSystem. So it's clearly a user-specific issue.

Do you have any ideas about this one? It seems rather sticky.

**Comment by InteXX** [comment]
@paulcbetts — I've applied your suggested changes, but I'm still getting the `AbandonedMutexException` on exit.

1. I removed all `Finalizer` calls in my code
2. I put `UpdateManager` in a `Using` block

Do you know why the `AbandonedMutexException` would throw only under my user profile?

**Comment by InteXX** [comment]
@paulcbetts — I don't get the exception when I change the executable name. I've looked through the Squirrel source and I'm not spotting it.

**Comment by InteXX** [comment]
@paulcbetts — Oops, that's not true. I'm still getting the exception after renaming the executable.

This is a complete mystery to me.

**Comment by InteXX** [comment]
@paulcbetts 

Very good, thank you. Your suggested code works.
