### ISSUE TITLE
Query parameters for RELEASES request are not included in subsequent request(s)

### ISSUE THREAD

**Issue by ezekg** [Squirrel/Squirrel.Windows#1236]
When using an update endpoint which requires query parameters (using `license-key` for authentication before allowing the update request),

```
https://example.com/releases/win?license-key=foo
```

Squirrel.Windows correctly requests the `RELEASES` file by including the `license-key` query param:

```
https://example.com/releases/win/RELEASES?license-key=foo
```

But then it does **not** include the query params for any subsequent requests to the actual release paths specified in the `RELEASES` file:

```
https://example.com/releases/win/app-1.0.0-delta.nupkg
```

While I would **expect** it to make the request while including the `license-key` query param like it does for the request for the `RELEASES` file:

```
https://example.com/releases/win/app-1.0.0-delta.nupkg?license-key=foo
```

Unfortunately, my release server does not allow requests without authentication so these update requests get rejected. I'd like to avoid having to generate a `RELEASES` file server-side which includes the query params for each release file.

I wouldn't expect Squirrel.Windows to drop query params like this.

Is this a bug?

**Comment by paulcbetts** [comment]
The URL that Squirrel downloads is based on what's in the RELEASES file, it doesn't carry along the URL that the RELEASES file came from (because like, it might not come from a URL at all!)  Instead, put the license-key parameter in your RELEASES file (release files are very simple to generate by-hand)

**Comment by lockiechen** [comment]
we need the query parameter when download the nupkg file? any suggestion? @anaisbetts

**Comment by anaisbetts** [comment]
@lockiechen My advice is the same as it was in 2018 :joy:   If the server hosting nupkg files needs a query parameter passed from the client, you need to write a web service that generates the RELEASES file dynamically.

**Comment by lockiechen** [comment]
> @lockiechen My advice is the same as it was in 2018 😂 If the server hosting nupkg files needs a query parameter passed from the client, you need to write a web service that generates the RELEASES file dynamically.

is there any example?

**Comment by anaisbetts** [comment]
@lockiechen Not to my knowledge. Read the RELEASES file, it is extremely simple
