### ISSUE TITLE
Set Version Incorrect accidentally now this error occurs - System.Exception: Your package version is currently 1.2.7.1, which is *not* SemVer-compatible, change this to be a SemVer version number

### ISSUE THREAD

**Issue by joelybahh** [Squirrel/Squirrel.Windows#1237]
So I added an extra number by accident instead of 1.2.71, and now no matter what I do, when I releasify I get this error.

I have checked my RELEASES file and it is not in there, I also made a completely fresh NuGet package with the version set to 1.3.0 and I still get this error. 

![one](https://user-images.githubusercontent.com/6394680/35252877-9f98a28c-0036-11e8-8e8f-0115758dd976.PNG)
![two](https://user-images.githubusercontent.com/6394680/35252879-a4f18f0a-0036-11e8-9e6b-70112c8beea2.PNG)

**Comment by joelybahh** [comment]
I resolved this by simply deleting the Releases folder and starting again. Not Ideal, any way to fix this without removing the entire Releases folder? 

Kind Regards,
Joel - InspaceXR Sydney

**Comment by lukeskinner** [comment]
In the Releases folder you likely had 1-2 nuget packages that had '1.2.7.1' in the file name. The RELEASES file should match the files in your Releases folder. So if you delete it from the file you need to individually delete them from the folder. You shouldn't need to delete the whole folder to correct this.

**Comment by paulcbetts** [comment]
@joelybahh the RELEASES file is just a file you can edit, just remove the line that has 1.2.7.1

**Comment by DorGoldi** [comment]
I have the same issue but the above doesn't work for me. This is my first use of Squirrel so maybe I did something wrong in the way?

that's what i get

Squirrel --releasify HitKli_WpfApp.1.0.0.1.nupkg --releaseDir "C:\SquirrelReleases"
Squirrel : System.Exception: Your package version is currently 1.0.0.1, which is *not* SemVer-compatible, change this to be a SemVer version numbe
r
At line:1 char:1
+ Squirrel --releasify HitKli_WpfApp.1.0.0.1.nupkg --releaseDir "C:\SquirrelReleas ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Exceptio... version number:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProce
ssor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String
 signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

**Comment by paulcbetts** [comment]
@DorGoldi The error literally tells you what to do

**Comment by DorGoldi** [comment]
change this to be a SemVer version number? 

i don't really know what SemVer version number is or where is it changed (first time dealing with this)

**Comment by DorGoldi** [comment]
OK got it

**Comment by sitanshu17** [comment]
@DorGoldi  Can you please explain how did you changed this "SemVer Version". It would of great help to me.

**Comment by paulcbetts** [comment]
@sitanshu17 Delete the last digit, so it's of the form `X.Y.Z`

**Comment by sitanshu17** [comment]
@paulcbetts  Thanks a lot for the quick response. But unfortunately I am not able to get the exact file where I need to do this change. Please elaborate. It would be really helpful to me.
Thanks,
Sitanshu

**Comment by paulcbetts** [comment]
It's either your nuspec file or in AssemblyInfo

**Comment by eranotz50** [comment]
I received this error if Squirrel did not find a Releases folder in the same directory it was running on.
i.e. 

C:\Users\KillMe> Squirrel.exe --releasify D:\MyProject\mynuget-1.0.1.nupkg

and Releases was in D:\Releases

**Comment by patricklee90** [comment]
Hi, I resolved the problem by deleted the previous build files in Release folder.

Hope it help

**Comment by smit666** [comment]
> @sitanshu17 Delete the last digit, so it's of the form `X.Y.Z`

Is there any other way? i want to keep version till four digit places.
