### ISSUE TITLE
Need to run code before uninstall

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1243]
I'm building a self-updating service using Topshelf. The Topshelf convention for managing the service installation is:

    MyApp.exe INSTALL
    MyApp.exe UNINSTALL

I'm getting the service installed OK, but uninstallation is failing because the `onAppUninstall` event fires after the uninstall is completed. By the time my code (below) runs, everything has been deleted and a `FileNotFoundException` occurs:

> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Squirrel, Version=1.7.9.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Intexx.Topshelf.Squirrel.Updater.Sample.Main.Main()

Is there a way to run code before the uninstall takes place? Something like `beforeAppUninstall` and `afterAppUninstall` events would be handy if they exist.

    Public Module Main
      Public Sub Main()
        Using oManager = New UpdateManager(UpdateSource)
          SquirrelAwareApp.HandleEvents(onInitialInstall:=Sub(Version)
                                                            ManageApp(InstallActions.Install)
                                                          End Sub,
                                        onAppUninstall:=Sub(Version)
                                                          ManageApp(InstallActions.Uninstall)
                                                        End Sub)
        End Using
      End Sub

      ...

      Private Sub ManageApp(InstallAction As InstallActions)
        Log.Info($"{InstallAction.ToString}ing the service")

        With New Process
          With .StartInfo
            .WorkingDirectory = Environment.CurrentDirectory
            .UseShellExecute = True
            .Arguments = InstallAction.ToString
            .FileName = Assembly.GetExecutingAssembly.Location
            .Verb = "runas"
          End With

          .Start()
        End With
      End Sub

      Public Enum InstallActions
        Install
        Uninstall
      End Enum

      Public ReadOnly Log As ILogger = Configuration.GetEventLogger(GetType(Main).Name)
    End Module

**Comment by paulcbetts** [comment]
You can't really install a service via Squirrel because you need to UAC elevate, and UAC elevation isn't supported. Squirrel's hooks (including the uninstall hook) do run before uninstall takes place like you're asking for, but you can't show a UAC dialog because it will time out after 15 seconds.

**Comment by InteXX** [comment]
@paulcbetts — Actually, my code does elevate properly. That's what the `runas` verb accomplishes. In my experience so far, uninstallation seems to elevate by default. So elevation hasn't been a problem.

Are you certain that `onAppUninstall` fires before uninstallation? Currently I'm paused at the Windows error dialog with the console window displaying the `FileNotFoundException`. No 15-second pause took place.

When I Alt-Tab to File Explorer at the installation folder, I see the `.dead` file, indicating that the app has been uninstalled.

This seems to indicate that `onAppUninstall` has been fired after uninstallation, not before.

**Comment by paulcbetts** [comment]
It will elevate, but if the user doesn't hit "Yes" or "No" in 15 seconds, everything gets deleted. You're most likely getting to the breakpoint after the timeout (it might even be 10 seconds, I can't remember). 

Also, the notion of installing a system-wide service whose source lives in a single user's directory doesn't make much sense - what happens if >1 user installs your app on the same computer?

**Comment by InteXX** [comment]
@paulcbetts 

The error is immediate; there's no pause at all.

I'm using `squirrel_temp` to place all my services in a central location.

**Comment by InteXX** [comment]
@paulcbetts 

BTW, here on GitHub do I need to address you specifically for threads you're already participating in? I don't know whether my practice of doing this is causing you to receive duplicates.

**Comment by InteXX** [comment]
@paulcbetts 

I ran a quick test using a process `cmd /c dir /s /b D:\Services > D:\Logs\Files.txt`, and this is what I got back. So the `Squirrel` assembly is indeed still present when my code runs, which means that `onAppUninstall` is running before uninstall. Just like you said.

I don't know why I ever doubted you, Paul  :-)

    Before:
      D:\Services\IntexxTopshelfSquirrelUpdaterSample
      D:\Services\SquirrelTemp
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\packages
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\Update.exe
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\DeltaCompressionDotNet.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\DeltaCompressionDotNet.MsDelta.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\DeltaCompressionDotNet.PatchApi.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.Core.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.NLog.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.Topshelf.Squirrel.Updater.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.Topshelf.Squirrel.Updater.dll.config
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\IntexxTopshelfSquirrelUpdaterSample.exe
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\IntexxTopshelfSquirrelUpdaterSample.exe.config
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\IntexxTopshelfSquirrelUpdaterSample.xml
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\itxcorlib.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.Mdb.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.Pdb.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.Rocks.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\NLog.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\NuGet.Squirrel.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\SharpCompress.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Splat.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Squirrel.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Topshelf.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Topshelf.NLog.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\packages\IntexxTopshelfSquirrelUpdaterSample-1.0.0-full.nupkg
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\packages\RELEASES
      D:\Services\SquirrelTemp\IntexxTopshelfSquirrelUpdaterSample-1.0.0-full.nupkg
      D:\Services\SquirrelTemp\RELEASES
      D:\Services\SquirrelTemp\SquirrelSetup.log
      D:\Services\SquirrelTemp\Update.exe


    After:
      D:\Services\IntexxTopshelfSquirrelUpdaterSample
      D:\Services\SquirrelTemp
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\packages
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\Update.exe
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\DeltaCompressionDotNet.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\DeltaCompressionDotNet.MsDelta.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\DeltaCompressionDotNet.PatchApi.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.Core.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.NLog.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.Topshelf.Squirrel.Updater.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Intexx.Topshelf.Squirrel.Updater.dll.config
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\IntexxTopshelfSquirrelUpdaterSample.exe
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\IntexxTopshelfSquirrelUpdaterSample.exe.config
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\IntexxTopshelfSquirrelUpdaterSample.xml
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\itxcorlib.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.Mdb.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.Pdb.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Mono.Cecil.Rocks.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\NLog.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\NuGet.Squirrel.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\SharpCompress.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Splat.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Squirrel.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Topshelf.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\app-1.0.0\Topshelf.NLog.dll
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\packages\IntexxTopshelfSquirrelUpdaterSample-1.0.0-full.nupkg
      D:\Services\IntexxTopshelfSquirrelUpdaterSample\packages\RELEASES
      D:\Services\SquirrelTemp\SquirrelSetup.log

**Comment by InteXX** [comment]
@paulcbetts 

The solution to this was as simple as calling `Process.WaitForExit()` after `Process.Start()`.

So I agree: using Squirrel on Windows Services is forcing a round peg in a square hole...  but it can be done.

**Comment by goyalsachin22** [comment]
@paulcbetts , Is there a way to stop that 15 seconds timer. I want to show user a GUI of Yes/No buttons and take some actions based on Yes/No select and then proceed with the uninstall of my application.

**Comment by InteXX** [comment]
@ToWhomItMayConcern

**UPDATE**

It turns out that the `Process.Start()` call isn't needed at all, nor are the Squirrel hooks (although you're free to use them for other reasons should you need them). The `Topshelf.Squirrel.Windows` code base includes functionality to elevate itself and install/uninstall the service. The consuming code shouldn't do it.

That functionality was broken in my case because I got bit by C#'s case sensitivity when converting to VB. Once I identified the problem and fixed it, it was plain to see that successful service install/uninstall is included in the box. (I haven't tested yet for UAC dialog expiration, but that's next.)

This clarifying note is for others who may come across my comments above advocating the `Process.Start()` call to get the job done. You don't need it.

**Comment by paulcbetts** [comment]
> , Is there a way to stop that 15 seconds timer. I want to show user a GUI of Yes/No buttons and take some actions based on Yes/No select and then proceed with the uninstall of my application.

There is explicitly **no** way to do this, by design. Squirrel uninstallers should not present UI of any kind.

**Comment by goyalsachin22** [comment]
@paulcbetts ,
But i'm able to show to show messageBox (I know that will go away after 10 seconds). But why i cannot show a custom window. below is my code.


public static void PrepareUninstallhook()
        {
            log.Info("Creating SquirrelAwareApp event handlers...");
            var url = Properties.Settings.Default.UPDATE_URL;
            using (var mgr = new UpdateManager(url))
            {
                 SquirrelAwareApp.HandleEvents(
                  onAppUninstall: v =>
                  {
//commented part working. I'm able to show the messagebox. ( I know it will go away after 10 seconds).
                   //MessageBoxResult result = MessageBox.Show("Do you want to do a complete uninstall", "Installation Options", MessageBoxButton.YesNo, MessageBoxImage.Question);
                      //if (result != MessageBoxResult.Yes)
                      //{
                      //    log.Info("Keeping the setting file during uninstallation");
                      //    return;
                      //}
                      //else
                      //{
                      //    log.Info("Doing the complete uninstall");
                      //}
//below not working
                    uninstallerwindow window = new uninstallerwindow ();
                     window.Show();

                  });
            }
        }
