### ISSUE TITLE
error when the application name start by a number (candle)

### ISSUE THREAD

**Issue by mbsanchez** [Squirrel/Squirrel.Windows#1244]
I'm receiving a candle error, when i try to build the installer for my application called 3OnLine.exe. The error message is the following:
   
    Error:
    System.AggregateException: Se han producido uno o varios errores. ---> System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out  ".\release\Setup.wixobj" ".\release\Setup.wxs"'

    Output was:
    Setup.wxs
    .\release\Setup.wxs(3) : error CNDL0108 : The Product/@Version attribute's value, '!(bind.FileVersion.3OnLine.exe)', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
    .\release\Setup.wxs(3) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
       en Squirrel.Update.Program.<createMsiPackage>d__21.MoveNext()
       --- Fin del seguimiento de la pila de la excepción interna ---
       en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       en System.Threading.Tasks.Task.Wait()
       en Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
       en Squirrel.Update.Program.executeCommandLine(String[] args)
       en Squirrel.Update.Program.main(String[] args)
       en Squirrel.Update.Program.Main(String[] args)
       ---> (Nº de excepción interna 0) System.Exception: Failed to compile WiX template, command invoked was: 'candle.exe -nologo -ext WixNetFxExtension -out ".\release\Setup.wixobj" ".\release\Setup.wxs"'

    Output was:
    Setup.wxs
    .\release\Setup.wxs(3) : error CNDL0108 : The Product/@Version attribute's value, '!(bind.FileVersion.3OnLine.exe)', is not a valid version.  Legal version values should look like 'x.x.x.x' where x is an integer from 0 to 65534.
    .\release\Setup.wxs(3) : error CNDL0010 : The Product/@Version attribute was not found; it is required.
        en Squirrel.Update.Program.<createMsiPackage>d__21.MoveNext()<---

I've googled about this error and i've found this thread: https://sourceforge.net/p/wix/bugs/2849/ and they explain why it happens. Based on that i've modified the source of squirrel, specifically, the **Update** project  (Program.cs), and method **createMsiPackage**: changing this code:

    var templateData = new Dictionary<string, string> {
        { "Id",  package.Id },
        { "Title", package.Title },

To this one:

    var templateData = new Dictionary<string, string> {
        { "Id",  Regex.IsMatch(package.Id, @"^\d")?"_":"" + package.Id },
        { "Title", package.Title },
 

After that the issue has disappear, i suggest you analyze this issue and update the code with my changes or maybe you can propose a better solution.

![image](https://user-images.githubusercontent.com/143726/35486646-5573e466-0471-11e8-9e9c-1ed32d26024e.png)

Thank you!!

**Comment by paulcbetts** [comment]
Thanks for tracking this down. I think the current recommendation would be to just not start your app with a number, but this write-up will definitely help people to figure out alternate solutions (another one is to just edit your `template.wxs` file to include the leading `_`)
