### ISSUE TITLE
Error "System.Threading.AbandonedMutex" when updating to the latest version using Squirrel 1.7.5

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1247]
Hello,

I'm using Squirrel 1.7.5 and I'm getting the following error when trying to update to the latest version:
  
  _Problem Event Name: CLR20r3
  Problem Signature 01: MyApp.exe
  Problem Signature 02: 18.1.9160.0
  Problem Signature 03: 5a6a101c
  Problem Signature 04: Squirrel
  Problem Signature 05: 1.7.5.0
  Problem Signature 06: 5939a786
  Problem Signature 07: 163
  Problem Signature 08: 14
  Problem Signature 09: System.Threading.AbandonedMutex
  OS Version: 6.3.9600.2.0.0.272.7
  Locale ID: 1033
  Additional Information 1: a9db
  Additional Information 2: a9dbfcc7d4172d39e3996600cfe404a8
  Additional Information 3: 394f
  Additional Information 4: 394f3f69607a506bdd4f94e197cc1136_

This happens when I'm doing the following scenario:
I have the 1.0.0 version installed and then I'm adding 2 more updates, 1.0.1 and 1.0.2. Starting the application, it crashes and causes the above error. However, if my installed application is at 1.0.1 version and I run it, it gets the latest 1.0.3 version with no problems. 

Does anyone have any idea why is this happening? Did anyone have the same issue? If yes, can you help me resolve it because otherwise it seems that I cannot use Squirrel at all since the updates do not get installed at all.

Thanks in advance.

**Comment by Thieum** [comment]
@SissiKonsta It looks like you are not disposing the result from the update manager. There has been similar issues reported in #587 . An updated doc proposal can be found in #1396 also.

**Comment by shiftkey** [comment]
Closing this out as #587 has a longer discussion about what's happening underneath, and the docs for #1396 should help with clarifying things.
