### ISSUE TITLE
Generated Launcher has false positives

### ISSUE THREAD

**Issue by ZARk-be** [Squirrel/Squirrel.Windows#1249]
Hello

I've had customers complain that the software contained viruses.

I've just run through virusTotal, and the launcher gives this : [https://www.virustotal.com/#/file/f3c9341137049bfdff6b89b62fc3903dc5e5533316abca5613cd047e345a6403/detection](https://www.virustotal.com/#/file/f3c9341137049bfdff6b89b62fc3903dc5e5533316abca5613cd047e345a6403/detection)

I've updated to latest Squirrel, recompiled, installed new version, and same false positives.

The user complaining is actually using BitDefender.

What can i do ?

**Comment by paulcbetts** [comment]
Are you signing your installer? Signing your installer will fix these problems

**Comment by WolfspiritM** [comment]
@paulcbetts I'm having the same problem. I don't think self-signed certs work so am I right that I have to buy a certificate for >200$ per year just to make sure I can distribute my app which I don't make and don't want to make any money with to others without worrying about AVs interrupting? I know that's not a squirrel problem but it's kind of bizzare in general.

**Comment by paulcbetts** [comment]
@WolfspiritM Yep, though you can get a cert for ~$80/yr, but yeah - you can either tell people to ignore their AV, or you can pay the money, this is why 3rd party Antivirus is frustrating and terrible.

**Comment by ZARk-be** [comment]
@paulcbetts  > Which cert would you recommend ?
