### ISSUE TITLE
Add release date to RELEASES

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#125]
For one of our internal requirements I need to add the release date to the RELEASES folder. Interested in a PR?

**Comment by GeertvanHorrik** [comment]
Are you interested in accepting this? Otherwise we can better close this issue to keep the project a bit organized.

**Comment by GeertvanHorrik** [comment]
Hi @paulcbetts , would you be open for a PR that would include this feature (without any breaking changes)?

**Comment by shiftkey** [comment]
> would you be open for a PR that would include this feature (without any breaking changes)?

@GeertvanHorrik not sure if this is something you're still interested in, but I'd love to hear about what you had in mind here before diving into a PR.

But generally speaking, this is still my current thinking on it:

> I'd rather not change the RELEASES file format

**Comment by GeertvanHorrik** [comment]
Hi @shiftkey , I would definitely be willing to help out here, we forked Squirrel.Windows for quite a while so I am a bit familiar with the source code. As Anais suggested, it could be a breaking changes so we need to tread carefully here.

We don't need it as much as we used to, so I'm ok with closing this as well.

**Comment by shiftkey** [comment]
@GeertvanHorrik if others were requesting this I'd be down for a bigger discussion, but I don't feel up to speed enough to entertain a breaking change like this.

Let's close this out for the moment as it's great that you were able to workaround it.
