### ISSUE TITLE
Application doesn't launch after install... but only from the folder Squirrel created in AppData

### ISSUE THREAD

**Issue by hauckwill** [Squirrel/Squirrel.Windows#1251]
If I try to run the EXE located in C:\Users\Will\AppData\Local\VRLiteBuilder\app-1.0.0, it shows up in the task manager but absolutely nothing happens. No main form -- nothing.

If I move the app-1.0.0 _anywhere_ outside of the C:\Users\Will\AppData\Local\VRLiteBuilder\ folder, it works!

Any ideas? I have disabled the UpdateManger altogether with no luck, so it isn't that...

**Comment by paulcbetts** [comment]
Not sure, I would try attaching a debugger and see what the app does

**Comment by hauckwill** [comment]
Strangely enough, restarting my computer fixed it.
