### ISSUE TITLE
How to structure application for debugger in Visual Studio?

### ISSUE THREAD

**Issue by lawrencetvo** [Squirrel/Squirrel.Windows#1259]
Apologies if this has been asked before but how would you structure the application so you can launch it in the debugger and not to release?

I have the UpdateManager code commented out since it always launches an Update.exe not found error when I try to debug my code.

Thanks.

**Comment by lukeskinner** [comment]
Here are 2 ways you could do this that I've used before. 

Option 1 - If you have a debugger attached to your application it will skip checking for updates.

```c#                   
if (System.Diagnostics.Debugger.IsAttached)
{
	using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
	{
		await mgr.UpdateApp();
	}
}
```

Option 2 - If you compile your code in the Debug configuration it will skip checking for updates. In the Release configuration it will still check for updates.

```c#                   
Boolean checkForUpdates = true;

#if DEBUG
checkForUpdates = false;
#endif

if (checkForUpdates)
{
	using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
	{
		await mgr.UpdateApp();
	}
}
```

I've gone with option 2 in my projects using Squirrel - you need to make sure you never make a squirrel release with a Debug built version of your application. I've setup my squirrel releases/builds on a build server to ensure that it's never a Debug build.

**Comment by Thieum** [comment]
@lawrencetvo did @lukeskinner explanations helped you? If it solved your issue, you can close this.
