### ISSUE TITLE
Separate initial installer?

### ISSUE THREAD

**Issue by Yavari** [Squirrel/Squirrel.Windows#1260]
I have tested Squirrel for a week now and everything seems to work well. My packages takes around 100Mb and I am therefor looking for an option to distribute a small installer that grabs the latest package from my server on the initial installation and then from then on use the auto update ability that comes with Squirrel. 

Is there already an option for this?

I am otherwise thinking of creating a package 1.0.0 that only have the Squirrel code to get the newest package. Would that be an good option?

Is it possible to create a console application that would do this? So that I have my WPF application called App with its own version numbers and then a App.Installer package that I distribute that grabs the latest App package to install?

**Comment by wardboumans** [comment]
If it's only initial install you can create a program that just downloads setup.exe from your url (the url doesn't change for future releases) and run it. Setup.exe is always the latest version, its recreated every time you package your app.

**Comment by Thieum** [comment]
@Yavari did you try using Setup.exe as suggested?
