### ISSUE TITLE
Security breach

### ISSUE THREAD

**Issue by aliniknejad** [Squirrel/Squirrel.Windows#1261]
Hello,

I was trying to clone your repo today and suddenly got a security warning from my McAfee anti-virus. Apparently somehow it downloaded a 'Setup.exe' file in the root folder, which contained 'Artemis!B6AE8E5CD382'. I am puzzled as to how that happened, as that file doesn't seem to exist in GitHub. Possibly something that came through the submodules? 

Cheers,
Ali

**Comment by paulcbetts** [comment]
This is a false positive, you can ignore it.

**Comment by jzabroski** [comment]
For some context: https://service.mcafee.com/webcenter/portal/cp/home/articleview?articleId=TS100414
