### ISSUE TITLE
Windows 7/8/10 installation failed suddenly

### ISSUE THREAD

**Issue by danielravina** [Squirrel/Squirrel.Windows#1267]
Hey there,

I'm posting an issue here to try and investigate a weird error we're getting with our app. We're not sure it's directly related to Squirrel but worth giving it a shot here.

Details on the issue are here: https://github.com/headsetapp/headset-electron/issues/129

In short:
When starting the install process this window pops-up immediately instead of the loading gif.
<img width="1440" alt="37247921-c743d700-2478-11e8-9be6-f5b25430cd61" src="https://user-images.githubusercontent.com/3150871/37250291-22a7fdf8-24ae-11e8-9809-dc4e7f17a603.png">

The error we're seeing is:
<img width="359" alt="screen shot 2018-03-10 at 9 29 21 pm" src="https://user-images.githubusercontent.com/3150871/37250262-7bf91fb4-24ad-11e8-9c36-b6b054261e2f.png">
But the app is indeed installed without a problem

Not sure if it helps but we're using `electron-squirrel-startup` https://github.com/headsetapp/headset-electron/blob/master/windows/index.js#L6. 

Here are some example logs from users which I can't really tell where the problem is:
https://pastebin.com/ju3J1efC
https://github.com/headsetapp/headset-electron/files/1800001/headset.log
https://github.com/headsetapp/headset-electron/files/1799880/SquirrelSetup.log

If you have any idea of what could be the problem, please let me know.

Thank you so much!

Daniel

**Comment by paulcbetts** [comment]
Squirrel is calling your app with `--squirrel-install` and it's failing. Try running it yourself with the install parameters and make sure it runs instantly and exits with a code of zero

**Comment by danielravina** [comment]
Thanks! when running `--squirrel-install` I'm getting this error:
```
$ ./headset.exe --squirrel-install

#
# Fatal error in d:\build\src\v8\src\handles.h, line 217
# Check failed: (location_) != nullptr.
#

==== C stack trace ===============================

v8_inspector::protocol::Debugger::API::SearchMatch::fromJSONString [0x6E                                                          95B2F0+102320]
v8::internal::interpreter::Bytecodes::ScaleForUnsignedOperand [0x6E73751                                                            3+8323]
v8::internal::Runtime::FunctionForId [0x6E76D6D8+7160]
Segmentation fault
```

any clues?..
