### ISSUE TITLE
File Extensions and elevated user how ? 

### ISSUE THREAD

**Issue by donnib** [Squirrel/Squirrel.Windows#1270]
Hi,
I need to register file extensions for my app and that can only be done as elevated user. If i run the setup.exe as elevated user i can see the log says `2018-03-13 09:59:16> Program: Starting Squirrel Updater: --install . --rerunningWithoutUAC` but why ? How can i overcome this ?

/donnib

**Comment by stefanolson** [comment]
Because you are running in the user context only, you can set file extensions for the user context only.  No need to set it across all users because they won't be able to run the program anyway.

**Comment by paulcbetts** [comment]
Yep, Squirrel apps never elevate!

**Comment by donnib** [comment]
@stefanolson thank you, i was not aware there was even a CURRENT USER for file associations so now that i know that i don't need elevated user which is great.
