### ISSUE TITLE
Gitter or Discord chat channel ?

### ISSUE THREAD

**Issue by donnib** [Squirrel/Squirrel.Windows#1271]
@paulcbetts have you considered above ? I think it would be a great idea to have a place for support/discussion no ?

**Comment by Logikgate** [comment]
There's already a Slack channel for Squirrel, the below link has information on joining

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/contributing/contributing.md

**Comment by donnib** [comment]
@Logikgate yes but that's not what i am after. I want a place for support / discussion and not for contributing which is the case with the Slack channel.

**Comment by jacksonisiah** [comment]
wouldn't doubt that you could get help in that slack channel. 

don't feel the need for anything else.

**Comment by Thieum** [comment]
duplicate of #9
