### ISSUE TITLE
Squirrel creates a copy of my app to start my app

### ISSUE THREAD

**Issue by MrBjorn** [Squirrel/Squirrel.Windows#1273]
Squirrel creates an exe with same info as my app, that just launches the real exe. Our app cant be started twice, has a test at startup, that is now triggered, when a "copy" of our app starts first. We dont want any changes to our app, or how it is started. We just want to install our app, i.e. copy our files and have a shortcut to the real app.

This was not mention anywhere in the documentation, it describes another scenario. 

Anyway to remove this "slave" app?

**Comment by paulcbetts** [comment]
This has nothing to do with the execution stub, your app is being launched twice because of Squirrel hooks, check out the documentation (or check the command-line parameters at each launch, you'll find that they are different)

**Comment by MrBjorn** [comment]
I assume you mean the shortcut app with "execution stub" ? I have not added any Squirrel code yet in my program.cs. Just want to have a clean install and start my app. But the shortcut starts my app, close it, and restart my app again. 

Why does the shortcut launch my app twice?

The documentation here says:

**Comment by teamboyd** [comment]
I have the same issue.  My install adds a desktop shortcut like @MrBjorn mentions:

Target:  c:\users\johndoe\AppData\Local\MyApp\MyApp.exe

The shortcut does not work either.  When you try to open the shortcut the screen just flashes and nothing opens.

The documentation at https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/install-process.md states a shortcut like this will be created:

Target:  c:\users\johndoe\AppData\Local\MyApp\Update.exe --processStart MyApp.exe

If I manually create a shortcut like this, it works, but the installer does not create this shortcut as the documentation states.
