### ISSUE TITLE
FetchReleaseNotes() returns 0

### ISSUE THREAD

**Issue by donnib** [Squirrel/Squirrel.Windows#1274]
Hi,
First of all this method is not documented or at least i couldn't find it. I am calling it but i don't get the release notes returned. The method does not fail it's just that i get nothing back. My nuget pack has one word in the release note so it should be valid text. Any ideas whayt might be wrong ? 

Needless to say but the ReleasesToApply is 1 so there is one release. I have a feeling this might not work if the NuGet pack is not locally downloaded which doesn't make sense. The release note should be available before update.

/donnib

**Comment by lukeskinner** [comment]
I haven't used the FetchReleaseNotes() method before but there's not much code to see how it works.

It looks like this feature does require the NuGet package to be downloaded - the code in the 2nd part I've copied below tries to make a ZipPackage from the local package it's downloaded. If it's not there I assume it'll throw an exception which is then caught in the 1st part of the code. 

I'm not sure how you would fix this in Squirrel - there's not a simple fix I can think of. 

I would either download the releases beforehand or look at fetching your release notes outside of Squirrel - i.e. make your own separate webservice call that gets the release notes for that specific version. 



1. Your application calls FetchReleaseNotes
```c#
    public Dictionary<ReleaseEntry, string> FetchReleaseNotes()
        {
            return ReleasesToApply
                .SelectMany(x => {
                    try {
                        var releaseNotes = x.GetReleaseNotes(PackageDirectory);
                        return EnumerableExtensions.Return(Tuple.Create(x, releaseNotes));
                    } catch (Exception ex) {
                        this.Log().WarnException("Couldn't get release notes for:" + x.Filename, ex);
                        return Enumerable.Empty<Tuple<ReleaseEntry, string>>();
                    }
                })
                .ToDictionary(k => k.Item1, v => v.Item2);
        }
```

2. For each release to apply it calls this method below internally.
```c#
   public string GetReleaseNotes(string packageDirectory)
        {
            var zp = new ZipPackage(Path.Combine(packageDirectory, Filename));
            var t = zp.Id;

            if (String.IsNullOrWhiteSpace(zp.ReleaseNotes)) {
                throw new Exception(String.Format("Invalid 'ReleaseNotes' value in nuspec file at '{0}'", Path.Combine(packageDirectory, Filename)));
            }

            return zp.ReleaseNotes;
        }
```

**Comment by donnib** [comment]
Ok so i succeeded by calling DownloadReleases beforehand then i get the releasenotes back but yeah it's not documented anywhere however now i have another problem. ->https://github.com/Squirrel/Squirrel.Windows/issues/1275
