### ISSUE TITLE
Install Location Changes on Update

### ISSUE THREAD

**Issue by MiddleTommy** [Squirrel/Squirrel.Windows#1276]
When you install an update from Squirrel it creates a new folder. This causes the shortcut on the Taskbar to open a pinned program as a separate window with a new taskbar button resulting in having your program on the task bar twice when the program is open.

Also the data stored in IsolatedStorageFile.GetUserStoreForAssembly(); is erased as the assembly is in a new location.

**Comment by paulcbetts** [comment]
This is fundamentally how Squirrel is able to update an application while it's still running. To mitigate the double taskbar icon, you can call SetCurrentProcessExplicitAppUserModelID with the value `com.squirrel.YOUR_NUGET_PACKAGE_ID.YOUR_EXE_NAME_WITHOUT_DOT_EXE`

So, for a NuGet package ID "MyProduct" with a program "MyApp.exe", the string is:

`com.squirrel.MyProduct.MyApp`
