### ISSUE TITLE
LoadingGif during update

### ISSUE THREAD

**Issue by spasha** [Squirrel/Squirrel.Windows#1277]
Hi,

First off, Squirrel is an excellent product kudos to all!!!

During initial setup, I am loading an animated GIF file.  This has been working and when a customer runs setup.exe, the animated GIF file is displayed until the application starts.  However, I was under the assumption that the animated GIF would also show during the update process.  Should it? or do I need to specify that or code for that?  When a new version is released, it can take 7-8 seconds for the update process to complete and the user is not seeing any feedback/activity.  I was hoping that there would be a way to show the animated GIF file (just like they see it during initial setup).

Below is my CheckForUpdates code:

        private static void CheckForUpdates(string updateUrl)
        {
            try
            {
                using (var mgr = new UpdateManager(updateUrl))
                {
                    var updates = mgr.CheckForUpdate();
                    updates.Wait();
                    if (updates.Result.ReleasesToApply.Any())
                    {
                        SencoMessageBox.UseCustomImage = true;
                        SencoMessageBox.CustomImage = Properties.Resources.SatelliteDownArrow32;
                        SencoMessageBox.ShowMessage(null, "There are updates available to Stellar PM. The application will automatically start when updates are completed.", "Updates Available!", MessageBoxButtons.OK, MessageBoxIcon.Asterisk, MessageBoxDefaultButton.Button1, string.Empty, false, "Click Here To Update");
                        SencoMessageBox.UseCustomImage = false;

                        var lastVersion = updates.Result.ReleasesToApply.OrderBy(x => x.Version).Last();
                        mgr.DownloadReleases(new[] { lastVersion }).Wait();
                        mgr.ApplyReleases(updates.Result).Wait();
                        mgr.UpdateApp().Wait();

                        BackupSettings();

                        UpdateManager.RestartApp();
                    }
                }
            }
            catch (Exception ex)
            {
                Logger.LogException(ex);

            }
        }

Thanks,
Steve

**Comment by paulcbetts** [comment]
> However, I was under the assumption that the animated GIF would also show during the update process. Should it? 

Definitely not! We want updates to be silent and in the background. You should choose in your app the best way you should surface that an update has occurred (perhaps not at all even!)
