### ISSUE TITLE
Setup.exe infected?

### ISSUE THREAD

**Issue by kribensa** [Squirrel/Squirrel.Windows#1280]
When I try to use `Install-Package Squirrel.Windows` to install Squirrel from Nuget, my antivirus blocks the download of `.nuget\packages\squirrel.windows\1.7.9\tools\Setup.exe`
It reports it is infected with gen:Variant.Razy.276845

Is this a false positive? Or does it need fixing?

**Comment by paulcbetts** [comment]
Please search through the issues for the 1203412304 times that this has been reported and indeed confirmed as a false positive.

**Comment by kribensa** [comment]
Thanks - I did search for "Razy" thinking that be sufficient and targeted, but there were no hits

**Comment by senprime** [comment]
You are being targeted do not use the spot reinstalled Discord otherwise they're going to be using your machine for mining
