### ISSUE TITLE
Handling VC redistributables

### ISSUE THREAD

**Issue by MihaMarkic** [Squirrel/Squirrel.Windows#1281]
So far I didn't find a definitive answer, hence the question here.
How does one run vc redistributables at installation (i.e. if your c# app requires them)?
I see these two options:
a) just include required dlls
b) use SquirrelAwareApp.HandleEvents (this might be tricky if your app requires redistributables to even start)

**Comment by paulcbetts** [comment]
The only option is A, you cannot launch vcredist.exe from a Squirrel hook. The good news is that option A is officially supported by Microsoft for quite some time

**Comment by MihaMarkic** [comment]
Ok, thanks. There is a drawback to the option, though. It won't get updated if somebody installs (patched) version of redistributables, but I can live with that.
