### ISSUE TITLE
Verify Authenticity of the nupkg files.

### ISSUE THREAD

**Issue by mbsanchez** [Squirrel/Squirrel.Windows#1288]
Is there some security build in squirrel that checks if the downloaded nupkg files are packages signed by me already?, I mean what if somebody would break in my servers/website and upload a own nupkg file and replace the RELEASE file with sha1?

I read from the update process of squirrel: Download & Verify Update Packages - if there is a new release, the UpdateManager determines whether to download the deltas or the latest full package (by calculating which one requires less total downloading) to update to the current version. The packages are compared against their SHA1 in the RELEASES file for verification, but if someone put his own nupkg file and change the SHA1 in the release file, a virus can be propagated to all machines using my application.

Is there another verification based maybe on some signature of the files?

**Comment by paulcbetts** [comment]
> Is there another verification based maybe on some signature of the files?

No, there is not, if someone breaks into your servers you're owned. If you want to add your own mechanism on top of what Squirrel provides to do signing / authentication, you definitely can, but "The server being owned" is not really the kind of threat that Squirrel is built to defend against.
