### ISSUE TITLE
How to not delete appdata folder on install?

### ISSUE THREAD

**Issue by fabsenet** [Squirrel/Squirrel.Windows#1289]
Hi,

i have many installations of my app v1 (without squirrel) and it uses .net settings. 

These settings are stored in 

`...\AppData\Local\adrilight\adrilight.exe_Url_vu0iivwqd3srduhwn4jr1qqgp2drs4d1\1.0.0.1\user.config`

I made a V2 of my app with squirrel and it deletes everything in `\AppData\Local\adrilight\` before installing. this wipes all existing settings.

I read many issues about the install location and most of the docs but I found no answer or idea so far.

What can I do to prevent this behavior? I really do not want to loose the settings of each user.

Thanks

**Comment by paulcbetts** [comment]
You should ship one more revision of your v1 app that moves the settings to some other place, wait awhile, then switch to Squirrel. Alternatively, you could change the package name of your application, then v2 could just grab the data out

**Comment by fabsenet** [comment]
i went with changing the package name. it works.
