### ISSUE TITLE
When onAppUpdate callback fires?

### ISSUE THREAD

**Issue by SteveMavic** [Squirrel/Squirrel.Windows#1293]
I'm pretty new with Squirrel that's why I would like to ask - when onAppUpdate callback is firing? 
It's after UpdateManager.UpdateApp() method called or before, when UpdateManager.CheckForUpdate() called?

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/9ab30c21a0b6397006f716d54ca13259da247a68/src/Squirrel/SquirrelAwareApp.cs#L17 should answer this question
