### ISSUE TITLE
Squirrel handles installation of wrong .NET Framework package

### ISSUE THREAD

**Issue by SteveMavic** [Squirrel/Squirrel.Windows#1297]
So I've tried to install my application on clean Virtual machine (without any .NET Frameworks) and I got this error
![image](https://user-images.githubusercontent.com/27968645/39213627-6278d7e0-4812-11e8-9a7b-bcde0419efc9.png)

However, in NuGet Package Explorer I choosed net461 as .NET folder, but during installation proccess Squirrel installer suggested to download and install .NET 4.5.2 as seen below
![image](https://user-images.githubusercontent.com/27968645/39213988-56e2f932-4813-11e8-8be5-2e3653b6678a.png)

**Comment by paulcbetts** [comment]
Squirrel doesn't care about what folder you put your code in with the NuGet package, put all your code in `lib/net45` even though your code is v4.6.1. You need to pass a flag to Squirrel.exe to pin the .NET Framework version number
