### ISSUE TITLE
[Request] Squirrel Auto Background Updating

### ISSUE THREAD

**Issue by zero77** [Squirrel/Squirrel.Windows#1298]
When first started can you please get Squirrel to first check for updates for its self.
Mabey, using a separate process as it may make things a bit more stable.
Thanks

**Comment by bddckr** [comment]
You have to do checks for updates yourself. This is seen in the documentation:
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/1-integrating.md#basic-squirrelwindows-update-code

**Comment by paulcbetts** [comment]
Squirrel self-updates along with your new app packages automatically. As @bddckr suggests, Squirrel is a Library, it will only do stuff on your behalf, it doesn't do automatic things like ClickOnce
