### ISSUE TITLE
Use Squirrel for updates with a different initial installer.

### ISSUE THREAD

**Issue by KentJohnsonW** [Squirrel/Squirrel.Windows#1299]
We are looking into moving to Squirrel from a different installer (Inno setup). However, we have a license agreement and privacy policy that they would need to agree to before install. It seems like with Squirrel the application is installed before we can handle any events, so by the time they agree it's already installed. Is it possible to use Inno for the initial install (forcing the agreement, and doing other initial install steps) as long as we write it to AppData, but then use Squirrel to do seamless updates?

**Comment by paulcbetts** [comment]
> However, we have a license agreement and privacy policy that they would need to agree to before install. 

You can just move this into your application - if users don't accept, just close. You don't need to run this during setup.

**Comment by senprime** [comment]
There is no license it's all been hacked I have the error logs screenshots and everything already reported and posted
