### ISSUE TITLE
Icon two times in Windows Program and Features

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#130]
I just created an installer.
When I install the app  using the Setup.exe appears the icon in the Desktop and in the control panel.

The app has this in its code

```
 using (var mgr = new UpdateManager(@"https://URL.com", "ID", FrameworkVersion.Net45))
{
   await mgr.UpdateApp();
 }
```

The strange behavior is that when the the code above runs, the program appears two times in the control panel.
![image](https://cloud.githubusercontent.com/assets/1263856/5066110/4d79eac6-6dfc-11e4-8167-e0e8ccd585c7.png)

Why could this happen?

**Comment by Adeshtalakane** [comment]
How to update the same package in squirrel again & again without new version. Eg: I want to update the v1.0.1 two times? is there any possibility.
