### ISSUE TITLE
Install doesn't create desktop icon.

### ISSUE THREAD

**Issue by KentJohnsonW** [Squirrel/Squirrel.Windows#1300]
I made my application Squirrel aware, and am using the SquirrelAwareApp.HandleEvents code to create the shortcut, but no shortcut is created. Code is as follows..
`                    SquirrelAwareApp.HandleEvents(
                         onInitialInstall: v => mgr.CreateShortcutForThisExe(),
                         onAppUpdate: v => mgr.CreateShortcutForThisExe(),
                         onAppUninstall: v => mgr.RemoveShortcutForThisExe(),
                         onFirstRun: () => ShowTheWelcomeWizard = true);
`
Attached is the log from the install.
[SquirrelSetup.log](https://github.com/Squirrel/Squirrel.Windows/files/1949013/SquirrelSetup.log)

It did create a shortcut before I made my app Squirrel aware (along with shortcuts for the additional exes that I didn't want shortcuts for).

I thought this might be partially because we use a tool to obfuscate and merge assemblies and my resulting exe is named something different from what it is in the actual project. So I rebuilt everything using the same names and the result is the same, no shortcut is created. Here is a log from that if it helps...
[SquirrelSetup.log](https://github.com/Squirrel/Squirrel.Windows/files/1952224/SquirrelSetup.log)

**Comment by KentJohnsonW** [comment]
This was all probably because my assembly is signed and Squirrel doesn't support that. I'll close the issue, looks like Squirrel probably won't work for us for now. I may try it on a different project at some point later.

**Comment by paulcbetts** [comment]
> This was all probably because my assembly is signed and Squirrel doesn't support that.

This isn't true at all, the logs say that your Squirrel Hook wasn't exiting properly and timed out
