### ISSUE TITLE
Unable to notify "backward" when application have been updated

### ISSUE THREAD

**Issue by SteveMavic** [Squirrel/Squirrel.Windows#1302]
I've created StartUp window in which I'm handling Squirrel events and creating new MainWindow instance, but when I want to update application and notify "backward" _(MainWindow to let user decide on restarting app by showing button)_ but event _(ApplicationUpdated)_ isn't firing; Nothing is printed out in Output , however MessageBox is showing up normally.

**StartUpWindow.xaml.cs**

        public static event EventHandler ApplicationUpdated;
        protected virtual void OnApplicationUpdated()
        {
            Console.WriteLine("OnApplicationUpdated from StartUp");
            ApplicationUpdated?.Invoke(this, EventArgs.Empty);
        }

        public void OnApplicationUpdate(Version version)
        {
            using (var manager = new UpdateManager(updateUrl))
            {
                manager.CreateShortcutsForExecutable(appFullName, ShortcutLocation.Desktop, true);
                manager.CreateShortcutsForExecutable(appFullName, ShortcutLocation.StartMenu, true);
                manager.CreateShortcutsForExecutable(appFullName, ShortcutLocation.AppRoot, true);

                manager.RemoveUninstallerRegistryEntry();
                manager.CreateUninstallerRegistryEntry();

                OnApplicationUpdated(); 
            }

            System.Windows.Forms.MessageBox.Show("OnApplicationUpdated");
        }

**Comment by paulcbetts** [comment]
You should read the docs more about how Squirrel events work, you're misunderstanding them. Have a look and if you're still stuck comment on this bug again

**Comment by SteveMavic** [comment]
Okay, as I see it onAppUpdate is being called when UpdateManager.UpdateApp has been called and new version of application has been downloaded, am I right?

What I want to achieve is to notify another view (not the one that handles Squirrel events) that new version is ready to apply and for example ask if application should be restarted now.

And since my own created event that notifies main view about new update will never fire up I'd like to ask if does make sense to handle events (SquirrelAwareApp.HandleEvents) in second class (first in StartUpWindow and second one in MainWindow) just for onAppUpdate event?

**Comment by paulcbetts** [comment]
> Okay, as I see it onAppUpdate is being called when UpdateManager.UpdateApp has been called and new version of application has been downloaded, am I right?

No. onAppUpdate is the place where you write code to handle the update process, that's all. Squirrel is starting a _new process_ of your app, that is different than the one that is currently running.

> What I want to achieve is to notify another view (not the one that handles Squirrel events) that new version is ready to apply and for example ask if application should be restarted now.

Your app is the one triggering the update check, you don't need an event :) Just handle it after you trigger the update.

**Comment by SteveMavic** [comment]
So my event have been fired up, but in new process so I would never handle it because of that, is that right? So that explains why I could see mbox, but not output of Console.WriteLine
