### ISSUE TITLE
Specify custom installation directory

### ISSUE THREAD

**Issue by DRSDavidSoft** [Squirrel/Squirrel.Windows#1303]
How can I set the Installation directory when installing a Squirrel Package?

The Squirrel installer on Windows just assumes All's Good ™ with `%APPDATA%` and installs the program right there without asking me, which I find very rude. I expect to set where I want the package to be installed, e. g. **`D:\Program Files`**. I didn't find anything regarding this in the Docs, or any existing issues. Is this possible?

**Comment by MarshallOfSound** [comment]
>  I didn't find anything regarding this in the Docs, or any existing issues

One could make a solid case that you didn't search very hard 🤔 

* https://github.com/Squirrel/Squirrel.Windows/issues/1002
* https://github.com/Squirrel/Squirrel.Windows/issues/1282
* https://github.com/Squirrel/Squirrel.Windows/issues/696

Took 2 minutes to find those 3 examples 😄

**Comment by DRSDavidSoft** [comment]
@MarshallOfSound I literally took 20 mins to search for this, I'm ashamed didn't find those issues. Thanks for pointing them out!
