### ISSUE TITLE
.net 4.7.2 support

### ISSUE THREAD

**Issue by dealproc** [Squirrel/Squirrel.Windows#1305]
Noticed this twitter feed: https://blogs.msdn.microsoft.com/dotnet/2018/04/30/announcing-the-net-framework-4-7-2/ ... and i'm assuming it's a low priority, but it would be worth getting a task in place to support this version, in case anyone is in need of its usage.

**Comment by peters** [comment]
https://github.com/Squirrel/Squirrel.Windows/pull/1306

**Comment by Thieum** [comment]
can be closed, as it is fixed by #1306
