### ISSUE TITLE
Can't access file at runtime

### ISSUE THREAD

**Issue by thatsumoguy** [Squirrel/Squirrel.Windows#1309]
I have a JSON file I am trying to read/write to at run time. It works fine when debugging, or when running from the solution folder, but fails after installing with squirrel.

I have it set to pull the JSON file from
`var jsonfolder = Path.Combine(Path.GetDirectoryName(assembly.Location), @"Config\Config.json");`
I am currently just copying the folder over to the working directory after install just to test it out. It doesn't work.

If I remove the JSON portion, the other parts in the method will run, but if the JSON read part is there, it fails.

**Comment by paulcbetts** [comment]
Are you including this config.json file in your application package?

**Comment by thatsumoguy** [comment]
Yes I am. I also just tested it by adding into the nupkg with the executables. Still not working.

I have also tested with moving the file into the working directory, still not working.

**Comment by paulcbetts** [comment]
It seems extremely unlikely that this is a Squirrel.Windows bug, though if you figure out that it is, please reopen!

**Comment by thatsumoguy** [comment]
Hey just retried with clickone, and it works there. I also tried making a Content Folder using Nuget Package Explorer. I made sure that json file was set to Content on Build Actions, made sure it was set to Always Copy. And still coming up with nothing. This has to be squirrel related as clickone works, running the exe without installing works, etc.
