### ISSUE TITLE
How to implement installer/updater access control using Squirrel/AWS? 

### ISSUE THREAD

**Issue by asfarley** [Squirrel/Squirrel.Windows#1315]
I'd like to ensure that only authorized users can install and update our application. 

Right now I've set up a public AWS bucket containing the Squirrel release folder, which obviously allows anyone with the URL to download the installer or incremental update. 

Is there a preferred method for implementing this type of security check?

Any simple check would probably be fine (i.e. basic HTTP security, if there's a way to do that with Squirrel and AWS); this isn't a security-critical application, we'd just like take basic steps to restrict access.

**Comment by paulcbetts** [comment]
I personally just wouldn't worry about it, but you can always download the RELEASES and NuGet package to a temp folder then point the updater to that. This means you can have any access restrictions you want.
