### ISSUE TITLE
Support for MSIX?

### ISSUE THREAD

**Issue by rogersachan** [Squirrel/Squirrel.Windows#1317]
Microsoft is creating a new, open-source packaging format that is *not locked down to their store*. This format has support for both Windows 7 and 10. They are working with **multiple** partners for this packaging as seen below: 
![image](https://user-images.githubusercontent.com/7173984/39970947-966af08e-56c1-11e8-80e4-09697950b59b.png)

See:

* [MSIX: Inside and Out](https://youtu.be/FKCX4Rzfysk) (video)
* [Accelerating Windows 10 enterprise app deployment with MSIX](https://youtu.be/z6q15jwk0H8) (video)
* [MSIX - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/MSIX/ct-p/MSIX)
* [MSIX on Github](https://github.com/Microsoft/msix-packaging)

**Comment by paulcbetts** [comment]
Can anyone articulate how this would make anyone's lives better? It seems to only make developers' lives harder, while providing no benefit to IT Admins or users (this question is in earnest! I may be uninformed)

**Comment by ap0llo** [comment]
As I understand it, MSIX defines a packaging format for applications and handles both installation and updating. So it implements more or less the same feature set as Squirrel. 
I don't know how MSIX support in Squirrel would look like. If you take everything out of Squirrel that is handled by MSIX, what would be left?

**Comment by WorldMaker** [comment]
Yeah, it sounds like MSIX takes over all that Squirrel does, plus a bit more. The updates system supports/builds incremental patch updates using nothing smarter than a file share or static web server, which sounds like a smarter ClickOnce replacement. Microsoft announced Windows 7 support, too.

I don't think Squirrel needs to support MSIX, more that it should have a useful MSIX transition guide? That might be easier when more of the official packaging tools release over the next few months.

**Comment by rogersachan** [comment]
@paulcbetts Please see the first two videos linked, although they are rather long there are quite a few advantages from this system. I'll include some screencaps from the video regarding some of the benefits:

![image](https://user-images.githubusercontent.com/7173984/39971406-699107ae-56c8-11e8-8446-13e4d70ef3fb.png)
![image](https://user-images.githubusercontent.com/7173984/39971410-78d62730-56c8-11e8-8b1e-23769bd90030.png)
![image](https://user-images.githubusercontent.com/7173984/39971419-94cde810-56c8-11e8-9642-4a3cc4e2b9b4.png)
![image](https://user-images.githubusercontent.com/7173984/39971422-9ed5940c-56c8-11e8-95f3-f5b54cb000cb.png)
![image](https://user-images.githubusercontent.com/7173984/39971427-b7b33718-56c8-11e8-9d9a-032170950aeb.png)
![image](https://user-images.githubusercontent.com/7173984/39971431-c02b35a8-56c8-11e8-9803-5b66dd6f3476.png)
![image](https://user-images.githubusercontent.com/7173984/39971442-e790593e-56c8-11e8-80a8-a3910c7154a8.png)
![image](https://user-images.githubusercontent.com/7173984/39971444-ef71fdba-56c8-11e8-8df0-e16d1040e9ea.png)

**Comment by paulcbetts** [comment]
Squirrel already does all of these things, I still don't really see the advantage

**Comment by paulcbetts** [comment]
@Worldmaker Squirrel has had delta updates for at least 4 years now, and has always supported static file shares since day one

**Comment by WorldMaker** [comment]
@paulcbetts Right. I was thinking more in terms of the advantages over previous APPX, not necessarily direct comparison, sorry. (Definitely my fault for preceding it with "plus a little bit more" as if I were to explain the one thing and then cognitively switched tracks I suppose to the other thing. Oops.)

In terms of what MSIX has that Squirrel doesn't: official Microsoft support; deeper containerization; Microsoft Store support; Windows 10's S-Mode/"Grandparent Mode" support (restricting a Windows system to store and container apps only).

Most of that doesn't matter to Squirrel, and I think you are correct in that there isn't a direct advantage to "support" MSIX in Squirrel. But much of that matters (indirectly or non-obviously in some of the cases) to users.

From what little I've heard so far (I still plan to watch more of the MSIX videos), there's also a lot coming down the pipeline for MSIX "customization"/"modification" tools, which mentions I heard on it were focused on corporate IT hands-on install management scenarios, but which hints were it also applied to supporting extension/plugin systems and PC gaming-culture type "mods"/overlays. Those matter to power users, but also could be useful for developers of certain types of applications that want to support easy to install/remove add-ins but don't want to own the infrastructure for it.

Anyway, yes, my position is still basically the assumption that perhaps Squirrel doesn't need to do anything but offer a good transition guide, for interested developers.

**Comment by yzorg** [comment]
Everyone that uses Squirrel is "used to" packaging via NuGet package format plus custom metadata (extensions).  I for one would be interested if Squirrel maintainers (i.e. Paul) could review MSIX as a package format to replace NuGet.  The scenario I have in mind is a "preview" channel of my app that uses Squirrel + MSIX, and "wide" releases (company-wide deployments) would use MSIX + Win10 + AD.  Does that make any sense?
P.S. I'm not using deltas (yet).

**Comment by paulcbetts** [comment]
@yzorg That makes sense, though I also think this is extremely doable today with Squirrel's channel support, we don't need to use MSIX for this. While MSIX has some promising aspects, I'm really loathe to jump into an even less widely used proprietary format after all of the problems that NuPkg has caused.

The fact is, MSIX is produced by an organization (Windows org) that has pretty consistently for the last 5+ years, shipped developer technologies that end up being unused / forgotten 12-18mo later, after the hype dies down, and should Squirrel move to it, surprise! We're stuck with a dead packaging format, that we can't control or improve, because all of the core libraries are owned by someone else

**Comment by OzBob** [comment]
CI/CD support added .Net WPF app (.netcore coming)(e.g. https://github.com/ridomin/msix-catalog)
https://www.twitch.tv/videos/395359527 jump to 7:09:00 for demo of:
GitHub check-in , build, sign, package, app store update sideloaded app, and auto upgrade on_relaunch of the desktop app.
