### ISSUE TITLE
Improve code-signing performance

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#1321]
When signing files, Squirrel does it 1:1. However... it takes about 3 seconds per file, which is horrible if you have hundreds of files. Most of the time is "lost" by the timestamp it needs to get from the server (it's not taking any CPU at all).

Could squirrel be enhanced by allowing multithreaded (e.g. 5 threads at the same time) code-signing actions? A build would literally be 5 times as fast. We could even make it optional via a `--code-sign-threads` (worst case defaulting to 1).

**Comment by GeertvanHorrik** [comment]
For example, we have about 40 open-source projects, with about 5 translations per component. This means it has to code-sign at least 200 files which takes at least 200 * 3 = 600 seconds (= 10 minutes).

**Comment by GeertvanHorrik** [comment]
FWIW I started code-signing all our open source libs in the hope to speed up the code-signing process of Squirrel (since they are already signed).

**Comment by paulcbetts** [comment]
> Could squirrel be enhanced by allowing multithreaded (e.g. 5 threads at the same time) code-signing actions?

No, we explicitly had to remove this, even a very reasonable 4x level of concurrency causes signing to randomly fail. You might ask yourself, "Why?? It's just editing a file!". To that I would respond, ":: sigh ::, Windows"

**Comment by paulcbetts** [comment]
@GeertvanHorrik One thing you could do is start to ILMerge some of those files, tbh, if you're loading all 200 files on app startup it's probably significantly hurting your startup perf

**Comment by GeertvanHorrik** [comment]
Thanks for getting back to me. Not all files have to be loaded directly at startup, .NET will load them on-demand if need be (and to be honest, performance is fine for our end-users). 

Weird that it would fail, but I understand your doubts to reimplement it.

**Comment by paulcbetts** [comment]
@GeertvanHorrik You can certainly give it a try, the code is still written in a way so you could parallelize it super easily (if you look at the blame you can probably even just revert the commit locally), but it definitely was trolling people
