### ISSUE TITLE
[Update] Quit app when unpacking nuget package causing error

### ISSUE THREAD

**Issue by haiphamcs** [Squirrel/Squirrel.Windows#1327]
Hi there,
I'm using electron winstaller to build my app. I see updater takes 20-30 secconds to unpack new `.nupkg` file after it's downloaded. If I quit my app during unpacking new package, it can not re-open.
For example my app's being updated from 1.0.0 to 1.0.1. When 1.0.1 is unpacking, I click close button then files are missing in `app-1.0.1` folder, and I cannot start my app with execution stub (MyApp.exe).
I see some electron app have same issue (Atom editor and Slack). 
Is there any solution?

**Comment by bddckr** [comment]
We work around this in our project by not allowing the app to quit while an update is happening.

**Comment by haiphamcs** [comment]
Thanks for your idea.
I see in old version of Squirrel, it starts app by passing argument to `update.exe` in shorcut instead of creating execution stub and it doesn't cause error in this case. I'm wondering why squirrel have to switch to use execution stub.

**Comment by Thieum** [comment]
@shiftkey question answered, this can be closed.

**Comment by JontyMC** [comment]
> We work around this in our project by not allowing the app to quit while an update is happening.

@bddckr how exactly did you do this?

**Comment by bddckr** [comment]
@JontyMC We're using the `UpdateManager` API directly, without the "do it all for me" method. I.e. `CheckForUpdate` + `DownloadReleases` + `ApplyReleases` and helpful ones Squirrel also comes with like `CreateUninstallerRegistryEntry`.

With that in place we have full knowledge about the state the updating process is in and can handle it appropriately.

**Comment by Thieum** [comment]
@JontyMC Not OP, but I interpreted this as waiting for the update task like documented [here](https://github.com/Squirrel/Squirrel.Windows/issues/1235#issuecomment-358187746)

**Comment by JontyMC** [comment]
Thanks. Anyone know why doesn't squirrel fully unpack the nuget package first, then switch the exe's?
