### ISSUE TITLE
Update.exe --install uses crazy amounts of memory

### ISSUE THREAD

**Issue by anaisbetts** [Squirrel/Squirrel.Windows#133]
Install Atom, watch Process Explorer and see how much bananas amount of memory Update.exe is using

**Comment by Moter8** [comment]
Well, this doesn't seem to be fixed to me:

![1](http://i.imgur.com/4RgpBtr.png)

^ Was the task manager during the initial installation of Atom 0.169.0!

**Comment by paulcbetts** [comment]
Has anyone seen the API crash because of this? Or are they just annoyed by the number?

**Comment by Moter8** [comment]
Just annoyed by the ~~bananas~~ number :)
