### ISSUE TITLE
Update to earlier version

### ISSUE THREAD

**Issue by AR1ES** [Squirrel/Squirrel.Windows#1332]
Is to possible to get list of all released versions and update to selected one?

**Comment by Thieum** [comment]
@AR1ES the goal of Squirrel is to have the latest version installed without any interaction. The only way to achieve what you want is to copy the setup.exe of each release (it changes everytime you create a new version), and provide access to them. You would have to consider how to handle updates in this case, as an automatic update would bring you back to the latest anyway.

**Comment by shiftkey** [comment]
Closing this out as Squirrel is very much about running the latest version of your app.
