### ISSUE TITLE
No Squirrel.exe in my release output?

### ISSUE THREAD

**Issue by coreyman** [Squirrel/Squirrel.Windows#1339]
I've downloaded and built in VS 2017 Community the project here and noticed there was no squirrel.exe in the folder that I could do "Releasify" with. I had to change the targeted SDK version to 10 instead of 8.1, there were lots of issues trying to build with 8.1

I moved on and added the squirrel.windows nuget package to my project and started integrating it with the code with this - https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started I got to step 2 'packaging' and built my project in release mode. I still do not see squirrel.exe in there, only a Squirrel.dll and Squirrel.pdb.

Correct me if I'm wrong, but aren't I supposed to be seeing a Squirrel.exe file that I can do "Releasify" with?

**Comment by paulcbetts** [comment]
Squirrel.exe is in your NuGet packages folder under Tools. In your packaged app, it gets renamed to `update.exe`.
