### ISSUE TITLE
Releasify by Squirrel in visual studio

### ISSUE THREAD

**Issue by StefanPap** [Squirrel/Squirrel.Windows#1343]
Hello, 
is it possible to releasify directly in c# Code with the squirrel.dll ,?I dont want to use extern squirrel.exe from cmd or the package-manager

**Comment by Thieum** [comment]
@StefanPap Squirrel [the dll](https://github.com/Squirrel/Squirrel.Windows/tree/develop/src/Squirrel) and Squirrel [the executable](https://github.com/Squirrel/Squirrel.Windows/tree/develop/src/Update) are two separate projects, even if the exe depends on the dll, so some code is shared.
If you want to call releasify from your code, the simplest way would be to instanciate a [Process](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process?view=netframework-4.8) to call squirrel.exe.

**Comment by shiftkey** [comment]
Without a better understanding of the problems with the current options, we don't have plans to support an alternative releasify API. @StefanPap please open a fresh issue if you want to discuss this further.
