### ISSUE TITLE
Memory Error in Squirrel Fetch for Tofware (Manipulating HDF files)

### ISSUE THREAD

**Issue by ldh96** [Squirrel/Squirrel.Windows#1351]
![error](https://user-images.githubusercontent.com/41441307/42952277-b96a9f52-8b3d-11e8-9c46-99c571854efa.PNG)
Hello, I'm using Squirrel for mass spec data analysis (Tof-Ware) and am trying to load and integrate HDF files. I get an error "squirrel_fetch" that states I am out of memory during the data make. I have performed the same integration steps of 10 other files in the same folder and only encounter the memory error with this one. Anyone encountered something similar?

**Comment by paulcbetts** [comment]
I think you've got the wrong Squirrel project, this is for installing Windows applications
