### ISSUE TITLE
setup.exe not being seen by Carbon Black as an installer

### ISSUE THREAD

**Issue by ivoloshin** [Squirrel/Squirrel.Windows#1356]
My company runs Carbon Black installer protection software which does not allow users to run arbitrary code. We made a rule in Carbon Black to allow based on Company Name, but the IT guys claim the setup.exe isn't marked as "Installer". Is there a setting or something, maybe even after the setup.exe is made, like maybe some metadata that can be added to mark it as such?

**Comment by paulcbetts** [comment]
There is no way we can know what Carbon Black considers an installer, I would recommend contacting them, or convincing IT to remove Carbon Black because it's garbage

**Comment by ivoloshin** [comment]
Well, I was wondering and have been searching to see if there's anything standard in Windows that marks an .EXE as an installer and though someone here might know. I'll contact Carbon Black as well. Thank you.
