### ISSUE TITLE
How to install prerequisites?

### ISSUE THREAD

**Issue by RasikaWaykar** [Squirrel/Squirrel.Windows#1357]
Using Squirrel, how can I create setup with its dependencies?

**Comment by dealproc** [comment]
Outside of the dotnet framework, you need to design the application so that it does not need third party dependencies.  Not recalling what the standards were for using ClickOnce, but think of squirrel.windows as more of an orchestrated xcopy deployment w/upgrading capabilities.

**Comment by frederikolsen88** [comment]
I think the only way is to include your dependency in the application resources and install it programmatically when the OnInitialInstall event is fired.

**Comment by RasikaWaykar** [comment]
Means I can't add dependency in NuGet package. Is it correct?

**Comment by paulcbetts** [comment]
@RasikaWaykar Nuget dependencies work fine, they'll just get bundled with your installer. @dealproc is more talking about system-wide dependencies like SQL Server
