### ISSUE TITLE
Non CS App - Making Squirrel Aware and Icons/Shortcuts

### ISSUE THREAD

**Issue by lehne** [Squirrel/Squirrel.Windows#1358]
Have a C++ app that we made handle all of the commands properly. However icons are no longer created. Why is this? Are we supposed to add them ourselves now?

**Comment by paulcbetts** [comment]
Maybe make a more thorough bug report? I have no way to answer any of your questions without knowing what you're doing to "handle all of the commands properly"

**Comment by lehne** [comment]
I just reread all of the docs and I appear to have missed the bit that said that I have to create/remove the shortcuts manually. Since I was using a non-cs app I only read that section in detail. Looks like I should do this:

- onInitialInstall: run "Update.exe --createShortcut=myExe.exe"
- onAppUpdate: run "Update.exe --createShortcut=myExe.exe"
- onAppUninstall: run "Update.exe --removeShortcut=myExe.exe"

**Comment by paulcbetts** [comment]
@lehne Yep, if you handle commands, you get opted out of the default behavior. You've got the right idea, just make sure in C++ to call `WaitForSingleObject` on the process handle once you launch Update.exe
