### ISSUE TITLE
Squirrel Updater opens on its own, no idea where I got it.

### ISSUE THREAD

**Issue by MoodySshuffle** [Squirrel/Squirrel.Windows#1369]
Hi, I'm a very confused user that didn't even know I was a user of this until now. I was just, casually on my computer, when suddenly this little window pops up, and then it fills in with a green like, fake terminal interface? It's full of blocks of things, like it's an animated UI, but it's doing its own thing, like there are big blocks where it looks like lines of text should be. I don't know what on Earth it is, so I immediately close it in Task Manager. Windows tells me something went wrong, and asks if I wanna see a setup log, which I look at.

That's when I find out at the top, that it's Squirrel Updater running. It prompts to install to a SquirrelTemp in my Appdata, and then it starts rooting around for various things, like my taskbar icons, and my Discord installs. I'm not even really sure what it was trying to do. I thought it was a virus or malware opening, but I guess it's kind of legit? The thing is, I don't know where I could've gotten Squirrel before; I've never heard of it, and I've never knowingly downloaded it. Can someone help me out here, I just don't know what's happening or if I should be concerned.

**Comment by paulcbetts** [comment]
Squirrel is a library that many applications use to create Windows installers, including Discord. You wouldn't get it directly, it's a component of an app you are using. Sorry to hear it was confusing, but it is definitely not malware.

You may have an app that is partially installed or the install is wedged somehow if you're seeing it pop up on its own - look for an entry in Add/Remove Programs, "(Something) Machine-Wide Install"
