### ISSUE TITLE
Unable to install Squirrel packages

### ISSUE THREAD

**Issue by esQmo** [Squirrel/Squirrel.Windows#1372]
I can't install Squirrel packages such as SourceTree or even the GitHub desktop client. The intsller crashes, I'm asked to check the log whic is 0o - blank. 

I was able to install such packages but I don't know why it is failling.

Windows 7, SP1.

![image](https://user-images.githubusercontent.com/10319812/44124786-db290590-a026-11e8-8891-14b1ba757d32.png)

May be some libs are missing? 
![image](https://user-images.githubusercontent.com/10319812/44124810-f4893186-a026-11e8-95ef-0d43fc94d32c.png)

**Comment by paulcbetts** [comment]
Sorry that you're having trouble, if you can get a call stack or a log file that says anything we can help, but right now this error is unactionable. Please reopen with more info if you can get it.
