### ISSUE TITLE
How does Setup.exe works when running as administrator from a standard user?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#1373]
Hi,

I'm logged in as a Standard user and I want to run Squirrel Setup.exe as Administrator. So, I right-click the Setup.exe file and choose the "Run as administrator" option. Squirrel then installs my application under the AppData\Local path of the ****Standard** user** with which I am logged in.

1. Since it runs under the administrator context, how does it know the Standard user's AppData\Local path?

2. Even if it does know that path, how does it have the permissions to write?

**Comment by paulcbetts** [comment]
Squirrel will detect an attempt to run itself as Administrator and re-run itself as not-administrator, Standard Users can install Squirrel apps without admin credentials.
