### ISSUE TITLE
Using update.exe from non-integrated apps

### ISSUE THREAD

**Issue by MihaMarkic** [Squirrel/Squirrel.Windows#1380]
I'm trying to make a deployment of a .NET Core Console application and thus can't integrate the UpdateManager (albeit it'd be nice if we had a .NET Core version).
Looking at controlling Update.exe now.
Is there any sample out there?

Anyway, how do I figure whether update (testing checkForUpdates) succeeded or not?
- Update.exe always returns 0 as exit code
- Error output is empty

The only way I can think of is the pre-last line (last is empty) received from OutputDataReceived:
- if it is a valid JSON, then it succeeded
- otherwise it failed.

Is this the way to go?

Something like  #1374, #1320

**Comment by SEAHood** [comment]
Did you ever find an example of using Squirrel in .NET Core? I'm running in to the exact same issues as you

**Comment by Thieum** [comment]
@MihaMarkic it seems it is resolved as you have a working project. Should we close this issue?

**Comment by shiftkey** [comment]
Closing this out as it looks like the interesting bits about using Squirrel with .NET Core can be found in the Cake script:

https://github.com/MihaMarkic/AutoMasshTik/blob/master/appbuild.cake#L212-L224

**Comment by ShemJM** [comment]
Does this mean we have to use Cake to get this to work with .net core?

**Comment by MihaMarkic** [comment]
@ShemJM No, Cake is optional - it's a build script tool where addins (such as Squirrel addin) provide additional functionality by (usually) invoking specific command line tools. Eventually it's all command line invocations. Said that, it's a good think if you automate deployment and Cake is quite good at it.

**Comment by ShemJM** [comment]
@MihaMarkic I see, I had a look at Cake it does seem good. I might use it in the future, right now I just need to get Squirrel working :D. Do you know how I might be able to pass my release directory to the Update.exe? I am using ```process.start("Update.exe")```

**Comment by MihaMarkic** [comment]
@ShemJM Not out of my head, sorry.
