### ISSUE TITLE
Installation destination foldername and nuget package id

### ISSUE THREAD

**Issue by schh** [Squirrel/Squirrel.Windows#1383]
Ive given my packages an id in the format XXX.XXX.XXX. For some reason the install folder created crops everything at the first dot.

I have two programs i use squirrel for and they both begin with the same letters before the dot wich is the same as my code namespaces and naming of my output binaries, and thats how i want it, but now i gotta manually rename the folder of the first install because the second one overwrites my first install.

Nuget best practices for package ids states:

> Follow a pattern similar to namespaces in .NET, using dot notation instead of hyphens. For example, use Contoso.Utility.UsefulStuff rather than Contoso-Utility-UsefulStuff or Contoso_Utility_UsefulStuff. Consumers also find it helpful when the package identifier matches the namespaces used in the code.

It would be very nice if the folder created retained the full id with dots. 

Thanks

**Comment by paulcbetts** [comment]
Hey, check out https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/naming.md - you don't want to name your Product with dots, remember that users will see this folder
