### ISSUE TITLE
Setup.msi not working,  Setup.exe installs to AppData but no Icon added to taskbar/desktop/start

### ISSUE THREAD

**Issue by svdhorst** [Squirrel/Squirrel.Windows#1384]
As I am nearing completion of my new windows desktop application it's time to make it distributabel. So I created a nuget package and releasified it with squirrel. No errors and all went fine.

I have created a setup for a windows desktop application "NopFinance". When I execute the setup.msi I see the installation machine-wide box. After pressing OK setup.msi seems to install something but I can not find a directory with my application.

So next I executed Setup.exe. Setup.Exe installed my desktop application in de AppData/Local/NopFinance. That's great! 

However the setup.exe did not create a desktop icon/ start icon or taskbar icon therefore making the desktop application almost impossible to find for a common user.

What would be the steps to actually get a a shortcut icon on my desktop/taskbar or start?

In the AppData/Local/NopFinance, there is a .ico file.

Any help or direction would be greatly appreciated

(Windows 8.1 , 64bit)
Stefan 
NopFinance

**Comment by paulcbetts** [comment]
Uninstall the MSI and don't use it, it's only for Enterprise scenarios. Just redistribute the EXE
