### ISSUE TITLE
Setup.exe Closes after a couple of seconds in idle

### ISSUE THREAD

**Issue by X2FrostFire** [Squirrel/Squirrel.Windows#1385]
Hello everyone for my Setup.exe when I double click on it and it launches if I leave it alone for 10 seconds it automatically closes by itself. Is this an issue or a setting I need to change?

**Comment by paulcbetts** [comment]
Your app isn't launching itself properly or responding to --squirrel-install. Try debugging your app from the installed folder

**Comment by X2FrostFire** [comment]
>           Your app isn't launching itself properly or responding to --squirrel-install. Try debugging your app from the installed folder

But if I click on it Setup.exe and click the install button all the files get installed properly would still be a --squirrel-install issue?

**Comment by paulcbetts** [comment]
> But if I click on it Setup.exe and click the install button all the files get installed properly would it still be a --squirrel-install issue?

Yep!

**Comment by X2FrostFire** [comment]
> Yep!

Sorry for the noobish question as I literally started learning this 4 hours ago what so you mean by --squirrel-install? And how would the app not launch itself properly?

**Comment by paulcbetts** [comment]
Have a look at https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md

**Comment by paulcbetts** [comment]
Squirrel is running your app at the end of startup. It is probably crashing or not working correctly. Try running your app from the installed folder by hand and see what happens

**Comment by X2FrostFire** [comment]
Is there a way for it to ot run the app after running setup.exe?

**Comment by paulcbetts** [comment]
> Is there a way for it to not run the app after running setup.exe?

No. The reason that users run your installer is that they want to _run your app_. Squirrel's goal is to install and run your app _as soon as possible_

**Comment by X2FrostFire** [comment]
Hmmmmm that's an issue for this project then. The use for this project is to have an installer extract a excel add-in to a specified folder. So the application that is created as a side effect doesn't do anything. So the installer needs to stay up and not exit on itself after 10 seconds of idle. Do you possibly know a way to route what is being launched? Like launch Excel instead?

**Comment by lukeskinner** [comment]
> Squirrel is both a set of tools and a library, to completely manage both installation and updating your Desktop Windows application, written in either C# or any other language (i.e., Squirrel can manage native C++ applications).

To me it doesn't sound like your scenario fits into the main purpose of Squirrel which is to install a desktop app, run it and provide a way to update it. 

A normal MSI installer _may_ be more appropriate - I've had success using WIX on Office add-ins in the past.

**Comment by X2FrostFire** [comment]
Do you guys know if there is a way to detect when the installation window has completed its task?

**Comment by bddckr** [comment]
If you insist on using Squirrel I suggest writing a very small app that does nothing more than the installation task you need to do. **Only that app needs to be SquirrelAware**.
