### ISSUE TITLE
Nested SquirrelAware Apps are not detected

### ISSUE THREAD

**Issue by JustinKaffenberger** [Squirrel/Squirrel.Windows#1389]
I'm integrating Squirrel into a Unity3D/WPF hybrid application, and I've been running into an due to the fact that Unity3D generates artifacts with spaces in the name, namely the `resources\unity default resources` file. After finding similar issues posted, it seems the only workaround is as follows:

1. Use URL-encoding on files that have spaces in them during the build process, in this case the `resources\unity default resources` becomes `resources\unity%20default%20resources`. This isn't a big deal as I'm using cake-build to manage my build pipeline.
2. Build a Squirrel-Aware application to handle decoding the files that were encoded. Easy enough, I even made it a general purpose package that I can import into any Squirrel-deployed application to handle this for all cases.
3. During the build pipeline, I pull in this Squirrel-Aware application into a sub-directory. I want to put it in a sub-directory so any dependencies of the Squirrel Aware application don't have a chance of conflicting with the application dependencies in the root folder.
4. My final application structure that gets deployed looks similar to the following:
```
    \MyApp.exe
    \SomeDependencies.dll
    \MySquirrelAwareApp\
        \MySquirrelApp.exe
        \MySquirrelAppDependencies.dll
```

All of this seems reasonable to me, except that Squirrel does not seem to detect Squirrel-Aware applications if they are not in the root directory. Now this whole process has gotten out of control, all because of a space in a file name.

I've read the Squirrel logs, it does not detect my Squirrel-Aware application when it is nested. Moving it up to the root directory shows in the logs, as well as my Squirrel-Aware application successfully performs the file decoding.

I propose that Squirrel should be able to detect applications in sub-directories, I'm sure this is easier said than done, but everyone keeps throwing around the 'Just make a Squirrel-Aware application' as a solution to simple problems. I guess the other option is to let me deploy any file that has a valid Windows filename, and then this whole debacle would be a lot simpler.

**Comment by paulcbetts** [comment]
Why do you need more than one Squirrel-aware app? I think you could just make the WPF app create shortcuts for both

**Comment by JustinKaffenberger** [comment]
Shortcuts are not the issue, the issue is that my application can't boot because the filenames have to be decoded first. @paulcbetts in [Issue 1266](https://github.com/Squirrel/Squirrel.Windows/issues/1266) you recommended the solution that I am now trying to implement.

**Comment by paulcbetts** [comment]
In this case, I'd make a really small Squirrel-aware app that has no dependencies and whose sole purpose is to do the install stuff. Sorry this is a pain, I want to avoid recursively searching for apps because for Electron apps this can be a pretty big drag searching through thousands of JavaScript files.

**Comment by JustinKaffenberger** [comment]
Ok, thanks for the perspective, sometimes I forget about the whole world of JavaScript apps. I did some research into the [PackUriHelper](https://referencesource.microsoft.com/#windowsbase/Base/System/IO/Packaging/PackUriHelper.cs) that seems to be the source of all of the pain related to the spaces in the filenames, but something tells me that's going to be a lot harder to change. Would be nice to have an attribute or something that I could put on my application that tells the Squirrel engine to escape my files when the package is created, then un-escape on deployment. I totally get that this would be a lot of work. My other option is to tell the Unity team to stop including files with spaces in them 😅
