### ISSUE TITLE
Issue in integrating Squirrel with Native C++ desktop application

### ISSUE THREAD

**Issue by tgvishnupriyabe** [Squirrel/Squirrel.Windows#1390]
I am trying to integrate Squirrel with a native c++ application. I see the very first step is to install nuget package-  Squirrel.Windows via package manager console in VS IDE.
I was getting the error that it was unable to find such package. So I opened the manage nuget packages GUI, and tried to install Squirrel. But getting the below error:

Could not install package 'DeltaCompressionDotNet 1.1.0'. You are trying to install this package into a project that targets 'native,Version=v0.0', but the package does not contain any assembly references or content files that are compatible with that framework. 

It works fine when integrating with C# application, but with C++ application, though Squirrel docs says native c++ is supported, the very first step of integrating itself fails.
Can you please do guide on how to proceed or redirect to a better tutorial that has more specific steps to integrate with C++ application?

**Comment by bddckr** [comment]
Those steps are for the C# usage. See [this document](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md) for non-C# usage.

**Comment by tgvishnupriyabe** [comment]
> Those steps are for the C# usage. See [this document](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md) for non-C# usage.

Christoper -thanks for the reply , but the document doesnt say about how to integrate Squirrel withe C++ project/solution. 
Setting SquirrelAwareApp property to  1, tells Squirrel not to create shortcuts,etc rather indicate that we will be handling custom events(install/uninstall/firstrun/onupdate..).

For C# solution document says very clearly how to install Squirrel from package manager and includes its references, so that in code we can further refer and create instance of UpdateManager as like below:

   using (var mgr = new UpdateManager(updateUrl))
    {
        // Note, in most of these scenarios, the app exits after this method
        // completes!
        SquirrelAwareApp.HandleEvents(
          onInitialInstall: v => mgr.CreateShortcutForThisExe(),
          onAppUpdate: v => mgr.CreateShortcutForThisExe(),
          onAppUninstall: v => mgr.RemoveShortcutForThisExe(),
          onFirstRun: () => ShowTheWelcomeWizard = true);
    }

HOW TO ACHIEVE THE SAME WITH C++ solution/project without being able to add Squirrel file references?I dont see any document related to this. Has anyone tried integrating squirrel with C++?
Your help/advise is much appreciated.

**Comment by paulcbetts** [comment]
@tgvishnupriyabe Look at the source code for `HandleEvents`, it's just a wrapper around parsing the command line args - Squirrel will call your EXE with `--squirrel-install` etc etc
