### ISSUE TITLE
Prevent program to be added on "Add/Remove Program" List

### ISSUE THREAD

**Issue by Altiano** [Squirrel/Squirrel.Windows#1397]
I don't want user to uninstall the application.
That is the requirement from my clients.

**Comment by Thieum** [comment]
@Altiano are the users administrators of their computer? If so, there's not much Squirrel can do. If not, there are other ways to prevent uninstallation of software.

**Comment by shiftkey** [comment]
@Altiano we don't have plans to support this use case

**Comment by Code-DJ** [comment]
@Altiano have you tried to remove the registry entries using [Custom Events](https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/docs/using/custom-squirrel-events.mdl) to see if your app continues to work?

```
using (var mgr = new UpdateManager(updateUrl))
{
    SquirrelAwareApp.HandleEvents(
        onInitialInstall: new Action<Version>(v =>
        {
            var key = Registry.CurrentUser.OpenSubKey(Software\Microsoft\Windows\CurrentVersion\Uninstall)
            // loop through all the subkeys to find your app, then delete that key and all child items.
        })
    );
}
```
