### ISSUE TITLE
SplashScreen/AnimatedGifWindow during simple upgrades

### ISSUE THREAD

**Issue by sopelt** [Squirrel/Squirrel.Windows#1398]
Hi, for simple update scenarios (similar to clickonce .. update check and rollout during app startup) it would be nice to have a way to show the same splashscreen (with the GIF) as used in Setup.exe.

What do you think about adding infrastructure for that? Moving AnimatedGifWindow from ...Update to Squirrels lib ... or have Update.exe show it during the update when requested?

Kind regards,
Simon

**Comment by Thieum** [comment]
As stated in https://github.com/Squirrel/Squirrel.Windows/issues/1470#issuecomment-486410297

>  in terms of updating, our goal is to be like Chrome - you open it and it's the latest version. No prompts, no UAC dialogs, no Wizards or Progress Bars. Every time we show an update progress bar, we say to the user, "What you're doing isn't important. Look at Me instead". Any feature that tries to do this should be met with "That's Not What We Do Here"

**Comment by sopelt** [comment]
Fair enough ;)

What would be a recommended pattern for our scenario? Right now we just check+update on startup but that might take a moment and the user doesn't have any feedback that we actually launched and are updating.
I also thought about doing it when quitting but that might delay shutting down/fail ... And if the user only sporadically uses the app they might run a stale version.

Kind regards.

**Comment by uygary** [comment]
You could wire up your own launcher UI to provide that functionality for your app.
After all, it's not a part of the update process, but the update process exposes enough information to the application itself to display a progress bar, etc. It's all up to you to design the UX according to your expectations.

**Comment by sopelt** [comment]
That is the way we were heading with the initial idea... It seemed reasonable to show the animated gif for a few seconds in case we needed to extract an update... But that would mean having to duplicate the AnimatedGifWindow which felt wrong

**Comment by Thieum** [comment]
We're doing what @uygary suggests, as there is an extension in EasyModeMixin that gives the progress of the update:
`        public static Task<ReleaseEntry> UpdateApp(this IUpdateManager This, Action<int> progress = null);`
This allows to give the user a feedback if needed, but keeps Squirrel itself as raw as possible.
