### ISSUE TITLE
What is SyncReleases.exe supposed to be for?

### ISSUE THREAD

**Issue by martingbrown** [Squirrel/Squirrel.Windows#1399]
So I have an issue which I'm looking at in the [OpenLiveWriter](https://github.com/OpenLiveWriter/OpenLiveWriter/) project which uses Squirrel to do its updates. I'm not sure if the issue is with Squirrel or whether OpenLiveWriter is doing it wrong.

The issue comes with the build. It runs a batch file at the end of the build which has two commands in:

```
.\src\managed\packages\squirrel.windows.1.4.4\tools\SyncReleases.exe -url=https://olw.blob.core.windows.net/stable/Releases/ -r=.\Releases
.\src\managed\packages\squirrel.windows.1.4.4\tools\Squirrel.exe -i .\src\managed\OpenLiveWriter.PostEditor\Images\Writer.ico --no-msi --releasify .\OpenLiveWriter.6.2.0.nupkg 
```

It does the SyncReleases because it is running on an AppVeyor build agent that is flattened and rebuilt before each build and it is trying to create a delta package. I tried changing the version to 6.3.0 but that didn't work either.

Squirrel.exe fails with the error:
```
System.IO.FileNotFoundException: The base package release does not exist
  File name: '.\Releases\OpenLiveWriter-0.6.0.0-full.nupkg'
     at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String o
  utputFile)
     at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe,
   String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
     at Squirrel.Update.Program.executeCommandLine(String[] args)
     at Squirrel.Update.Program.main(String[] args)
     at Squirrel.Update.Program.Main(String[] args)
```

If you take a look at https://olw.blob.core.windows.net/stable/Releases/RELEASES and https://olw.blob.core.windows.net/stable/Releases/OpenLiveWriter-0.6.0.0-full.nupkg you will see that it does contain the 0.6.0.0-full file. The issue is that SyncReleases.exe isn't fetching it. I can see that there was a [commit to this project](https://github.com/Squirrel/Squirrel.Windows/commit/0c2a0937b5bc4b03974a1f0db766595543e47d74#diff-e0f4d610a4c0670797c085f9a4e5c9d4) that changed the number of previous releases SyncReleases downloads from 5 to 1.

I can't really see any documentation for SyncReleases.exe so I'm not entirely sure what its intended purpose is. Is it not working by failing to download old releases or is that not what its for? If it isn't for downloading old versions is there a better way?

**Comment by paulcbetts** [comment]
> System.IO.FileNotFoundException: The base package release does not exist

This is a shitty error message, but it usually is telling you that this release didn't change the version number (i.e. you're trying to build a new 0.6.0 but 0.6.0 is already released).

**Comment by martingbrown** [comment]
Looks like that was the case, but I also needed to clear out the .\Releases directory.
