### ISSUE TITLE
.mdf files lock up BsDiff

### ISSUE THREAD

**Issue by frederikolsen88** [Squirrel/Squirrel.Windows#1402]
I'm working on an application with which we have an SQL database bundled. The .mdf file is presently roughly 8 MB in size.

Whenever there are changes in the database between versions, Squirrel hangs during releasify. I've debugged through the process and found that the process stalls during `BinaryPatchUtility.Create`, and the process just never finishes unless we bypass delta packages altogether, which I'd rather not do. Why exactly the algorithm can't handle the file is beyond me, unfortunately.

Would it be reasonable to let `createDeltaForSingleFile` throw an Exception after a reasonable interval (perhaps determined from the file size) to ensure we simply include the whole file rather than a delta? Alternately, let MsDelta handle .mdf along with .exe, .dll and .node. I wouldn't mind turning in a PR if either of these are desirable.

**Comment by shiftkey** [comment]
@frederikolsen88 is this something you're able to capture in a test case? I'm not sure if there's other cases like this which affect delta compression, but I think that would be a reasonable first step to then evaluate our options...

**Comment by frederikolsen88** [comment]
That's going to be a bit tricky, since we've only been using production data. But sure! I'll have a look at it in the coming days and see whether I can replicate the issue with some sample data.

**Comment by frederikolsen88** [comment]
I've spent some time investigating the issue, and I think the flaw is in our database design rather than in Squirrel. We store a few BLOBs exceeding 1 MB in size, and this seems to be what makes the database hard to swallow for BSDiff. Even very large SQL database files appear to be handled fine, as long as there's no BLOB content. So I think it's safe to close this.

**Comment by frederikolsen88** [comment]
Closing again. Database shrinking solves the issue for us.
