### ISSUE TITLE
Http url automatic doesn't work

### ISSUE THREAD

**Issue by SubasishMohapatra** [Squirrel/Squirrel.Windows#1404]
Why does the update not work when we give a http url as the package folder, but works wonderfully when we give local folder path?
Anything missing from my side? Other than changing the path to url, anything else needs to be done?

**Comment by paulcbetts** [comment]
HTTP URLs definitely work, I suspect that you are constructing them wrong

**Comment by SubasishMohapatra** [comment]
Ohh now it works...U were right...the constructor parameters were not right and also the IIS settings as well
