### ISSUE TITLE
Squirrel Aware EXE without embedding .rc

### ISSUE THREAD

**Issue by ziahamza** [Squirrel/Squirrel.Windows#141]
I am trying to build an installer for a program written in Go Language. The go compiler can generate an executable, but it doesnt support resource files to embed into the executable, so I cant have an App.rc and add set the SquirrelAwareVersion -> 1. 

But I want to handle Squirrel install events. Any chance I can explicitly specify if an executable should be called with installing/uninstalling?

**Comment by joshuawarner32** [comment]
I haven't tried this on a Go executable, but I *think* you can do this with the github.com/atom/rcedit tool:

```
rcedit.exe <the_exe> --set-version-string SquirrelAwareVersion 1
```

I know that sets the right value, as long as the version info block already exists in the executable.  I'm not sure what it would do if it doesn't exist (or must it always exist?).

**Comment by paulcbetts** [comment]
Ooh, good idea, I'd try this ^^
