### ISSUE TITLE
Releases URL is now in lowercase on GitHub

### ISSUE THREAD

**Issue by ahallicks** [Squirrel/Squirrel.Windows#1412]
I don't know if this is a new thing done by GitHub but the URL generated by Squirrel to fetch releases from a GitHub repo will 404 when the word 'releases' is capitalised. I'm making assumptions here as I don't really know how all this works but this is my best guess and it only started happening at about 11 am this morning.

I believe this is found on https://github.com/Squirrel/Squirrel.Windows/blob/master/src/SyncReleases/SyncImplementations.cs#L22 and in other places throughout that file.

For example, if you go https://github.com/Squirrel/Squirrel.Windows/releases everything is fine. But https://github.com/Squirrel/Squirrel.Windows/RELEASES (as generated by Squirrel.Windows) produces a 404.

```
× Error: C:\Users\hall.a\AppData\Local\electron-builder\Cache\Squirrel.Windows\Squirrel.Windows-1.9.0\SyncReleases.exe exited with code 4294967295
Output:
Trying to download RELEASES index from https://github.com/Organisation/RepoName/RELEASES
```

**Comment by stajs** [comment]
I'll preface this with (1) I'm running a pretty old version of Squirrel and (2) I haven't looked at the code, but just to sanity check are you sure you aren't confusing the GitHub releases URL with the Squirrel `RELEASES` file?

For instance, our releases are located here `https://github.com/lic-nz/Malone/releases` while the file for the latest "release" is `https://github.com/lic-nz/Malone/releases/download/v0.9.7/RELEASES`.

**Comment by ahallicks** [comment]
Hmmm... possibly. I don't really know what happened but it is all working again now! I'll close this.
Thanks for your response.
