### ISSUE TITLE
Security: DLL preloading via `urlmon.dll` 

### ISSUE THREAD

**Issue by Metnew** [Squirrel/Squirrel.Windows#1415]
Hi Squirrel,

I've recently found that Squirrel-based Electron apps are vulnerable to DLL preloading:
1. Build a Squirrel-based Electron app with [windows-installer](https://github.com/electron/windows-installer). I've tested [this Electron app](https://github.com/atom-archive/electron-starter)
2. Open procmon
3. In procmon add next rules: set path to the dir of `${MyApp}Setup.exe`  (dir where the installer is stored), "Result" contains "NAME NOT FOUND", "Operation" contains "CreateFile"
3. Open `${MyApp}Setup.exe`
4. Observe "urlmon.dll" gets required on Win10, `version.dll` on Win7

Full list:
- `iertutil.dll` - Win10
- `urlmon.dll` - Win10
- `version.dll` - Win7
- `api-ms-win-appmodel-runtime-l1-1-1.dll` - Win 7
- `ext-ms-win-kernel32-package-current-l1-1-0.dll` - Win 7
- `api-ms-win-core-synch-l1-2-0.dll ` -  Win7

> That's pretty severe, because it applies to all Electron-based Squirrel apps (all Squirrel apps maybe?).
I think you could test this issue on Brave's installer. (I mean Muon-based Brave)

**Comment by paulcbetts** [comment]
Can you verify the version of Squirrel being used here? We try to mitigate this as early as possible in setup

**Comment by Metnew** [comment]
I've used the latest [windows-installer](https://github.com/electron/windows-installer/tree/master/vendor). As far as I understand, that's [Squirrel 1.9.0](https://github.com/electron/windows-installer/pull/267)

**Comment by Metnew** [comment]
Actually, the version of `Setup.exe` in electron-winstaller repo is 1.8.0, not 1.9.0.

**Comment by paulcbetts** [comment]
Alright, I'm not super interested in the Win7 issues, but I do think we can fix urlmon (and iertutil by proxy). If you're feeling up to it, can you send in a PR to mark urlmon as delay-load? If not I can do it

**Comment by paulcbetts** [comment]
![image](https://user-images.githubusercontent.com/1396/48639519-ab167580-e988-11e8-87e3-8b8d0c8b5c88.png)

**Comment by Metnew** [comment]
@paulcbetts Sadly, I can't send a PR (no background in Windows).

**Comment by Metnew** [comment]
Any updates on this?
Sorry for asking, but that's a security issue :(

**Comment by paulcbetts** [comment]
@metnew I'll get to it eventually, I'm not suuuuuper worried about it. Every browser is super wise to DLL planting and makes you click through like 4 scary dialogs to make it happen

**Comment by shiftkey** [comment]
The `urlmon.dll` issue was fixed in #1444, and I'm not sure how much interest there is for `version.dll` given #738 was opened a while ago but never went anywhere.

If someone wants to take a shot at addressing `version.dll` I'd be interested in reviewing a PR, but otherwise I'm going to close this out as resolved.
