### ISSUE TITLE
How to check if another instance already completed the update?

### ISSUE THREAD

**Issue by dsikic** [Squirrel/Squirrel.Windows#1416]
Hi.

Suppose there are two instances running of version 1.0.0. They each periodically run UpdateApp() on a background thread, and if successful prompt for a restart. 

If both call UpdateApp() at the same time, the built in mutex takes care of that which is great. However, if instance#2 calls UpdateApp() after instance#1 has already completed it, nothing happens. 

The CurrentlyInstalledVersion() will return 1.0.0 for that instance forever and UpdateApp won't do anything until 1.0.2 is out.

Could we have a LatestInstalledVersion() which would return 1.0.1 to tell this instance that an update has already taken place? 

Then perhaps: 

if(umgr.LatestInstalledVersion() > umgr.CurrentlyInstalledVersion()) 
    prompRestart = true; 

In my testing code I'm not using CheckForUpdates() as I don't see the benefit of adding more code than UpdateApp() but if I'm wrong, please correct me. 

I'm just trying to simulate various scenarios before integrating it into existing projects. Thus far, it's miles ahead of ClickOnce, and very easy to use, so thank you!

Just to be clear, I understand that I can look for newer folders which may exist outside of the current version directory. However, if there's something already baked in, I'd rather use it. :)

Thanks.

**Comment by dsikic** [comment]
Come to think of it, I can check the version of the stub exe located next to update.exe and if newer then prompt. I'd still like to know if there's something else, but that's what I'll do for now.

**Comment by owns** [comment]
This is how I check if there's already been an update installed
```csharp
bool updatesExist;
            
using (var mgr = new UpdateManager(Properties.Settings.Default.ReleasesFolder))
{
    // check if updates were installed - are we a version behind?
    var curr = mgr.CurrentlyInstalledVersion();
    var fd = mgr.RootAppDirectory;
    log.DebugFormat("searching for update from {0} in '{1}' ...", curr, fd);
    updatesExist = Directory.EnumerateDirectories(fd, searchPattern: "app-*", searchOption: SearchOption.TopDirectoryOnly)
        // to version
        .Select(s => NuGet.SemanticVersion.Parse(Path.GetFileName(s).Substring(4)))
        // greater than current?
        .Where(v => v > curr).Any();
}
```

**Comment by Thieum** [comment]
@dsikic did you manage to fix your issue with your own solution, or @owns solution?

**Comment by dsikic** [comment]
I did something pretty much identical to @owns ’s solution.


On May 2, 2019, at 00:18, Matthieu Penant <notifications@github.com<mailto:notifications@github.com>> wrote:


@dsikic<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsikic&data=02%7C01%7C%7C5e2851a6bf1d4195422c08d6ceb549bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636923675349172853&sdata=D63w29yGrF734D4OCWl2HI8EeIOa6mfpbSrNxqYfcxI%3D&reserved=0> did you manage to fix your issue with your own solution, or @owns<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fowns&data=02%7C01%7C%7C5e2851a6bf1d4195422c08d6ceb549bc%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636923675349182870&sdata=d%2BTgF5WBManiaXspffKprIkAeYZoc2XOpkRUNm7uyhI%3D&reserved=0> solution?

**Comment by shiftkey** [comment]
@dsikic thanks for following up. I'm going to close this out as resolved.
