### ISSUE TITLE
Shortcut overwritten if similar program is installed

### ISSUE THREAD

**Issue by pltaylor** [Squirrel/Squirrel.Windows#1417]
I have an application where I have created 2 .nuspec files, one for a beta release and one for a main release.  The application ids are different i.e. MyApplication and MyApplicationBeta and most of the other fields have 'Beta' added to them.  In my project file I have it create an output of MyApplication if the release build configuration is built and MyApplicationBeta if the ReleaseForBeta configuration is built.  This all works fantastically except when I install both applications on 1 computer the squirrel installer deletes the desktop shortcut of the 1st application installed when I install the 2nd one.  Both of the applications are installed to the users local directory in 2 different folder i.e. MyApplication and MyApplicationBeta but the shortcut disappears.  What can I do to keep both shortcuts?

**Comment by Thieum** [comment]
@pltaylor Do you change the name of your assembly, when switching from channel to channel? We found it easier this way to have individual shortcuts. One way to do it is to create a temporary csproj with the AssemblyName that fits with your channel from a script at publish time.

**Comment by gojanpaolo** [comment]
@pltaylor Theium's https://github.com/Squirrel/Squirrel.Windows/issues/1417#issuecomment-488769721 works. Basically, you should [determine how Squirrel.Windows gets your app's shortcut names](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/naming.md#shortcut-name). From there, create a build process such that it switches the name for main/beta release.

**Comment by shiftkey** [comment]
Closing this out as it looks like there's a resolution here
