### ISSUE TITLE
GitHubUpdateManager private repo

### ISSUE THREAD

**Issue by DatalyticUk** [Squirrel/Squirrel.Windows#1423]
I have a private repository. Adding the access key to the GitHubUpdateManager as part of the string fails to authorise (I don't know if this has changed recently). 

`client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("token", accessToken);`

is required.

The second problem is that the returned UpdateManager does not have any mechanism for using this token - will call github and fail on authorisation with any requests. 

I am also confused why GitHubUpdateManager is just a static method returning the standard UpdateManager. Unless I am missing something it makes more sense to extend the UpdateManager (if not then name should really be something like "CreateGitUpdateManager"). This also avoids the double request call when you want to check for updates as this method gets list of updates from github then creates the UpdateManager which then calls github to see if updates.

**Comment by stajs** [comment]
The official word: [no, you can't use a private repo](https://github.com/Squirrel/Squirrel.Windows/issues/911#issuecomment-431689041).

The access token was initially added to [up the rate limit](https://github.com/Squirrel/Squirrel.Windows/pull/464). I've never tested a private repo, but what might add to the confusion:

1. A casual glance at [the GitHub API docs](https://developer.github.com/v3/#authentication) suggests to me that authentication with the token _should just work_.
2. It may [have worked in the past](https://github.com/Squirrel/Squirrel.Windows/issues/134).
3. Squirrel does [set the token on the client](https://github.com/Squirrel/Squirrel.Windows/blob/250fe4ce09035a682d90836f8c89097760638f66/src/SyncReleases/SyncImplementations.cs#L49).

**Comment by paulcbetts** [comment]
Do you really want to embed a read-repo token for your app's source code in a place your users could trivially obtain it?

**Comment by stajs** [comment]
Well, nahhh, not for the general case - it defeats the purpose of a private repo! However thinking out loud, I wonder if there is a case for "trusted" users of an internal app. Even then it probably falls in to the Chris Rock you-can-drive-with-your-feet camp of bad ideas. I was thinking if it was technically feasible rather than if you should.

**Comment by DatalyticUk** [comment]
Doesn't have to be embedded into the code, can be read from an external source. In my case the code belongs to the client as is custom built for them and only used by them, they have access to this repo anyway.  I wanted to provide one click updates so seemed to make sense to do it via GitHub (as its all there anyway) rather than from my own server.

**Comment by PerezRE** [comment]
> Doesn't have to be embedded into the code, can be read from an external source. In my case the code belongs to the client as is custom built for them and only used by them, they have access to this repo anyway. I wanted to provide one click updates so seemed to make sense to do it via GitHub (as its all there anyway) rather than from my own server.

Trying to do the same. Were you @DatalyticUk able to do it with a private GitHub repository and Squirrel.Windows? I have tried with a public one and works fine but we talk about the private ones, the app which look for updates just simply get stucks by permissions.

**Comment by paulcbetts** [comment]
@PerezRE Just use S3, or set up a public GitHub repo that only has releases

**Comment by Thieum** [comment]
@shiftkey this should be closed as wontfix.

**Comment by yigitcanolmez** [comment]
why wont you fix this ulan?

**Comment by yigitcanolmez** [comment]
ı was wondering how can ı use a private repo? can you guys help me ?

**Comment by caesay** [comment]
A bug is the reason private repo's don't work here. I have fixed this, and private repositories do work just fine [in the fork that I maintain.](https://github.com/clowd/Clowd.Squirrel) Create an update manager like so: `new UpdateManager(new GithubSource(...))` and pass in an access token that has access to your target private repo's releases. 

Of course do be aware that this token will be easily accessible to your users by opening your source code in a decompiler or hex editor, and iirc GitHub currently does not allow you to grant read-only permission to a private repository, so all of your users will be able to edit your repository. (in other words, it's not a great idea)

**Comment by anaisbetts** [comment]
why why why would you ship a feature like that?

**Comment by caesay** [comment]
All I did was fix a bug 🤷‍♂️. One of many many bugs I fixed here. I'm not the updates police. People can ship updates in a publicly editable google doc for all I care.
