### ISSUE TITLE
update.exe help printed over prompt

### ISSUE THREAD

**Issue by ferenczy** [Squirrel/Squirrel.Windows#1425]
When I print `update.exe`'s help using `update.exe --help` it's somehow weirly printed over the prompt. Respectively, the prompt is printed over the help, see:

![squirrel-update](https://user-images.githubusercontent.com/1712992/49614676-452b7580-f9ab-11e8-9298-ac10c4ab340a.png)

It's same in both `cmd` and PowerShell. Unfortunatelly, I don't know the exact version and it's possible that newer one doesn't behave like that anymore.

**Comment by paulcbetts** [comment]
Yep, this is because Update.exe shipped to an app is a Win32 PE not a Console PE. If it wasn't this way, background updates would pop CMD dialogs
