### ISSUE TITLE
How to Retrieve the FutureReleaseEntry release notes?

### ISSUE THREAD

**Issue by jaspervanzfive** [Squirrel/Squirrel.Windows#1436]
Hi i started using squirrel in my app and I can update my app smoothly from the web location(where i put my setup, versions)

I want to get the release notes for the future version. 
I can get get the future version's version number however, i couldnt get the release notes of it.

Here's my code 

```
 using (var mgr = new UpdateManager(@"http://mysamplewebsite.com/version/"))
{
 var updateInfo = await mgr.CheckForUpdate();

                    if (updateInfo.ReleasesToApply.Any())
                    {
                        string futureVersion = updateInfo.FutureReleaseEntry.Version.ToString();
                       //GOOD
                        MessageBox.Show(futureVersion);
                        
                       var futureReleaseNotesLocalDirectory = updateInfo.FutureReleaseEntry.GetReleaseNotes(@"C:\Users\source\repos\UpdateAppTesting\Releases");
                        //GOOD I can even get the release notes in my local directory
                        MessageBox.Show(futureReleaseNotesLocalDirectory);
                      

                     //giving me an error of URI FORMATs are not supported
                      var futureReleaseNotesWEBLocation = updateInfo.FutureReleaseEntry.GetReleaseNotes(@"http://mysamplewebsite.com/version/");
                        MessageBox.Show(futureReleaseNotesWEBLocation);
                    }
                    else
                    {
                        MessageBox.Show("No updates detected.");
                    }
}
```

While i can get the update's release notes through the directory , I cannot get the release notes through web url location.

The web url location is working because i can get the future version's version number. 
But when i am trying to get the release notes, its giving me an error of
**URI FORMATs are not supported**

Hope someone can help me, because release note is very important for the user know what is the new update/changes from the app. 
Thanks

**Comment by Inzanit** [comment]
This isn't the intended usage of this API, you need to provide the path to the package to get the notes this way.

https://github.com/Squirrel/Squirrel.Windows/blob/39c42be73c50be3497b1c66eb4be9d04aae7521d/src/Squirrel/ReleaseEntry.cs#L77-L87

I think this can be closed @shiftkey
