### ISSUE TITLE
Update Topshelf service

### ISSUE THREAD

**Issue by Abd3lrhm4n** [Squirrel/Squirrel.Windows#1439]
I have used Squirrel.Windows trying to update my topshelf service so i used that code
`
            using (var manager = new UpdateManager(@"D:\win Service project\Firebase Version\New folder\3ayezPricesService\Versions"))
            {
                    await manager.UpdateApp();
             }`
so when i extract the setup.exe folders inside appdata:- app-versionNumber, packages, Service.exe and update.exe
inside app-4.0.0 i got the service with all dlls so i went inside and hosted it by topshelf by using install cmd in cmd prompt and everything working well
we i make new version and put it in specify folder i get new app-5.0.0 with the new version contain on all dlls and libraries but when i were trying to run the service the old version which works which hosted by topshelf so i have to uninstall it and install(host) the new one 
but when i run the service.exe which out of app folder  which in the same location with update.exe the new version works but as a console app what should i do?!

**Comment by paulcbetts** [comment]
You cannot update NT Services via Squirrel, since it doesn't run as administrator. Sorry!

**Comment by Abd3lrhm4n** [comment]
@paulcbetts  first thank you, you made me end this and saved my time
sorry for that but do you know another way ?!

**Comment by ricardopolo** [comment]
@Abd3lrhm4n you could use https://github.com/kohsuke/winsw with the auto download parameters
