### ISSUE TITLE
Install some files based on OS version?

### ISSUE THREAD

**Issue by MihaMarkic** [Squirrel/Squirrel.Windows#1446]
I'm thinking of redistributing VC++ 2015 redistributables and some of them apply only on when Windows <10.
So, is there a way to copy(install) files based on Windows OS version?
I guess a workaround is to have two separate installation packages which I'd like to avoid though.

**Comment by paulcbetts** [comment]
There isn't, sorry :(

**Comment by MihaMarkic** [comment]
@paulcbetts Thanks, I thought so and I thought of the same workaround :) Perhaps something to consider in the future.

**Comment by shiftkey** [comment]
Closing this out as this doesn't seem feasible currently with how Squirrel is architected 😢

**Comment by MihaMarkic** [comment]
Understood. Just write it down somewhere if you are re-architecting squirrel in future.
