### ISSUE TITLE
How to get ReleaseNotes from the GitHub updatemanager?

### ISSUE THREAD

**Issue by alexdi220** [Squirrel/Squirrel.Windows#1449]
Hi. I use github releases and squirrel. The UpdateManager works fine but I have no idea how to get the release notes for the available update. Could someone help? I have tried updateInfo.ReleasesToApply.FirstOrDefault().GetReleaseNotes("my GitHub repo url") 
but it just raises an exception: System.NotSupportedException: 'The given path's format is not supported.'

**Comment by owns** [comment]
This is a bit old, but have you tried using [DownloadReleases](https://github.com/Squirrel/Squirrel.Windows/blob/250fe4ce09035a682d90836f8c89097760638f66/docs/using/update-manager.md)? you'll have to download the release beforehand to get the info.

**Comment by alexdi220** [comment]
Don't worry. I'll close the issue. We no longer show release notes in our app.
