### ISSUE TITLE
What kind of host should i put my squirrel Setup in to be able to update Online ?

### ISSUE THREAD

**Issue by Abd3lrhm4n** [Squirrel/Squirrel.Windows#1450]
I have tried squirrel and it success to update my application locally but i wanna to host it 
i have tried google drive and firebase storage but didn't do anything so what kind of host should i use ?!

**Comment by cfguimaraes** [comment]
I've made in my own host.
What I've seen is that HTTPS is required.
All you have to do is to make your RELEASES directory be in sync with your site folder, after that, point UpdateManager to that HOST ADDRESS.

**Comment by Abd3lrhm4n** [comment]
i made it since long days
