### ISSUE TITLE
Squirrel Event Convert to VB.Net

### ISSUE THREAD

**Issue by arifaarish** [Squirrel/Squirrel.Windows#1451]
Hi,

I am trying to convert Squirrel events on VB.Net but getting error "Expression does not produce the value" on the below line of code
SquirrelAwareApp.HandleEvents(onAppUpdate:=Login.OnAppUpdate, onAppUninstall:=Login.OnAppUninstall, onInitialInstall:=Login.OnInitialInstall) 
Since I have login form and for OnAppUpdate event , I have written below code
  Friend Shared Sub OnAppUpdate()
        Throw New NotImplementedException()
    End Sub

Request you to please help me out. I can't convert my whole application on C#

**Comment by rvoisin** [comment]
This should work for you.

`Squirrel.SquirrelAwareApp.HandleEvents(onInitialInstall:=AddressOf onSquirrelAppInstall,
                                                                   onAppUpdate:=AddressOf onSquirrelAppUpdate,
                                                                   onAppUninstall:=AddressOf onSquirrelAppUninstall,
                                                                   onFirstRun:=AddressOf onSquirrelFirstRun,
                                                                   onAppObsoleted:=AddressOf onSquirrelAppObsoleted)`

**Comment by shiftkey** [comment]
As this is a general question about porting C# APIs to VB.NET rather than anything we can change in Squirrel.Windows, I'm going to close this out as I think @rvoisin has answered the question as best as possible...
