### ISSUE TITLE
Unable to download previous version full package.

### ISSUE THREAD

**Issue by BradB111** [Squirrel/Squirrel.Windows#1457]
Hello all,

I cant seem to be able to get the exe to download a previous 'full' package, only deltas.

What commands do I need to add to the exe shortcut target?

I have a release list and the download url.
Any help will be much appreciated.

**Comment by Inzanit** [comment]
You'll need to provide some more information, I it'd be handy to know if you're hosting these packages yourself, going through GitHub releases or what your setup is.

Might be worth explaining:
- How you go about packaging your application, do you have scripts for this or is it a manual process
- What arguments are you passing to `releasify`
- How are you versioning?
- How are you deploying?
- How have you implemented the `UpdateManager` in your app.

**Comment by BradB111** [comment]
Sorry all, I believe I was trying to use the updater incorrectly by basically trying to 'break' it to force a previous version download for content I wasn't hosting. (basically an old version of a particular app worked and the new one didn't and the devs refused to let people downgrade / download previous versions) 

Needless to say the app in question has since been updated and is now full working and this should have been closed sooner.
