### ISSUE TITLE
cleaning up old packages in fully automated deployment

### ISSUE THREAD

**Issue by themightylc** [Squirrel/Squirrel.Windows#1459]
Hello.
I'm sure I've read this before, but I can't find the info anymore... is it safe to delete old release packages?
I am using Squirrel to deploy my software in 3 "branches": stable, beta and dev. Currently I am making a lot of small updates and the packages start piling up in the download folders, as well as on my build agent machine.
My software is force-auto-update and nobody will ever want to install an "older version".
Everything is automated and works so well that I have to think hard about my workflow, but I have two folders on my build machine that are not getting cleaned up: a "Packages" folder where I put the source nuget Package, and a "Releases" folder where I build the Installer, Full- and Delta-Packages. This directory is being uploaded in it's entirety after each release as I am too lazy to write a script that only grabs new files.

**My Questions:**

1. I actually only need the latest FULL package in the path that is served to the end-user correct?
2. I'm on build 1.0.200 and delete everything up to 1.0.196, then everyone on a lower version will automatically be served with a full package, correct?
3. Can I also delete the old "source packages" with that mindset? The squirrellify-process will only create deltas for the full packages that remain and then it's the same situation as 2., correct?

Thank you very much for your time to answer.
For clarification, these are the folders I am referring to:
![image](https://user-images.githubusercontent.com/6189326/54373571-c4e97000-467d-11e9-8fd6-520b9f7b1256.png)
as clearly seen by the dates, each build adds a new "source" package to the Packages folder, then a new Installer, Full and Delta Package are created in the "Releases" folder which then is uploaded to the webserver.

**Comment by paulcbetts** [comment]
> I actually only need the latest FULL package in the path that is served to the end-user correct?

You don't need to use delta packages, correct. That being said, from your screenshot it's clearly saving you bandwidth, but if you're deploying internally where you don't care about bandwidth, you can just use full packages.

In a production deployment Over The Internet, it's usually a good idea to keep a few months worth of versions, so that if users get behind they can delta their way back up.

> I'm on build 1.0.200 and delete everything up to 1.0.196, then everyone on a lower version will automatically be served with a full package, correct?

Correct

> Can I also delete the old "source packages" with that mindset? The squirrellify-process will only create deltas for the full packages that remain and then it's the same situation as 2., correct?

From a build perspective, you only need one version behind's full package.

**Comment by themightylc** [comment]
You the man, Paul.
My first point was badly formulated though, I intend to keep the Delta packages. But only the latest full.
