### ISSUE TITLE
How squirrel update the updater.exe?

### ISSUE THREAD

**Issue by dengyaolong** [Squirrel/Squirrel.Windows#1461]
I wonder that squirrel updater.exe how to update itself?
It seem's like a loop question?

**Comment by Inzanit** [comment]
There's options in `Update.exe` to self update, which involves the updater looking for specific files in the downloaded package. If you're interested in how this works (or indeed, how to achieve it), you can find it here:

https://github.com/Squirrel/Squirrel.Windows/blob/39c42be73c50be3497b1c66eb4be9d04aae7521d/src/Squirrel/UpdateManager.ApplyReleases.cs#L346-L368

**Comment by shiftkey** [comment]
Thanks for the detailed answer @Inzanit!

I'm going to close this out for now, but @dengyaolong please also check out the [documentation](https://github.com/Squirrel/Squirrel.Windows/tree/master/docs) that has more details about the various features.
