### ISSUE TITLE
Incompatible with Splat 7.0.1

### ISSUE THREAD

**Issue by ondrasvoboda** [Squirrel/Squirrel.Windows#1462]
The latest Splat version 7.0.1 has some breaking changes that makes squirrel updates failing with:
Method not found: 'Void Splat.IFullLogger.Info(System.String, !!0)'

So avoid updating of Splat package, until this version is supported by squirrel.

**Comment by paulcbetts** [comment]
Fixed in #1464

**Comment by jeremy-bridges** [comment]
Is this the permanent fix for this issue? As other dependencies of our application depend on Splat 7.0.1 and newer, Squirrel will prevent us from moving forward with other updates. Akavache 6.5.1 is an example. I wouldn't mind submitting the pull request to use 7.0.1. Sound good?

**Comment by jeremy-bridges** [comment]
I've discovered this update would require an update to .NET Framework 4.6.1. Likely, you would judge this update as a breaking change, moving Squirrel to 2.0.0. For us, this is not an issue as this is already a requirement of our apps. How many other users need to stay with 4.5?

**Comment by Thieum** [comment]
@jeremy-bridges considering .NET 4.5 is no long supported [since january 2016](https://devblogs.microsoft.com/dotnet/support-ending-for-the-net-framework-4-4-5-and-4-5-1/), I'd consider it legitimate to upgrade to a newer version. I'm not fully aware of all the implications. We choose to discuss the different dependency upgrades in [this issue](https://github.com/Squirrel/Squirrel.Windows/issues/897).

**Comment by jeremy-bridges** [comment]
I've commented there about moving to 4.6.1. 

Another part of this pull request will have to be how to implement newly required parts of Splat's iLogger interface. There's three new methods on that interface that seem to be implemented to select an underlying logger for any particular provider:

void Write(Exception exception, string message, LogLevel logLevel);
void Write(string message, Type type, LogLevel logLevel);
void Write(Exception exception, string message, Type type, LogLevel logLevel);

I'll need to provide an implementation for these. I can certainly provide an implementation of the first one. It will simply add the exception to the string being written to the log. I assume Squirrel's setup logger won't need a real implementation for the other two overloads (that take a type). The purpose of these is also not very obvious to me, looking through Splat's repository. An example of NLog's implementation can be found below. Seem alright to throw a not-implemented exception for these overloads?

https://github.com/reactiveui/splat/blob/master/src/Splat.NLog/NLogLogger.cs

**Comment by Thieum** [comment]
@jeremy-bridges imho it would be better to avoid the not implemented exceptions, and call the write, like the example you linked, even without using all the parameters as a a default implementation. It would be a matter of adding the proper implementation in here I think: https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/SyncReleases/Program.cs#L92

**Comment by bddckr** [comment]
Here's another one, which brings up the question of why these are different in the first place:
https://github.com/Squirrel/Squirrel.Windows/blob/bdfcd72033565431a04055dcbd525dd2de22f481/src/Update/Program.cs#L808

**Comment by samirem** [comment]
Hi! Is it possible to solve this without downgrading Splat? I have other packages requiring Splat to be 8.2.4 or higher

**Comment by anaisbetts** [comment]
tbh the best solution is probably just to remove Splat entirely since it's too painful of a dependency now

**Comment by rschoenbach** [comment]
I am struggling with the same thing and I am not sure how to resolve. My goal is to be able to use Squirrel and the latest ReactiveUI at the same time. If somebody has time, I would appreciate an explanation.

**Comment by FooBartn** [comment]
@rschoenbach same. This means not using Squirrel for me at this time, unfortunately.
