### ISSUE TITLE
.Net Framework 4.6.1 Fails

### ISSUE THREAD

**Issue by CousinGil** [Squirrel/Squirrel.Windows#1465]
I'm specifying **--framework-version=net461** when releasifying. Now I'm testing my install on a machine **without** .net 4.6.1.

If I am logged in as **admin** user, it prompts me for .Net install and works fine.

If I am logged in as **non-admin** user, it prompts me for .Net install and fails telling me to try installing .Net framework manually.

I understand that the .Net install requires admin privileges (since it is a per machine install).
But, I assumed that the .Net framework install would ask me to elevate to admin but it didn't.
And..running my Squirrel setup.exe "as admin" doesn't solve the problem either.

So is the only solution for getting .Net installed..is to tell my users to have an admin manually install .Net framework and then install my app?

**Comment by CousinGil** [comment]
Disregard...I was testing as a non-admin on Windows Server OS. The server was locked down and preventing the .Net Framework from being downloaded.

**Comment by EasyAsABC123** [comment]
@CousinGil close issue?
