### ISSUE TITLE
Uninstalling application does not remove all files

### ISSUE THREAD

**Issue by loomarc** [Squirrel/Squirrel.Windows#1468]

**Comment by loomarc** [comment]
When a squirrel setup uninstalles the application folder is not removed.
the folder still contains a ```.dead``` file and the file: ```update.exe```

To my opinion an uninstall should leave nothing behind

**Comment by Inzanit** [comment]
This is intentional behaviour by Squirrel, as per https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs

```
// NB: We drop this file here so that --checkInstall will ignore 
// this folder - if we don't do this, users who "accidentally" run as 
// administrator will find the app reinstalling itself on every
// reboot
```

**Comment by loomarc** [comment]
Oke, thanks for the reactions, I could find any documentation about this behaviour but now i know it is intentional behaviour.

**Comment by youyinnn** [comment]
I still can not understand that the `uninstall` process does not finish its job --- "remove everything"

**Comment by Alonzzzo2** [comment]
Can someone explain in more detail why we need the .dead and update files? and this directory, after the app has been removed?
I didn't understand the sentence "the app reinstalling itself on every reboot".
Why would a reboot do anything related to our app if our app is not installed on the machine?
Is it related to the MSI we can create in the releasify process where the app's msi runs on startup?

**Comment by C1rdec** [comment]
This issue is blocking me from having my app on the Windows Store.
![image](https://user-images.githubusercontent.com/5436436/145044821-1c16a861-02a9-45b2-a2da-0f861f0ac086.png)

**Comment by patrickklaeren** [comment]
> This issue is blocking me from having my app on the Windows Store.
> 
> ![image](https://user-images.githubusercontent.com/5436436/145044821-1c16a861-02a9-45b2-a2da-0f861f0ac086.png)
> 
> Any news?

Might I suggest to use MSIX packaging instead and use the Store's native update functionality.

**Comment by C1rdec** [comment]
Yes but since the Microsoft Store now support `.exe` I think this should be considerate.
I found that the .dead file is only used for `Machine Wide Installer` would it be possible to by pass this for an `exe` ?
