### ISSUE TITLE
Fork NuGet into Squirrel org

### ISSUE THREAD

**Issue by robmen** [Squirrel/Squirrel.Windows#1472]
Squirrel.Windows (as of today) contains a submodule reference to NuGet. That submodule points to https://github.com/paulcbetts/NuGet which we don't (and shouldn't) have the ability to update *and* is now a redirect (https://github.com/anaisbetts/NuGet).

We should have a fork of the dependency in the Squirrel org.

I don't have Squirrel level access but if @shiftkey could create the fork, I'll take care of getting it set correctly and the submodule reference updated.

**Comment by shiftkey** [comment]
Done (and you've got admin rights if you need to manage it @robmen): https://github.com/Squirrel/NuGet
