### ISSUE TITLE
add a basic issue template to the repository

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/Squirrel.Windows#1479]
As a first step to help troubleshooting, this list should help:

 - what squirrel version
 - steps to reproduce
 - expected behaviour
 - actual behaviour

**Comment by Thieum** [comment]
Here is the adapted template used in https://github.com/madskristensen/CommandTaskRunner that matches your criteria:

> ### Squirrel version(s)
> - Squirrel version(s) impacted
> 
> ### Description
> Replace this text with a short description
> 
> ### Steps to recreate
> 1. Replace this
> 2. text with 
> 3. the steps
> 4. to recreate
> 
> ### Current behavior
> Explain what it's doing and why it's wrong
> 
> ### Expected behavior
> Explain what it should be doing after it's fixed.

Not sure how to send a PR for this.

**Comment by shiftkey** [comment]
@Thieum thanks for the suggestions. I took yours as a starting point and opened #1480 to close this out (required admin rights to initialize it).
