### ISSUE TITLE
The type name GitHubManager does not exists in the type UpdateManager

### ISSUE THREAD

**Issue by MikeKatsoulakis** [Squirrel/Squirrel.Windows#1488]
I installed the squirrel.windows NuGet from visual studio. I seem to get a weird error though. What could it be? I am trying to use the GitHubUpdateManager, but I get the error above. Thank you in advance.

**Comment by shiftkey** [comment]
@MikeKatsoulakis it's not clear to me what code you're using or the version of Squirrel.Windows you have installed, but this set of using statements:

```c#
using Squirrel;
```

And this snippet:

```
using (var manager = await UpdateManager.GitHubUpdateManager("https://github.com/shiftkey/my-cool-app"))
{
    // TODO
}
```

Builds for me with Squirrel.Windows `1.9.1`.

**Comment by MikeKatsoulakis** [comment]
@shiftkey Thank you very much for your answer! It seems like I hadn't put the `await` keyword. Even though that does not explain the error, it fixed it. Thanks again!
