### ISSUE TITLE
Using squirrel in delay signed application

### ISSUE THREAD

**Issue by quasarea** [Squirrel/Squirrel.Windows#1489]
**Squirrel version(s)**
1.9.1

**Description**
I'm getting exception during my app start (when its checking for update:

> Getting System.IO.FileLoadException: 'Could not load file or assembly 'Squirrel, Version=1.9.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (0x80131044)

As far as I see squirrel assemblies are not signed (tho package is). Was looking for any documentation on how to deal with unsigned squirrel in delayed signed c# application but without luck, can't find any issues on this as well so I assume I'm doing something wrong, am I? 

Thanks

**Comment by gojanpaolo** [comment]
I found 2 closed issues regarding strong named assemblies.
https://github.com/Squirrel/Squirrel.Windows/issues/711
https://github.com/Squirrel/Squirrel.Windows/issues/199

Solution is to either [stop strong naming your assembly](https://github.com/Squirrel/Squirrel.Windows/issues/711#issuecomment-221702831) or [sign Squirrel during build process](https://github.com/Squirrel/Squirrel.Windows/issues/711#issuecomment-221723644).
