### ISSUE TITLE
Question: How can I migrate from NSIS to squirrel.windows

### ISSUE THREAD

**Issue by liuxini** [Squirrel/Squirrel.Windows#1493]
can I uninstall NSIS package while installing squirrel package?  Or is there any other good way to migrate

**Comment by Code-DJ** [comment]
@liuxini see [Custom Events](https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/docs/using/custom-squirrel-events.mdl).

You can write your custom logic of uninstalling the previous app in onInitialInstall.

```
using (var mgr = new UpdateManager(updateUrl))
{
    SquirrelAwareApp.HandleEvents(
        onInitialInstall: new Action<Version>(v =>
        {
            /* Uninstall Previous app */
        })
    );
}
```

**Comment by liuxini** [comment]
@Code-DJ  thank you， It can really meet my needs
