### ISSUE TITLE
Build Squirrel app from Cmd

### ISSUE THREAD

**Issue by maheesuryal** [Squirrel/Squirrel.Windows#1498]
I have incorporated the auto-update functionality into my app using Squirrel. I have been using the Package Manager Console present in Visual Studio to run the Squirrel commands like "Squirrel --releasify" etc. Is there any way by which I can run those commands using cmd or build the whole app after I build my app using MSBuild?

**Comment by gojanpaolo** [comment]
Hello @maheesuryal you can take a look at [this simple build script](https://github.com/gojanpaolo/SquirrelDemo/blob/master/build.ps1)

**Comment by blazingeagle1002** [comment]
I am facing another issue with the build process.  "Your package version is currently 2019.6.10.1137, which is *not* SemVer-compatible, change this to be a SemVer version number" Any solutions?

**Comment by gojanpaolo** [comment]
@blazingeagle1002 the version number should only have 3 digits. change it to 2019.6.10 and you should be good. :)

**Comment by blazingeagle1002** [comment]
I really need the four digits. Is there any way by which I can do this or maybe disable semver check?

**Comment by gojanpaolo** [comment]
I don't think there will be plans to support non-semver versions. You can always fork Squirrel.Windows to make changes :)
