### ISSUE TITLE
How to manually install previous version for testing?

### ISSUE THREAD

**Issue by JontyMC** [Squirrel/Squirrel.Windows#1503]
I understand from reading other issues that providing support in the framework for rollbacks is undesirable, but how do you manually install a previous version in order to test that it still works?

The setup.exe in the releases folder will always install the latest version.

**Comment by Thieum** [comment]
@JontyMC the best way is to backup the setup.exe for each version to a separate folder, with the name that fits the version. Setup.exe is standalone installer. If you don't have auto-update activated, it will install and run the version it was built with.

**Comment by JontyMC** [comment]
Thanks. I figured out that the exe the shortcut points to is stored in the nupkg as {exeName}_ExecutionStub.exe. So, it's possible to manually sort everything out using that file, amending the RELEASES file and moving some things around.
