### ISSUE TITLE
Add .NET 4.8 support?

### ISSUE THREAD

**Issue by ErikRosengren** [Squirrel/Squirrel.Windows#1505]
Hi!

Any possibility to add support to require .NET 4.8? Currently 4.7.2 is supported and I looked at [the pull request](https://github.com/Squirrel/Squirrel.Windows/pull/1306) when that was implemented and it doesn't look like too much hassle but I might be wrong.

**Comment by Thieum** [comment]
I did most of the work in https://github.com/Thieum/Squirrel.Windows/tree/net48 I think.

The hardest part is testing it - I need to find or setup an environment without .net48 to test that it installs correctly,

**Comment by ErikRosengren** [comment]
Brilliant! I will try to spend a few hours today and tomorrow testing it on a virtual machine. Should I report back here after or is it better to do so in a pull request?

**Comment by Thieum** [comment]
@ErikRosengren You can report here if you have issues with what I coded, and I'll try to help if needed. Considering you'll do the hard part of testing, feel free to send a PR based on what I did, it would be a nice contribution :)

**Comment by ErikRosengren** [comment]
@Thieum I just tried to build a version of our application with the required version 4.8 and I did not get a popup to install .NET. I used a Windows 8.1 installation with .NET version 4.7. I also tried building a version that required .NET 4.7.2 and that worked as expected and I got the .NET update popup.


I also found an issue in Windows 7 with the latest version of squirrel (1.9.1) that was not present in 1.9.0 which is the version that we currently run. It involves not being able to install the application at all and getting an error message that says something like "kernel32 entry point not found" but I have not tested that enough to know exactly what caused it and since it isn't related to this I will raise a separate issue for that.

**Comment by Thieum** [comment]
@ErikRosengren I used this table for the version number, and took the smallest number, like the previous versions: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies

**Comment by ErikRosengren** [comment]
@Thieum I tested it again now with a rebuilt version of the branch and it worked as expected! I must have accidentally built Squirrel incorrectly last time I guess.. I tried Windows 8 and Windows 10 but have not yet tested Windows 7 since it still has issues for me. Looks like it should work with a update that I don't have on my VM so will let you know how it worked on Win 7 when I get that to work.

**Comment by ErikRosengren** [comment]
@Thieum I have now tried it on Windows 7 as well and it works as expected! I have tried a few different scenarios and as far as I can tell it behaves as it has in the past when I have tested it. Thank you very much for putting this together!

Would it be okay with you if you put up the pull request if it is time to do so as I am unsure of how to do it on someone else's fork?

**Comment by Thieum** [comment]
@ErikRosengren Awesome news! Thanks a lot for you efforts in testing, I will send the PR.

**Comment by InteXX** [comment]
I'm adding my vote for Framework 4.8 support.

**Comment by Thieum** [comment]
@anaisbetts fixed with https://github.com/Squirrel/Squirrel.Windows/commit/b2d092b5507f01813a2e9b73b889e73bf59ee2a7 , this can be closed.
