### ISSUE TITLE
Warnings Online about update.exe –processStart

### ISSUE THREAD

**Issue by lukeskinner** [Squirrel/Squirrel.Windows#1508]
I've seen a few social media places in the last day or so mentioning Squirrel in relation to the update.exe –processStart command. 

I normally track all things squirrel through this github as I'm sure others do - I couldn't see this mentioned on here. 

https://medium.com/@reegun/nuget-squirrel-uncontrolled-endpoints-leads-to-arbitrary-code-execution-80c9df51cf12

http://www.hexacorn.com/blog/2019/03/30/sqirrel-packages-manager-as-a-lolbin-a-k-a-many-electron-apps-are-lolbins-by-default/

**Comment by anaisbetts** [comment]
I mentioned this via several tweets, but there's no security boundary being broken here, it's more about evading AppLocker which seems pretty Easy to do in general.

**Comment by lukeskinner** [comment]
Thanks for the response! I'm happy to close this (unless others want it open) - I just saw your tweet on it too.

Makes sense that in general it's pretty easy to replicate this behaviour with other programs/built in windows tools.
