### ISSUE TITLE
Windows 7 support dropped?

### ISSUE THREAD

**Issue by erwinwolff** [Squirrel/Squirrel.Windows#1512]
**Squirrel version(s)**
1.9.1 

**Description**
Installer fails to install on Windows 7

**Steps to recreate**
Create an installer

**Expected behavior**
Should silently install the application

**Actual behavior**
Gives a message about a missing entry on Kernel32.dll on Windows 7

**Comment by anaisbetts** [comment]
Maybe tell us what the message says?

**Comment by erwinwolff** [comment]
Sure:
![image](https://user-images.githubusercontent.com/602021/60770596-d3e8a800-a0dc-11e9-8367-dec1713e58e4.png)

**Comment by lukeskinner** [comment]
When I google the exact error there appears to be a few different solutions online.

One of which being: https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot

Have you tried any of these?

**Comment by anaisbetts** [comment]
@erwinwolff This API was added in Win7 SP1, which you absolutely need to install Right Now.

**Comment by erwinwolff** [comment]
Fair enough, but can we at least have a nice message saying that vanilla Windows 7 isn't supported?

**Comment by erwinwolff** [comment]
That is a change of about 10 lines of C++ code

**Comment by erwinwolff** [comment]
Something along the lines of:

`void MitigateDllHijacking()
{
try
{
	// Set the default DLL lookup directory to System32 for ourselves and kernel32.dll
	SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_SYSTEM32);

	HMODULE hKernel32 = LoadLibrary(L"kernel32.dll");
	ATLASSERT(hKernel32 != NULL);

	SetDefaultDllDirectoriesFunction pfn = (SetDefaultDllDirectoriesFunction)GetProcAddress(hKernel32, "SetDefaultDllDirectories");
	if (pfn) { (*pfn)(LOAD_LIBRARY_SEARCH_SYSTEM32); }

	PreloadLibs();
}
catch (...)
{
MessageBoxW(NULL, L"Setup", L"Installation failed, please run at least Microsoft Windows 7 Service Pack 1", MB_OK);
Exit(EXIT_FAILURE);
}
}`

**Comment by vadi2** [comment]
Could you send that in as a PR?

**Comment by erwinwolff** [comment]
Sure

**Comment by erwinwolff** [comment]
Pull request is under way

**Comment by erwinwolff** [comment]
We have our nice message 🥇 

![image](https://user-images.githubusercontent.com/602021/62078130-26d0fd80-b24c-11e9-9be0-075953fbe8fd.png)

**Comment by jairiidriss** [comment]
> When I google the exact error there appears to be a few different solutions online.
> 
> One of which being: https://support.microsoft.com/en-us/help/2533623/microsoft-security-advisory-insecure-library-loading-could-allow-remot
> 
> Have you tried any of these?

Thank you, your proposal has fixed this issue for me

**Comment by robmen** [comment]
Thanks for this change. However, I decided to go a slightly simpler route in 0bad6df14d9fdbb1c23686d77003fcf53bcfcc44 by skipping the hijack if the OS doesn't support it. Vanilla Win7 is out of service and not getting security updates. Squirrel doesn't need to block and be the one to tell people they need to upgrade to get secure. :)

**Comment by lavahasif** [comment]
https://catalog.update.microsoft.com/Search.aspx?q=KB4343900

i updated this version .problem solved .other link expired
https://www.dell.com/support/kbdoc/en-in/000177896/microsoft-windows-7-update-kb2533623-needed-to-install-dell-update-package-dup
