### ISSUE TITLE
squirrel is downloading the new version on auto update and not deleting the older one

### ISSUE THREAD

**Issue by MuhammadHaseebAli** [Squirrel/Squirrel.Windows#1514]
![2019-07-23 18_51_54-Window](https://user-images.githubusercontent.com/19229312/61717692-fafcd600-ad7a-11e9-9f36-9a4b1d14cdf5.png)

**Comment by Mrxx99** [comment]
I don't think that is a bug but more intended behavior. It will keep I think the last 1 or 2 older versions always around. If you search a bit you find documentation about it or at least another similiar issue that has already an explanation.

**Comment by musmuris** [comment]
It will keep one previous version around - so when 1.4.0 (or higher version than 1.3.0) gets installed , and then subsequently run, it should clean up 1.1.0

**Comment by MuhammadHaseebAli** [comment]
@musmuris @Mrxx99 The main problem is when user login in windows both of the versions Launch Automatically . desired behavior is it should not auto launch  the previous version
