### ISSUE TITLE
Any way to clean old releases from a Releases folder

### ISSUE THREAD

**Issue by musmuris** [Squirrel/Squirrel.Windows#1515]
Each .nupkg we're making is ~100Mb and we release often (and every day into a "canary" channel). Realistically we only need to keep the last 10.  Is there a way, or has anyone crafted a way, to clean up old versions?

If not I plan to get some powershell to do this, possibly using squirrel.exe as a library if possible. This is assuming it's just remove lines from RELEASES file and clean up packages.

**Comment by anaisbetts** [comment]
You can just delete them and remove lines from RELEASES

**Comment by musmuris** [comment]
Thanks @anaisbetts  - I just a way to automate it. I was hoping to use the existing code, but it's all ilmerge'd in. I can use some powershell.  It might be nice to add a `--keep-n-releases=10` option to the `--releasify` to effect this as well? Can look at making a PR if people think that's reasonable?

**Comment by anaisbetts** [comment]
Update.exe already has 10230232032 parameters, I don't think we really need any more. You can automate it by just simply adding in a shell script:

```
tail -n 10 RELEASES > RELEASES
```

**Comment by musmuris** [comment]
Well except you have to remove the old files and possibly then the oldest -delta package if using them (I've not check if that gets ignored or not). And yes I've automated in Powershell, just thought it would be a nice option (and given how many options some things have (e.g. curl to pick one out the air) Update really doesn't have that many :) ) But saves me making a PR.
