### ISSUE TITLE
Shortcut points to wrong path? (non C# app)

### ISSUE THREAD

**Issue by eiymba** [Squirrel/Squirrel.Windows#1516]
**Squirrel version(s)**
1.9.1

**Description**
Hi, apologies for raising an issue. I am reluctant to call it a bug as it's very specific to my use case. 

I'm hoping to get a little guidance on my use case if possible.

Using the `--releasify` argument from the command line works to install the app, however the shortcuts it creates point to the wrong path, e.g,

```sh

C:\Users\eiymba\AppData\Local\MyApp\program.exe

```

instead of:

```sh

C:\Users\eiymba\AppData\Local\MyApp\app-1.0.0\program.exe

```

__I'm not entirely sure__ whether the issue is caused because the `app-1.0.0` in the path shouldn't exist, or whether the installer just hasn't concatenated it properly for the shortcut. 

I'm actually using Squirrel in a very similar manner to the Electron installer for Node.js applications, but my app is purely command line.

I snooped around and deduced that [UpdateManager.ApplyReleases.cs](https://github.com/Squirrel/Squirrel.Windows/blob/develop/src/Squirrel/UpdateManager.ApplyReleases.cs#L229) plays a hand at creating the shortcuts. On line `229`, I noticed the `target` path does not concatenate anything specifically which would indicate the presence of the `/app-1.0.0` subdirectory. I'm not sure what the expected behaviour to be. 😕 

Any help is appreciated. Thanks!

**Comment by eiymba** [comment]
Okay I figured it out. No worries!

So in a Node.js application, the `SquirrelAwareVersion` technique proposed in the documentation is realistically unfeasible. To give background, I create the binary with [pkg](https://github.com/zeit/pkg) and then use that with Squirrel.

In order to apply the `SquirrelAwareVersion`, I ran `rcedit` on pkg's cache of the precompiled binary. Prior, I was running `rcedit` on the result of the pkg process which broke the executable. As a temporary hack, I make the process fail once to download the binary and then run rcedit on that first. The output of that pkg process is used by Squirrel. Afterwards, I monitor the flags which my app is ran by `Setup.exe` and I'm finally able to see it being launched with the `--squirrel-install` flag, as well as others.

I recognise that this process inevitably means I make my own shortcuts when the `--squirrel-install` flag is detected.

I've basically been following how it's done in Electron and recreated the process for my use case.

Hopefully, this information may help others in future. 😘

**Comment by anaisbetts** [comment]
Command line apps don't get shortcuts by default because they wouldn't work right (the window would be invisible). We've discussed doing a node.js-style `.cmd` stub but nobody _really_ has needed it.#command

**Comment by farhadfarhadii** [comment]
Right, okay. That makes sense. Thanks for taking the time to read my issue and helping me, @anaisbretts! I managed to get everything working in the end! 😄

**Comment by eiymba** [comment]
Right, okay. That makes sense. Thanks for taking the time to read my issue and helping me, @anaisbretts.

Also, whoops! Posted my initial response on the wrong account! 😲
