### ISSUE TITLE
Question: Auto-updating non C# app? 🤔

### ISSUE THREAD

**Issue by eiymba** [Squirrel/Squirrel.Windows#1519]
Hello!

I'm looking for some guidance regarding using GitHub for releases, for a non C# app. I'm really just looking to learn here so there's no expectation that this is a necessity.

Since I can't directly use the `UpdateManager`, here are some of the solutions I have.

1. Don't, LUL 🤣 .
2. Create a C# program which acts as a wrapper for Squirrel.
    - Point the GitHub `UpdateManager` to `/my-repo/my-app/releases/latest`.
    - Compile and use that as a drop-in for `update.exe`.
3. Recreate the `UpdateManager` and difference checking in JavaScript using the GitHub API.
    - Modify the Squirrel source if need be so the update can be triggered by spawning `update.exe` with the new proprietary flag.
4. Compile my app into a stand-alone binary executable, and import that into a C# app which can spawn it, and performing the updating procedures via the `UpdateManager`.
5. Something else I have overlooked. 🤔

Any advise is appreciated, Thanks! ❤️ 

_Edit: I'm aware of the `--obsolete` flag but not quite sure how to trigger that._

**Comment by anaisbetts** [comment]
The way that non-C# apps use Squirrel is to invoke `update.exe` with various flags, `--update` being the easiest one:

```
../update.exe --update https://path/to/the/updates
```

**Comment by eiymba** [comment]
LOL you're kidding me?! It's _THAT_ easy? That's brilliant, thank you @anaisbetts, you're the best! 😄

I'm sure glad I asked first in that case.

So with the path to the updates, am I correct in assuming I would point that to `/repos/eiymba/my-app/releases/latest` ? And also, the update release is to have a delta NuGet package?

Sorry for asking so many questions! I'm a bit dim witted and I have to double check what I've understood is correct, otherwise I go down rabbit holes and dead ends. 😩

**Comment by eiymba** [comment]
Oh, I see. the `--update` flag will try to download from `<URL>` with query parameters `localversion` and `arch`. So, if I just create a back-end server which checks my GitHub releases using those parameters, I assume that could sent whatever the updater needs?

I need to figure out exactly what I should send back if that's the case... 🤔

**Comment by anaisbetts** [comment]
You don't need an update server, just take the Releases folder and upload it to S3 or any other static file host, then point `--update` at that URL (without RELEASES at the end)

**Comment by eiymba** [comment]
@anaisbetts Thanks so much for being patient with me! ❤️ 

That's a lot easier than what I had in mind. I'm going to play with this information and see how it works out for me.

So, could you help clarify something for me? I read in the docs that the RELEASES file I upload containing the information for the update has to be "manually" edited to point to the new release. Squirrel then uses this information to deduce whether to download the delta package or the full package. Is this correct?

Apologies for imposing onto your time, genuinely appreciate you helping me! As you can see, if left unguided my imagination tends to lead me astray...

**Comment by anaisbetts** [comment]
> So, could you help clarify something for me? I read in the docs that the RELEASES file I upload containing the information for the update has to be "manually" edited to point to the new release.

No, you only need to manually edit RELEASES if you pull a release. If you just make a new release, you don't have to hand-edit this file, Squirrel --releasify will do this all for you. 

>  And also, the update release is to have a delta NuGet package?

You don't have to have delta releases, but obviously they'll save you bandwidth and your users download time. In general, you don't have to Think about delta updates, Squirrel will do them automatically on your behalf. If you decide to _pull_ a release, you should pull both the delta and full entries from the RELEASES file.

**Comment by eiymba** [comment]
Right, okay. See, this is why I have to ask so many questions, otherwise I end up going awry pretty quickly!

I'm trying out the S3 deployment method now, and I'll get back to you if I have any more questions, though probably not today since I don't want to be too imposing. Thanks again! Hope you enjoy the rest of your day/evening! 😄

**Comment by eiymba** [comment]
@anaisbetts thank you, thank you, thank you! ❤️ 

I managed to get it working last night and I've been playing around with it ever since. It's really quite astonishing. This is actually the first time I've written software using this type of practice and i'm very pleased with the results.

I don't mean to come off as rude in anyway, but if it's welcomed then I wouldn't mind documenting this process...er... just in case it hasn't been done already.

![Thank  You](https://media2.giphy.com/media/13qctMBrrgbwJi/source.gif)
