### ISSUE TITLE
Taskbar icon...has no icon

### ISSUE THREAD

**Issue by 50Wliu** [Squirrel/Squirrel.Windows#152]
Refs #137.

The newly-added taskbar icon uses the default (super-ugly) missing icon.  In addition, it has no name.
Might be an Atom bug, in which case I'll comment over there.

![noicon](https://cloud.githubusercontent.com/assets/2766036/5328902/a7778708-7d61-11e4-996b-c4a11af7b42e.png)

**Comment by paulcbetts** [comment]
Fixed in #184
