### ISSUE TITLE
Application version not SemVer-compatible

### ISSUE THREAD

**Issue by jainpratham1989** [Squirrel/Squirrel.Windows#1540]
**Squirrel version(s)**
Squirrel.Windows version 1.2.2.

**Description**
I have build a WPF application which has version "2.2.0.2" in AssemblyInfo.cs file and I have build a nuget package for this project. I am getting the below error on executing the releasify command: 
Squirrel --releasify C:\MyProjects\MyWPFApplication\MyWPFApp.2.2.0.2.nupkg

Squirrel : System.Exception: Your package version is currently 2.2.0.2, which is *not* SemVer-compatible, change this to be a SemVer version number
At line:1 char:1
+ Squirrel --releasify C:\MyProjects\MyWPFApplication
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Exceptio... version number:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProce
ssor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, 
String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion, Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)   

**Expected behavior**
It should releasify the application and create new Release build in Releases folder without any error.   

**Actual behavior**
It did not create new release build and giving the above exception on executing Releasify command. I came to know of "Sem Version" which has form X.Y.Z and contains only three digits but in my application I need to depict application version in 4 digits.

Please let me know how can I resolve this issue ASAP.

Regards,
Pratham

**Comment by anaisbetts** [comment]
You resolve it by using a SemVer-compatible version number, like it says in the message

**Comment by Lukkian** [comment]
You should do as @anaisbetts said and please consider close this issue ASAP.

**Comment by ynsbleng** [comment]
Why this limitation?

**Comment by lobbo232** [comment]
@anaisbetts Is this still the case? There is no support for 4 part version numbers? (a.b.c.d)
You closed this case without an explanation other than "do what the message says"

**Comment by anaisbetts** [comment]
@lobbo232 Correct, you need to use SemVer-compatible versions. The explanation is that many of the version parsers in Squirrel (the C++ one in the bootstrapper and the C# one inside the core updater) are SemVer version parsers. Your actual executable can have any version it wants, but the NuGet package (and by extension, the version that Squirrel understands) has to be SemVer.
