### ISSUE TITLE
"Invalid release entry: \t\t<!DOCTYPE html>"

### ISSUE THREAD

**Issue by dhiliph98** [Squirrel/Squirrel.Windows#1545]
**Squirrel version(s)**
1.9.1

**Description**
Getting this error Invalid release entry

protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            Task.Run(async () =>
            {
                using (var mgr = UpdateManager.GitHubUpdateManager(MyURLString, accessToken: MyAccessToken))
                {
                    try
                    {
                        await mgr.Result.CheckForUpdate();
                    }
                    catch (Exception ex)
                    {
                        throw;
                    }
                }
            });
        }

**Comment by anaisbetts** [comment]
Your update server is returning a web page, or one of your users are on a network that is blocking updates.
