### ISSUE TITLE
.Net Core 3.0 with Squirrel

### ISSUE THREAD

**Issue by ghaith100994** [Squirrel/Squirrel.Windows#1547]
**Description**
I don't need An Updater 
I only need Squirrel.Windows for releasing Installing
After Installing App work fine
but if i close it and reopen the app through desktop shortcut it's not open
if open it from the package through the find app location it's work

**Steps to recreate**
1. Create Wpf core 3.0 
2. Add Squirrel.Windows
3. releasify through package manger console  
4. Installing App

**Comment by Thieum** [comment]
Duplicates #1374
