### ISSUE TITLE
UpdateManager.RestartApp() makes windows server 2012 R2 opens crash form

### ISSUE THREAD

**Issue by leventmenekse** [Squirrel/Squirrel.Windows#1548]
**Squirrel version(s)**
1.9.1

**Description**
UpdateManager.RestartApp() actually does its job but windows server 2012 R2 says "Application crashed". New exe does not start untill i click "Close the program" button. After i do, updated version works.

**Steps to recreate**
1. `var x = await msg.UpdateApp();`
2. `try
            {
                UpdateManager.RestartApp();
            }
            catch(Exception)
            {
                //SWALLOW
            }`

**Expected behavior**
Close the current version without giving any error

**Actual behavior**
Windows Server 2012 R2 says for the current version "it is crashed". New version isn't open untill i click to close button.

**Additional information**
> 2019-10-07 15:32:35> Program: Want to launch 'C:\StockMountMasterV2\app-1.10.33\Haser.StockMount.Consumer.Master.exe'
> 2019-10-07 15:32:35> Program: About to wait for parent PID 19356
> 2019-10-07 15:32:56> Program: About to launch: 'C:\StockMountMasterV2\app-1.10.33\Haser.StockMount.Consumer.Master.exe': 

![windowsForm](https://user-images.githubusercontent.com/1311988/66314326-8b7b9900-e91c-11e9-8673-4e6b093e6097.PNG)

After close program is clicked then new version can start. I couldn't find any issue like this but if its duplicate, apologies.

**Comment by varKeytrap** [comment]
Hi,

I had the same problem "Threading.AbandonedMutex".
Try replace .RestartApp() function with
 ```UpdateManager.RestartApp($"\"{Path.GetFileName(Assembly.GetEntryAssembly().Location)}\"");```
