### ISSUE TITLE
Errors when attempting interactive updates

### ISSUE THREAD

**Issue by steveski** [Squirrel/Squirrel.Windows#1561]
I've followed the example here https://github.com/Squirrel/Squirrel.Windows/issues/979 but I'm facing some issues I just can't work out. I've actually put the code provided into a separate SoftwareUpdater project in Visual Studio and provide a callback function from the main application for providing the UI interaction so I can reuse this library with WinForms, WPF or whatever without the updater library needing to know what presentation technology is being used:

`public class SquirrelUpdater : ISoftwareUpdater
{
    private static readonly Logger _logger = LogManager.GetCurrentClassLogger();

    public async Task UpdateAsync(string updateUri, Func<string, PerformSoftwareUpdate> confirmUpdateFunc)
    {
        using (var mgr = new UpdateManager(updateUri))
        {
            // https://github.com/Squirrel/Squirrel.Windows/issues/979
            _logger.Info("Checking for updates...");
            try
            {
                var updateInfo = await mgr.CheckForUpdate();                
                if (updateInfo.ReleasesToApply.Any())
                {
                    var versionCount = updateInfo.ReleasesToApply.Count;
                    _logger.Info($"{versionCount} update(s) found.");

                    var versionWord = versionCount > 1 ? "versions" : "version";
                    var message = new StringBuilder().AppendLine($"App is {versionCount} {versionWord} behind.")
                        .AppendLine("If you choose to update, changes won't take affect until App is restarted.")
                        .AppendLine("Would you like to download and install them?")
                        .ToString();

                    var result = confirmUpdateFunc(message);
                    if (result != PerformSoftwareUpdate.Yes)
                    {
                        _logger.Info("Update declined by user.");
                        return;
                    }

                    _logger.Info("Downloading updates");
                    var updateResult = await mgr.UpdateApp();
                    _logger.Info(
                    $"Download complete. Version {updateResult.Version} will take effect when App is restarted.");
                }
                else
                {
                    _logger.Info("No updates detected.");
                }
            }
            catch (Exception ex)
            {
                _logger.Warn($"There was an issue during the update process! {ex.Message}");
            }
        }
    }
}`

When debugging I found that the `var updateInfo = await mgr.CheckForUpdate();` call got swallowed up and when this happens it's usually something to do with async, my calls are correctly configured as far as I can tell:
`public async Task RunAsync()
{
    // Check for software updates
    var updateUri = ConfigurationManager.AppSettings["UpdateUri"];
    await _softwareUpdater.UpdateAsync(updateUri, message =>
    {
        var result = MessageBox.Show(message, @"App Update Available", MessageBoxButtons.YesNo);
        return result == DialogResult.Yes ? PerformSoftwareUpdate.Yes : PerformSoftwareUpdate.No;
    });

    ConfigureEnvironment();

    // Make simple call to database to ensure it gets created if not present
    var custs = _repository.GetCustomers();

    Application.Run(_mainForm);
}`

If I take out the calls to the update the application runs fine.
Soo, I tried releasifying to see what happens and it installs but I get a stack of errors
[SquirrelSetup.log](https://github.com/Squirrel/Squirrel.Windows/files/3835980/SquirrelSetup.log)

The C:\Users\steve\AppData\Local\ServiceToolbox\packages\ exists so why is it complaining about not being able to write to .betaid? Isn't this stuff supposed to be done by Squirrel?

I'm lost, anyone know what may be going on?

**Comment by anaisbetts** [comment]
> 2019-11-12 22:38:48> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: Access to the path 'C:\Users\steve\AppData\Local\ServiceToolbox\app-1.5.5\ServiceToolbox.exe' is denied.
