### ISSUE TITLE
The request was aborted: The connection was closed unexpectedly

### ISSUE THREAD

**Issue by andrewstillie** [Squirrel/Squirrel.Windows#1563]
Hi - I am struggling to get the Squirrel updater to work with github.  I am currently getting the error message in the title of this thread.  Can anyone help or point be at a step by step tutorial for setting this up?

**Comment by anaisbetts** [comment]
I would read the documentation, but in general this is telling you your HTTPS server is being blocked by a firewall or it isn't able to negotiate a TLS connection
