### ISSUE TITLE
Couldn't write out staging user ID, this user probably shouldn't get beta anything

### ISSUE THREAD

**Issue by Mourad57** [Squirrel/Squirrel.Windows#1567]
**Squirrel version(s)**
1.9.1

**Description**
Whenever an update is performed on my application, i got an error dialog saying "Application XYZ has stopped working"

In the log we can see the following lines : 
CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path ....

If i close the dialog and start the application, it runs then fine.

**Steps to recreate**
1. create a squirrel package for Application XYZ
2. run the package on the machine having already an old version installed

**Expected behavior**
Update is performed, and starts the updated application.

**Actual behavior**
Error dialog is shown with the message "Application XYZ has stopped working"

**Additional information**
The fix proposal #1071 is obviously not helping since for me it occurs in 1.9.1

**Comment by anaisbetts** [comment]
If Application XYZ is not working, then Application XYZ crashed, this message "Couldn't write out staging user ID" is unrelated
