### ISSUE TITLE
Squirrel not working with Themida packed exe

### ISSUE THREAD

**Issue by chldbwnstm** [Squirrel/Squirrel.Windows#1568]
**Squirrel version(s)**
_Which version(s) of the project are you using?_ Latest

**Description**
1. I package my exe with themida TigerVM. Then, the auto updater unpackages the files until the exe file then stops from then. For example, for app-1.0.1 to 1.0.2, successfully checks the difference then downloads 1.0.2 full nuget package successfully, creates app-1.0.2 folder then starts unpackaging, downloads well until it reaches the Themida packed exe, does not unpackage from that specific exe.

**Steps to recreate**
1. Package exe with themida
2. squirrel --releasify app then put it on http server
3. start update with the old version

**Expected behavior**
unpackaging stops at themida packed exe.

**Actual behavior**
It should unpackage all the files in the package.

**Additional information**
_Add any other context about the problem here_

**Comment by anaisbetts** [comment]
I have no way to test Themida TigerVM or any other proprietary packing software, and you have provided zero debugging information. Please take this up with your packager vendor.
