### ISSUE TITLE
DeleteDirectory doesn't delete junction symlinks

### ISSUE THREAD

**Issue by shaharmor** [Squirrel/Squirrel.Windows#1570]
**Squirrel version(s)**
latest

**Description**
When Squirrel tries to "burn down" the app folder, it doesn't delete any symlinks that were created within that folder, and thus fails in the removal of the app folder, which aborts the installation.

**Steps to recreate**
1. Install once
2. Create "junction" symlink from within the app folder (appdata\local\app\symlink)
3. Try to install again

**Expected behavior**
Should successfully remove the old installation and re-install

**Actual behavior**
Some of the old app files are being removed, while the symlink remains, and the new installation is aborted

**Comment by anaisbetts** [comment]
Everything under `app-` is owned by Squirrel, creating junctions inside that folder isn't supported, sorry

**Comment by shaharmor** [comment]
I am not talking about the `app-x.y.z` folder, but 1 level above it.

If my app is called "MyApp": `C:/Users/Username/appData/Local/MyApp` is the folder that contains the symlink, not `C:/Users/Username/appData/Local/MyApp/app-1.2.3`
