### ISSUE TITLE
Releasify removes the ability to switch application languages

### ISSUE THREAD

**Issue by Drise13** [Squirrel/Squirrel.Windows#1571]
**Squirrel version(s)**
1.9.1, latest

**Description**
After building with a Multilingual App Toolkit build and releasifying, my build is no longer able to display alternate languages.

Pre-releasify:

(This is a Pseudo-language for debugging purposes)  
![image](https://user-images.githubusercontent.com/10517125/71285052-dd339d00-2329-11ea-8655-1ab3db9ecaf0.png)

Post-releasify:

![image](https://user-images.githubusercontent.com/10517125/71285127-07855a80-232a-11ea-9f2b-ad4bbfd4acef.png)

**Steps to recreate**
1. Use MSBuild to create a Multilingual App Toolkit enabled build.
2. Run the built exe
3. Notice the language adaptations
4. Releasify
5. Notice the lack of language adaptations

**Additional Notes:** 
Setting up a MAT build for MSBuild is not intuitive. You need to extract the `$MSBuild` contents from the VSIX plugin (MAT is *only* available as a plugin, which seems silly) to your msbuild directory.

Something like:
![image](https://user-images.githubusercontent.com/10517125/71285353-95614580-232a-11ea-9402-7c9aa33b20ca.png)

Otherwise, most guides should provide the ability to get started with a MAT project.

Setting up the pseudo language:

```
        public static string appTestCulture = "qps-PLOC";

        [STAThread]
        public static void Main()
        {
            Thread.CurrentThread.CurrentCulture = new CultureInfo(appTestCulture);
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(appTestCulture);
            ........
            app.run
         }
```

**Comment by anaisbetts** [comment]
It sounds like some files aren't being distributed with your app (the MUI files?) - check to see that the files that end up in `%LocalAppData%\yourapp\app-VERSION` are the same as the ones in the build directory

**Comment by Drise13** [comment]
@anaisbetts Yea, looks like we are missing all of these. That probably explains things.
![image](https://user-images.githubusercontent.com/10517125/71285834-c3935500-232b-11ea-92a5-d28542d195ec.png)

**Comment by Drise13** [comment]
Our nuspec (which is how I assume these are getting copied):

```
  <files>
    <file src="*.*" target="lib\net45\" exclude="*.pdb;*.nupkg;*.vshost.*"/>
  </files>
```

**Comment by Drise13** [comment]
Confirmed, it was the lack of `**` for folder recursion. Closing.
