### ISSUE TITLE
SharpCompress version fixed in 1.9.1, potentially inadvertently?

### ISSUE THREAD

**Issue by chrisalexander** [Squirrel/Squirrel.Windows#1572]
**Squirrel version(s)**
1.9.0 trying to upgrade to 1.9.1

**Description**
In this commit: https://github.com/Squirrel/Squirrel.Windows/commit/c1e8987e2a42c7124600a79b7592d67fbd488969#diff-3b1ce2ddd72c8c150c95e50f61b0778e @anaisbetts looks like a version bump also included a change which fixes the SharpCompress dependency version to 0.17.1. I am already ahead of this as was permitted by the 1.9.0 version, which means that I am now in a bit of a funny state as I would have to go backwards on SharpCompress in order to forwards on Squirrel.

Now as this isn't linked to a work item or mentioned in the commit, I wonder if it was accidental while testing something else at the same time as doing the version bump. Is it possible to check, and if so, can 1.9.2 be issued with it rolled back?

Having a search of the issues I see there have been some issues upgrading it in the past, so similarly if it is now a requirement to have 0.17.1 it would be good to know that for certain so I can take positive action to roll that back.

Thank you :-)

**Comment by chrisalexander** [comment]
Having thought about it a bit more, it almost looks like it was _meant_ to be fixed before, and this change actually made it work? Not a massive nuget dependency expert so not sure.

**Comment by anaisbetts** [comment]
The dependency is intended to be pinned, you should definitely go backward as all subsequent versions of SharpCompress are incompatible with Squirrel

**Comment by chrisalexander** [comment]
Thank you for the clarification! :)
