### ISSUE TITLE
squarrial1

### ISSUE THREAD

**Issue by jayr713** [Squirrel/Squirrel.Windows#1574]
**Squirrel version(s)**
_Which version(s) of the project are you using?_

**Description**
_Replace this text with a short description of the problem_

**Steps to recreate**
1. Replace this
2. text with 
3. the steps
4. to recreate

**Expected behavior**
_Explain what it's doing and why it's wrong_

**Actual behavior**
_Explain what it should be doing after it's fixed_

**Additional information**
_Add any other context about the problem here_

**Comment by Inzanit** [comment]
Looks like spam @shiftkey
