### ISSUE TITLE
Is a partial update app possible?

### ISSUE THREAD

**Issue by greengumby** [Squirrel/Squirrel.Windows#1579]
Hi,

Really liking Squirrel and am hoping the development continues but I am wondering if there is a way to compartmentalize the updates.

For example the main application is over 500Mb but inside that application are several unrelated components each of which are only 1Mb.

Can you have the nuspec setup in a way that there are dependencies to other nuspec files each of which download and update independently?

There would be no point running the component without the main application so no shortcut would be required and the components would have to install to a location known to the main application to run.

Thanks

**Comment by anaisbetts** [comment]
Squirrel doesn't support this feature, sorry
