### ISSUE TITLE
Auto update from web host

### ISSUE THREAD

**Issue by khold93** [Squirrel/Squirrel.Windows#1597]
**Squirrel version(s)**
squirrel.windows 1.9.1

**Description**
The app doesn't update

First of all sorry if I'm not suppose to ask question here, but I couldn't find anywhere else to ask.

I followed guides both here and on youtube and it seems straight forward. However all update guides are locally. 
I have packed it with "NuGet Package Explorer - Store - X64 - (5.6.3+236ad96855)" and everything seems fine.

I uploaded the files to the web host's server

![Capture](https://user-images.githubusercontent.com/62477961/77325186-2a078500-6d18-11ea-8285-39bc7d237c89.PNG)

![Untitled3](https://user-images.githubusercontent.com/62477961/77325788-27f1f600-6d19-11ea-81af-76ab0cc0dcfc.png)

`string networkPathForUpdate = @"https://x.com/y/release/";`

 `private async Task CheckForUpdate()`
        `{`
            `using (var manager = new UpdateManager(networkPathForUpdate))`
            `{`
               `await manager.UpdateApp();`
            `}`
        `};`

Any idea what I'm doing wrong? Is it not able to see my files at the webhost?
Sorry again if I'm not suppose to ask this sort of questions here.

- Tore

**Comment by anaisbetts** [comment]
Does that path actually exist? Like, `https://x.com/y/release/RELEASES` fetches your RELEASES file?

**Comment by khold93** [comment]
Yes, the path exist. I'm not sure how to check if it fetches anything thought, however I did a couple test tries today and they both worked. No changes to code etc, so I have no idea why it works now.
Perhaps a nuget package explorer issue
Thanks for replying!

**Comment by varKeytrap** [comment]
What error do you have ?

**Comment by khold93** [comment]
Hey
Haven't updatet my application in a few weeks but I did it today. Same issue again as earlier. No update happens. I wish I could tell you what kind of error I get. Honestly not sure how I'm gonna debug it since it's a released product & it's grabbing update from the web. Please tell me if you know a decent way to debug it :)

_I want to point out that this worked for my build 1.0.7 to 1.0.8 with no issues._

`string networkPathForUpdate = @"https://brukstuen.com/bygg/release/";`
Current build on computer: 1.0.8

Files at https://brukstuen.com/bygg/release/ (see picture below)
![Untitled](https://user-images.githubusercontent.com/62477961/80622745-8497ad80-8a49-11ea-9ebc-21b73d71e4a9.png)

This is from NuGet. It still managed to update from 1.0.7 to 1.0.8 with this "Missing Symbol errors", but I don't know why they suddently appeared. I did not have them the first 4 builds.
![Capture](https://user-images.githubusercontent.com/62477961/80623204-24553b80-8a4a-11ea-939e-2b7a3e28fa4a.PNG)

**Comment by varKeytrap** [comment]
You can have an index.html/php or whatever you want in the release directory of your web server. The updater looks for the file RELEASES. Can you try a post request with Postman on https://brukstuen.com/bygg/release/RELEASES and post a screenshot of the response ? (I’m on my phone actually so I can’t do it right now).
Also, can you post a screenshot of your nuget package manager « Installed » tab please ? (In Visual Studio)

**Comment by khold93** [comment]
Thanks for quick reply.
See pictures below
<details>
  <summary>Postman</summary>
![postman](https://user-images.githubusercontent.com/62477961/80694657-1ac4e580-8ad5-11ea-94d3-f299877d4aca.PNG)
</details>

<details>
  <summary>NuGet Packages</summary>
![Capture](https://user-images.githubusercontent.com/62477961/80694644-15679b00-8ad5-11ea-9eed-f8a7d1c09264.PNG)




</details>

**Comment by varKeytrap** [comment]
Can you remove

- Squirrel.Windows
- Splat
- SharpCompress
- Mono.Cecil
- DeltaCompressionDotNet

And reinstall squirrel.windows ?
Then make a screenshot of the 'Installed' tab again

From my experience, splat has to be v1.6.2 max (the v9.X gives me errors)

**Comment by khold93** [comment]
Done, Splat is now 1.6.2 automatically as you recommended
![bilde](https://user-images.githubusercontent.com/62477961/80706480-aeec7800-8ae8-11ea-9045-89f8e9a499e3.png)

Should I try to update my app a couple times now? one for local build, than a new one to the web and see if it updates?  If no responds I will try it and update this message within a couple hours with the result :)

**Comment by khold93** [comment]
Sounds good!
Thanks :)

**Comment by Zujaj** [comment]
@BarryThePenguin 

> **Squirrel version(s)**
> squirrel.windows 1.9.1
> 
> **Description**
> The app doesn't update
> 
> First of all sorry if I'm not suppose to ask question here, but I couldn't find anywhere else to ask.
> 
> I followed guides both here and on youtube and it seems straight forward. However all update guides are locally.
> I have packed it with "NuGet Package Explorer - Store - X64 - (5.6.3+236ad96855)" and everything seems fine.
> 
> I uploaded the files to the web host's server
> 
> ![Capture](https://user-images.githubusercontent.com/62477961/77325186-2a078500-6d18-11ea-8285-39bc7d237c89.PNG)
> 
> ![Untitled3](https://user-images.githubusercontent.com/62477961/77325788-27f1f600-6d19-11ea-81af-76ab0cc0dcfc.png)
> 
> `string networkPathForUpdate = @"https://x.com/y/release/";`
> 
> `private async Task CheckForUpdate()`
> `{`
> `using (var manager = new UpdateManager(networkPathForUpdate))`
> `{`
> `await manager.UpdateApp();`
> `}`
> `};`
> 
> Any idea what I'm doing wrong? Is it not able to see my files at the webhost?
> Sorry again if I'm not suppose to ask this sort of questions here.
> 
> * Tore

`string networkPathForUpdate = @"https://x.com/y/release/";`

`string networkPathForUpdate = @"https://x.com/y/release";` //Remove the trailing slash

**Comment by Thieum** [comment]
@khold93 if your issue is fixed, feel free to close this thread.
