### ISSUE TITLE
[Feature Request] Add ability to truly install in system context/ for all users

### ISSUE THREAD

**Issue by o-l-a-v** [Squirrel/Squirrel.Windows#1601]
GitHub, Teams, Yammer. They all have the same problem, thanks to Squirre.Windows. They can't really be installed in system context.

The current way of installing a installer that then again eventually installs the application when a user logs in. It's not working very well. For Teams we find that users often have to log in and out multiple times before Teams eventually appears. It also makes it harder to manage applications in a client management solution like Intune, where we'd prefer to install applications in system context/ for all users.

Please add ability to truly install and run applications in system context (to %ProgramFiles(x86)% or %ProgramW6432%).

Reference to my GitHub Desktop issue on install switches:

* https://github.com/desktop/desktop/issues/9408

**Comment by anaisbetts** [comment]
Sorry, this breaks one of the core tenets of Squirrel, to be able to update in the background without requiring a UAC dialog or a reboot. Unfortunately because Teams is using their own (broken) fork of Squirrel, they're no longer getting any bug fixes, even if we were to do this Teams wouldn't get it.

**Comment by thomasdarde** [comment]
Dear @o-l-a-v , have you found a solution to create this kind of .msi, I'm reviewing electron-wix-msi for this specific case

**Comment by o-l-a-v** [comment]
> Dear @o-l-a-v , have you found a solution to create this kind of .msi, I'm reviewing electron-wix-msi for this specific case

Nope, sorry. We're using Intune MDM for all our client management, so we're just rolling with the broken Office PeoPlus installer that includes Teams.

If I had to make a solution to this I'd probably package a PowerShell script that downloads and installs latest version of Teams in user context, inside a Win32 package for detection rules.

**Comment by thomasdarde** [comment]
Thanks for the update , I was able in the end to do a "clean" intune compatible .msi package thanks to 👍 

https://github.com/felixrieseberg/electron-wix-msi
