### ISSUE TITLE
How prevent unwanted shortcuts?

### ISSUE THREAD

**Issue by Pengii** [Squirrel/Squirrel.Windows#1604]
**Squirrel version(s)**
Latest version

**Description**
This seems like a problem when I escpecially use the CefSharp libraries. On first installation Squirrel is creating an empty shortcut of CefSharp alongside my apps main shortcut.

**Steps to recreate**
1. Add CefSharp to winforms app
2. Pack it
3. Install the app from Squirrel package

**Comment by extstopcodepls** [comment]
Have you try [this](https://stackoverflow.com/questions/42970309/squirrel-windows-create-multi-shortcut-on-desktop)?

**Comment by anaisbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md will help you out!
