### ISSUE TITLE
How to use multiple release channels for .Net Windows application?

### ISSUE THREAD

**Issue by SunnySv72** [Squirrel/Squirrel.Windows#1606]
Hi,

I am new to Squirrel.Windows. I am implementing a Windows Forms application and I want to use Squirrel.Windows for the deployment using multiple release "channels", therefore it can be easy for UAT purpose. In issue #795, two users @SissiKonsta and @dennismi successfully implemented the same i.e.

- https://github.com/Squirrel/Squirrel.Windows/issues/795#issuecomment-255842749

- https://github.com/Squirrel/Squirrel.Windows/issues/795#issuecomment-265702633

So could you also please show a bit more detail on how did you achieve releasing for multiple channels.

Thanks

**Comment by Inzanit** [comment]
Can't speak for the other two. We achieve this through having two individual applications, one for live and one for staging.

**Comment by dennismi** [comment]
Yup that's the way to go..

\\Dennis

________________________________

**Comment by Thieum** [comment]
Same here. We have a ps1 script that transforms the csproj and nuspec file to have different assembly names for each versions.

**Comment by SunnySv72** [comment]
Thanks @Inzanit , @dennismi , @Thieum 
However, I need some more details about the same therefore could you please given me some sample code and bit more detail about how we can implement the same so that it would be easy for me.
@Thieum, could you please give me also some sample code for ps1 script to change the assembly name  in .csproj file.

@SissiKonsta could you please also help me by sharing some details on how did you achieve releasing for multiple channels.

Thanks

**Comment by Inzanit** [comment]
Our build pipeline handles this according to the branch being built.

Steps:
1) Rename "Product" property in csproj, this serves as the application name
2) Modify the nuspec (or properties in nuspec), version/nuget package id/description
3) Compile app
4) Use nuget.exe to pack app
4.5) Download RELEASES file from target destination (if it exists)
5) Releasify
6) Distribute

**Comment by SunnySv72** [comment]
Thanks @Inzanit 

I need some more help from your side for the very first step, as per the [document ](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/naming.md#shortcut-name) Squirrel takes the shortcut name from "Assembly.cs" and to automate the process, is there any way to change the Assembly Title and other assembly information automatically. 

Thanks

**Comment by anaisbetts** [comment]
If you want multiple release channels, you upload your installer to different paths (i.e. `myproduct.com/updates` vs `myproduct.com/dev-updates` and change the update URL. 

The solution that others describe of having separate app names can work too if you want to allow people to have *both* dev and prod versions of the app installed at the same time, but if you don't need that, the former solution is way easier.
