### ISSUE TITLE
could not find project “Core.csproj”

### ISSUE THREAD

**Issue by YouDragonZhang** [Squirrel/Squirrel.Windows#1607]
Squirrel 1.9.1

![微信截图_20200402130318](https://user-images.githubusercontent.com/20747354/78212485-7609b500-74e2-11ea-9bdd-980e0d0c3000.png)

**Comment by anaisbetts** [comment]
You need to clone the submodule via `git submodule update --init --recursive`

**Comment by YouDragonZhang** [comment]
非常感谢。
Thank you very much.
