### ISSUE TITLE
Running installer with /quiet fails

### ISSUE THREAD

**Issue by kevinsawicki** [Squirrel/Squirrel.Windows#161]
Ran `AtomSetup.exe /quiet` and got this.

![screen shot 2014-12-10 at 3 26 25 pm](https://cloud.githubusercontent.com/assets/671378/5386452/f607ebf2-8080-11e4-82bf-f793665c7fab.png)

Log contents:

```
Program: Starting Squirrel Updater: /quiet
```

**Comment by kevinsawicki** [comment]
Bump, was hoping to push the new installer to chocolatey but having a quiet install would be pretty nice.

**Comment by paulcbetts** [comment]
Can you give this a try with the latest release? I think @flagbug already fixed this

**Comment by kevinsawicki** [comment]
Sure thing

**Comment by kevinsawicki** [comment]
Still seeing it, just to confirm, running something like `MySetup.exe /quiet` should be supported right?

![screen shot 2015-01-08 at 5 38 33 pm](https://cloud.githubusercontent.com/assets/671378/5674318/34af7422-975d-11e4-91b4-dde860ce0cf9.png)

![screen shot 2015-01-08 at 5 37 57 pm](https://cloud.githubusercontent.com/assets/671378/5674310/1bf59c04-975d-11e4-982b-35dc1336fda0.png)

Maybe I'm doing something wrong? If you run an installer for a squirrel app you've built with `/quiet`, you don't see this error?

**Comment by paulcbetts** [comment]
I didn't verify it; I'll go HAM on this tomorrow

**Comment by flagbug** [comment]
I've only fixed the quiet switch when you call `FullInstall` in the C# API, maybe this is a separate issue?
