### ISSUE TITLE
Invalid Release entry

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [Squirrel/Squirrel.Windows#1625]
Hi I am trying to build using electron builder, everything works but I get the following err. I tried to setup __url__ against `.exe` too but nothing works. __url__ is fine, works perfectly in the browser.

![image](https://user-images.githubusercontent.com/46624268/83778312-fa73e200-a6a3-11ea-82e3-7549da3b3874.png)

**Comment by anaisbetts** [comment]
That is indeed a completely invalid release entry. Electron Builder is not supported here, because they use a fork of Squirrel.Windows

**Comment by muhammad-usman-anwar** [comment]
so what should I use? @anaisbetts

**Comment by muhammad-usman-anwar** [comment]
I am using electron builder, configured to use `squirrel` as target and its running in release and is not a first run.

**Comment by anaisbetts** [comment]
I personally am a big fan of Electron Forge!
