### ISSUE TITLE
Does Squirrel Support Compressed(Zip/ Rar) Setup Updates?

### ISSUE THREAD

**Issue by Zujaj** [Squirrel/Squirrel.Windows#1626]
I am using Squirrel `UpdateManager.GitHubUpdateManager`  method to update my app. In my **Github Release** Tab, I have the following files:

**1. MyDummyApp-1.0.0-full.nupkg
2. RELEASES
3. Setup.exe
4. Setup.msi**

- Rather than individual files, is it possible that squirrel would work if I compress these files into a single rar/ zip file?

- If so how?

**Comment by anaisbetts** [comment]
Squirrel updates are already compressed, you cannot combine these files any further. Usually the thing you want to hand to users is `Setup.exe`, you don't need to give them anything else ✨

**Comment by tonyzoi** [comment]
> Squirrel updates are already compressed, you cannot combine these files any further. Usually the thing you want to hand to users is `Setup.exe`, you don't need to give them anything else ✨

How can I give the online url path for update the exe. I am using like following. But it shows 404 error
using (var updateManager = new UpdateManager("https://subdom.domain.com/testagentzoi/sqsetup/Releases"))
{                    
    await updateManager.UpdateApp();
}

**Comment by Zujaj** [comment]
> > Squirrel updates are already compressed, you cannot combine these files any further. Usually the thing you want to hand to users is `Setup.exe`, you don't need to give them anything else ✨
> 
> How can I give the online url path for update the exe. I am using like following. But it shows 404 error
> using (var updateManager = new UpdateManager("https://subdom.domain.com/testagentzoi/sqsetup/Releases"))
> {
> await updateManager.UpdateApp();
> }

It seems that this link is not working, I opened it and it says Error 404. Please fix the link.

**Comment by Zujaj** [comment]
> Squirrel updates are already compressed, you cannot combine these files any further. Usually the thing you want to hand to users is `Setup.exe`, you don't need to give them anything else

You're wrong when I only upload Setup.exe in my release (public Github repo) , I get errors. 
After uploading the Release file along with -full.nupkg file all errors are resolved. Can you please elaborate your statement?

**Comment by lightlike** [comment]
`RELEASES`is kind of an indexing file telling squirrel which versions are available to download and the size of each file.
Squirrel always looks for that file and determines the version to update to.

But that only matters for updates. The `Setup.exe` already contains a Version for your program, as Squirrel does not know where to download any packages as you manage that inside your code.

**Comment by Zujaj** [comment]
> `RELEASES`is kind of an indexing file telling squirrel which versions are available to download and the size of each file.
> Squirrel always looks for that file and determines the version to update to.
> 
> But that only matters for updates. The `Setup.exe` already contains a Version for your program, as Squirrel does not know where to download any packages as you manage that inside your code.

So what are the files that should be uploaded only?

**Comment by lightlike** [comment]
The Updating needs `RELEASES` and every file that is named in there for full functionality. (But will also work with last version only. Only `delta` packages need successive versions)
If you are using the `GithubUpdateManager` you can also have different Versions via different Github-Releases.

`Setup.exe` only needs to be used manually so you could deploy that separately in any way you want.
