### ISSUE TITLE
Customizing the Application Shortcut created by Squirrel

### ISSUE THREAD

**Issue by sharadnair** [Squirrel/Squirrel.Windows#1629]
**Squirrel version(s)**
1.9.1.0

**Description**
Shortcut to the application is using the name from assemblyinfo.cs file, butin our scenario we have the same application installed twice on the machine for different configuration. We have unique package id but when the application is installed there is only one shortcut. So my question is - is there a way to instruct squirrel to use the Title from the nuget package for creating shortcut ?

**Steps to recreate**
Create application exe MyApp.exe
AssemblyTitle is 'MyApp' in  AssemblyInfo.cs 
In nuget package, use id myapp_test and title MyApp (Test)
Install the app
Shortcut created is MyApp
Create another nuget package with id myapp_uat and title MyApp (UAT)
Install the app
Shortcut created is MyApp

**Expected behavior**
I want the shortcut for both the app to come from the title included in the nuget package

Is there any way i could achieve this. We want our customers to take the same app and publish it for different testing enviornments like (UAT and Staging)

**Comment by InteXX** [comment]
There's a workaround. You can do this using your release pipeline. It's a bit awkward, but it can be done.

Add a RegEx step in your release tasks that uses a scoped variable to update `AssemblyInfo.cs` accordingly, and then a build step that creates your custom-named assembly.

I'm doing this with a RegEx step that updates a working environment setting in `MyApp.exe.config` (`<appSettings><add key="Environment" value="Test"/></appSettings>` in my case), so I don't need the extra build step. But there's no reason you can't use it.

This should work for you.

**Comment by anaisbetts** [comment]
Make your app a squirrel aware app and create the shortcuts yourself, there are several APIs to help you do this

**Comment by InteXX** [comment]
@anaisbetts 

This looks interesting, but the APIs don't seem to be documented anywhere. I'm not finding clarity on how to use them (but I could be looking in the wrong place).

For example, what do `exeName` and `programArguments` mean in this call:

`GetShortcutsForExecutable(exeName, locations, programArguments)`

How are these APIs intended to be used?

**Comment by InteXX** [comment]
@anaisbetts 

I took a walk through the source just now, and there doesn't seem to be a way to specify the shortcut name. The shortcut target, yes—but not its name.

Please correct me.
