### ISSUE TITLE
Preventing setup from deleting folders within the LocalAppData (is it possible)

### ISSUE THREAD

**Issue by GeekyEggo** [Squirrel/Squirrel.Windows#1630]
### Scenario

Our customers wishes to...
- Block auto updates (via blocking our update URL).
- Themselves distribute latest (accepted) version of `Setup.exe` within their network.

### Problem

1. User installs application.
1.1. Application is installed under `%LOCALAPPDATA%\Foo`.
2. User uses application.
2.1. Files / folders, i.e. settings, are created within `%LOCALAPPDATA%\Foo`.
3. User's sys admin pushes out new `Setup.exe`.
4. `Setup.exe` removes all files / folders within `%LOCALAPPDATA\Foo`.
5. User settings are lost.

### Question

Is it possible to prevent `Setup.exe` from removing all files / folders?
_N.B. It isn't *just* settings, there are also files that reside within this directory._

Many thanks!

**Comment by lightlike** [comment]
I would not recommend putting the User's Settings in the Installation Directory (%localappdata%).
Instead try putting them in %appdata%\Foo that way they even get distributed to multiple machines for one user via the active directory.

**Comment by GeekyEggo** [comment]
@lightlike you make an interesting case, and this is something we had considered doing; sadly the settings / file relate to a users specific machine, so we weren't sure if `%APPDATA%` was a viable option. That may be an option we have to explore further in the event we aren't able to prevent the removal of files.

**Comment by lightlike** [comment]
In that case I would either try the parent (non-versioned) folder (which you probably tried already) or just make a separate folder like Foo.Settings or something similar.
As for preventing the removal: I have no idea.

**Comment by GeekyEggo** [comment]
No problems, @lightlike, I appreciate your input. We're hopeful that it _is_ possible to prevent the removal of files within the installation directory, with the guidance of someone here, although we are considering other options.

**Comment by anaisbetts** [comment]
Setup.exe will always delete its folder in LocalAppData, this solves issues where installations are corrupted (which is super common in practice). I would recommend setting up a custom update server for your customers who want this, then charging them a metric ass-ton of money for it 😅

**Comment by avviano** [comment]
I just had an issue, where squirrel wipped out all my user specific data which caused a big headache. App developer said this is squirrel, which always wipes the folder clean and has no option not to. Also no possibility to warn or prompt user. Deleting a directory without prompting is definetly not best practise. Also, deleting a folder is actually no update / upgrade but a fresh install. This is not at all ideal. If possible, you should at least add prompts to warn users of what is about to happen. I lost a week of work because of it.

**Comment by anaisbetts** [comment]
@avviano Sorry to hear about this. This is a bug in chaiNNer, it should never store any user data in the installation directory. Instead, they should be storing data in `%AppData%`, which Squirrel of course will not wipe. 

> You just discovered an unfortunate combination of the save window defaulting to the exe directory and the way the updater works.

chaiNNer should never default its save window to this folder, they should set a reasonable default like the desktop
