### ISSUE TITLE
CheckForUpdate() doesn't return

### ISSUE THREAD

**Issue by Alonzzzo2** [Squirrel/Squirrel.Windows#1632]
This is (part of) my code:
` using (var mgr = new UpdateManager(swUpdateRepoPath))
                {
                    var updateInfoTask = mgr.CheckForUpdate();
                    updateInfoTask.Wait();
                    var updateInfo = updateInfoTask.Result;`

I can't seem to get past the Wait().
I also can't step into CheckForUpdate, though I am able to step into the ctor.

I don't know how to proceed...

**Comment by lightlike** [comment]
Try using `await` instead or use `updateInfoTask.Result` directly inside the using section. That should work if there are no ther issues.

You can also look at [this](https://github.com/Drachenhorn-Team/Drachenhorn/blob/master/Drachenhorn.Desktop/UserSettings/SquirrelManager.cs) as an example.

**Comment by Alonzzzo2** [comment]
Thanks @lightlike ,
I switched back to .Result and it didn't work.

`using (var mgr = new UpdateManager(@"C:\\Projects\\some\\dir\\ectory\\src\\Releases"))
            {
                var updateInfoTask = mgr.CheckForUpdate().Result;
                Console.WriteLine(updateInfoTask);
            }`

I didn't use await since my function isn't async, I prefer to block for now.

I'm really lost here, spent the whole day on this.
I have another dead-simple app, which I created only for Squirrel testing, which works as expected, but nothing works in my current project.

The task just never returns....

**Comment by lightlike** [comment]
Is `C:\\Projects\\some\\dir\\ectory\\src\\Releases` the path to the directory that contains the RELEASES file (no subdirectory) or is it the RELEASES file directly?

```
folder\
  *.nupkg
  RELEASES
  Setup.exe
```

In this case you have to reference `folder` to the UpdateManager and not `folder\RELEASES`.

**Comment by Alonzzzo2** [comment]
Yes, this is a path to a folder.
This folder contains the generated releases file along with the already releasified packages (1 in this case) and setup.exe

**Comment by lightlike** [comment]
If there are no Administrator privileges or something like that set then everything should be fine.
At least I got no idea what it could be.

**Comment by Alonzzzo2** [comment]
I double checked the folder permissions and there should be no issues with it.
I even moved the content of the release folder of the simple project to the release folder of the current project, and the simple project read that dir content and everything worked fine.

So I'm still stuck...
Thanks anyway for taking the time to try and help me

**Comment by Alonzzzo2** [comment]
The issue was that we wait on the squirrel methods but these methods are async and are awaiting on something else.
When the await returns with the same thread (I have a WPF app, not sure why this happens), we get a deadlock.
It's weird that in every example I saw, they always Wait or using Result of the squirrel's API... 
Anyway, I can't do mgr.CheckForUpdate().Result or mgr.CheckForUpdate().Wait() since it's a deadlock.
Switched to var updateInfo = await mgr.CheckForUpdate()

Look at this for an explanation:
https://stackoverflow.com/questions/34151179/async-await-deadlocking-when-using-a-synchronizationcontext
