### ISSUE TITLE
Access installer URL in the app

### ISSUE THREAD

**Issue by KumG** [Squirrel/Squirrel.Windows#1634]
Hello,

I have a backend application hosted in IIS (on each customer's server, with their own database), and a frontend application connecting to the server API.

Is there a possibility, after the installation of the application on a client, to get the URL of the server it was downloaded from?

I would like to use it to set the URL of the API to connect to.

If not, is there another possibility to do what I need ? (set API URL during installation)

**Comment by anaisbetts** [comment]
This is not a possibility, sorry - you'll have to store this information in the executable somehow or have the user enter it
