### ISSUE TITLE
Squirrel namespace not available in .NET Core

### ISSUE THREAD

**Issue by chrishanzlik** [Squirrel/Squirrel.Windows#1649]
**Squirrel version(s)**
2.0.0 and 1.9.1

**Description**
The Squirrel namespace is not available, after squirrel.windows was installed.

**Steps to recreate**
```
mkdir testapp
cd testapp
dotnet new wpf
dotnet add package squirrel.windows --version 2.0.0
dotnet build
```
Open the project with VS2019 and try to access the namespace.

**Actual behavior**
Cannot access Squirrels namespace.

**Comment by dakahler** [comment]
I've been using 1.9.0 on .net core due to this problem, and it's working well. Not sure what's causing it, though!

**Comment by chrishanzlik** [comment]
@dakahler The problem with 1.9.0 is, that this version has its own Splat reference which forces a downgrade in my current app.

I got the latest version working with .NET Core using a little trick. I created a "Proxy project" which targets .NET Framework. This one will include Squirrel and expose all `UpdateManager` methods through its own helper class. The project can be consumed without problems by a .NET Core app.

Nevertheless it would be nice to know why the namespace is not available by default.

**Comment by GeertvanHorrik** [comment]
We wrapped the executable for our .NET Core implementation. You can find it here as a reference: https://github.com/WildGums/Orc.Squirrel/blob/develop/src/Orc.Squirrel/Services/UpdateService.cs

The exe wrapper works as good as calling the libs, and we no longer need to update references for updates to Squirrel (you can independently update Squirrel in your infrastructure only).

**Comment by meJevin** [comment]
Bump! WPF application on .NET Core 3.1 and with Squirrel.Windows 2.0.0 does not see the namespace. However, with older versions this problem is absent. Can we investigate on this?

**Comment by meJevin** [comment]
@GeertvanHorrik, can we investigate this?

**Comment by GeertvanHorrik** [comment]
I am happy to look into this, but I have another PR (#1656) open and would like to see that one closed first.

**Comment by RomainAn** [comment]
Hi guys,

I was searching for this issue, it's pretty recent !
Gonna sit here for update.

**Comment by RomainAn** [comment]
Bump ! Is there any update about this ? 

Thank you so much !

**Comment by GeertvanHorrik** [comment]
I am happy to look into this. I don't really need this feature myself but happy to contribute. 

Interested in a deal that helps out all of us? If so, then either support @anaisbetts (preferred) for her hard work on Squirrel or me and I'll implement this.

**Comment by RomainAn** [comment]
What kind of support do you want ?

**Comment by GeertvanHorrik** [comment]
GitHub sponsoring / open collective (if Squirrel has one) / etc would be great. It's a way to show appreciation for the hard work being done by others.

**Comment by consultorcva** [comment]
> @dakahler The problem with 1.9.0 is, that this version has its own Splat reference which forces a downgrade in my current app.
> 
> I got the latest version working with .NET Core using a little trick. I created a "Proxy project" which targets .NET Framework. This one will include Squirrel and expose all `UpdateManager` methods through its own helper class. The project can be consumed without problems by a .NET Core app.
> 
> Nevertheless it would be nice to know why the namespace is not available by default.

Hi, could you please a little sample o give me more details. Thanks!

**Comment by chrishanzlik** [comment]
> Hi, could you please a little sample o give me more details. Thanks!

Add a new project to your solution, which is targeting the old .NET Framework (.NET Framework 4.7 for example). Add Squirrel as NuGet dependency, then paste [these](https://gist.github.com/chrishanzlik/f175fffb494aa9311bde8139d809be0b) classes.

In your main project add a reference to this project and use the proxy `UpdateManager` class.

This works for me at this time.

**Comment by JackB-WAI** [comment]
Same issue here, had to downgrade to v1.9.0 on a project.

**Comment by CoreyHendrey** [comment]
Also having this issue on .NET 5.0, .NET Core 3.0 and .NET Core 3.1

**Comment by danilobreda** [comment]
This is very bad for early adopters like me.. is this project dead?

**Comment by robmen** [comment]
Nope, not dead. Squirrel is just a lower priority than WiX v4 is for me right now. No one pays [us](https://www.firegiant.com/) to work on Squirrel yet so it remains a lower priority than things that pay the bills.

**Comment by GeertvanHorrik** [comment]
I would like to emphasize again: you can simply wrap the executable and run it. You can use this from any app (even VBA or whatever your preference is). You don't *have* to reference Squirrel directly.

You can view an *example* implementation here:

https://github.com/WildGums/Orc.Squirrel/blob/develop/src/Orc.Squirrel/Services/UpdateService.cs

Or you can just consume that package ([Orc.Squirrel](https://www.nuget.org/packages/Orc.Squirrel/)) and use it directly as wrapper for your .NET Core / 5 projects.

**Comment by AArnott** [comment]
The regression in the v2 packages for netcore apps comes from the fix made in #1440. By "fixing" the `build` folder in the package to actually match the pattern, the package is seen as supporting multiple frameworks (since the `build` folder specifies no TFM). Since the `lib` folder *does* specify a TFM, nuget now ignores it if your project doesn't target net45.
The fix would presumably be ship a package with `lib` sub-folder that applies to .NET Core apps.

**Comment by AArnott** [comment]
The workaround for now is this:

```xml
  <ItemGroup>
    <PackageReference Include="Squirrel.Windows" Version="2.0.1" GeneratePathProperty="true" />
  </ItemGroup>
  <ItemGroup>
    <!-- workaround for https://github.com/Squirrel/Squirrel.Windows/issues/1649 -->
    <Reference Include="$(PkgSquirrel_Windows)\lib\Net45\*.dll" />
  </ItemGroup>
```

Of course this is just one of the issues that a .NET Core app will hit in using squirrel.

**Comment by AArnott** [comment]
I am preparing a PR for this repo that adds proper .NET Standard 2.0 support. I hope they'll take it.
