### ISSUE TITLE
NuGet targeting

### ISSUE THREAD

**Issue by InteXX** [Squirrel/Squirrel.Windows#1650]
I'm trying to better understand the proper use of .NET Framework version targeting in the project's NuSpec file, as relates to Squirrel.

For example:

    <file src="bin\Release\*.dll" target="lib\net472\"></file>

Does the version specified here affect Squirrel's operations at all? Or is it a NuGet-specific construct only?

What does it mean when we say [.NET 4.8](https://github.com/Squirrel/Squirrel.Windows/commit/b2d092b5507f01813a2e9b73b889e73bf59ee2a7) is now supported?

**Comment by owns** [comment]
Please see [squirrel-command-line](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/squirrel-command-line.md) argument `--framework-version`
If you dig around the source, you'll follow it all the way to [`WriteZipToSetup`](https://github.com/Squirrel/Squirrel.Windows/blob/b1c0e160d5098ccd0dc24a88f08a40fc6c1bd87c/src/WriteZipToSetup/WriteZipToSetup.cpp#L113).
You can see net48 specific support added [here](https://github.com/Squirrel/Squirrel.Windows/blob/b1c0e160d5098ccd0dc24a88f08a40fc6c1bd87c/src/Setup/FxHelper.cpp#L16) and follow those to see how they're used! I very much enjoy walking though open-source.

**Comment by owns** [comment]
And about Squirrel and NuGet .  Squirrel uses NuGet mostly for containing (zip) and versioning (what's the latest).

**Comment by InteXX** [comment]
This sounds like an interesting exercise. Yes, I'll have a look.

**Comment by InteXX** [comment]
> Squirrel uses NuGet mostly for containing (zip) and versioning (what's the latest)

From this it sounds like the answers to 1 & 2 are No and Yes, respectively.

Am I reading you correctly?

**Comment by owns** [comment]
Correct.

**Comment by InteXX** [comment]
Very good, thank you.
