### ISSUE TITLE
Improve progress reporting

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#1652]
We have fairly large apps. What we see whenever we run an update:

1. Instant download (since delta package is normally ~ 2-4 mb)
2. Squirrel being "stuck" at 66%

Then completing very fast again.

I've been digging into this, and think it's caused by the full packages from delta creation:

https://github.com/Squirrel/Squirrel.Windows/blob/813dd91a5ec179cb4e2db9b692fd34296c5db599/src/Squirrel/UpdateManager.ApplyReleases.cs#L35

I think the apply releases progress can be split into the following:

```
00 => start
00 => 40 (create full packages from deltas)
40 => 80 (install pacakge to dir)
80 => 85 (update local releases file)
85 => 90 (self update)
90 => 95 (post install)
95 => 96 (remove dead entries)
96 => 97 (unshim ourselves)
96 => 98 (clean dead versions)
100
```

I think this will more reliably reflect the actually installation status and give users a better sense of progress.

**I am happy to implement this (non-breaking) change as a PR if you are open to this.**

**Comment by anaisbetts** [comment]
Seems reasonable, go for it

**Comment by GeertvanHorrik** [comment]
PR is ready for review. Progress is now correctly calculated for both creating packages and installation (in ranges between 0 => 40 and 40 => 80). The rest is still similar to the old situation since I don't think it's worth reporting such fine-grained progress reporting for super fast steps.
