### ISSUE TITLE
UpdateApp() method always return null after upgrade to 2.0.0

### ISSUE THREAD

**Issue by yunfandev** [Squirrel/Squirrel.Windows#1654]
**Squirrel version(s)**
v2.0.0

**Description**
mgr.UpdateApp() method always return null, even the ReleasesToApply list is not empty.

I found an exception was thrown here: 
https://github.com/Squirrel/Squirrel.Windows/blob/develop/src/Squirrel/IUpdateManager.cs#L171

```text
Could not load file or assembly 'Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Expected behavior**
Return a valid ReleaseEntry

**Actual behavior**
Always return null

Seems that the package Mono.Cecil referenced by [Squirrel.Windows](https://www.nuget.org/packages/squirrel.windows/2.0.0) need to upgrade.

**Comment by yunfandev** [comment]
The problem disappeared after upgrading the package Mono.Cecil to 0.11.2.0 😂😂😂

**Comment by anaisbetts** [comment]
This is on my list

**Comment by Nextra** [comment]
Cheers!
