### ISSUE TITLE
Signing stub executable

### ISSUE THREAD

**Issue by SultanaJon** [Squirrel/Squirrel.Windows#1657]
**Squirrel version(s)**
v2.0.0

**Description**
I am signing an application and then creating a release with Squirrel. When I install the application, the stub executable is not signed but the one within the ‘app-{version}’ directory is signed. I see that Slack’s stub executable is signed and I want to replicate that behavior. Can you explain how to achieve this?

**Steps to recreate**
``` xml
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo" />
    </GetAssemblyIdentity>
    <Exec Command="signtool sign /tr http://timestamp.digicert.com /td sha256 /fd sha256 /a $(OutDir)myApp.exe" />
    <Exec Command="nuget pack myApp.nuspec -Version $([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3)) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
    <Exec Command="Squirrel.exe --releasify $(OutDir)myAppd.$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3)).nupkg" />
  </Target>
```

**Expected behavior**
The stub executable should be signed.

**Actual behavior**
The stub executable is not signed.

**Additional Information**
I have reviewed PR #868 and searched the open and closed issues for my problem.

**Comment by owns** [comment]
Hello @SultanaJon. Please see the docs on [application signing](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/application-signing.md).
My absolute favorite part of open source is checking "under-the-hood".  You can see in [the source](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Program.cs#L349-L363), it creates the stubs, then signs all files.

**Comment by SultanaJon** [comment]
I changed my releasify command to sign all files instead of just the app executable. This fixed the issue described above. Thanks @owns!
