### ISSUE TITLE
it breaks discord

### ISSUE THREAD

**Issue by customvideogames** [Squirrel/Squirrel.Windows#1658]
**Squirrel version(s)**
_Which version(s) of the project are you using?_ 1.9.1

**Description**
It tries to install squirrel to discord.

**Steps to recreate**
click setup.exe

**Expected behavior**
Install properly

**Actual behavior**
It tries to install squirrel to discord.
**Additional information**
no

**Comment by anaisbetts** [comment]
What on earth are you saying

**Comment by customvideogames** [comment]
It gives an error and then I press check log file,  the log shows that its trying install squirrel to discord(It's a texting app).

**Comment by customvideogames** [comment]
It's a good thing discord auto-fixes things

**Comment by anaisbetts** [comment]
The log shows squirrel installs from all apps that use Squirrel, scroll to the bottom

**Comment by customvideogames** [comment]
Oh I seee
