### ISSUE TITLE
Machine wide installs not possible

### ISSUE THREAD

**Issue by mimi89999** [Squirrel/Squirrel.Windows#1678]
Hello,
Sorry for the missunderstanding in https://github.com/Squirrel/Squirrel.Windows/issues/314. This was not a support question.

Basically, I want to explain the issues that admins have with Squirrel installers:
* Huge waste of space
* Breaks software restrictions policies that disable execution from user profile folders (a security requirement we have)
* Profile sync time

I saw that you made some interesting counter argument that disk space is cheaper than dev time. This probably is true for cheap $5 pendrives, but that might not be true for enterprise class HDDs. The number of drive bays in RAID arrays is also limited.

I propose two solutions and I'm even willing to contribute them to Squirrel if you accept them:
1. Add a CLI option for admins that will install to ProgramFiles the entire package without automatic updates. Probably the easiest option to implement. I know that Updates are one of the core goals of the projects, but you can't force them on all users. Admins can just repack Squirrel installers and won't get them anyway and since that repacking takes time, providing a proper installer will actually speed up those updates.
2. Install the updater and the package in ProgramFiles (if run with correct privileges and CLI option), but install updates to AppData and launch the most recent version. If the version in ProgramFiles is newer, remove the package from AppData. More difficult to implement, but still has auto updates.

You also said that this issue should be reported to app developers, but they point back at Squirrel. I doubt that app devs will want or even be able to support several installers, so it's either Squirrel or something else.

**Comment by anaisbetts** [comment]
I don't understand why Squirrel would affect profile sync time - Squirrel installs to %LocalAppData% (and always has been).

I appreciate you thinking about alternate solutions, but neither of these are tenable solutions. I'm not sure what the second one even gets you, you're still installing everything in LocalAppData anyways? How does that solve the space or execution policy problems?

**Comment by mimi89999** [comment]
> I don't understand why Squirrel would affect profile sync time - Squirrel installs to %LocalAppData% (and always has been).

Many programs use Local when they should use Roaming, so you end up syncing both. See https://github.com/brave/brave-browser/issues/1473 as an example. We are not using Brave, but it's the first example of a popular app I found.

Even if you ignore that, in school envs there are a lot of users using the same computer. Students are usually only using computers during one or two school hours and there are 7 school hours in a day. In the worst case you have 30 profiles on the same machine. Usually it's not that many. If computers have the smallest standard disk size of 128GB (most do), this greatly limits profile size you can store on each machine. Squirrel apps do add a significant overhead. If you want to offer users a reasonable amount of storage, you don't fit, so you must basically delete and resync everything. Having all apps installed at the same time on every logon is quite a bad idea, so it might be better to actually sync them.

I guess that we now need 256GB SSDs and Squirrel devs won't mail them to us.

Anyway, I started https://github.com/mimi89999/squirrel-to-nsis. Let's see where it goes.
