### ISSUE TITLE
Delta nupkg

### ISSUE THREAD

**Issue by nutterthanos** [Squirrel/Squirrel.Windows#1691]
How do you install delta .nupkg with Squirrel.Windows apps? like manually with a command in cmd.

**Comment by varKeytrap** [comment]
This seems to be able to answer your questions ? #1519

**Comment by nutterthanos** [comment]
maybe with this command ../update.exe --update https://path/to/the/updates

**Comment by nutterthanos** [comment]
actually there is this flag i see called --deltify i wonder how you use this?

**Comment by anaisbetts** [comment]
Squirrel does not ever Install delta updates - deltas are always used to offline transform one *package* into another. So, we start with a base package, apply a delta to get a new current full package, then apply that full package
