### ISSUE TITLE
SharpCompress dependency with exact version

### ISSUE THREAD

**Issue by adaskos** [Squirrel/Squirrel.Windows#1701]
**Squirrel version(s)**
2.0.10

**Description**
Is there a specific reason why `SharpCompress` version is strictly defined? 
This leads to build errors if the project also has a diamond dependency to `SharpCompress` from another nuget (e.g. `MongDB.Driver.Core`)

**Steps to recreate**
1. Create a new project
2. Add squirrel.windows 2.0.10 nuget
3. Try to add MongoDB.Driver.core nuget

**Expected behavior**
It should have a minimum version defined in the nuspec and let another nuget fetch a later version without an issue

**Actual behavior**
Package Manager will produce an error:
```
NU1107: Version conflict detected for SharpCompress. Install/reference SharpCompress 0.23.0 directly to project ConsoleApp5 to resolve this issue. 
 ConsoleApp5 -> MongoDB.Driver.Core 2.11.6 -> SharpCompress (>= 0.23.0) 
 ConsoleApp5 -> squirrel.windows 2.0.1 -> SharpCompress (= 0.17.1).
```

**Comment by anaisbetts** [comment]
Yes, please search the previous issues. Newer SharpCompress is incompatible with NuGet's zip parser

**Comment by adaskos** [comment]
I see. That means that as we stand right now Squirrel can't pack such an application.

**Comment by anaisbetts** [comment]
You can just follow the steps for non-C# apps - ie shell out to update.exe. To be honest I'd actually recommend this approach anyways!

**Comment by adaskos** [comment]
If I build with newer `SharpCompress` library updating existing installation work. 
But new setup (with `setup.exe`) doesn't. I get 
```
your build did not correctly replace the IDR_UPDATE_ZIP resource
``` 
Is this related to the newer `SharpCompress` library?

Can I install the app some other way? Any link would be helpful.

**Comment by adaskos** [comment]
I rerun from command prompt and setup was created find. Probably a transient issue (maybe same as https://github.com/Squirrel/Squirrel.Windows/issues/645). I'll see if it happens again.

**Comment by anaisbetts** [comment]
@adaskos I promise that this *will* screw you over if you do this and your users will not be able to update, _after_ you've rolled out your first version to everyone. You will have a Bad Time

**Comment by adaskos** [comment]
That's definitely not my intention. But I haven't understood what other options I have to releasify. You suggested I update from shell. But packaging is the one who failed me
