### ISSUE TITLE
DeltaCompressionDotNet not compatible with net5.0

### ISSUE THREAD

**Issue by SeriousM** [Squirrel/Squirrel.Windows#1716]
**Squirrel version(s)**
2.0.1

**Description**
The DeltaCompressionDotNet is not compatible with net5.0 because it only targets dotnet framework 2.0

**Steps to recreate**
1. Create a winforms application for net5.0
2. add squirrel
3. Problem:
```
  Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1701	Package 'DeltaCompressionDotNet 1.1.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.
```

**Expected behavior**
The DeltaCompressionDotNet is not available for netstandard nor net5.0. Ditch the DeltaCompressionDotNet and implement the mechanic in squirrel.

**Actual behavior**
Exception during compilation.

**Comment by patrickklaeren** [comment]
Squirrel doesn't even support .NET 5.0 if you're it as a Nuget package.

**Comment by simader** [comment]
any idea when this will be supported?

**Comment by dsikic** [comment]
Pretty please!!

**Comment by AArnott** [comment]
DeltaCompressionDotNet already compiles for netstandard1.3, but this package hasn't yet been pushed to nuget.org: https://github.com/taspeotis/DeltaCompressionDotNet/issues/17

Given the inactivity on *that* repo, and that the library is a very tiny wrapper around two methods, I'm working on a change to simply drop the dependency on that package.
