### ISSUE TITLE
Is it possible to install/uninstall and register/unregister windows shell extensions with Squirrel?

### ISSUE THREAD

**Issue by theofanis** [Squirrel/Squirrel.Windows#172]
What the title says.

I'm looking in ways to install shell extensions and uninstall them when uninstalling my app.

Clickonce appears to be a huge bother in this, since I can't install and register my shell extensions while installing my main app, and if I do this by executing code that does that, while my main apps runs, I have no way of uninstalling and unregistering my extensions.

Is there a way to handle this in Squirrel? I see that custom events may help in that regard, but I need your points on this before I decide to spend more time with Squirrel, which by the way looks really promising.

**Comment by julian-r** [comment]
@theofanis 
Have you been successful installing shell extensions in HKCU?

**Comment by theofanis** [comment]
@julian-r I have moved from this, for almost a year now, and I currently don't have access to the code base, but I remember I was creating extensions by running some custom code, hooked in squirrel events.

The code was simple, something like this for example:
```
private static void RegisterShellExtension(string installDir)
{
    string dllName = Path.Combine(installDir, "myExtension.dll");

    if (Environment.Is64BitOperatingSystem)
    {
        dllName = Path.Combine(installDir, "myExtension64.dll");
    }

    var p = Process.Start("regsvr32.exe", "/s " + dllName);

    p.WaitForExit();
}
```

**Comment by julian-r** [comment]
Alright thank you :)
