### ISSUE TITLE
Zip file missing from squirrel.windows release artifacts?

### ISSUE THREAD

**Issue by repl-chris** [Squirrel/Squirrel.Windows#1724]
I see that as of squirrel.windows v1.8 the release zip file is no longer attached to the release. Is there a new location to get this zip from? Is Squirrel.Windows still usable/recommended for projects which don't use Visual Studio?

**Comment by vernou** [comment]
Squirrel.Windows is integrated directly in the NuGet package. You can download the package at [nuget.org](https://www.nuget.org/packages/squirrel.windows/) and unzip (package NuGet is a zip).
In the unzip folder, you will find the library (dll) and all tools.

**Comment by repl-chris** [comment]
> Squirrel.Windows is integrated directly in the NuGet package. You can download the package at [nuget.org](https://www.nuget.org/packages/squirrel.windows/) and unzip (package NuGet is a zip).
> In the unzip folder, you will find the library (dll) and all tools.

Oh, sweet!  Works perfect...thanks a bunch 👍
