### ISSUE TITLE
How to run powershell script as admin in Squirrel windows

### ISSUE THREAD

**Issue by zhex900** [Squirrel/Squirrel.Windows#1736]
Hi,

I am using the latest version. 

I want to use Squirrel events to run powershell script after install. I can run powershell script. But how do I run the script as admin?

**Comment by frederikolsen88** [comment]
I've done something like this, and I wound creating a small console application that runs with admin privileges. Through that, you can invoke the script using System.Management.Automation.PowerShell.

Be aware that unless it's a very fast script, it may be a good idea to use the OnFirstRun() hook. Off the top of my head, the others are limited to 15 seconds.

**Comment by zhex900** [comment]
Thank you
