### ISSUE TITLE
VS.Net Tooling similar to octo.exe for Octopus Deploy

### ISSUE THREAD

**Issue by dealproc** [Squirrel/Squirrel.Windows#176]
Octopus Deploy has a mechanism that allows it to build a nupkg from your web project with little or no work involved by default, and subsequently allows you to build a minimal nuspec file to custom tailor the system.  On top of that, you can install an Add-in into TeamCity, and the conjunction of the two allows the CI server to handle the packaging of the nuspec; etc.  Would be nice to get a similar function in Squirrel.

**Comment by paulcbetts** [comment]
Creating a NuGet package is pretty easy, and Squirrel often requires you to put in custom information, I don't know that we need this

**Comment by dealproc** [comment]
Ok.  I haven't gotten into a spike project yet, but I always feel as if my web projects are rather easy, and yet, there is a reason why Octopus built the integrations into the CI server, so it seemed to align with what my suspicions of my needs are going to be as I get into Squirrel.

**Comment by paulcbetts** [comment]
Building NuGet packages for web projects is inherently way more complicated, especially because Octopus Deploy probably has to make up extra folders to hold content vs code, etc (so many magic folders!)  Desktop apps are easy, you just put everything in `lib/net45`. YAGNI :)
