### ISSUE TITLE
Visual Studio 2022

### ISSUE THREAD

**Issue by Bernardoskau** [Squirrel/Squirrel.Windows#1775]
So, i downloaded the newest Squirrel.windows develop file with the swl file edit etc, then i tried to open the visual studio project file (that i believe being vsxproj.) in visual studio 2022, and it showed me this:
![20211206_120529.jpg](https://user-images.githubusercontent.com/95549506/144875782-917397af-6039-43b8-887f-3f8e01097002.jpg)![Screenshot_20211206-120740_Google.jpg](https://user-images.githubusercontent.com/95549506/144875799-02201447-58f6-4ebf-b3ed-d4c40ea07e9d.jpg)
Then i clicked cancel, it opened normally on Visual Studio 2022, but it was using Visual Studio 2019 components, as some files had a "(Visual Studio 2019)" after its name.
I do know thats probaly because of the 64 bit update thing and because the project components are from VS2017.
Im only posting that because i dont know if that could be a reason to another bugs, and i know there is probaly no need to fix this.
Goodbye.

**Comment by robmen** [comment]
Yeah, you can skip the upgrade steps (select the no upgrade option in each dropdown) or use VS2019.
