### ISSUE TITLE
Clean Appdata folder on uninstall

### ISSUE THREAD

**Issue by C1rdec** [Squirrel/Squirrel.Windows#1776]
Basically when `--uninstall` is run we should be able to specify a flag to delete `all data`.
Right now this is blocking me from having my app on the Windows Store since there's a left over folder in local Appdata.

![image](https://user-images.githubusercontent.com/5436436/145045490-967708c9-b369-45c1-8ae6-c895f52f7f6d.png)

**Steps to recreate**
1. Install any squirrel app
2. execute `--uninstall`

**Expected behavior**
The folder from Local Appdata should be deleted.

**Actual behavior**
Folder is still there.

**Comment by anaisbetts** [comment]
This is not possible without running as Administrator, CopyFile with the DELETE_ON_REBOOT command doesn't work
