### ISSUE TITLE
stubexcutable can not find correct LatestAppDir

### ISSUE THREAD

**Issue by liutian1998** [Squirrel/Squirrel.Windows#1777]
My app has been updated several times, i think the lastest app folder is app-2.3.12-release22, but actually run app-2.3.12-release3.
To one's surprise, I modify folder name app-2.3.12-release3 to app-2.3.12-release03,  app working correct.
![5b35feb814d2a8249f0e25cc7e4a39e](https://user-images.githubusercontent.com/28467309/147086109-6562ea62-5028-4afe-acda-3c2790dc79b4.png)

**Comment by anaisbetts** [comment]
Tags have no semantic sorting order in semver. According to semver all four of these releases are identical
