### ISSUE TITLE
Squirrel doesn't abort an installation?

### ISSUE THREAD

**Issue by felipsant** [Squirrel/Squirrel.Windows#1779]
**Squirrel version(s)**
2.0.1 
.Net Framework 4.8

**Description**
I'm trying to create an UI for the user to agree with some User Agreements before the installation. If he doesn't, I just want to leave the application, but Squirrel, doesn't stop. I can make it load an Form and wait for an answer before it continues to install, but I cannot make it abort the process.

Aren't there any way for it to stop Squirrel from installing the Application?

**Steps to recreate**
onInitialInstall: v =>
{
    this.Close();
    System.Environment.Exit(1);
    mgr.CreateShortcutForThisExe();
},

**Comment by anaisbetts** [comment]
This isn't possible, sorry. You should do this on first run of your application instead.
