### ISSUE TITLE
squirrel packages entire electron.exe in every update (electron-winstaller) (fix already in master)

### ISSUE THREAD

**Issue by MichaelBelousov** [Squirrel/Squirrel.Windows#1784]
**Squirrel version(s)**
2.01-eef3746

**Description**
electron-winstaller's vendored squirrel's bsdiff fails to diff electron.exe's which differ only by 4 bytes, the 4 references to updated versions embedded in the exe. This causes squirrel to package the entire electron.exe every update.

As discussed in #1287, *this is already fixed in master*. But for some reason it was never cherry-picked to the development branch from which the electron-winstaller vendored binaries are from

> looks like master has a fix here: afe47c9
> but the version in electron winstaller is here: eef3746
> according to `git branch --contains eef37460ae` that squirrel version (2.0.1) comes from the develop branch which does not have this fix

The PR to master where a fix was added https://github.com/Squirrel/Squirrel.Windows/pull/1421

**Steps to recreate**
See #1287

1. use electron-forge/electron-packager/electron-winstaller to build a squirrel package for your electron app
2. bump the patch version for your app
3. use electron-forge/electron-packager/electron-winstaller to generate an update for your app
this invokes their vendored 2.01 squirrel

**Expected behavior**
A small-ish patch for the app's renamed electron.exe executable is generated rather than the entire file placed in the update.

**Actual behavior**
squirrel's bsdiff fails because there is only is no bsdiff-extra-data generated by diffing this case, and there is a divide by zero error when trying to write an empty byte stream for the diff. The error is taken as reason to just stuff the binary file in the update if diffing failed.

**Comment by MichaelBelousov** [comment]
@anaisbetts (sorry for the ping, I believe you're still the de facto maintainer/permission-holder) if I make a PR cherry-picking this fix into development and then talk to the electron-winstaller maintainers about releasing a new version, will the PR get accepted?

**Comment by MichaelBelousov** [comment]
@robmen is this something that you will accept via PR?

**Comment by robmen** [comment]
@MichaelBelousov so I'm clear, is this simply a commit (or two) in `master` that didn't get ported to `develop`? If so, I can cherry-pick them in my next round of changes (tonight).

**Comment by MichaelBelousov** [comment]
yes exactly. The description above references the exact commit. I've been using a fork with the one commit cherry-picked.
for this to be picked up by us (and other electron consumers), a new version of electron-winstaller would have to be released as well consuming this. Do you know who can be asked from their side to do so?

**Comment by robmen** [comment]
Okay, I have the changes in `master` in `develop` adn everything should be straightened out there now. I'm evaluating my next step in the process automation.

However, your real question is what is the process for `election-wininstaller` to get an updated Squirrel with all these fixes. For that, I still need to lean on @anaisbetts as I haven't done that yet. Perhaps this should be the time I learn from @anaisbetts how but that means it'll happen pretty slowly. 😄

**Comment by MichaelBelousov** [comment]
@robmen would it be appropriate for me to open a new tracking issue for updating the electron-winstaller package with the latest squirrel?
