### ISSUE TITLE
Installation of prerequisites

### ISSUE THREAD

**Issue by dealproc** [Squirrel/Squirrel.Windows#179]
I feel as if I may be stepping outside of the lines on what Squirrel.Windows is meant for, but is there any idea of supporting a package installation medium similar to how you can tell the ClickOnce installer that it needs to check the hierarchy of necessary bits on a user's computer, and if something is missing (Sql Server Express; Postgres; etc.) that the bootstrapper should install that?  I know we have support for the .net fx, but wasn't sure if anything else was being considered/proposed.

**Comment by paulcbetts** [comment]
> I know we have support for the .net fx, but wasn't sure if anything else was being considered/proposed.

Nope, the only reason we have support for .NET Framework is that we need it to run Squirrel itself. You could certainly use Squirrel events to install other things though.

**Comment by bjarki** [comment]
@paulcbetts Can you give an example on how to do that?

**Comment by paulcbetts** [comment]
@bjarki You'll want to follow the steps in https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/squirrel-events.md - then, in your `onInitialInstall` callback, you'll install SQL Server there

**Comment by moswald** [comment]
Here's an issue I'm running across: Squirrel only waits 15 seconds for the hook to complete, and then moves on. Something like SQL Server can't install that quickly. (I'm not actually installing SQL Server, but a third-party tool that asks for user input during the install process, and it usually takes about 20 seconds for me to click through it as fast as possible.)

**Comment by jpchow26** [comment]
I'm investigating using Squirrel in my company's application, and if this is the case as @moswald said it's a non starter. We depend on Visual C++ redistributables to install for our application.

**Comment by paulcbetts** [comment]
@jpchow26 Ever since VS2010 you don't need to install VC++ redistributables anymore, just include the DLLs in the lib/net45 folder

**Comment by jpchow26** [comment]
Oh. OK cool! Shows you how out of date we are with our installer implementation. Thanks @paulcbetts
