### ISSUE TITLE
Symlink: Could not find a part of the path

### ISSUE THREAD

**Issue by fluidblue** [Squirrel/Squirrel.Windows#1796]
**Squirrel version(s)**
2.0.1+eef37460ae

**Description**
I describe the problem in the situation where it happens. During this process, Squirrel is called.
Squirrel is called from [electron-forge](https://github.com/electron-userland/electron-forge) (via [electron-winstall](https://github.com/electron/windows-installer)).

Everything works fine, except when the source files to be copied contain symbolic links that cannot be resolved.

The following error is produced by electron-forge:

    [...]

    Making for the following targets: squirrel
    × Making for target: squirrel - On platform: win32 - For arch: x64

    An unhandled error has occurred inside Forge:
    An error occured while making for target: squirrel
    Failed with exit code: 1
    Output:
    Attempting to build package from 'timelog.nuspec'.
    Could not find a part of the path 'C:\Users\<user>\Desktop\timelog\electron\out\timelog-win32-x64\resources\app\node_modules\better-sqlite3\build\Release\obj\global_intermediate\sqlite3\sqlite3.c'.

    Error: Failed with exit code: 1
    Output:
    Attempting to build package from 'timelog.nuspec'.
    Could not find a part of the path 'C:\Users\<user>\Desktop\timelog\electron\out\timelog-win32-x64\resources\app\node_modules\better-sqlite3\build\Release\obj\global_intermediate\sqlite3\sqlite3.c'.

        at ChildProcess.<anonymous> (C:\Users\<user>\Desktop\timelog\electron\node_modules\electron-winstaller\src\spawn-promise.ts:52:16)
        at ChildProcess.emit (node:events:526:28)
        at ChildProcess.emit (node:domain:475:12)
        at maybeClose (node:internal/child_process:1092:16)
        at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

I think the part produced by Squirrel is:

    Attempting to build package from 'timelog.nuspec'.
    Could not find a part of the path 'C:\Users\<user>\Desktop\timelog\electron\out\timelog-win32-x64\resources\app\node_modules\better-sqlite3\build\Release\obj\global_intermediate\sqlite3\sqlite3.c'.

**Steps to recreate**
1. Create a small testing application. For this, run the following commands in PowerShell as admin. Hint: You need to have node.js installed.

```
npx create-electron-app test
cd test
npm install better-sqlite3
npm run make
```

2. See the error displayed in the terminal.

**Expected behavior**
Squirrel should not exit completely, but only give a warning when the target of a symlink does not exist.

**Actual behavior**
Squirrel exits (with exit code 1) when the target of the symlink cannot be found.

**Additional information**
Possibly the problem occurs in function `CopyToAsync` in file [Utility.cs](https://github.com/Squirrel/Squirrel.Windows/blob/develop/src/Squirrel/Utility.cs).

**Comment by anaisbetts** [comment]
Why would you want to distribute .c files in your app? You need to clean up the node_modules directory before packaging

**Comment by fluidblue** [comment]
Well, the point is, that squirrel crashes on certain symlinks.
Could happen with any file, not just .c files.

The .c files are distributed with the package "better-sqlite3", because it requires recompiling of .c files (better-sqlite3 recompiles sqlite3 from source). Therefore, .c files are required to be in the node_modules directory.
Without the node_modules directory, an electron app cannot start.

So, please reopen the issue.

**Comment by anaisbetts** [comment]
You're asking Squirrel to do something Invalid (package symlinks to files that don't exist), and then asking that the undefined behavior happen to be the undefined behavior that you want. That seems Bad!

**Comment by anaisbetts** [comment]
> The .c files are distributed with the package "better-sqlite3", because it requires recompiling of .c files (better-sqlite3 recompiles sqlite3 from source). Therefore, .c files are required to be in the node_modules directory.

Yes, you need to remove these files as part of your build, _after_ you `npm install`, but _before_ you package the app

**Comment by fluidblue** [comment]
As I see it, there are two problems:
* One problem is the npm package "better-sqlite3", which creates symbolic links that are pointing to a location that does not exist. However, symbolic links that are pointing to an invalid location are still valid files - e.g. when the location becomes valid, the link becomes valid again. Still, this is a problem that should be fixed in the package "better-sqlite3".
* The other problem is how squirrel handles symbolic links. In my opinion, when squirrel encounters a symbolic link that points to a non-existing location, it should just copy the link (and maybe warn), but not fail.

What do you think?

**Comment by robmen** [comment]
Symbolic links aren't a big thing on Windows. They aren't going to survive the deployment process. So, one option would be for Squirrel should ignore "broken" symbolic links (perhaps with a warning). Or it could error indicating that the symbolic link you thought was being included in the package is not being included.

The current behavior is the latter.

**Comment by fluidblue** [comment]
Ok, thanks for the clarification.
From my side, this issue can then stay closed.

For others having the same problem: I posted this issue at better-sqlite3 (see https://github.com/JoshuaWise/better-sqlite3/issues/784).
