### ISSUE TITLE
Inconsistent code in UpdateManager.ApplyReleases?

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#180]
Shouldn't this line:

https://github.com/Squirrel/Squirrel.Windows/blob/master/src%2FSquirrel%2FUpdateManager.ApplyReleases.cs#L163

be the same as:

https://github.com/Squirrel/Squirrel.Windows/blob/master/src%2FSquirrel%2FUpdateManager.ApplyReleases.cs#L117

**Comment by paulcbetts** [comment]
Yep, good catch
