### ISSUE TITLE
Can squirrel install others .exe with specific argument? 

### ISSUE THREAD

**Issue by UnnecessaryPunctuation** [Squirrel/Squirrel.Windows#1802]
May I drop other .exe  in the nugget package, and have them installed with a specific argument?

For example if I add Vs_Code.exe can I call it with the /verysilent and /Lang=fr argument?

**Comment by caesay** [comment]
If you mark your binary [as SquirrelAware](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/custom-squirrel-events.md), then it will be executed during install. In the `onInitialInstall` hook, you can execute any other binary you want, with any arguments you want, using `Process.Start` for example. 

A couple things you need to know: 
 - Your app will be killed after 15 seconds if it is still running (this is all the time that Squirrel allows for hooks to run during install). 
 - You really shouldn't install a program that the user is not expecting to be installed. If I downloaded an installer for "YourApp" and it also installed vscode in the background, this is going to be very annoying.

**Comment by UnnecessaryPunctuation** [comment]
The solution was for me in a Squirrel Aware app: 

. In onInitialInstall, Simply install the main application. And create Main shortcut.
. The other exe will be in the `"%localappdata%/ApplicationName/"`.
. Grab somehow the custom command and execute from the application  with `Process.Start` but outside of the `onInitialInstall`. 
This way you can escape the 15 sec restriction.

Thanks for the direction.
For the "not expected" apps, It's an application deployed on our domain. Users have no right nor say. 
We will gladly duel any annoyed users.
