### ISSUE TITLE
Using Squirrel UpdateManager with a normal webserver

### ISSUE THREAD

**Issue by OssieFromDK** [Squirrel/Squirrel.Windows#1804]
Hi, I'm trying to use the Squirrel UpdateManager with my normal webserver, NOT ASP.Net or ASP, is this possible?

When using Fiddler I can see it tries to connect, however It returns a 406, I put the files at https://ossie.dk/download/<filename>

Fiddler looks like this: https://i.imgur.com/qP9jGRe.png

I can see it trying to use a GET request, however I'm not good enough to write something in PHP to handle this, is there another smarter way? Or am I doing something wrong?

**Comment by anaisbetts** [comment]
I'm not sure why your webserver is sending back a 406 but indeed, there are no special requirements for the webserver. S3 / Blob Storage, or any web server that is serving static content is sufficient to use Squirrel.Windows

**Comment by OssieFromDK** [comment]
> I'm not sure why your webserver is sending back a 406 but indeed, there are no special requirements for the webserver. S3 / Blob Storage, or any web server that is serving static content is sufficient to use Squirrel.Windows

Could it be because my webserver uses HTTPS? In the fiddler request it says "HTTP" and not HTTPS

**Comment by renfroewendy** [comment]
WAK...INK...
