### ISSUE TITLE
Information on DownloadReleases behavior

### ISSUE THREAD

**Issue by UnnecessaryPunctuation** [Squirrel/Squirrel.Windows#1813]
Use case:

We will check for update.If there are update available. 
We will display the realease note.
But for that we need to download the releases.
User can still choose to postpone the update. 

Question:
 . Does `DownloadReleases(updateInfo.ReleasesToApply)` download the package every time, regardless if it's already on the disk?

**Comment by anaisbetts** [comment]
You don't need to download the release to check to see if an update is available, use the CheckForUpdate method. As to the release notes, to be honest I recommend just putting the notes in a separate file to download vs using Squirrel's release note feature, for exactly the reason you describe
