### ISSUE TITLE
Is there a way to maintain the same small Setup.exe and let is download the latest nupkg from the web instead?

### ISSUE THREAD

**Issue by danielkornev** [Squirrel/Squirrel.Windows#1822]
Hi! I'm currently working on submitting my product to Microsoft Store, and found a few limitations:

1. Each new release has to be a separate package in the Microsoft Store metadata
2. In the future (starting with July 16, 2022) each release has to be code-signed
3. Yet many code-signing operations are provided on a limited basis (e.g. up 60 releases per year, see the image below from [signpath.io](https://about.signpath.io/product/editions?AdGroupId=138796163408&gclid=Cj0KCQjw5ZSWBhCVARIsALERCvzZB7wtg08NavM36DZtav_MMY_thADEzUvKgcRQ8eQD2dWipdWiIkgaAiL0EALw_wcB))

With all that said, it would be much simpler if:
1. One could have a few major setup.exe files during the year
2. Smaller changes could be delivered by deltas

Is this possible to be done with Squirrel for Windows?

![image](https://user-images.githubusercontent.com/5264043/177513278-731ff0a7-f6dd-435f-a033-5b05e759689f.png)

**Comment by anaisbetts** [comment]
This is not possible - your delta builds have to be code-signed (Squirrel.Windows doesn't care, but if you didn't sign them, your binaries would go from signed => unsigned, which would almost certainly trigger 3rd party AV). 

I'm not sure that you can use this service pictured with Squirrel.Windows, you need to just buy a real signing certificate. Here's a good list of places to get one: https://docs.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage
