### ISSUE TITLE
Custom icon and exe name

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#183]
Is it possible to change the icon of `Setup.exe`?
And the name of the exe?

I did not fni anything in the docs.

**Comment by paulcbetts** [comment]
You can just rename Setup.exe to whatever you want. The Icon is something that needs to be done, it's on the TODO list

**Comment by BarryThePenguin** [comment]
I've done some work towards it in #154 but wasn't able to complete it successfully. I was having trouble replacing the icon group using UpdateResource

**Comment by paulcbetts** [comment]
Fixed in #186

**Comment by ricardopolo** [comment]
@paulcbetts please release a new bower version (tag) with #186. I also be awesome if you lauch releases with every commit (using a CI server like Appveyor)

**Comment by paulcbetts** [comment]
s/Bower/NuGet/g?

**Comment by ricardopolo** [comment]
@paulcbetts hahahaha you are right! :+1:

**Comment by paulcbetts** [comment]
The latest version that has this patch is already up on NuGet, it's v0.8.0
