### ISSUE TITLE
35 Gig of files in SquirrelTemp

### ISSUE THREAD

**Issue by jaywalker291** [Squirrel/Squirrel.Windows#1846]
Can I manually delete this folder's contents without it breaking anything? I am not happy to find this today on my work laptop, which has a 250 gig SSD drive, so obviously I can't spare 35 gigs for whatever this is. 

No idea what Squirrel is, but not a fan.  Edit - the application causing this appears to be Github Desktop, as mentioned by others. It's not really up to me to help Github fix their application. Surely they know this is happening but likely don't care. 

![sq](https://user-images.githubusercontent.com/14767201/216240576-fe7aedef-d71c-404c-ab7d-03e38c24da41.jpg)

**Comment by anaisbetts** [comment]
Yes you can, but before you do, you should look what app is using all that space and report it as a bug to them, because they're Doing Something Wrong, almost certainly closing themselves while an update is in progress

**Comment by jaywalker291** [comment]
The app causing it is Github Desktop, but I would argue the blame should be shared between the two apps causing the problem.

I just noticed in their [release notes ](https://desktop.github.com/release-notes/) under January 25th 2023 they have listed the following fix: "**Prevent closing GitHub Desktop while it's being updated**"

Hopefully that fix will stop this madness.

**Comment by anaisbetts** [comment]
> but I would argue the blame should be shared between the two apps causing the problem.

Well I wouldn't!
