### ISSUE TITLE
/LARGEADDRESSAWARE support for Stub executable

### ISSUE THREAD

**Issue by SneIdr19** [Squirrel/Squirrel.Windows#1858]
Squirrel version(s)
Squirrel.Windows 2.0.1

Description
I am using electron-forge, which uses electron-winstaller which uses Squirrel.Windows 2.0.1. SquirrelWindows generates the YOUR_EXE_NAME_ExecutionStub.exe without support for /LARGEADDRESSAWARE. 

Linking to the code responsible for the stub executable
https://github.com/Squirrel/Squirrel.Windows/blob/0ee9447d0f70744ad3624de953fc0eccf600990a/src/StubExecutable/StubExecutable.cpp

Expected behavior
The missing /LARGEADDRESSAWARE for Stub.exe should be added as it will support the handling of bigger address and helping to reduce or eliminate out of memory errors.

Actual behavior
Currently Stub.exe does not have support for /LARGEADDRESSAWARE

**Comment by anaisbetts** [comment]
Stub.exe shouldn't need Large addresses? Why would this ever be necessary? If Stub.exe ever allocates more than 3GB of memory something has gone insanely wrong

**Comment by anaisbetts** [comment]
If there's a reason to enable this, leave a comment and we'll be glad to take a look again
