### ISSUE TITLE
Squirrel won't install any program like Discord.

### ISSUE THREAD

**Issue by Ilexcitly** [Squirrel/Squirrel.Windows#1859]
**Squirrel version(s)**
1.38.2

**Description**
Discord wont install because its complaining about the MSTeams missing. Example: RegistryService: RegKeyExists: HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run does not have TeamsMachineInstaller

**Steps to recreate**
None. Randomly happened for no particular reason.

**Expected behavior**
It should work normally.

**Actual behavior**
Complains about the teams registry key missing

**Additional information**
Discord crashed, and froze. Restarting would do nothing. I uninstalled it, but then everything broke. I also tried to install Teams again, but Teams was missing for SquirrelSetup, while it wasn't. Log:[SquirrelSetup.log](https://github.com/Squirrel/Squirrel.Windows/files/12030967/SquirrelSetup.log)I

**Comment by Ilexcitly** [comment]
Update: there is nno fucking team registry in regedit
![image](https://github.com/Squirrel/Squirrel.Windows/assets/95829101/cf024c05-0d84-4df1-93ff-fc166367a49a)

**Comment by Ilexcitly** [comment]
That is the whole folder

**Comment by anaisbetts** [comment]
Hi, this isn't a forum for user support, please contact Discord Support. That being said, I would try redownloading the Discord installer.
