### ISSUE TITLE
exit code: 255(System.IO.IOException: Permission denied)

### ISSUE THREAD

**Issue by guguji5** [Squirrel/Squirrel.Windows#1874]
**Squirrel version(s)**
_Which version(s) of the project are you using?_

**Description**
```
An unhandled rejection has occurred inside Forge:
Error: Failed with exit code: 255
Output:
System.UnauthorizedAccessException: Access to the path '/Users/flashcat/.local/share/SquirrelTemp' is denied. ---> System.IO.IOException: Permission denied
```

**Steps to recreate**
```
git clone git@github.com:guguji5/electron-quick-start.git
cd electron-quick-start
npm install
brew install wine-stable
brew install mono
npm run make
```

**Expected behavior**
I want to build a exe 

**Actual behavior**
_Explain what it should be doing after it's fixed_

**Additional information**
_Add any other context about the problem here_

**Comment by anaisbetts** [comment]
Wine is not officially supported
