### ISSUE TITLE
.NET 8 is not supported

### ISSUE THREAD

**Issue by Geek-Bob** [Squirrel/Squirrel.Windows#1876]
**Squirrel version(s)**
Latest version

**Description**
.NET 8 is not supported

**Comment by anaisbetts** [comment]
.NET Core isn't directly supported though you can make it work by following the steps for non-.NET apps

**Comment by Geek-Bob** [comment]
> 不直接支持.NET Core is not direct support， but you can make it work by following steps for non-.NET apps
****
Okay, thank you.

**Comment by Geek-Bob** [comment]
> .NET Core isn't directly supported though you can make it work by following the steps for non-.NET apps

Okay, thank you.
