### ISSUE TITLE
How can I remove old version resources after auto-update?

### ISSUE THREAD

**Issue by dipen-atharva** [Squirrel/Squirrel.Windows#1887]
After auto-update to the newest version, I find my app keep the old version resources:
![image](https://github.com/user-attachments/assets/9a179065-80f3-42e5-877c-7e083abde067)

How can i remove old resources ?

**Comment by anaisbetts** [comment]
Squirrel automatically cleans up old versions but it leaves two previous ones behind in case an installation fails - if you see more than a few, it usually means you are accidentally killing Squirrel before it can complete
