### ISSUE TITLE
Signtool stops working

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#190]
Today I tried to release a new entrie of our software with the updated NuGet and see this
![sign](https://cloud.githubusercontent.com/assets/1263856/5765590/c928d696-9cc8-11e4-91ba-aba797db6bf1.PNG)

So I tried running the command from a cmd.exe and see this
![cmd](https://cloud.githubusercontent.com/assets/1263856/5765619/f2eba10c-9cc8-11e4-9c9d-bdb245438483.png)

Any idea?

**Comment by paulcbetts** [comment]
What happens if you just run Setup.exe? Does it also throw "Setup.exe is not a valid Win32 application"?

**Comment by ricardopolo** [comment]
@paulcbetts not, it works.

**Comment by paulcbetts** [comment]
And reverting to the old NuGet package works?

**Comment by ricardopolo** [comment]
@paulcbetts sorry it was my fault. I was calling ``-i favicon.ico`` and that file does not exist.  This is an invalid issue.
