### ISSUE TITLE
Specify installation subfolder

### ISSUE THREAD

**Issue by rgmills** [Squirrel/Squirrel.Windows#193]
We're playing around with using Squirrel as our installer for a new app.  We're hoping to use a package id following a convention of `MyCompany.MyApp`.  Ideally, AppData would just have MyCompany with MyApp as a subfolder (`\AppData\MyCompany\MyApp`).  Currently, we have shipping apps that use this convention (just for local data).

Based on what I see, there isn't a way to specify a root directory for install - it's always inferred to be `AppData\PackageId` with PackageId is split on '.' and '-'.  One option would be to create a PR to understand these semantics.

Or

Have a mechanism to infer change the subfolder which is hardcoded to "app-".

Would you be up for either change? PR would be provided - hopefully :)

**Comment by paulcbetts** [comment]
Hey @rgmills, I don't think this is going to change, this would destabilize a lot of working code and we'd have to have difficult to test migration plans.  

> with PackageId is split on '.' and '-'

This is currently a bug, we're going to fix the incorrect parsing of the package ID so that you can have '.'s in your package name

**Comment by rgmills** [comment]
@paulcbetts Thanks!

**Comment by paulcbetts** [comment]
Exactly. You could also independently use `AppData\MyCompany` for stuff too

**Comment by vinkal-chudgar** [comment]
Is this issue fixed? Currently our app is installed in AppData\Local\PackageId folder. Our requirement is to install the app in AppData\Local\{Company Name}\PackageId. Please let me know if there is a way to achieve it.

**Comment by paulcbetts** [comment]
@vinkal-chudgar There is no way to achieve that

**Comment by vinkal-chudgar** [comment]
@paulcbetts: Thanks for the response. It will be helpful if we have flexibility creating subfolders (at least 1 or 2 level) under AppData\Local\ folder something like **AppData\Local\MyCompany\PackageId**.Are we planing to implement it in near future.

**Comment by yonatankahana** [comment]
something new about it?

**Comment by Alex-us** [comment]
UP!
Also interested in instllation into 'myCompany/myApp' subfolder. Any updates on this?
