### ISSUE TITLE
Proposal: Better workflow for creating delta packages

### ISSUE THREAD

**Issue by kevfromireland** [Squirrel/Squirrel.Windows#194]
One of the nicest things about Squirrel is the fact that it can trivially create and apply delta packages.

At the moment, this is tricky to do from a CI environment. Our build works as follows:

1. Use TC to perform a clean checkout of the our product repo in GitHub
2. Build our product (`c#` based)
3. Test our product
4. Build an installer using Squirrel

Squirrel is building an installer from freshly compiled artifacts and doesn't have access to any previous `nupkg`s as we are working in a newly created clean TC checkout.

The current workflow means that I need to add a step between 3 and 4 which downloads the most recently uploaded `nupkg` and `RELEASES` from our S3 account and drops it in the `Releases` directory in TC.

My proposal is that an additional parameter be added to `--realeaseify` that points to an existing RELEASES url. `Releaseify` woulud then parse that, download the latest `nupkg` and therefore always be in a position to create both the `-full` and `-delta`

Does this seem like a sensible addition, or is there something about my workflow that means we are using Squirrel incorrectly?

**Comment by stefanolson** [comment]
@kevfromireland Sounds fantastic to me, even though we don't use the same sort of process that you do. Just not having to keep all the old nupkgs around would be great

**Comment by paulcbetts** [comment]
Fuck why didn't I think of that, can you put that into SyncGitHubReleases?

**Comment by kevfromireland** [comment]
@paulcbetts: Sure. That seems like as good of place as any, but then that project is probably badly named.

Shall I also rename it to something like `RemoteReleasesSync` or something and update a README.MD to describe how it can be used with either GitHub or arbitrary HTTP?

**Comment by paulcbetts** [comment]
@kevfromireland Can you just do the PR to add the feature and I'll handle the rename?

**Comment by kevfromireland** [comment]
Sounds good, it seems trivial from my first thinking about it and the code seems sensible so if I don't find time to do it at work then it shouldn't take me very long this weekend.
