### ISSUE TITLE
Any change Squirrel gets a strong name?

### ISSUE THREAD

**Issue by theofanis** [Squirrel/Squirrel.Windows#199]
Otherwise, I have to do it manually and I finally get an error while trying to do so.

**Comment by paulcbetts** [comment]
No problem! I would love to strong name Squirrel for your business! Check out http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets for more details

**Comment by theofanis** [comment]
OK Paul, we've also decided not to strong name our assemblies. Thanks for the response.
