### ISSUE TITLE
Support for windows service

### ISSUE THREAD

**Issue by peters** [Squirrel/Squirrel.Windows#20]
It should be pretty simple adding support for windows services. Keeping it really simple you can reuse the existing installation structure **%appdata%\app\0.1.1**.

The only change really is that after you have "installed" the app, you just kill the existing service and execute `myservice.exe install` and you're good.

Obvious stuff like waiting for the service to stop (give a minute or kill it).

**Comment by dealproc** [comment]
@peters have you gotten anywhere on this aspect of getting a RunAs prompt?

**Comment by peters** [comment]
@dealproc Haven't found the time to look at this yet

**Comment by darkmyst** [comment]
any movement on this?

**Comment by gschuager** [comment]
+1

**Comment by paulcbetts** [comment]
Locking to stop +1s. This has already been settled in https://github.com/Squirrel/Squirrel.Windows/issues/20#issuecomment-56914508
