### ISSUE TITLE
Make RestartApp() restart gracefully.

### ISSUE THREAD

**Issue by theofanis** [Squirrel/Squirrel.Windows#200]
RestartApp() is calling ```Environment.Exit(0)``` to close the running instance, but this prevents apps from running clean up code, possibly hooked in closing events.

Why not call ```Application.Current.Shutdown()```? 

Another side effect of this is tray icons being left in the tray area because the app didn't shutdown properly (the usual behavior with the icon staying in the tray area and disappearing if the mouse hovers over it).

**Comment by dealproc** [comment]
Is that available both in WPF and Windows Forms (Application.Current.Shutdown())???

**Comment by theofanis** [comment]
Yes, I completely forgot about Windows Forms. It's not available since it's in the System.Windows which is the base for WPF.

So I guess the only option is to write custom logic to figure out the latest version exe path to run with Process.Start() and immediately call Application.Current.Shutdown().

**Comment by paulcbetts** [comment]
I'm not too worried about this, the developer is the one calling RestartApp, if they want to clean something up explicitly, they can just do it before the call
