### ISSUE TITLE
Question: It's easy to use Squirrel on Monodevelop / Xamarin Studio ?

### ISSUE THREAD

**Issue by castarco** [Squirrel/Squirrel.Windows#202]
Hello,

I'm developing a multiplatform C# + GTK# application, and I'm using Xamarin Studio as the project IDE. I'd like to use Squirrel.Windows in the Windows version, but in the "Getting Started" section of the documentation I see a lot of references to MS Visual Studio.

Is it possible (& easy) to use Squirrel.Windows if I don't use MS Visual Studio?

Thanks for your time and effort.

**Comment by paulcbetts** [comment]
You can use Squirrel without VS but you have to be on Windows (I.e. can't make an installer on Linux)
