### ISSUE TITLE
Workflow: Cleaning up old versions

### ISSUE THREAD

**Issue by kevfromireland** [Squirrel/Squirrel.Windows#206]
Users of our stuff have reported old builds left lying around. 

Is there a preferred workflow for cleaning these up? I see `void cleanUpOldVersions(Version currentlyExecutingVersion, Version newCurrentVersion)` in `UpdateManager.ApplyReleases.cs` but it is currently dead code in the head of master. 

Should this code be exposed in some way? Or deleted?

**Comment by paulcbetts** [comment]
@kevfromireland I think that it should be executed but it got left out somehow, probably need to add it back in.

**Comment by Inzanit** [comment]
I'm 100% on Squirrel cleaning up old versions - which I assume was not the case at the time of writing this issue. Should be considered resolved, or closed. @shiftkey

**Comment by shiftkey** [comment]
@Inzanit I believe this is working fine, at least based on my recent usage of Squirrel.

@kevfromireland please open a fresh issue if you have new information to add.
