### ISSUE TITLE
What is Squirrel.Core and Squirrel.Client and why did it waste 2 cycles of my life

### ISSUE THREAD

**Issue by sickboy** [Squirrel/Squirrel.Windows#209]
I was rather confused by no mention of [Squirrel.Core](https://www.nuget.org/packages/Squirrel.Core) / [Client](https://www.nuget.org/packages/Squirrel.Client) in Squirrel.Windows, and wondering why UpdateApp is actually UpdateAppAsync... but thought it might be just some outdated docs or so.

You might think the alternative version numbering, suspicious dependencies and nuget author info, or the duplicate classes would give me a hint or two, but apparently it didn't.

So here I found myself shooting Squirrel packages with Squirrel.Windows 0.8, but trying to apply them on the client with Squirrel.Core/Client 0.7.5.
So far so good until Delta patching came into the mix, ending up with 'Corrupt patch' all the time.
Obviously bsdiff-like patches are no MSDelta patches...

After several doubletakes, everything has become clear now; you really just need the Squirrel.Windows :)
Lessons learned - do trust docs, pay more attention to version numbers and authors...

**Comment by sickboy** [comment]
Cheers, indeed that was me, thanks :)

**Comment by shiftkey** [comment]
> /cc @shiftkey to delist these packages. 

These packages have now been unlisted :fire:

![screen shot 2015-02-01 at 11 28 11 am](https://cloud.githubusercontent.com/assets/359239/5990442/73ddd32c-aa05-11e4-89db-80e6e6a68b18.png)

**Comment by sickboy** [comment]
Thanks guys :)
