### ISSUE TITLE
Is there a best practice for multiple channels

### ISSUE THREAD

**Issue by Martin-Andersen** [Squirrel/Squirrel.Windows#217]
I am working with an XBAP app that I want to turn into a WPF app. The users access up to 4 different version of the app via urls.

Whats the best way to mimic this behavior with Squirrel?

**Comment by dealproc** [comment]
Publish each build to a specific Url.

In your app, you're going to have to (somehow) record where the base url is, so that when you call the update command, it goes to the right base url and gets the `RELEASES` document for that channel.

**Comment by GeertvanHorrik** [comment]
We release everything to different urls:

[company]/[product]/beta/RELEASES
[company]/[product]/stable/RELEASES

We can then add as much channels as we want and it's very clear to the end-user what they get.

We sync our generated files using AzureStorageSync (see https://github.com/CatenaLogic/AzureStorageSync).

**Comment by TyBarthel** [comment]
You probably have this figured out by now, but I'll add a note as I just recently encountered this.

If you want them to be able to install side by side different versions, then you are going to want to set the package ID in the nuspec file (becomes the app folder name) and the product name (becomes the application/icon description, etc.) in AssemblyInfo to be unique per channel. Basically append the channel name to the package ID and product name.

**Comment by Franklin89** [comment]
@TyBarthel I changed my Package Id to MyApp.Testing and MyApp.Production, but the app folder name is still MyApp. Is that be because of the "."?

**Comment by shiftkey** [comment]
These are my two best bits of advice about supporting different channels with Squirrel:

> We release everything to different urls:
> ...
> If you want them to be able to install side by side different versions, then you are going to want to set the package ID in the nuspec file (becomes the app folder name) and the product name (becomes the application/icon description, etc.) in AssemblyInfo to be unique per channel.

Regarding this follow-up:

> I changed my Package Id to MyApp.Testing and MyApp.Production, but the app folder name is still MyApp. Is that be because of the "."?

It's not clear to me if this has been fixed. @Franklin89 if you are still seeing this issue please open a fresh issue and we can investigate and confirm whether this is the problem.
