### ISSUE TITLE
Kaspersky Anti-virus identifies Setup.exe and Update.exe as trojans

### ISSUE THREAD

**Issue by chrispret** [Squirrel/Squirrel.Windows#218]
Kaspersky's heuristic scan detects both Setup.exe and Update.exe as HEUR:Trojan.Win32.Generic.

Obviously it isn't liking some of the squirrel code. While I was happy to scan the files using a few different engines and none of them resulted in detections, typical end-users might not agree and end up not installing the software.

When I build from the source code, the resulting Setup.exe is detected as well.

It was also a pain to download and install Squirrel.windows through the Visual Studio Package Manager, since Kaspersky deleted Setup.exe every time it was downloaded. I eventually figured out what was going on and set it to prompt me before deleting the file, which made it possible to install it.

**Comment by paulcbetts** [comment]
While this was originally a problem, these days as long as you sign your installer, most people aren't seeing the virus warnings. Can you send in Setup.exe and Update.exe to Kapersky to whitelist then?

**Comment by chrispret** [comment]
I'll submit them.

Is the setup.exe that is distributed through the Visual Studio Package manager signed? If so, there might be value in submitting new versions to them when publishing. If I didn't realize that my anti-virus was deleting the files (without even telling me) I would have never gotten the package installed on my project.

**Comment by paulcbetts** [comment]
> Is the setup.exe that is distributed through the Visual Studio Package manager signed?

No, because the setup.exe we distribute there is a template that we'll edit (and therefore, break the signature)

**Comment by cwoolum** [comment]
I had the same issue with Bit defender but I sent in Setup.exe and they added it to their database. Not sure if that is possible with Kapersky as well

**Comment by JVimes** [comment]
Symantec Endpoint Protection's generic trojan detector, [Trojan.Gen.2](http://securityresponse.symantec.com/security_response/writeup.jsp?docid=2011-082216-3542-99), quarantined test\fixtures\Setup.exe. I submitted it on their [false positive form](https://submit.symantec.com/false_positive/).

**Comment by paulcbetts** [comment]
Thanks @JVimes

**Comment by jg123** [comment]
Windows Defender quarantined the unsigned Update.exe as a Trojan (Trojan:Win32/Codinx.B!plock). I submitted it as not malware here: https://www.microsoft.com/security/portal/submission/SubmissionHistory.aspx?SubmissionId=a1235358-fbb7-4d39-83a8-942440050036&lc=1033

**Comment by sawilde** [comment]
Even signing doesn't always seem to stop these AVs from killing your apps, from I've seen valid apps taken out for all sorts of reasons, signed or not and using OS or commercial installer packages; it's just a constant battle and unfortunately you have to visit every AV vendor to do the whitelisting and no common procedure in place.

**Comment by paulcbetts** [comment]
Thanks @jg123, people submitting to whitelists whenever bad stuff happens is a huge help

**Comment by muhammetalay** [comment]
Hi there,

How much time passed between the time you guys submitted false positive reports and the antivirus warnings disappeared?

I have the same problem and can't seem to have any progress. I followed the online guide listed at the FAQ document, which is this http://www.techsupportalert.com/content/how-report-malware-or-false-positives-multiple-antivirus-vendors.htm, and submitted reports via both email and website but got no positive response from the Kaspersky. Is there anybody who reached a positive result trying another channel of communication to resolve this? My angry users keep increasing and I'm open to suggestions.

**Comment by paulcbetts** [comment]
There's nothing we can do about AV vendors hating us, closing this

**Comment by JVimes** [comment]
The other option is to find what API calls look like a virus and refactor until they don't, if possible.

**Comment by paulcbetts** [comment]
> The other option is to find what API calls look like a virus and refactor until they don't, if possible.

I mean, the thing that "looks like a virus" is the fact that we install software :)  The funny thing about Squirrel is, from a "what it actually does" perspective it really does look a lot like malware - it unpacks and installs code to your computer and executes it, _and_ it downloads code from the Internet in the background and runs it. The difference of course being, that we do it with the user's consent, and malware doesn't :)

**Comment by JVimes** [comment]
Ahh right ;) It's probably wishful thinking that we could avoid the malware fingerprint. Hoping proper signing is the key, here.

**Comment by paulcbetts** [comment]
Signing makes a huge difference for distributing to your users, you'll most likely see this issue go away

**Comment by jvoisin** [comment]
> No, because the setup.exe we distribute there is a template that we'll edit (and therefore, break the signature)

What about signing the reulsting binary? Using a *template* shouldn't make any differences…
