### ISSUE TITLE
Request: option to specify the target Setup.exe filename

### ISSUE THREAD

**Issue by teekay** [Squirrel/Squirrel.Windows#219]
As a mISV using Squirrel to distribute my app, I'd like to be able to specify, using a command-line parameter, the desired name of the setup executable.

Currently, the filename is always "Setup.exe".

I'd like it to be for instance MyappSetup.exe so that it's more easily recognizable by the user in case they've downloaded it from the Internet.

**Comment by flagbug** [comment]
Just rename the file :smile:

**Comment by paulcbetts** [comment]
^^^

**Comment by teekay** [comment]
Fair enough :)
