### ISSUE TITLE
Can't releasify

### ISSUE THREAD

**Issue by Matthias-Hess** [Squirrel/Squirrel.Windows#222]
I am trying to follow the *Quick Start (for the impatient)*

When I try to invoke Squirrel in the package manager window (in VS2013), I get the following error message:

`
PM> squirrel --releasify "C:\Users\PC_DOJO\Documents\Visual Studio 2013\Projects\SimpleApp\SimpleApp\TheSimpleApp12345.1.0.0.nupkg"
squirrel : The term 'squirrel' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
+ squirrel --releasify "C:\Users\PC_DOJO\Documents\Visual Studio 2013\Projects\S ...
+ ~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (squirrel:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by paulcbetts** [comment]
Restart VS, you're probably hitting https://nuget.codeplex.com/workitem/4439

**Comment by Matthias-Hess** [comment]
Restarting VS didn't help. 

Did I install Squirrel correctly? When I type **Install-Package squirrel.windows ** it says it's already installed:


Package Manager Console Host Version 2.8.50926.663

Type 'get-help NuGet' to see all available NuGet commands.

PM> Install-Package squirrel.windows
Attempting to resolve dependency 'DeltaCompressionDotNet (≥ 1.0.0)'.
Attempting to resolve dependency 'NuGet.Core (≥ 2.8.3)'.
Attempting to resolve dependency 'Microsoft.Web.Xdt (≥ 2.1.0)'.
Attempting to resolve dependency 'Mono.Cecil (≥ 0.9.5.4)'.
Attempting to resolve dependency 'Splat (≥ 1.5.1)'.
'squirrel.windows 0.8.3.1' already installed.
SimpleApp already has a reference to 'squirrel.windows 0.8.3.1'.

PM>

**Comment by Matthias-Hess** [comment]
I got it working by simply uninstalling it and then reinstalling it (see below)
Perhaps it was a mistake to add the Nuget package to my project using the solution explorer and I should have used the Package manager Console to install Squirrel...
Anyway, It worked and I now have a Release Folder with 3 files in it.

-Matthias

PM> unInstall-Package squirrel.windows
Removing 'squirrel.windows 0.8.3.1' from SimpleApp.
Successfully removed 'squirrel.windows 0.8.3.1' from SimpleApp.
Uninstalling 'squirrel.windows 0.8.3.1'.
Successfully uninstalled 'squirrel.windows 0.8.3.1'.

PM> Install-Package squirrel.windows
Attempting to resolve dependency 'DeltaCompressionDotNet (≥ 1.0.0)'.
Attempting to resolve dependency 'NuGet.Core (≥ 2.8.3)'.
Attempting to resolve dependency 'Microsoft.Web.Xdt (≥ 2.1.0)'.
Attempting to resolve dependency 'Mono.Cecil (≥ 0.9.5.4)'.
Attempting to resolve dependency 'Splat (≥ 1.5.1)'.
Installing 'squirrel.windows 0.8.3.1'.
Successfully installed 'squirrel.windows 0.8.3.1'.
Adding 'squirrel.windows 0.8.3.1' to SimpleApp.
Successfully added 'squirrel.windows 0.8.3.1' to SimpleApp.

PM> Squirrel --releasify "C:\Users\DOJO\Documents\Visual Studio 2013\Projects\SimpleApp\SimpleApp\TheSimpleApp12345.1.0.0.nupkg"

**Comment by Vilmir** [comment]
Sorry to talk again about this issue. I had the same problem on Visual Studio 2013 R4 with Squirrel 0.9.5 and the fix that worked was:
* Uninstall Squirrel
* Restart VS
* Install Squirrel via the package manager interface
* A license agreement appeared for package "Microsoft.Web.Xdt", I accepted it. With the package console, the license agreement never appeared
* Open the package console
* Yay, cmdlet Squirrel exists!

**Comment by PushOrigin** [comment]
This also seems to occur when squirrel is updated through manage nuget packages for solution. The Squirrel cmdlet isn't available until VS is restarted.

**Comment by mike-cochrane** [comment]
Same issue for me. The cmdlet was not available until VS was restarted

**Comment by paulcbetts** [comment]
dunno, sorry Microsoft sucks

**Comment by mbulava** [comment]
I'm having an issue executing e "squirrel --releasify bin\Release\MyApp.1.0.0.0.nupkg" from the AfterBuild Target  keeps erroring out saying : 5>  'squirrel' is not recognized as an internal or external command,
5>  operable program or batch file.

**Comment by fancyfanta** [comment]
same issue...

**Comment by leubac** [comment]
I had the same problem because my obj folder got deleted. Reinstalling from Package Manager readded missing stuff and I was able to releasify again.
