### ISSUE TITLE
UpdateManager.RestartApp() does not restart

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#228]
I have a WPF app. The app has a button who calls this function
````
public void RestartApp()
{
    MessageBox.Show("Will be restart");
    try
    {
        UpdateManager.RestartApp();
    }
    catch (Exception ex)
    {
        MessageBox.Show(ex.ToString());
    }
}
````

When I use the button while I debug in Visual Studio I see
![image](https://cloud.githubusercontent.com/assets/1263856/6171209/81ff264a-b2a7-11e4-96de-59024e23f4ed.png)
then I see
![image](https://cloud.githubusercontent.com/assets/1263856/6171229/9589d19c-b2a7-11e4-9047-e0f1b1ffa36e.png)

So think i only works in apps installed using Squirrel.
So when I use the same code using the shortcut created after call `setup.exe` I see 
![image](https://cloud.githubusercontent.com/assets/1263856/6171209/81ff264a-b2a7-11e4-96de-59024e23f4ed.png)

Then the app closes, I dont see exception but the new version (what I expected) does not start.

Any Idea please?

**Comment by locksmithdon** [comment]
Ricardo, I've run into this too. I may have found a solution, but unfortunately it requires either adding or removing a line of code in Squirrel. Check out my most recent comment on #225 for more info. I also put together a sample app if you're curious.

**Comment by ricardopolo** [comment]
@paulcbetts do you know what cand be the cause for this?

**Comment by paulcbetts** [comment]
Probably a race condition where we're not giving update.exe enough time to start before killing ourselves

**Comment by ricardopolo** [comment]
@paulcbetts can I do anything by my side?

**Comment by paulcbetts** [comment]
@ricardopolo @locksmithdon Can one of you try what's on master right now?

**Comment by ricardopolo** [comment]
@paulcbetts doing thest in development enviroment i have this.

![off](https://cloud.githubusercontent.com/assets/1263856/6261529/ff3d6cfe-b7be-11e4-9189-dd28d0d3b242.png)

Tomorrow I'll make a new release and test again

**Comment by paulcbetts** [comment]
Just put update.exe in your bin directory

**Comment by ricardopolo** [comment]
@paulcbetts using latest Nuget available same behavior.After press restart the app close but not start the new version.

**Comment by paulcbetts** [comment]
@ricardopolo You'll have to build from source, I haven't put it up on NuGet yet

**Comment by ricardopolo** [comment]
@paulcbetts I just tested it.

I think the problem is because `RestartApp` function calls 
`Process.Start(getUpdateExe(), String.Format("--processStart {0} {1}", exeToStart, argsArg))`
and then exits the current process.

In the `Process.Start`,  `getUpdateExe()` returns the path of update.exe and `exeToStart`  is the exe tha will be launch.

In my case `exeToStart` is `SigntulActiveDirectorySync.exe`, a relative path, not an absolute path.

The issue is that `update.exe` and `exeToStart` are in different folder.
![update](https://cloud.githubusercontent.com/assets/1263856/6275135/dda4b32c-b84a-11e4-89c9-c5fdf0959708.PNG)

In my case `exeTostart` is inside debug folder while `update.exe` is outside.
If I just put `update.exe` inside `debug` folder I get an exception saying update does not exists.

**Comment by willdean** [comment]
@ricardopolo - I don't think you're going to easily get this to work in your build bin directories, because Update.exe actually takes the 'exeToStart' command line argument and builds a path of the form `[... path of update.exe--- ]\<appName>\App-<Version>\<exeToStart>`

It's not really that <exeToStart> is relative, its more that it's just an input into a much more complex way of building a full filename.

**Comment by eggapauli** [comment]
I just tried it with version 0.9.0.1, and it restarts my app now (it didn't work with 0.8.5). Anyway, during installation `Update` crashes, but the app starts normally. If you can confirm this I can create a separate issue. Otherwise I will dig deeper what I did wrong.
![image](https://cloud.githubusercontent.com/assets/237707/6458954/eddc037e-c189-11e4-8aee-0dba25cc4284.png)

**Comment by paulcbetts** [comment]
@eggapauli Can you create a separate issue?

**Comment by willdean** [comment]
@paulcbetts Pretty sure his new crash is #257
