### ISSUE TITLE
Temporary Files Overload

### ISSUE THREAD

**Issue by karai17** [Squirrel/Squirrel.Windows#231]
Two days ago I had an issue with Atom that required me to reinstall it. Today I am doing a routine clean out of my temp files and I have 42,802 empty .tmp files dating to the date and time I installed Atom. While I am not 100% certain it was Atom/Squirrel, it is high on my list of suspects as I have not installed or updated any other software recently.

The files are all named in the same format: `tmpA7E3.tmp`, where `A7E3` are hex values. Every single file is 0kb so I suspect there may be an issue with deleting these files, not only their contents.

**Comment by karai17** [comment]
To add to this, there was also a nuget folder in there with 77,182 files totalling 1GB with the same date.

**Comment by paulcbetts** [comment]
I recommend that you delete them

**Comment by karai17** [comment]
I already did, but shouldn't Squirrel clean up after itself?

**Comment by paulcbetts** [comment]
Probably

**Comment by shiftkey** [comment]
Closing this out because #250 was merged, and it's not clear to me if there's any extra work that should be done in here.

Please open a fresh issue with more details if this is seen with a more recent version of Squirrel.
