### ISSUE TITLE
When would I choose Squirrel vs. Windows Installer/MSI?

### ISSUE THREAD

**Issue by pisees** [Squirrel/Squirrel.Windows#241]
Thanks,

**Comment by paulcbetts** [comment]
Choose Squirrel unless its design constraints can't work for your application:

https://github.com/squirrel/squirrel.windows#installation

For example, if your app needs to install a device driver or be in Program Files, Squirrel won't work for you. Most apps don't *need* to be in Program Files (a very small number of accessibility-related APIs require it though)

**Comment by pisees** [comment]
Thanks Paul,
What are top couple of challenges with ClickOnce that led you to develop Squirrel?
