### ISSUE TITLE
Are there hooks that would enable me to check validity of certificates?

### ISSUE THREAD

**Issue by pisees** [Squirrel/Squirrel.Windows#243]
I have tested a sample WPF client placing released in IIS over SSL. Using self-signed certificate everything working great. But if I want to lock down more, for example, only use if certificate signed by trusted root authority can I do this?

**Comment by paulcbetts** [comment]
@pisees I'm actually surprised that WebClient allows self-signed certificates by default. Squirrel doesn't build this in, but you could do it yourself by implementing a custom `IUrlDownloader`

**Comment by pisees** [comment]
I tested on the same machine so perhaps this is why WebClient allowed. I will update if different across machines.

**Comment by BarryThePenguin** [comment]
I ran into #237 as a result of overriding ServicePointManager.ServerCertificateValidationCallback with a custom Validation Callback. You would be able to do the same thing
