### ISSUE TITLE
.NET 4.5 dependency required?

### ISSUE THREAD

**Issue by joshuawarner32** [Squirrel/Squirrel.Windows#244]
What does squirrel require .net 4.5 for?  Would it be difficult to compile it such that it could run on, say, .net 4.0 or .net 3.5 and above?  That would be ideal, since a substantial fraction of our customer base is on .net 4.0.

**Comment by paulcbetts** [comment]
@joshuawarner32 It would be difficult but not impossible to get it running on .NET 4.0, and extremely painful to get running on .NET 3.5. I probably would not take a PR to do this, you'd have to run it in a separate fork

**Comment by joshuawarner32** [comment]
Thanks, fair enough.  I'm guessing the main sticking point is going to be async/await support, which was new in .net 4.5.  Is there anything else you could point out off the top of your head?

Otherwise, feel free to close this.

**Comment by paulcbetts** [comment]
@joshuawarner32 Splat is also 4.5-only (though surprisingly, NuGet.Core is 4.0)

**Comment by Petoj87** [comment]
If async is the problem you can get that up and running on .net 4.0
http://blogs.msdn.com/b/bclteam/archive/2012/10/22/using-async-await-without-net-framework-4-5.aspx

The requirement on 4.5 means that it can't run on XP.. if i just could force all my clients to use Vista or newer i would be happy but i can't...

**Comment by joshuawarner32** [comment]
We actually ended up writing our own installer, in-house, in c++.  I've been wanting to open-source it, but it's not really ready for general consumption yet.

If you're interested, @Petoj87, I may be able to speed that along.

**Comment by Petoj87** [comment]
Oh great news 😃 im not in need of it yet but in a few months!

**Comment by Petoj87** [comment]
@joshuawarner32 is there any issue or fork to check the progress on the c++ installer?
