### ISSUE TITLE
Public API methods don't comply with recommendations for Async API

### ISSUE THREAD

**Issue by willdean** [Squirrel/Squirrel.Windows#248]
There's really good guidance from MS about providing functions with meet the 'Task-based Async Programming Model' here:  https://www.microsoft.com/en-us/download/details.aspx?id=19957

They include things like naming, cancellation support and progress reporting.

The Squirrel API doesn't comply with some of these at the moment, and I think that's a pity, as it doesn't seem that it would be any more difficult to use/implement, and all other things being equal I tend to think following these sort of guidelines is helpful to API consumers.

As an example, the UpdateManager.UpdateApp(...) signature might be more standard as UpdateAppAsync(IProgress<int> progress).   

I would be happy to do the work for these changes, if I thought it would be accepted by the project.  Obviously there are several different approaches to changing the public API (ranging from 'don't' to 'just do it'), and if the answer wasn't 'don't', then that would need to be discussed.

**Comment by paulcbetts** [comment]
I think those guidelines are stupid and need to go away, sorry. We don't need the word "async" to be in every method that returns Task<T> because we already have a way to tell if they're Async: they return Task<T>. I don't prefix all of my strings with 'lpsw' either :)

**Comment by willdean** [comment]
OK, fair enough - What about IProgess<T> vs non-standard custom actions?

**Comment by paulcbetts** [comment]
I don't really see the huge advantage of Progress<T>, though it's at least far more reasonable a request. I could be sold, but I'm not excited about the breaking change, nor the fact that if people see IProgress<T>, most of them are going to think they have to implement that interface in a dummy class.

Personally, if I wanted to Get Fancy with it, I'd move to IObserver<T> because it can express both progress and error conditions

**Comment by willdean** [comment]
I don't think there is any *huge* advantage to it, beyond the mild feeling that one should use a standard if it's available and it's little more effort than something non-standard.  Theoretically it's more likely to composite nicely with other things using IProgress, though don't ask me for a concrete example...   I am using Squirrel in an app which was already reporting progress via IProgess, which is why it occurred to me.

Perhaps the opportunity to educate those poor souls who don't know how to use IProgress might be a bonus rather than a downside :-)

**Comment by willdean** [comment]
I'm not going to bang on about this any more, but it occurred to me overnight that the reason `IProgress` might be recommended over `IObserver` is that completion and errors are already handled via the `Task`, and providing overlapping mechanisms for those might be confusing (to both producer and consumer).

Anyway, if by some chance you wake up one day thinking that the API would be improved by using `IProgress` rather than a custom `Action`, I'd be happy to make the changes for you.

**Comment by BarryThePenguin** [comment]
Why not both? :wink:
