### ISSUE TITLE
What's the right way to call Squirrel.exe on a build server?

### ISSUE THREAD

**Issue by willdean** [Squirrel/Squirrel.Windows#255]
I must be missing something obvious here...

We're running a build on a build server, which starts by doing a nuget-restore, and then after compiling, building packages, etc, it needs to run squirrel --releasify.   We've been doing this by searching the packages tree recursively for squirrel.exe, and then running that.

We've just updated Squirrel, which has in turn caused the build server to pull down a new version of the nuget package - so it now contains two different versions in the package directory (because nuget restore is dimwitted about deleting dead versions).  The build process now finds two versions of squirrel.exe in the packages directory, doesn't know which to use, and fails.

I cannot believe life needs to be this hard - I understand that nuget does some magic within VS so that you can run squirrel.exe from the package manager console, but that's not useful for a CI server.  

What's the proper mechanism by which processes outside VS are supposed to find executable tools within nuget packages?

**Comment by BarryThePenguin** [comment]
From my experience you want build servers to be a blank slate. Every build should be from scratch. That way you don't run into the issue with multiple versions of a dependency in your packages folder.

I'm currently using Appveyor to build [SparkleShare](https://github.com/barrythepenguin/sparkleshare/tree/squirrel-updates). I've based my solution off [HangfireIO](https://github.com/HangfireIO/Hangfire).

**Comment by paulcbetts** [comment]
> I cannot believe life needs to be this hard - I understand that nuget does some magic within VS so that you can run squirrel.exe from the package manager console, but that's not useful for a CI server.

You could always just copy the tools directory into your project and check it in ¯\_(ツ)_/¯

**Comment by willdean** [comment]
@paulcbetts Of course, but then I've got to remember to manually update that every time I nuget-update Squirrel, otherwise the DLL linked with my app will be out-of-sync with the bits being used to build the installer.  Or automate it myself, which is sort of where I came in - I don't have a technical problem making it work, it just seems ridiculously complex, given that nuget already provides the whole 'tools' mechanism, but seemingly no way to use it outside a VS interactive session.  (And I'm not even clear how well that works if you have multiple versions in the tree)
@BarryThePenguin I guess that's the fix - the tool which makes sure you have all the right files can't be  trusted to do its job properly (or completely), so you have to make life easier for it.  I like `$package_dir\squirrel.windows.*\tools\Squirrel.exe` though, thanks.

**Comment by paulcbetts** [comment]
@willdean Yeah - the original design was to make it easy for people to get started and build installers interactively, but the design of NuGet makes it annoying to automate :(   Not sure what else we could do though

**Comment by willdean** [comment]
I hadn't previously realised that nuget caches everything it downloads, so blowing away packages\* before doing a nuget-restore at the beginning of a build is not actually too painful a process: it rebuilds from the cache very quickly anyway.  So I'll stick with my recursive search for squirrel.exe...
