### ISSUE TITLE
Restart App Does not work

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#261]
I have a very simple App with `UpdateManager.RestartApp()`

With Nuget in version 0.9.1 I have this behavior:
1. I see a command prompt window
2. The App closes
3. The App never starts again

Using Process Monitor to undestand what is happening I see a call to `update.exe` and the the app closes.

Update.exe is called with this parameters
`"C:\Users\Ricardo\AppData\Local\SigntulActiveDirectorySync\Update.exe" --processStartAndWait SigntulActiveDirectorySync.exe `

So I understand why this fail. `SigntulActiveDirectorySync.exe` is not in the same folder of `Update.exe`.

My folder structure inside AppData is like this
![capture](https://cloud.githubusercontent.com/assets/1263856/6471251/5331c38a-c1b7-11e4-90b8-a7d8fd8e6322.PNG)

**Comment by paulcbetts** [comment]
@ricardopolo The EXE name isn't intended to be used as a path, it's solely a file name. We automatically look up the latest version of the app and look for the EXE name in there

**Comment by ricardopolo** [comment]
@paulcbetts Now I calling the command from my command prompt I have this behavior
![capture](https://cloud.githubusercontent.com/assets/1263856/6471420/dcc57bae-c1b8-11e4-9090-86029566a1c5.PNG)

I checked and `SigntulActiveDirectorySync.exe` exists in both  `app-1.0.1527` and `app-1.0.1536', but the App never starts

Any idea?

**Comment by paulcbetts** [comment]
What's the version of Update.exe in your update folder? Both of these commands work for me

**Comment by ricardopolo** [comment]
@paulcbetts for some reason `update.exe` was not being updated. 
It was stuck at version 0.8.5.0.

I deleted the whole Releases folder, a create a new one. Now `update.exe` is version 0.9.1.0 and its working.

Is thre any recommend procedure for you to delete all releases and clean the folder? (Understanding we'll losoe Delta Updates)

**Comment by paulcbetts** [comment]
@ricardopolo You don't need to delete all releases, you just need to update Update.exe, include Squirrel.exe in your update package (and call it Squirrel.exe).

**Comment by ricardopolo** [comment]
@paulcbetts so I need to add to include Update.exe as Squirrel.exe in the folder of the App. Right?

Why dont you include this exe as you include `Squirrel.dll` reference?

**Comment by paulcbetts** [comment]
@ricardopolo File size reasons mostly (you only have to include it if you need an update to update.exe so most releases don't need it), though I'm reconsidering this decision especially because delta updates

**Comment by ricardopolo** [comment]
@paulcbetts I think this is a very good idea. With delta updates the releases wont be very big and always have the update system updated :smile:

**Comment by ricardopolo** [comment]
@paulcbetts what about this, have you reconsider and includes `update.exe` by default now? Or do we need to keep including it manually in each  nuspec?
