### ISSUE TITLE
Documentation is very poor

### ISSUE THREAD

**Issue by joaomoreno** [Squirrel/Squirrel.Windows#264]
I'm coming from the Atom Shell project. I have an Atom Shell based application that I want to create an installer and have it auto-update automatically. They use Squirrel for OS X. They also talk about how Squirrel.Windows can work.

I decide to drop the Atom Shell and play around with a simple Console C# application. I then go through all the documentation in this project. I create the project in Visual Studio, add Squirrel.Windows and... lost it.

I have fundamental questions that stay unanswered when going through the docs:

- How can I create an installer for my application?
- How does signing work? Is it required? When does it come into play, in the tools?
- What exactly is `Setup.exe` created by `Squirrel.exe --releasify...`?
- What does `Squirrel.exe --releasify...` actually do to my application?

**Comment by paulcbetts** [comment]
If you're doing an Atom Shell-based app, you should look at https://github.com/atom/atom/pull/3815 and https://github.com/atom/grunt-atom-shell-installer

**Comment by joaomoreno** [comment]
Thanks!
