### ISSUE TITLE
Installer creates broken shortcut to non-squirrel-aware apps

### ISSUE THREAD

**Issue by willdean** [Squirrel/Squirrel.Windows#269]
* Installing a non-squirrel aware app
* Installer automatically creates a shortcut which points to update.exe, with command line args to run the app itself (this is OK, in principle)
* Unfortunately, the shortcut points to the copy of update.exe in squirrelTemp, rather than the one at the app root, so the shortcut is broken.

This is because the getUpdateExe() call in CreateShortcutsForExecutable returns the path to the wrong copy of update.exe.  I guess it works well in the other situation it's used (RestartApp), but it's not good in CreateShortcutsForExecutable.

Given that CreateShortcutsForExecutable apparently already knows rootAppDirectory, a simple Combine of rootAppDirectory & "update.exe" ought to be enough?  It works here anyway, so I'll put in a PR for consideration.  

As it stands, it seems like the current version of Squirrel can't really be used with a non sq-aware app.

**Comment by paulcbetts** [comment]
This should be fixed now
