### ISSUE TITLE
Use SquirrelAwareExecutableDetector instead of copying code

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#271]
I wrote a helper a while back and I think I even created a PR, but I think you shouldn't repeat yourself in code (copy/paste). It bit code in squirrel before (the shortcuts code).

In UpdateManager.ApplyReleases, the squirrelApps check is the same in multiple locations. I think it should be replaced by this:

https://github.com/GeertvanHorrik/Squirrel.Windows/blob/pr/semver/src/Squirrel/SquirrelAwareExecutableDetector.cs#L21

Instead of adding the check for "squirrel." everywhere, just use the SquirrelAwareExecutableDetector.

**Comment by paulcbetts** [comment]
:+1:

**Comment by Thieum** [comment]
@GeertvanHorrik couldn't find a PR related to this, is this something you want to revisit?

**Comment by GeertvanHorrik** [comment]
No, I didn't create a PR back then. I think the code is too different nowadays and could be refactored at another stage. My suggestion is to close this ticket.

**Comment by Thieum** [comment]
@shiftkey this can be closed.
