### ISSUE TITLE
Support relative paths for the icon file

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#274]
I think it's a nice feature to support relative files for the icon file.

It requires a 1-line code-change here:

https://github.com/Squirrel/Squirrel.Windows/blob/e0de05f955/src%2FUpdate%2FProgram.cs#L602

```
args.AppendFormat(" --set-icon \"{0}\"", Path.GetFullPath(iconPath));
```

**Comment by paulcbetts** [comment]
:+1:

**Comment by GeertvanHorrik** [comment]
I will close this one, created a PR.

**Comment by paulcbetts** [comment]
@GeertvanHorrik You can just put "Fixes #XYZ" in the PR description and it'll close and link it Automagically

**Comment by GeertvanHorrik** [comment]
Thanks for the tip, will do that next time.
