### ISSUE TITLE
Update.exe hanging

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#278]
All my shortcuts have been changed to point to update.exe (0.9.1). There are several issues with this:
1. Update.exe hangs trying to run my splash screen starter. here is the path: C:\Users\Stefan\AppData\Local\LegacyDocs\Update.exe --processStart C:\Users\Stefan\AppData\Local\LegacyDocs\app-1.0.268\SplashScreenStarter.exe.  If I remove the update.exe --processStart bit and then start the application, it works fine.  Also, it's interesting to note that there are no quotes around the application name so if this was some reason a path with a space in it there would be a big problem.  What could be causing the application not to start? The splash screen is a c++ app, not the one that is registering the icon, that is LegacyDocs.exe, which is squirrel aware and it runs this code to register the icon:
updateManager.CreateShortcutsForExecutable(Assembly.GetExecutingAssembly().Location.Replace("LegacyDocs.exe", "SplashScreenStarter.exe"), ShortcutLocation.Desktop | ShortcutLocation.StartMenu, updateOnly);
up until now it has worked perfectly.
2. I definitely don't want update.exe running before my application. I have written the splash screen start so that the CLR is not instantiated as part of the start-up process so I can display my splash screen very quickly.  How can I turn off using update.exe?

Thanks,
Stefan

**Comment by stefanolson** [comment]
Also, related to this, for some reason it seems to create the shortcut in a folder that is the author name.  I want it directly in the start menu and not within a folder, and puts my font installer application in that folder as well even though that is not squirrel aware and I don't want it to appear on the start screen, and I haven't called CreateShortcutsForExecutable for it.

**Comment by willdean** [comment]
Stefan, I can't help with all of this, but:

* The idea is that update.exe (confusingly named when performing this role, but it's just the Squirrel Swiss Army Knife) is doing the 'latest version' selection process, so that the shortcut can always point to update.exe, and then update.exe finds the latest version exe to launch.
* The update.exe command should look like --processStart SplashScreenStart.exe
i.e. it's just the exe name, not the full path.  You should probably just pass "SplashScreenStart.exe" to CreateShortcutsForExecutable, rather than a full path.  (Obviously CreateShortcutsForExecutable should be able to cope with this or at least fault actively)
* The point about quoted paths is perhaps less of a risk given that it's only supposed to be the exe name, but it's still a risk for apps with a name with a space in it.
* I don't think you can turn this new update-redirection off.  Maybe Squirrel could/should expose the lower level shortcut helpers to let you make your own of control this behaviour.
* I don't know about the rest, sorry.

**Comment by stefanolson** [comment]
Hi Will,

Thanks for your suggestions.  I have now tried manually changing the path in the shortcut just for testing to: C:\Users\Stefan\AppData\Local\LegacyDocs\Update.exe --processStart SplashScreenStarter.exe

Sadly that doesn't work either :-(  but I understand your point.

Thanks,
Stefan

**Comment by willdean** [comment]
If update.exe is hanging waiting for something, then that's probably a problem which has been fixed in the current code, just not made it to nuget yet.   If you run that line from a command prompt window and then close the command window, does your app then start?

**Comment by stefanolson** [comment]
Just for clarification it is possible that the shortcut for the font installer was added some time previously, because it didn't disappear when I just uninstalled, so that may have been fixed in later builds. But I am now manually creating the shortcuts as part of the install and removing them as part of the uninstall until (if) there is a more automated solution

**Comment by stefanolson** [comment]
@willdean Yes, it does. How weird!

**Comment by willdean** [comment]
It's because the --processStart option in the version you're using waits (infinitely) for its parent process to terminate before carrying on.  That's because it was originally intended for a different role (part of app-restarting after upgrade) and not as a general launcher.  This has been fixed in the latest code.

**Comment by willdean** [comment]
Actually, looking at the commit history, I think this was supposedly fixed in 0.90 ( 532cd5d637884261ff9b8878abc6a1cb38dd2cb4 ), so perhaps your update.exe in the application root directory is older than that?

**Comment by stefanolson** [comment]
@willdean good to know it is fixed, hopefully can get some comment from @paulcbetts from on how I can avoid using update.exe and have the application put into the main program group rather than into its own group, that would work better for me

**Comment by stefanolson** [comment]
@willdean That could well be the case, because it may not have been deleted or updated as part of the install.  I might have to try and ship it with my next release.

**Comment by paulcbetts** [comment]
Hey guys, I totally screwed up on this one, by not indicating that you *need* to do a Squirrel Self-update with the last release (i.e. include Squirrel.exe in your update package). 

In the future, I'm going to try to watch out for this class of errors (features that depend on certain Update.exe versions), as well as put up release notes for releases so people know what's in them

**Comment by willdean** [comment]
I don't think I ever understood that I ever needed to include Squirrel.exe in the package - do I need to find the exe somewhere in packages and add that to my nuspec file?    I still haven't worked out why and when it's called squirrel.exe and/or update.exe :-)

**Comment by stefanolson** [comment]
@willdean here is what I do in my nuspec file:

<file src="packages\squirrel.windows.0.9.1\tools\squirrel.exe" target="lib\net45\" />

**Comment by paulcbetts** [comment]
@willdean You usually don't...except when you do

**Comment by stefanolson** [comment]
@paulcbetts I have updated update.exe in the past, the problem that I've found is when do I remove it from the setup, or really should it be there all the time?  Some users might take a long time before they restart the application and update and by that stage I have removed it from my nuspec to make the download smaller.

I wonder if there is a way to have the update/install check if it has the correct version number of update.exe and then downloaded as a separate download rather than putting it in my delta file all time even when it doesn't need it...

**Comment by stefanolson** [comment]
@willdean that didn't work very well - try again:
    
    <file src="packages\squirrel.windows.0.9.1\tools\squirrel.exe" target="lib\net45\" />

**Comment by paulcbetts** [comment]
@stefanolson lol I keep fixing it

**Comment by stefanolson** [comment]
@willdean clearly I really don't understand this commenting system - here is the key line:
    <file src="packages\squirrel.windows.0.9.1\tools\squirrel.exe" target="lib\net45\" />

**Comment by stefanolson** [comment]
@paulcbetts I have now figured it out and try fixing it too :-) Thanks!

**Comment by willdean** [comment]
So you hard-code the package version into the nuspec file?   So you have to update that after a nuget update?  Thanks but no thanks.  

No doubt to Paul's considerable relief I think I'm about to go back to Innosetup...

**Comment by stefanolson** [comment]
@paulcbetts what about options for not using update.exe in the shortcut and putting the shortcut directly into the program groups rather than into a subfolder?  Should I start a new issue for that request?

**Comment by paulcbetts** [comment]
@stefanolson You can start a new one

**Comment by stefanolson** [comment]
@willdean would be better if it were automated I agree. But I think squirrel is so much better than any other setup package I've used primarily because of the ability for it to automatically update, which in the case of my application is quite critical. I did quite a bit of searching prior to using squirrel and wasn't able to find anything that would work nearly as well.  For my situation it really is outstanding.

**Comment by willdean** [comment]
If we put 'squirrel.exe' into our package, does it automagically become update.exe at some point during the installation?

**Comment by paulcbetts** [comment]
@willdean Yeah, that's a special case that is explicitly handled, you don't have to do anything else

**Comment by BarryThePenguin** [comment]
Nuget works with globs too

```
<file src="packages\squirrel.windows.*\tools\squirrel.exe" target="lib\net45\" />
```

**Comment by willdean** [comment]
@BarryThePenguin Awesome...

**Comment by stefanolson** [comment]
@BarryThePenguin that looks a lot nicer, but what happens when you have multiple packages in the packages folder. In my case, and I don't know why, I have got packages\squirrel.windows.0.8.0 and packages\squirrel.windows.0.9.1. Obviously I can just delete one, but it could cause a accidental problem...

**Comment by willdean** [comment]
@stefanolson nuget restore doesn't delete old versions, which can cause this.  People have been complaining about it for years.

**Comment by BarryThePenguin** [comment]
Yeah, I just delete my packages folder after I update packages. On next build, VS will restore packages which are cached locally most of the time too

**Comment by locksmithdon** [comment]
I'm so glad I read this thread. I didn't know that including `squirrel.exe` in the package would update `update.exe`. Very cool. I was concerned about this after being slightly bit by the last update. Relieved. Cheers.

**Comment by sergey-tihon** [comment]
- Could I always pack `squirrel.exe` and `myApp.exe` in NuGet package? 
- Will squirrel execute `myApp.exe` after update if find two `*.exe` files in folder?

**Comment by Thieum** [comment]
@shiftkey Considering https://github.com/Squirrel/Squirrel.Windows/issues/278#issuecomment-78158237 , the original issue is fixed.

**Comment by stefanolson** [comment]
happy to close this now
