### ISSUE TITLE
Update.exe referenced in shortcut

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#279]
With the latest versions of squirrel update.exe runs before my application. I have written my splash screen starter so that the CLR is not instantiated as part of the start-up process so I can display my splash screen very quickly. How can I turn off using update.exe in the shortcut?

**Comment by paulcbetts** [comment]
@stefanolson At the moment, you can't :(  How much of a delay is Update.exe injecting into startup time?

**Comment by stefanolson** [comment]
@paulcbetts haven't measured it, but years ago I spent quite a lot of time writing a C++ splash screen so that from the time of the user clicks the shortcut to the splash screen appearing was quite quick, because the CLR does take quite some time to start up if it hasn't already been started. These things are a LOT more efficient than they were, but for the moment I've borrowed the shortcut creation code out of squirrel and using that to create an icon that points directly to my application. I've had no issues that other people have had with the need to use update.exe to launch the application. The shortcuts have always been working for me.  So, there may be absolutely no basis for my request, maybe the CLR launches hugely quickly now, but sort of one of those things that I knew in the past I needed to do it so kind of still wanting to do it :-)

**Comment by paulcbetts** [comment]
> for the moment I've borrowed the shortcut creation code out of squirrel and using that to create an icon that points directly to my application

:+1: That works too, as long as your app is Squirrel aware, you can create shortcuts however

**Comment by Thieum** [comment]
@shiftkey I think we can close this as wontfix, as there is an alternative to work with atm.
