### ISSUE TITLE
CreateShortcutsForExecutable ShortcutLocation.StartMenu puts it in a sub-group

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#280]
Currently CreateShortcutsForExecutable when creating a program group puts it inside of a group folder with the name of the author.  This may be what some people want, but I would like my single icon to appear directly in the start menu. Could we have an option for this please?

Thanks,
Stefan

**Comment by willdean** [comment]
@paulcbetts  would the best way to do this be to add another flag in ShortcutLocation (e.g. StartMenuRoot)?
If so, I can do this and put in a PR if you like

**Comment by stefanolson** [comment]
@willdean thanks!

**Comment by utd1878** [comment]
Was there ever a way to ensure the icon was created outside this group folder?

**Comment by Thieum** [comment]
@shiftkey this can be discussed in #484 , like proposed in #281 , so this can be closed.
