### ISSUE TITLE
Code signing question

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#285]
I am implementing code signing in our build server. So far, so good, but... why is it signing my executables?

```
Done Adding Additional Store 
Successfully signed and timestamped: C:\Users\buildagent\AppData\Local\Temp\a\lib\net45\MyApp.exe
Done Adding Additional Store
Successfully signed and timestamped: C:\Users\buildagent\AppData\Local\Temp\a\lib\net45\Squirrel.exe
Done Adding Additional Store
```

My app executables are already signed and timestamped as a result of the build itself. I think the only files Squirrel should touch are the Squirrel.exe / update.exe / setup.exe. What do you think?

**Comment by stefanolson** [comment]
Personally, I want it to sign my executables, because they are not signed as part of my build.

**Comment by GeertvanHorrik** [comment]
But then there should be an option / check to not re-sign files (it will result in 2 different executables since we also generate an offline setup).

**Comment by willdean** [comment]
I can't really see the benefit of using Squirrel to do any signing - it's just one of umpteen build steps which you have to automate anyway - and signing would have to be done separately if you used a different installer anyway.   It's not even like the Squirrel build is likely to be the last step of any automated build - if nothing else it's almost certainly going to be followed by a rename.

**Comment by GeertvanHorrik** [comment]
Fully agree, except... it should sign both the installer and the update.exe it packs into the package (we ship squirrel.exe with every release to ensure the user is on the latest version). What we do in our build is:

1) Build software + sign
2.1) Create offline installer
2.2) Create squirrel channels (beta and official if official build)
3) Copy setup.exe to [projectname].exe (we support the download of both setup.exe and [projectname].exe
4) Sync with azure

The signing of both the setup and the squirrel is done by the tools (inno setup or squirrel). I think it should only sign what it is currently creating (the setup), not any other build artifacts.

**Comment by stefanolson** [comment]
I think it would make sense to have an option to turn it off but there are many people like myself for whom having it sign as part of its process is exactly what we want.

**Comment by paulcbetts** [comment]
Why don't you just not use Squirrel signing altogether then sign Setup.exe yourself?

**Comment by GeertvanHorrik** [comment]
That's an option as well, but I liked the fact that it took care of update.exe inside the package (which is also squirrel related). Same as that Inno Setup also signs both the installer and uninstaller.

**Comment by paulcbetts** [comment]
Hm, we're probably not gonna change the existing behavior, asking people to sign stuff in their build process then turning around and asking them to setup signing _again_ for Squirrel is silly goose

**Comment by Aluxian** [comment]
@paulcbetts So.. just to clear my head. As OP said, Squirrel signs every .exe inside the build folder.

1) Does it also sign the Setup.exe file it creates?
2) Am I supposed to copy Squirrel.exe myself inside my build folder? Or will Squirrel automatically package an Update.exe file too?

**Comment by paulcbetts** [comment]
> 1) Does it also sign the Setup.exe file it creates?

Yes 

> 2) Am I supposed to copy Squirrel.exe myself inside my build folder?

Yes, this is a good idea but not required. You don't have to update Squirrel itself for every update, but you can!
