### ISSUE TITLE
Fallback if releases files does not exist

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#286]
Just updated to the latest version of squirrel and the client completely broke. The reason is because it's now using update.exe to run the app. However... it breaks on not finding the releases file.

Here is a fix that will work in Program.cs (ProcessStart method):

```
// Find the latest installed version's app dir
var appDir = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);

var latestAppDir = (from directory in Directory.GetDirectories(appDir)
                    orderby Directory.GetCreationTime(directory) descending
                    select directory).FirstOrDefault();

var releasesFile = Utility.LocalReleaseFileForAppDir(appDir);
if (File.Exists(releasesFile))
{
    var releases = ReleaseEntry.ParseReleaseFile(File.ReadAllText(releasesFile, Encoding.UTF8));
    latestAppDir = releases
        .OrderBy(x => x.Version)
        .Select(x => Utility.AppDirForRelease(appDir, x))
        .FirstOrDefault(x => Directory.Exists(x));
}
```

Another issue is that the path is checked relative to the executing assembly (which is wrong, it's using SquirrelTemp, which should be the installation folder).

**Comment by GeertvanHorrik** [comment]
And the best way to determine the app directory is this utility method for now:

```
public static string GetApplicationDirectory()
{
    var directory = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
    if (!directory.ToLower().Contains("squirreltemp"))
    {
        directory = Path.GetFullPath(Path.Combine(directory, ".."));
    }
    else
    {
        directory = Environment.CurrentDirectory;
    }

    return directory;
}
```

For now I will revert back.

**Comment by willdean** [comment]
Do you know why there isn't a releases file?  Seems a bit odd.

**Comment by GeertvanHorrik** [comment]
Maybe because I had an in-between version where the wrong temp file was being used. Might be an install screw up.

**Comment by Thieum** [comment]
@shiftkey seems like the original issue has been resolved, this can be closed.
