### ISSUE TITLE
UpdateManager.DownloadReleases does not report progress in %

### ISSUE THREAD

**Issue by ogborstad** [Squirrel/Squirrel.Windows#288]
According to the API documentation the progress parameter in the callback is supposed to be between 0-100. I am getting large numbers which appear to be downloaded bytes...

**Comment by Cyral** [comment]
The same happens with `UpdateApp`, it returns some very large numbers while downloading before reporting the progress of installation.

**Comment by paulcbetts** [comment]
This is definitely a bug, I think this was introduced with one of @sickboy's PRs - cc /@sickboy

**Comment by sickboy** [comment]
Whoops! How does that look: #297

**Comment by Thieum** [comment]
@shiftkey fixed in #297 , this can be closed.
