### ISSUE TITLE
Getting update of new version  of the apps.

### ISSUE THREAD

**Issue by vikashk2** [Squirrel/Squirrel.Windows#305]
Hi,

After implementing the Squirrel.Windows to get latest update form windows apps. What are the supporting idea to getting latest update of the apps?

How do we know that latest update?

Thanks and regard!
Vikash

**Comment by paulcbetts** [comment]
You can use the CheckForUpdate method on UpdateManager to check for this!

**Comment by vikashk2** [comment]
Hi,

Thanks for this clarification regarding update.

Still i have some queries about this.

1)   How to check update manually on local machine?

2)  I also want to wait machine to install the update to verify the version number to check the updates are valid or not?

3) If it is possible, Could you please provide me a complete sample application for this therefore i can check latest update and all. That would be better for understanding and implementation.

Thanks and regard.
Vikash

**Comment by paulcbetts** [comment]
Hey Vikash,

I would check out the docs folder at https://github.com/Squirrel/Squirrel.Windows/tree/master/docs, it can answer a lot of your questions
