### ISSUE TITLE
App doesn't start when installer is executed twice

### ISSUE THREAD

**Issue by johannesegger** [Squirrel/Squirrel.Windows#307]
When I run an installer for a specific version of an app twice, the second time it doesn't start the app. I took a look at the logs and it says:

> ...
> ApplyReleasesImpl: No release to install, **running the app**
> ApplyReleasesImpl: Squirrel Enabled Apps: []
> ApplyReleasesImpl: No apps are marked as Squirrel-aware! **Going to run them all**
> ... [Creating shortcuts]

So the log says that the app will be started, but when I took a look at the code, the installation is aborted before running the app due to the following line:

```
if (!isInitialInstall || silentInstall) return;
```

You obviously had a reason for running the app only on initial install. Can you explain it to me?

**Comment by paulcbetts** [comment]
Well I mean, having the app pop up when being updated would be a bit Weird

**Comment by eggapauli** [comment]
Ahh of course, I overlooked that this exact routine is also used when updating. If you can give me some advise on how you want this to be fixed I could create a PR.

**Comment by eggapauli** [comment]
Any updates on this?

**Comment by paulcbetts** [comment]
I'll fix this, this code is Very Tricky and Easy To Break

**Comment by eggapauli** [comment]
Perfect, thanks.

**Comment by rafaelwinter** [comment]
This seems to be related to issue https://github.com/Squirrel/Squirrel.Windows/issues/317

**Comment by abakaa** [comment]
Any updates on this issue? 
Or a quick workaround would be appreciated.

**Comment by Thieum** [comment]
@johannesegger  @arda-a is it an issue you are still experiencing with the latest version of Squirrel?

**Comment by johannesegger** [comment]
Sorry, I don't work on the project that had this issue any more. So feel free to close this whenever you want.

**Comment by shiftkey** [comment]
Closing this out because we don't have much to work with, and it's been quiet since 2015 so maybe it was resolved indirectly by another update.
