### ISSUE TITLE
Best way to check updates frequently in forever running app

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#315]
Hello.

I used to have an app that was running only for a few minutes per day (triggered by the Task Scheduller) so when it starts It checks for updates using Squirrel.

Now we are going to change the app for a forever running hiiden app (running at startup).  In an scenario like that what do you recommend for check updates like 2 times per day?

I think Github for Windows or Chrome does something like that.... it does check for updates even if you not restart the software.

I know this may be not related to Squirrel and relies more in our implementation, but any idea would be appreciated

Thanks :)

**Comment by paulcbetts** [comment]
> In an scenario like that what do you recommend for check updates like 2 times per day?

Seems reasonable to me - Slack checks every 6hrs, since RELEASES is very small, you don't usually have problems with capacity on the server side. The bigger problem is how to set up the restart, though if your app is completely hidden to the user, you could always just restart whenever you want.

**Comment by theofanis** [comment]
@ricardopolo My app checks 1 minute after launch and every 24 hours after that while open. When an update is found, its downloaded and installed and an "indicator" appears informing the user that an update was found. Clicking that opens the about page of my app, which just prompts for a restart.

I guess you could also restart if you're running in the background (maybe minimized in the tray?) without even asking the user.

**Comment by ricardopolo** [comment]
And exactly what do you do for "re check"?
Someting like
' _timer = new Timer(SqurirelUpdate, null, TimeSpan.Zero, TimeSpan.FromHours(6))';

Is enough?
