### ISSUE TITLE
Update.exe targeted shortcut not launching app after a new app update, using squirrel 0.9.4

### ISSUE THREAD

**Issue by theofanis** [Squirrel/Squirrel.Windows#316]
My app (v. 1.4.2) runs with squirrel 0.9.2.1. I want to release an update (v 1.4.3), which includes squirrel 0.9.4. I also changed the executable's name, although I don't know if this affects the problem I have in any way.

So, after successfully updating, I see that the shortcut now points to `..\Update.exe --processStart NewAppName.exe`, while previously it targeted `..\Update.exe --processStart OldAppName.exe`. OK this works as expected.

I run Setup.exe which updates the app and successfully launches it. I close it and try to run it from the desktop shortup but it fails, leaving Update.exe hanging. Squirrel log is empty after this action, but with the older version it logged all attempts to launch the app.

**Comment by paulcbetts** [comment]
> leaving Update.exe hanging

Attach a debugger and get a call stack?

**Comment by theofanis** [comment]
False alarm, sorry about this, custom code in handle events crashed and caused this.
