### ISSUE TITLE
Close all process in uninstall

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#318]
Hello.

Whats the correct way for kill of process of the App on Uninstall?

I mean I can do something like
````  
                  foreach (var process in Process.GetProcessesByName(Constants.ExeName))
                    {
                        process.Kill();
                    }
````
onAppUninstall event, but It will work? Or it will close the Uninstalling process too?

Thanks

**Comment by paulcbetts** [comment]
There *is* no generalized correct way to kill your app's processes on uninstall, that's why we don't do it :-/
