### ISSUE TITLE
Do you support single instace apps?

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#320]

**Comment by paulcbetts** [comment]
Yes? No? What do you mean

**Comment by ricardopolo** [comment]
I mean an App that only have one instance... if you run the same exe two times it wont open a new one. Using a Mutex for example (http://stackoverflow.com/a/522874/909974)

But, it will affect the behavior of Squirrel?  For example when using RestartApp() for open the new version.. (I think maybe it fill fail because in some mili seconds the two version would be open.

**Comment by paulcbetts** [comment]
Squirrel waits for the old one to die before it starts the new one in RestartApp.

**Comment by ricardopolo** [comment]
So It will work, right?

**Comment by paulcbetts** [comment]
Should!
