### ISSUE TITLE
Could not load file or assembly NuGet.Core

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#321]
Hello.

We are recently having this exeption while applying updates:

`Could not load file or assembly 'NuGet.Core, Version=2.8.50926.602, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I checked and in the App folder exists this DLL
![image](https://cloud.githubusercontent.com/assets/1263856/7449417/6d6934bc-f1fb-11e4-8c6d-fc86135937d4.png)

And in the App config we have this binding redirection

````xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="NuGet.Core" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.8.60318.667" newVersion="2.8.60318.667" />
      </dependentAssembly>
````

Any idea about what more should we check?
I think this is related with the latest Nuget update, without modifying the code it was working some days ago.

Thank you

**Comment by distantcam** [comment]
I've hit the same problem. When the Updater is called with ProcessStart it starts the exe in a new process, but doesn't set the working directory of the process when it starts. So the process runs in the wrong directory. Normally this doesn't break assembly resolution, but it can sometimes with things like reflection, and possibly binding redirects.

I'll be submitting a PR for this shortly.

**Comment by ricardopolo** [comment]
@distantcam thanks. It seems razonable to my issue, I'll be waiting that @paulcbetts bump a new release for this PR :)
