### ISSUE TITLE
Trouble installing Visual Studio Code (uses Squirrel Setup)

### ISSUE THREAD

**Issue by albertinix** [Squirrel/Squirrel.Windows#322]
Hi,

I wanted to install Visual Studio Code. I am using Windows 7, 64-bit, in a corporate environment (no direct Internet connection, authenticated proxy).

After downloading the setup file from [here](http://download.microsoft.com/download/0/D/5/0D57186C-834B-463A-AECB-BC55A8E466AE/VSCodeSetup.exe) I have proceeded to install it.

Alas, no such luck. The error I got is: "Installation has failed. Failed to extract installer". The button "Open setup log" did not do anything. I have attached a screenshot of the error dialog.

There is no .log file created in  %LocalAppData%\SquirrelTemp folder. That folder only contains 
the 4 files included in the setup package.

I have tried to execute the installer with and without admin privileges. No change. Downloaded it again. Same thing.

In the end I had to open the executable file, extract its contents, then with a command prompt figure out how to use the "Update.exe" file.

In the end, I think the parameters I used were: "update.exe --install=."

![image](https://cloud.githubusercontent.com/assets/4851179/7451126/49930a7a-f24d-11e4-859c-d07af30d7e02.png)

**Comment by paulcbetts** [comment]
If you got "Failed to extract installer", that means that Software Restriction Policy has been put in place on your machine. We've already worked around this but VS Code apparently is using an old version of Squirrel

**Comment by stajs** [comment]
@albertinix I feel your pain. You can verify that Group Policy is blocking you thusly:

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/troubleshooting.md

@paulcbetts Is the work around something I saw about failing over to installing to ProgramData?

**Comment by paulcbetts** [comment]
@stajs Yeah, but they're running an old version
