### ISSUE TITLE
Squirrel target framework and update mechanism

### ISSUE THREAD

**Issue by goldsmit409** [Squirrel/Squirrel.Windows#326]
hi

We have an app which targets dotnet 4 client profile and will be used in a LAN environment i have the following two questions

1) does squirrel require the application to target framework 4.5, or it could work with older version as well?

2) How does it update the app? from what i read on the docs, it says a nuget package is needed for the installer, so will that package needs to be hosted on the internet, or hosting on LAN could also work...
thnx

sorry could not find a Q A section so posting here

**Comment by paulcbetts** [comment]
> 1) does squirrel require the application to target framework 4.5, or it could work with older version as well?

Yes, .NET 4.5 is the minimum version.

>  so will that package needs to be hosted on the internet, or hosting on LAN could also work

You can use any HTTP / HTTPS URL, or you can use any valid file path (including UNC paths)
