### ISSUE TITLE
UpdateApp doesn't always return

### ISSUE THREAD

**Issue by stirno** [Squirrel/Squirrel.Windows#328]
In Scrawl, we've had users report issues with updates not completing. I've started to see it randomly as well. We've simplified our squirrel use to the most basic to try and resolve this. To install an update we run:

```
await manager.UpdateApp();
UpdateManager.RestartApp();
```

But even with this we've seen the behavior continue. We don't use squirrel-aware hooks or any other method on UpdateManager.

**Comment by stirno** [comment]
Additional information: I've confirmed 2 of the users having this issue are using Win10 preview builds (10074 I believe).

**Comment by paulcbetts** [comment]
Gotta get a call stack or a crash dump!

**Comment by stirno** [comment]
Looks like its the same issue as #329 - Added some deps on scriptcs latest and upped our NuGet version. I'll close this one.
