### ISSUE TITLE
Possible to show splash while dotnet 4.5 is being installed?

### ISSUE THREAD

**Issue by goldsmit409** [Squirrel/Squirrel.Windows#333]
is it possible to show the splash screen for the app while the dotnet framework is being installed in silent mode by passing command line argument to the installer?
i was thinking maybe when the installer checks for dotnet we can show a splash screen n then continue installing dotnet in background in that case it will make the UX more uniform...

**Comment by paulcbetts** [comment]
The splash screen is shown using C# code, so this isn't possible :(
