### ISSUE TITLE
Disabling installer time limit

### ISSUE THREAD

**Issue by bostondv** [Squirrel/Squirrel.Windows#334]
Is there a way to extend or disable the time limit during `--squirrel-install` and `--squirrel-uninstall` events? 

According to the docs [here](https://github.com/atom/grunt-electron-installer#handling-squirrel-events) it times out and quits after ~15 sec.

We need to extend the timeout because our application needs to spawn installers for a couple dependencies during the initial setup.

**Comment by paulcbetts** [comment]
There's no way to currently extend or disable the time limit - there could in the future be a mechanism where the application asks for more time if it needs it, but I don't really know what that looks like at the moment. Any ideas?

**Comment by bostondv** [comment]
Until I learned about the time limit, I assumed that the installer waits
for the quit command before continuing to the app. Maybe something like
that?

Regarding the time limit, does that apply to all squirrel events?

What I'll probably do in the meantime is install the dependencies on first
run. First run event is available in the electron installer and wouldn't be
subject to any time limit I assume?

Thanks

**Comment by paulcbetts** [comment]
> Until I learned about the time limit, I assumed that the installer waits for the quit command before continuing to the app. Maybe something like that?

This means if the app does something dumb or gets confused, the installer / updater hangs forever

> Regarding the time limit, does that apply to all squirrel events?

Yes, though the time limit is different for different events

> What I'll probably do in the meantime is install the dependencies on first run. First run event is available in the electron installer and wouldn't be subject to any time limit I assume?

First run event is just a hint to your app, there's no time limit there

**Comment by bostondv** [comment]
True, though maybe the choice could be left to the developer?

A hard time limit in my case makes it impossible to install the
dependencies, I have a 3rd party driver to install which takes over a
minute to complete...

**Comment by paulcbetts** [comment]
If you have to install a driver, then Squirrel is nor for you, sorry. Squirrel is a per-user install, installing drivers is not in our scope.

**Comment by Pinpickle** [comment]
@paulcbetts is there any way this could be re-visited? There appear to be a number of use-cases for this and a few people also expressed concerns in the original commit affd8d7f59e36df88d168510251ba901a84948f8.

I'm more thinking of this in the scope of #382 (which I wouldn't consider a valid use-case as its installing to a machine location as opposed to a user location) but for installing other dependencies and showing dialogs, I'd consider the timeout a hinderance.

This should probably come with caveats explained as well - if a hook you're writing does have something that could cause the installer to hang, include your own built-in timeout or something sensible.
