### ISSUE TITLE
How to use it without Visual Studio

### ISSUE THREAD

**Issue by MOZGIII** [Squirrel/Squirrel.Windows#338]
So, I'm making a C++ & Qt app, working with MinGW compiler and QtCreator. Is Squirrel.Windows usable for me? It seems like it is possible by design, however toolbelt is not very suit for non-Visual-Studio guys.

Can anyone describe the correct way of doing things?
I'm also looking forward to automate my build/deploy routine, so command line way would be the best I guess.

I managed to create my `.nuspec` file and a `.nupkg` from it.
What's left? It seems like I need to implement updates in my C++ program somehow now, and I also need to put my files somewhere online...

**Comment by paulcbetts** [comment]
> So, I'm making a C++ & Qt app, working with MinGW compiler and QtCreator. Is Squirrel.Windows usable for me? It seems like it is possible by design, however toolbelt is not very suit for non-Visual-Studio guys.

Absolutely - every Release includes zip file with the folder of executables you need - you just need to run `Update.exe --releaseify` on it, no Visual Studio is required. The way you'll implement updates in your app is by invoking the installed Update.exe (which is always guaranteed to be one directory above your EXE) and capturing the standard output.

**Comment by MOZGIII** [comment]
Oh, ok, so do I have to add any Squirrel-related files to my `.nupkg`? My "deploy package" now looks like this: http://c2n.me/3hrRU5r
Is there a way to somehow build an installer with Squirrel as well? So that user could click the link, run the installer and magicly be runnig the app.

This is my `/NuGet/ScreenerApp.0.0.1.nuspec`:
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2011/08/nuspec.xsd">
    <metadata>
        <id>ScreenerApp</id>
        <version>0.0.1</version>
        <authors>MOZGIII</authors>
        <description>Makes screenshots.</description>
    </metadata>
    <files>
        <file src="..\AppFiles\**" />
    </files>
</package>
```
I noticed it prints a lot of warnings about `.dll`s not being in `lib`. Is that ok with the way we use nuget?

As I can tell, the resulting layout of my installed app would be different from what it usually is when using an installer: it will install into a subdirectory of some sort...

Also, it seems like I have to have my Release directory persistent across version updates for Squirrel to build incremental updates?

**Comment by paulcbetts** [comment]
> Is there a way to somehow build an installer with Squirrel as well? So that user could click the link, run the installer and magicly be runnig the app.

Yep, "--releasify" will automatically build you a Setup.exe too.

> I noticed it prints a lot of warnings about .dlls not being in lib. Is that ok with the way we use nuget?

```
<file src="..\AppFiles\**" />
```

Needs to be:

```
<file src="..\AppFiles\**" target="lib\net45" />
```

> Also, it seems like I have to have my Release directory persistent across version updates for Squirrel to build incremental updates - which I don't mind, but can it still update the app when Release dir is gone and rebuild from scratch?

This is what `SyncReleases` is for, in a CI server you run it before `--releasify` and it downloads the last set of releases, so your CI server doesn't have to hold around any persistent state

**Comment by MOZGIII** [comment]
Thanks, I guess it didn't work before because of the wrong target location. I'll try it tomorrow.

**Comment by MOZGIII** [comment]
Works, thank you again.

**Comment by omykhayl** [comment]
@MOZGIII, how did you integrate UpdateManager into C++ app?

**Comment by MOZGIII** [comment]
What update manager are you referring to? I was using just the command-line API, and implemented the rest in C++.

**Comment by omykhayl** [comment]
Hi @MOZGIII,
I'm referring to this one: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/update-manager.md

Basically, it should check if there are new updates available, download and apply them. Am I missing something?

**Comment by MOZGIII** [comment]
No, you described it's responsibilities correctly. It's pretty straightforward to implement manually.
Personally, I'm currently moving to `.msi` based deployment, simply because it's what supported by Microsoft. Seems it's possible to even integrate `.msi` deployments with squirrel.
