### ISSUE TITLE
Update after a new version of Squirrel gets stuck.

### ISSUE THREAD

**Issue by Cyral** [Squirrel/Squirrel.Windows#339]
In my last application release, I updated the version of Squirrel.Windows, and pushed the update with no issues. It seems (as this has occurred twice), that the update _after_ an update the updates Squirrel, causes the updater to become stuck. On the updated version of Squirrel, I pushed an update, which goes to from 33% to 69%, jumps back to 33%, and then gets stuck on 69%. 

Last time this happened, I had to send a message to all clients with directions on how to manually update. Every update after this, using the same Squirrel version, worked fine, even the update to a newer version of Squirrel. It is the update after the newer version that causes issues.

I have tried editing the RELEASES file and deleting the delta, to force a full download, without any luck. Anyone got any ideas? If I can't solve this, everyone will be stuck on a version that is not able to update.

The SquirrelSetup.Log contains no information.

**Comment by amweiss** [comment]
You're probably hitting the same problem as a few others of us.
See:
#329 #328

https://github.com/Squirrel/Squirrel.Windows/pull/331 fixed it for me.

**Comment by Cyral** [comment]
So, once #331 is released, I should be able to use it to make a new release, upload that one, and use it for new installs, but all old versions are affected by the bug and will need to be manually re-installed with the new version?

**Comment by amweiss** [comment]
If you are in the same situation as me, yes.

**Comment by Thieum** [comment]
@shiftkey fixed by #331. This can be closed.
