### ISSUE TITLE
Create shortcut directly to update.exe

### ISSUE THREAD

**Issue by Nooth** [Squirrel/Squirrel.Windows#340]
I would like to create 2 shortcuts in start menu:
1. Pointing to uninstall: C:\Users\username\AppData\Local\app-id\Update.exe --uninstall -s
2. Forcing update in case of crashing mainapp. C:\Users\username\AppData\Local\app-id\Update.exe --update "\\newtwork_share\app-id"

It would be nice to have it in Update manager. Currently there's only 'CreateShortcutsForExecutable' option. 
We can create it manually - but it won't be managed automatically by Squirrel in case on uninstall etc.

**Comment by paulcbetts** [comment]
I don't think we're going to add this as a feature, sorry. However, Squirrel does expose an API to create arbitrary shortcuts (ShellLink) so this should be pretty easy to accomplish
