### ISSUE TITLE
Where to put event code?

### ISSUE THREAD

**Issue by bkCDL** [Squirrel/Squirrel.Windows#342]
I need a bit of clarification. I'm new to squirrel and somewhat new to .NET forms application development (though I've done asp.net for years). 

I'm migrating my ClickOnce app to be installed/uninstalled via Squirrel, mainly because I want to have some code triggered on uninstall and ClickOnce doesn't support that

I see the [Events](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/squirrel-events.md)  docs, and where to put SquirrelAwareApp in AssemblyInfo file. But where do I put the [C# code](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/squirrel-events.md#user-content-c-developers-do-this-instead) in my ClickOnce Visual Studio project? In ApplicationEvents.cs or something?

Any help or examples would be helpful.

Bryan

**Comment by paulcbetts** [comment]
You want to put that C# code as close to `Main()` as possible. Your app will exit as soon as the hooks complete, and you need to make those hooks run very quickly, because you have 15sec before it gets killed

**Comment by bkCDL** [comment]
Thanks! I ended up putting it in MyApplication_Startup in my ApplicationEvents.vb file.
