### ISSUE TITLE
App not updating in squirrel.dll v0.99.0.0

### ISSUE THREAD

**Issue by goldsmit409** [Squirrel/Squirrel.Windows#350]
Hi

I was previously using squirrel.dll v0.9.4.0 and it was working fine, but now after the nuget package update to .99 app is not updating, inside the appData\Local\AppName\packages the nupkg and delta files are created for the update but no entries added for in RELEASE file

i am calling update as below

 Task.Run(async () =>
            {
                using (var mgr = new UpdateManager(@"Path/to/Update/Url", "AppName"))
                {
                    await mgr.UpdateApp();
                }
            });

am I missing something?

**Comment by PushOrigin** [comment]
Make sure your Nuget.Core is up to date. I ran into a problem the other day where the Nuget.Core installed with the package was different from the one it was built with. You can either update through the package manager console or up the version range on the binding redirect. See my comment on issue #71.

**Comment by goldsmit409** [comment]
i tried changing binding redirect from 2.8.50926.602 to 2.8.60318.667 but still the same it will detect the updates but RELEASES file has no entires and it wont apply the update

**Comment by PushOrigin** [comment]
Which part of the redirect did you change? Honestly I didn't actually try changing the redirect, I updated nuget.core through the package manager. But it seems like it should work. You would want to change the oldVersion range to end at 2.8.6.60318.667. Leave the newVersion at 2.8.50926.602.

**Comment by PushOrigin** [comment]
My bad. I finally had a chance to check if the redirect works and as far as I can tell it does not. I'm working on a pull request to remove the references to 2.8.6 and replace them with 2.8.5. I'm trying to figure out what went on there that brought in 2.8.6.
