### ISSUE TITLE
No high DPI support for loading GIF

### ISSUE THREAD

**Issue by joaomoreno** [Squirrel/Squirrel.Windows#357]
It would be sweet to have smooth animated GIF on high DPI screens such as a Macbook's.

**Comment by paulcbetts** [comment]
Hm, wonder why this doesn't Just Work, do you have >1 monitor that has different DPIs?

**Comment by Thieum** [comment]
@shiftkey considering https://github.com/atom/atom/issues/15873#issuecomment-371903247 it seems to be resolved, this can be closed.
