### ISSUE TITLE
Error when installing when is already install

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#358]
Hello.

Did you have seen this behavior:
1. You install an app
2. You uninstall it
3. You try to install it again and it fails

It's because after you uninstall it the app is still running. (Related to #318)

So you have any plan for support it, or should we manage in the Uninstall event?

**Comment by ricardopolo** [comment]
@paulcbetts any comments?

**Comment by paulcbetts** [comment]
@ricardopolo Squirrel can't know how your application works so it can't know what to kill - you should shell out to `TaskKill.exe /F /IM Image.exe /T` in your uninstall hook
