### ISSUE TITLE
Error when running Setup.exe on machine without msvcr110.dll

### ISSUE THREAD

**Issue by hogjosh** [Squirrel/Squirrel.Windows#359]
Ran Setup.exe on a (non-dev) machine and was greeted with an error.
`The program can't start because MSVCR110.dll is missing from your computer. Try reinstalling the program to fix this problem`

I'm unsure of the best squirrel-y solution, but I imagine installing Visual C++ Redistributable on the target machine works in a pinch.

**Comment by theofanis** [comment]
I just had a user of our application report the exact same problem. Using Squirrel 0.9.4.

**Comment by locksmithdon** [comment]
I fixed this by including the VC++ runtime with the app. This is from my `.nuspec`

    <file src="VCRuntime\msvcp110.dll" target="lib\net45\msvcp110.dll" />
    <file src="VCRuntime\msvcr110.dll" target="lib\net45\msvcr110.dll" />
    <file src="VCRuntime\vccorlib110.dll" target="lib\net45\vccorlib110.dll" />

**Comment by paulcbetts** [comment]
Which program crashed, was it Setup.exe or Update.exe?

**Comment by oliveiragabriel07** [comment]
I had a user with the same problem when running **Setup.exe**. Using Squirrel 1.1.2.

**Comment by paulcbetts** [comment]
This is most likely not a Squirrel bug, this is that your application requires the MSVC redistributable and we're failing to run Squirrel hooks because of it.

**Comment by oliveiragabriel07** [comment]
I'm sorry for insist on this, but as I found (in this SO question: http://stackoverflow.com/questions/16167305/why-does-my-application-require-visual-c-redistributable-package) that VS 2005, 2008, 2010, 2012, 2013 and 2015 compilers link against msvcrt80.dll, msvcrt90.dll, msvcrt100.dll, msvcrt110.dll, msvcrt120.dll and msvcrt140.dll respectively, which are not shipped with windows.

So, developing with one of this VS makes the application dependent on VC++ redistributables.
One possible solution is to add specific VC++ runtime dependencies with the app, as suggested by @locksmithdon, but wouldn't it be nice if Squirrel allowed us to require Microsoft Visual C++ Redistributable package to be installed on user’s machine as a prerequiste?

**Comment by paulcbetts** [comment]
Squirrel doesn't need this DLL, your app does.
