### ISSUE TITLE
While installing app option to put shortcut in user autostart folder

### ISSUE THREAD

**Issue by mwave** [Squirrel/Squirrel.Windows#360]
Hello,
It would be nice to have an option to add the app in the autostart folder from the user:
*C:\Users\YOURUSER\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup*
*shell:startup*

Or registry based:
*REG ADD "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /V "My App" /t REG_SZ /F /D "C:\MyAppPath\MyApp.exe"*

What you mean?

Thanks for your cool project :-)

**Comment by dealproc** [comment]
can that start without logging into the system?

**Comment by paulcbetts** [comment]
> can that start without logging into the system?

No, that requires you to write to HKLM which you won't have privileges to do, not to mention, we always install to a user's directory

**Comment by mwave** [comment]
Hi, but HTCU should not be a problem.. Do you think this could be an option for squirrel? Would be nice :-)

**Comment by paulcbetts** [comment]
This is already an option: https://github.com/Squirrel/Squirrel.Windows/blob/7c7483137f1717d8c648fc36496b9949de272d79/src/Squirrel/IUpdateManager.cs#L18

**Comment by fancyfanta** [comment]
How to use it? @paulcbetts

**Comment by chingchang** [comment]
```
    private void OnInitialInstall(UpdateManager mgr)
    {
        mgr.CreateShortcutForThisExe();
        mgr.CreateShortcutsForExecutable("MyApp.exe", ShortcutLocation.StartUp, false);
        mgr.CreateShortcutsForExecutable("MyApp.exe", ShortcutLocation.Desktop, false);
        mgr.CreateShortcutsForExecutable("MyApp.exe", ShortcutLocation.StartMenu, false);
        mgr.CreateUninstallerRegistryEntry();
    }
```
