### ISSUE TITLE
Server reference

### ISSUE THREAD

**Issue by patrickdet** [Squirrel/Squirrel.Windows#361]
Hey,

I found the https://github.com/Squirrel/Squirrel.Windows/blob/master/specs/Implementation.md#production--server-side Spec but it hasn't been touched in more than half a year. Also found this config for IIS.

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <staticContent>
      <mimeMap fileExtension=".nupkg" mimeType="application/zip" />
      <mimeMap fileExtension="." mimeType="text/plain" />
    </staticContent>
  </system.webServer>
</configuration>
```

Does the Updater expect the files to be present at the provided `remoteReleases` URL or would it also follow a `301 MOVED PERMANENTLY` so that when it requests a `.nupkg` it would get a 301 and URL to the `.nupgk` on Amazon S3?

**Comment by paulcbetts** [comment]
The updater just uses standard HTTPS, you definitely don't need IIS - this is just if you _happen_ to be using IIS already. I'm 95% sure we'll follow redirects and if we don't it's a bug
