### ISSUE TITLE
Pass arguments to Update.exe

### ISSUE THREAD

**Issue by Mzartek** [Squirrel/Squirrel.Windows#367]
Currently for launching an application with Update.exe, we need to create a shortcut with the following target:

Update.exe --processStart MyExe

But is there a way to pass arguments to the command?

For example, i tried this:

Update.exe --processStart MyExe arg1 arg2

But saddly it's not working.

Thanks!
Kevin

**Comment by stajs** [comment]
I haven't tested the idea at all, but have you tried quoting your args? E.g.:

```
Update.exe --processStart "MyExe arg1 arg2"
```

**Comment by Mzartek** [comment]
Nice idea!
But sadly it didn't work.

**Comment by stajs** [comment]
I found there is an option to pass them here: 

https://github.com/Squirrel/Squirrel.Windows/blob/0d1250aa6f0c25fe22e92add78af327d1277d97d/src/Update/Program.cs#L123

```
Update.exe --processStart Malone.exe --process-start-args "huh say wut"
```

I then used `Environment.GetCommandLineArgs()` to retrieve them, and for my simple testing purposes spat them out to a textbox:

![image](https://cloud.githubusercontent.com/assets/2253814/8390514/a92d5f5c-1cec-11e5-8e07-e66c96d8097a.png)

@paulcbetts some commands/options that are in code, aren't shown when you run `Update.exe` without any parameters (to see the available commands and options):

![image](https://cloud.githubusercontent.com/assets/2253814/8390553/9e36c344-1ced-11e5-8729-b3fc6939bf65.png)

Worth raising an issue for?

**Comment by Mzartek** [comment]
Oh thx it works like a charms!
