### ISSUE TITLE
What is the story behind update.com?

### ISSUE THREAD

**Issue by potentZilla** [Squirrel/Squirrel.Windows#369]
I have found the update.com file was added in reference to the issue #27 in commit SHA: 9862654fb114fdb5f4b29a25f166ddfcb3d6560c 

I have been unable to find out how the update.com under the src\Update\ was actually created.  Is it possible to include in the repository how this file was created.  The concern is forward maintenance and how this file is in place to resolve a known issue but how the solution was derived is not explicit or how the update.com file actually accomplishes the solution.

I have not see .com files in a long time and it was interesting to see one in this project.

**Comment by paulcbetts** [comment]
It's a long story, but basically the idea is that update.com makes update.exe act like a Console-Based Application™ but only if executed from a console - if executed from a UI, it acts like a Windows-based app (i.e. doesn't allocate a console window)

**Comment by CSharpFan** [comment]
How is this `update.com` built?

**Comment by Unit2Ed** [comment]
It'd be useful to know more about this; I'm in a position where I've got to make some tweaks to the install process, and there's very little documentation that I can find about update.com.
