### ISSUE TITLE
The story behind update.zip at src/Setup/update.zip

### ISSUE THREAD

**Issue by potentZilla** [Squirrel/Squirrel.Windows#370]
From the initial commit SHA: 4b70bdcd4fe5bc74240bbf698409340d637ee741 the file is described as a dummy payload which will echo the command line.  
It is not clear where this file came from or how it was created.  Would it be possible to document how to create this dummy file or where it came from?  Where is the source code that was used to compile the update.exe file?

**Comment by paulcbetts** [comment]
I don't think there is any source code available for it (even on my computer). It's literally just a call to `MessageBox.Show` then it exits

**Comment by potentZilla** [comment]
That is what I was thinking.  Nothing special and possibly easy to replace
with anything.  Potentially something even during build time.

It might need its own separate issue but the update.zip/update.exe is the
file that Avast flags as a threat and perhaps changing this file to be
generated will resolve some of the false positives squirrel.windows keeps
getting.

the nuget package is also flagged as a threat.  I know code-signing will
resolve this problem but there was an anomaly I noticed while testing
self-signed code-signing that I will explore.

Avast business and not being in control of the AV system does make it a
challenge to have the nuget package on the workstation when it is flagged
as a threat even if as a false positive.

I understand a workaround would be to code-sign the nuget file but that
would only address my situation and not globally.
