### ISSUE TITLE
Antivirus vs src/Setup/update.zip->update.exe

### ISSUE THREAD

**Issue by potentZilla** [Squirrel/Squirrel.Windows#371]
I am becomming convinced some problems with squirrel.windows and Antivirus software could be due to the dummy update.exe in the update.zip in the repository.  It seems the Antivirus software has the update.exe in the threat signature database.  Any file it finds it it is flagged as a threat. Note, the threat isn't the setup.exe but the update.exe it finds inside the setup.exe.

I am thinking if the update.exe and update.zip were part of the compile process that would help reduce the flagging of a file with the current update.exe as a Threat.

When setup.exe is packed with a nuget package using the --releasify the Antivirus does not flag the setup.exe.  

The setup.exe file that I build with nuget packages is not identified as a threat.
The setup.exe file that was created from hello.squirrel https://github.com/mkoertgen/hello.squirrel/ is not identified as a threat. 
The setup.exe that is from the squirrel.windows nuget package 0.99.1.1 is detected as a threat because it contains the dummy update.exe
The setup.exe compiled from the squirrel.windows source code is detected as a threat because it contains the dummy update.exe
A failed releasify setup.exe is detected as a threat.
The update.zip in /src/Setup/ is detected as a threat.

Attached are links to the virustotal.com scans for the different files.
This is the setup.exe that is found in the nuget package 0.99.1.1  This setup.exe file has the dummy update.zip/update.exe in it.
3 out of 57 detected the file as a threat
https://www.virustotal.com/en/file/baabdf0adc0e7735cc9fe0428d63734bd78bbeba8042837bbf1e5584ff029a19/analysis/1434652522/

This is the dummy update.exe that is in the squirrel.windows source code repository update.zip.
8/57 identified the file as threat
https://www.virustotal.com/en/file/f0120ddc2a9c184ec6df2c980f03cb5807cdb37a6367a6f37ca0d183916de520/analysis/

This is the update.zip with the same dummy update.exe as above but scanned as the zip.
https://www.virustotal.com/en/file/c1172519c6b17577f91a1d074b6223e59c240ccb708e911e5cab303e365fdade/analysis/1434652605/

This is the setup.exe that is compiled from the hello.squirrel example found in github.com.  It is built with squirrel.windows nuget package updated to the latest 0.99.1.1
0/57. none of the antivirus scanners identified the file as a threat and the file is not code-signed.
https://www.virustotal.com/en/file/dcb78a4ada366050311314e9baea6b03bb278ef465624447097231bef6614fd1/analysis/1434652637/

The following screenshot is from my workstation where I scanned my test squirrel.windows tests, hello.squirrel, squirrel.windows source code repository with built output, the zip of that source, and the nuget package unpacked.

The Avast scan result has identified every file containing the dummy update.zip/update.exe as containing a threat.  None of the squirrel.windows setup.exe files I generated or the hello.squirrel setup.exe has been flaged as a threat.  None of the files have been code-signed.

Note from the screenshot that the result is explicitly pointing out that the update.exe inside the setup.exe is the threat.  Not the setup.exe itself.

![image](https://cloud.githubusercontent.com/assets/389969/8239421/547ba31a-15c1-11e5-94b4-82bb3387c0fa.png)

Below is a screen shot of all setup.exe files that were included in the scan above.  Each of these directories had squirrel.windows --releasify generated content that was not code-signed.

![image](https://cloud.githubusercontent.com/assets/389969/8239571/4c155c10-15c2-11e5-9cc2-8c2c729c13b8.png)

I wanted to initially post this as a lead into the issue.  I do have a remaining test at replacing the dummy update.zip with something else and see how that changes the detection with the AV scans.

**Comment by potentZilla** [comment]
I have evaluated what happens if the dummy update.zip is replaced with a different update.exe file.  When a different update.exe is used the newly compiled setup.exe is not identified as a threat.

A screenshot of the scan will show that the unit test\fixtures setup.exe is still identified as a threat because that file is static and is not updated during the build process.  This file contains the original dummy update.zip/update.exe that is flagged as a threat.

Missing from the scan results is the Setup.exe that was compiled using a new update.zip.  Also missing are the build artifacts /obj/Debug/Setup.res.  Even the update.zip was not flagged as a threat.
![image](https://cloud.githubusercontent.com/assets/389969/8240007/55832180-15c5-11e5-989e-fbee5f7bbed0.png)

When the newly built setup.exe is uploaded to virustotal.com it hits 0/57 https://www.virustotal.com/en/file/d4baa9aecb27faa33a600a3e7858bf0f3c02790e8c79560f0933709ab220edd2/analysis/1434655358/ none of them find the file as a threat.

Replace the update.zip with a component that has a project that builds the dummy update.exe and have that pulled into the setup.exe build would at least eliminate the hits that use the dummy update.exe as signature.  My test was with an empty c# WPF form.  

Although, maybe releasify should have logic to prevent the need for a dummy executable file and not produce a setup.exe that would only be known to have failed if it was executed.

Alternatively if this is used for unit testing the goals of the unit test probably could be met in a different method.

**Comment by paulcbetts** [comment]
At the end of the day, Update.exe is a program that:

1. You click it
1. It copies executable binaries to another intermediate location, and
1. Runs them

What does that sound like? It turns out there's not much difference between Squirrel (or any other installer that installs to the user's profile) and malware, except that our installation is consensual with respect to the user. For development, people just need to stop using Avast and use MS Security Essentials instead, which has never flagged us. 

For shipping an application, signing your application and installer with a Code Signing Certificate will solve this problem and AV vendors will trust you.

**Comment by potentZilla** [comment]
Paul,

We might not be discussing the same "update.exe" here.  I am talking about the file https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Setup/update.zip 
This file https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Setup/update.zip has the update.exe that Avast and the other AV don't like.

The update.exe that is produced from the project https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Update.csproj is not a problem.

the setup.exe that is produced when I execute squirrel.exe (update.exe) --releaseify is not a problem because the dummy update.zip is replaced with my nuget package.

There are alternative solutions to the problem that does not require all developers to switch AV or stop using Avast.  Auto generate the update.zip/update.exe as part of the solution.  Trust me I would stop using Avast if I had the choice. I have the freedom for everything else but the Avast software is pushed onto all workstations via AD group policies.  

The screen shots of the setup.exe was not ones that contain the workhorse update.exe but all contain the dummy update.zip/update.exe that is only there to display a MessageBox.Show of the command line parameters.

 I do understand that if i code-sign the setup.exe that contains the dummy.zip/update.exe it will be trusted by the AV.  I have actually already tested this. Avast does not flag a file it had just identified as a threat once is signed.

If it would help I can make an example of it in a fork or issue a PR.

**Comment by potentZilla** [comment]
I have submitted false positive for the update.zip/update.exe to Avast and it appears it is in the dictionary to ignore this file.

Right now.
Avast still flags nuget packages 0.8.5 and lower tools\setup.exe as threat.
Avast does not flag packages greater than 0.8.5.  The latest package does not flag as a threat anymore.
The source code \test\fixtures\Setup.exe is still flagged as a threat.

**Comment by potentZilla** [comment]
The dummy update.zip/update.exe has zero information filled out for company name and publisher which some AV use to flag files as suspect.  Another method to reduce the suspect signature would be to fill in some of the version and file metadata for this dummy file.
