### ISSUE TITLE
Squirrel-based Setup.exe fails Windows App Certification test

### ISSUE THREAD

**Issue by danielkornev** [Squirrel/Squirrel.Windows#375]
Specifics:

Install to the correct folders test

* **FAILED**
**Install to Program Files**
Error Found: The install to Program Files test detected the following errors:
Program Zet Universe Insider Preview for Windows fails due to install location C:\Users\Daniel\AppData\Local\Zet.
Impact if not fixed: Native apps e.g. 32 and 64 bit must be installed to the %ProgramFiles% folder by default, note that 32 bit apps installing on x64 versions of Windows must be stored under %ProgramFiles(x86)%. Storing program files in another folder can cause access and security problems for the user.
How to fix: Write the files to the correct folders. See link below for more information: 
Working with Known Folders

* **FAILED**
**Loading apps on Windows startup**
Error Found: The Windows startup app loading test detected the following errors:
C:\ProgramData\SquirrelMachineInstalls\Zet.exe
Impact if not fixed: Apps that load at startup may cause undesirable effects such as, displaying unwanted pop-ups, reducing battery life, or causing the computer to become less responsive.
How to fix: Follow the best practices for the on/off transition. See link below for more information:
Windows On/Off Transitions Solutions Guide

Adhere to system restart manager messages

* **FAILED**
**Don't block reboot**
Error Found: The don’t block reboot test detected the following errors:
No new shortcuts were identified.
Some apps display EULAs, auto update, registration forms, and, or other prompts for user interaction. If your app does this, it could be reported as non-compliant with the restart requirement. If any of these files are reported for this reason, disable or dismiss all such modules and restart testing on a clean OS.
Impact if not fixed: If an app doesn’t shut down gracefully, customers can lose data when the OS forces the shutdown. Not responding to system shutdown requests also slows the shutdown/reboot process, which makes the entire system appear slower.
How to fix: The app must respond to system shutdown and end session messages as quickly as possible. See link below for more information: 
Application Shutdown

**Comment by danielkornev** [comment]
Overall, I'm super satisfied with Squirrel. Of all installers we've used in the past three years, this is clearly the best one, especially with its auto-update technology.

We used the Windows App Certification check and were quite surprised that this check didn't like Squirrel. Why is it so?

**Comment by paulcbetts** [comment]
You selected the wrong radio option before you ran it, you need to say that it is installed to the user account, not take the default (machine wide)

**Comment by danielkornev** [comment]
First of all, sorry for coming so late to this thread - got into emergency, and then, coincidentally, our house was broken into, not the best time to work :(

Anyways, thank you for your answer, Paul. 

One more thing: 

Is the second failed test a real problem or not?

Loading apps on Windows startup

__FAILED:__
Error Found: The Windows startup app loading test detected the following errors:
 C:\ProgramData\SquirrelMachineInstalls\Zet.exe

 Impact if not fixed: Apps that load at startup may cause undesirable effects such as, displaying unwanted pop-ups, reducing battery life, or causing the computer to become less responsive.
 How to fix: Follow the best practices for the on/off transition. See link below for more information:
 Windows On/Off Transitions Solutions Guide

**Comment by paulcbetts** [comment]
It's not a problem, WACK is running your per-user installed app under elevated UAC, so it's installing machine-wide

**Comment by danielkornev** [comment]
Oh, I see. Thank you a lot!

Squirrel rocks!!!

Sent from my Windows Phone
________________________________

**Comment by InnovaTex** [comment]
Did you ever manage to get the application completely through the wack test tool? We are trying to but we cannot get passed the following error:
The don’t block reboot test detected the following errors: No new shortcuts were identified.

We tried all kinds parameters for machine-wide installation but it cannot get passed this error. Any ideas?
