### ISSUE TITLE
Squirrel executes the wrong version of the app

### ISSUE THREAD

**Issue by aeschli** [Squirrel/Squirrel.Windows#376]
I have VS Code installed, which uses this framework. Through a series of successful updates, I ended up with the following in my `%APPDATA%\Code`:

![image](https://cloud.githubusercontent.com/assets/6461412/8373985/e852856e-1bf1-11e5-980b-71a429d21228.png)

All versions except `0.1.38` and `0.1.39` are empty with a `.dead` file inside.

Running VSCode's shortcut (`C:\Users\martinae\AppData\Local\Code\update.exe --processStart Code.exe`) starts version `0.1.38`. I would expect it to start `0.1.39`. Especially since it appears that the shortcut was correctly created with the `0.1.39` update:

![image](https://cloud.githubusercontent.com/assets/6461412/8374187/b1349426-1bf3-11e5-80e7-3d447a57a32a.png)

Manually starting `0.1.39` seems to work, so the update indeed worked successfully.

My `SquirrelSetup.log` doesn't show me a lot of information when executing:

```
Program: Starting Squirrel Updater: --processStart Code.exe
Program: Want to launch 'C:\Users\martinae\AppData\Local\Code\app-0.1.38\Code.exe'
Program: About to launch: 'C:\Users\martinae\AppData\Local\Code\app-0.1.38\Code.exe': 
```

But I did find this: [SquirrelSetup.log](https://gist.github.com/aeschli/d2ce133bece90a7009d7). Looks like the whole thing stopped when trying to delete `0.1.37`, leaving `0.1.38` intact behind. Might that be the reason why `Update.exe` is executing that version instead of the latest?

**Comment by aeschli** [comment]
Manually deleting the 0.1.38 folder and restarting VSCode correctly opens Code.exe from the 0.1.39 folder.

**Comment by paulcbetts** [comment]
This is a bug in VS Code, they're doing the Single Window thing but not checking versions first before handing off to the existing window

**Comment by joaomoreno** [comment]
@paulcbetts can you clarify? What do you mean by the Single Window thing?

**Comment by paulcbetts** [comment]
So, if you try to set up a situation similar to Atom, where running the app a 2nd time will just focus the currently running app and exit, you have to be careful:

1. User opens the app at v1.0
1. Squirrel wakes up, background updates you to v1.1. 
1. However, since Squirrel never interrupts users' work, v1.0 is still running
1. User opens the app again, we load a new instance with v1.1
1. v1.1 says "Oh cool! There's already an instance running, pass it off to them"
1. Currently running app is still v1.0

**Comment by joaomoreno** [comment]
Right. Notice that that doesn't seem to be what @aeschli reported.

Without having VSCode running, the `C:\Users\martinae\AppData\Local\Code\update.exe --processStart Code.exe` shortcut seems to be executing an older version than the latest he has installed.

**Comment by paulcbetts** [comment]
Hm, not so sure - @aeschli, is it possible that VSCode was running already when you hit the shortcut?

**Comment by joaomoreno** [comment]
I was sitting beside him this morning debugging the issue. :wink:

**Comment by paulcbetts** [comment]
Oh! Well in that case I'm out of ideas :). I'd try to capture that directory as a repro, then build your own Update.exe and step through

**Comment by joaomoreno** [comment]
Makes sense, will report back if there's more info.
