### ISSUE TITLE
Unable to build with squirrel

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#377]
Up until now, squirrel has been working really well.  Howerver, as of today, in visual studio (both 2015 and 2013) when I run that this command line in this particular project (and only in this project, it is working correctly on another project) it just displays a new line with: >> on it.
PM> squirrel --releasify "..\..\nuget\[packagename].1.0.242.nupkg" -g " C:\cw\src\ajax-loader.gif" -n "/a /f C:\cw\src\certs\filename.pfx /p [pwd] /t http://tsa.starfieldtech.com" -r "C:\cw\UmReleases

The output is then:
>>  

And then if I run the same command line again:
>>  squirrel --releasify "..\..\nuget\packagename.1.0.242.nupkg" -g " C:\cw\src\ajax-loader.gif" -n "/a /f C:\cw\src\certs\filename.pfx /p [pwd] /t http://tsa.starfieldtech.com" -r "C:\cw\UmReleases

I get the following error messages
squirrel : System.ArgumentException: Illegal characters in path.
At line:1 char:1
+ squirrel --releasify "..\..\nuget\packagename.1.0.242.nupkg" -g " C:\cw\src\ajax ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Argument...acters in path.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   a
t System.IO.Path.GetFullPathInternal(String path)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String 
signingOpts, String baseUrl, String setupIcon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)

If I exit visual studio 2015, and load 2013 the same problem happens. I've upgraded from 99 to 99.1, apart from rebooting my machine have no idea what to do.

As I say, squirrel is working fine in another visual studio project.

Any ideas?

Thanks,
Stefan

**Comment by paulcbetts** [comment]
Could you possibly have put smart quotes in somewhere?

**Comment by stefanolson** [comment]
@paulcbetts Because I haven't yet automated this process, I manually copy and paste the command into visual studio, and I had neglected to include the final " on the -r parameter when I pasted.  So, now it works.  Is there a way that squirrel can check for such invalid input?

Thanks,
Stefan
