### ISSUE TITLE
Exit Code 998 in Windows 7

### ISSUE THREAD

**Issue by allanrsmith** [Squirrel/Squirrel.Windows#379]
We have tested our machine-wide install on Windows 7, Windows 8 and Windows 10 Preview.  All machines are 64-bit with >8GB RAM.  On two Windows 7 boxes the "Setup.exe --machine" process exists with code 998. On the Windows 8 and Windows 10 machine we had success.

Any reason why this would be?  I can provide more information as necessary.

**Comment by paulcbetts** [comment]
@allanrsmith Can you look in `C:\ProgramData` for a Squirrel folder with a log file in it?

**Comment by allanrsmith** [comment]
There is none. We have been looking for the SquirrelMachineInstall folder but it doesn't even get that far.

**Comment by allanrsmith** [comment]
Double-clicking the Setup.exe file from Windows Explorer installs the app in the local app data fine, but once when we try it from a shortcut with --machine, PowerShell, Cmd (elevated), it just exits and doesn't install anything.

**Comment by allanrsmith** [comment]
Investigating this some more.... is the DACL correct for the ProgramData\SquirrelMachineInstalls directory that needs to get created?  Is there some weird conversion bug on 64-bit machines from the string representation?

**Comment by allanrsmith** [comment]
@paulcbetts it appears the SecurityDescriptorString does not work on Windows 7 x64.  What are the bare minimum permissions needed on the SquirrelMachineInstalls folder to have this work?  I would like to move away from using a string, and instead use the constants that are part of the SDDL/ACE headers.

**Comment by paulcbetts** [comment]
It should have the same permissions as Program Files

**Comment by allanrsmith** [comment]
So the following applies to Windows 8+ as far as an ACE:
"(A;;0x1200a9;;;AC)(A;OICIIO;GXGR;;;AC)"
The AC SID is for the "ALL APPLICATION PACKAGES" account which does not exist in Windows 7.

Pull Request following shortly

**Comment by allanrsmith** [comment]
PR merged with the fix. Thanks!
