### ISSUE TITLE
(Sorry!!) Add an option to install to Program Files for those apps that really need it

### ISSUE THREAD

**Issue by Pinpickle** [Squirrel/Squirrel.Windows#382]
I hate to propose this feature, I really do.

But I'm currently working on an application with `uiaccess="true"` which means it has to run in Program Files.

I really love the installing experience for Squirrel - that being no experience at all! I want a similar experience for this app - even if there is a UAC dialog to go through.

So is it possible to add an option to `--releasify` that allows people to do this? Maybe make it more useful by allowing an arbitrary location, though I'm unsure how much value that will add.

From what I can tell, #308 did some of the groundwork to make this possible.

I don't know how this will fit in with the updating process. I think a caveat could be that automatic updating just wouldn't work in these situations.

Any documentation for this feature, should it exist, should advise users at all costs *not* to use it unless it is completely unavoidable.

**Comment by paulcbetts** [comment]
This will never happen, sorry - you're going to have to use a different installer technology (and you're totally right that `uiaccess="true"` is one of the only legit conditions where this is a True Dealbreaker).

One thing you could do is on the first-run of your app, copy over your `uiaccess=true` helper to Program Files, but this gets Tricky (you can't do this in a Squirrel hook because if the user doesn't answer the hook in 15secs or so, it gets killed).

**Comment by Pinpickle** [comment]
Well at least I have a definitive answer now! I'll look for a different solution for this but I'll definitely use Squirrel when I've got a project that doesn't play dirty like this.

**Comment by Pinpickle** [comment]
> One thing you could do is on the first-run of your app, copy over your uiaccess=true helper to Program Files, but this gets Tricky (you can't do this in a Squirrel hook because if the user doesn't answer the hook in 15secs or so, it gets killed).

I actually ended up doing this because every other solution was pretty terrible. It works well, the only disadvantage being that the app isn't removed from program files on uninstall yet.

**Comment by malipetek** [comment]
Why this is something undesirable? I used nsis for doing that. It seems more proper way that a program sitting in program files right?

**Comment by paulcbetts** [comment]
@malipetek I don't want to explain this for the three millionth time, please read through the repo and existing issues if you want to understand more.

**Comment by malipetek** [comment]
@paulcbetts Very sensible proposal. I didnt think its something so disclosed. Sorry for infollution, you may delete this and above issue comments as these out of context actually.

**Comment by Neustradamus** [comment]
@anaisbetts: Can you reopen this closed ticket?
It is not solved.

It must be possible like all good softwares to select where the user/admin want to install.
- Program Files
- Program Files (x86)
- A choice from the user/admin
- Shortcut for the Current User
- Shortcut for All Users
