### ISSUE TITLE
Squirrel.exe doesn't wait for all processes to finish before exiting

### ISSUE THREAD

**Issue by ChaseFlorell** [Squirrel/Squirrel.Windows#384]
I'm trying to rename my setup.exe to something more useful, and in doing so, I've discovered that even after squirrel.exe exits, there are other processes handling the files.

I'm not in love with the fact that I need to `Start-Sleep` in order to rename my file.

    Exec {
        Squirrel.exe --releasify "$currentDir\website\MCA.$version.nupkg" `
                     -r "$appFilePath" `
                     -i "$currentDir\website\MCAIcon.ico" `
                     -g "$currentDir\website\SplashScreen.gif" `
                     -n "/a /f $currentDir\$($es.certificates.codeSigning.name).pfx /p $($es.certificates.codeSigning.password)"
    }
    # Even though squirrel.exe has exited, the setup.exe doesn't exist yet... Must wait
    while(!(Test-Path "$appFilePath\setup.exe")){
        Start-Sleep -s 1
    }
    # even though the setup.exe now exists, it's still not generated based off of the nupkg... must wait moar.
    Start-Sleep -s 5
    Rename-Item "$appFilePath\setup.exe" "$appFilePath\MCA.exe"

Is there a way to force squirrel.exe to wait for all processes to finish before exiting?

**Comment by paulcbetts** [comment]
> Is there a way to force squirrel.exe to wait for all processes to finish before exiting?

Start `squirrel.com` instead
