### ISSUE TITLE
Can squirrel.windows create a web installer (.application)?

### ISSUE THREAD

**Issue by ChaseFlorell** [Squirrel/Squirrel.Windows#385]
With clickonce there's a way to generate a web installer that begins the download and executes the setup.exe with one click.

Right now I have our app working with squirrel, and it generates the setup file, but the end user still needs to download the exe, and that can cause warnings in the browser.

Is there a baked in way too generate a web installer? If not, is there a recommended way?

**Comment by paulcbetts** [comment]
Not really, this is a sneaky secret handshake between IE and ClickOnce that is built into the OS, and is ClickOnce-only :(

**Comment by zh99998** [comment]
could Squirrel.Windows build a normal web installer? a small .exe, and download application from update url.

**Comment by paulcbetts** [comment]
@zh99998 You're certainly welcome to do this yourself, but I don't think we're going to pursue this
