### ISSUE TITLE
Update.exe is missing

### ISSUE THREAD

**Issue by joaomoreno** [Squirrel/Squirrel.Windows#386]
From a VSCode user

> I ran into this problem several times before tracking it down. Here's the sequence:
> - Uninstall VSCode
> - Without rebooting, install VSCode
>
> Result: Everything seems fine. VSCode runs OK.
> Sometime later reboot your machine.
> Result: Update.exe gets deleted and you'll get the error:
> '"C:\Users\Bret\AppData\Local\Code\bin\\..\Update.exe"' is not recognized as an internal or external command,
> Note that that other files are still there. Just this one is gone.
> That's problem # 1.

> How does one get out of this situation? I attempted before, multiple times, by trying once again to reinstall VSCode. But at this point uninstalling VSCode fails completely (it just does nothing if you attempt to uninstall, while Update.exe is gone).
> That's problem # 2.

> The only way I could get it to reinstall before is by installing new, then uninstalling, the installing again. > That seemed to work for a while. But then the problem just repeated itself after the next reboot.

**Comment by marwanhilmi** [comment]
I am noticing this happen on some user's systems as well - it appears for whatever reason after a reboot, `Update.exe` disappears and desktop shortcuts pointing to it break. Is there any reason for `Update.exe` to just disappear - perhaps getting swept up by Windows Defender or something? I asked users to check their AV logs but it never appears to find/flag `Update.exe`, it simply disappears. 

Any ideas - have you seen this behavior @paulcbetts ?

**Comment by paulcbetts** [comment]
We've heard a few reports of this too and have never been able to track down why :(

**Comment by ionoy** [comment]
Same problem here. 
Created clean Windows 7 SP1 virtual machine and installed my app. After the reboot Update.exe is missing.

**Comment by thughes** [comment]
Just chiming in that I saw this once on a Windows 10 virtual machine after rebooting. The `Update.exe` file actually existed, but it was zero bytes.

**Comment by Thieum** [comment]
:+1:  Happened to some of my users too on Windows 7 x86 - updates on network share. Nothing appears in antivirus.

**Comment by wballet** [comment]
Hi @paulcbetts 

I think this explains the mysterious disappearance of our `update.exe`. After I uninstall my application, the registry key **HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\PendingFileRenameOperations** (https://technet.microsoft.com/en-us/library/cc960241.aspx) contains the following entries:

```
...
\??\C:\Users\<user>\AppData\Local\<app>\Update.exe

\??\C:\Users\<user>\AppData\Local\<app>

...
```
The entries in this registry key are renamed after rebooting, but an empty line after an entry will delete that entry.

Now, if I uninstall my application and subsequently reinstall it, these entries are not cleaned up and will effectively remove the `update.exe` on the next reboot.

Hope this helps...

**Comment by UVLabs** [comment]
Yep...gets deleted...scared to go into production

**Comment by juturu** [comment]
@paulcbetts, following is one scenario where i hit this bug.

Scenario:
1. Install the app
2. Uninstall the app in such a way uninstall fails with following errors
2015-10-14 09:53:39> Utility: safeDeleteFileAtNextReboot: failed - %localappdata%\Foo\Update.exe - 5
2015-10-14 09:53:39> Utility: safeDeleteFileAtNextReboot: failed - %localappdata%\Foo\app-0.x.x\content_resources_200_percent.pak - 5
3. Install the app again
4. Restart the machine

You will hit update.exe missing and the files for which safeDeleteFileAtNextReboot failed. 
So, on reinstall of the app (step 3) we should undo the file deletion on next reboot.

**Comment by paulcbetts** [comment]
Yeah, so, it sounds like if users incorrectly run Setup.exe as an Elevated UAC account, we'll end up actually succeeding at the MoveFile call, which causes Problems

**Comment by paulcbetts** [comment]
This is fixed in #466 by removing the MoveFile call

**Comment by mgnslndh** [comment]
I've seen this issue with a missing update.exe using `<package id="squirrel.windows" version="1.4.0" />  `

This was in production so I'm guessing the machine has not been rebooted since uninstall/install during last deployment, until today.

**Comment by Helpbot643** [comment]
do not do anything he says this is caused do to discord people think its a virus but no it is not it is whats used to launch discord on startup and even launch discord in genral and its a github idk why lol but i thought it was bad too
