### ISSUE TITLE
Signing of Setup.exe fails through Squirrel

### ISSUE THREAD

**Issue by Pinpickle** [Squirrel/Squirrel.Windows#389]
When using `--releasify` with `-n` and a Digicert certificate, I get an error. It signs the executables inside the package just fine, but the final installer file, `Setup.exe`, has an error thrown when Squirrel tries to sign it

```
squirrel : System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: [...]\packages\squirrel.windows.0.99.1.1\tools\signtool.exe sign /t 
http://timestamp.digicert.com [...]\Releases\Setup.exe'
```

Full stack trace:

```
   at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Failed to sign, command invoked was: '[...]\pcr-touch\packages\squirrel.windows.0.99.1.1\tools\signtool.exe sign /t http://timestamp.digicert.com 
[...]\Projects\pcr-touch\Releases\Setup.exe'
   at Squirrel.Update.Program.<signPEFile>d__93.MoveNext()<---
```

I can get around it at the moment by signing the file manually, and the command that is specified that fails with Squirrel runs successfully when I run it manually (with quotes around paths).

There's no more information other than the stack trace in the Squirrel log file.

**Comment by naishx** [comment]
I had the same issue this is because you have blanks in the outpath?

The root of the problem:

Tuple<int, string> processResult = await Utility.InvokeProcessAsync(exe,
                String.Format("sign {0} {1}", signingOpts, exePath), CancellationToken.None);

should be changed to this:

Tuple<int, string> processResult = await Utility.InvokeProcessAsync(exe,
                String.Format("sign {0} \"{1}\"", signingOpts, exePath), CancellationToken.None);

**Comment by paulcbetts** [comment]
@naishx Good catch, can you submit a PR?

**Comment by naishx** [comment]
@paulcbetts i fixed the issue. I hopefully did everything in the right way. This was the first time working with GitHub.

**Comment by paulcbetts** [comment]
@naishx Yep! Good work!

**Comment by Franklin89** [comment]
I am getting this exact error when I am trying to run the code signing from my _deploy.ps1_ script used in octopus. I use squirrel.exe with the -n parameter. If i create a release via octopus and then deploy my package and run the deploy.ps1 which creates my squirrel installer, squirrel crashes. If I then call the exact same powershell manually it works. Any idea what the problem could be?

Thanks for getting back

`System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\OctopusTentacle\Applications\Test\Tridoo.Client\1.5.0-automate-deploym0024\tools\Squirrel\signtool.exe sign /a /f PersonalCodeSigningCertificate.pfx /p ******** /fd sha256 /tr http://timestamp.digicert.com /td sha256 C:\Windows\system32\config\systemprofile\AppData\Local\SquirrelTemp\tempa\lib\net45\MLSoftware.Tridoo.Client.exe'`

**Comment by shiftkey** [comment]
@Franklin89 my gut feeling is that you should set the full path to `PersonalCodeSigningCertificate.pfx`

**Comment by Franklin89** [comment]
Tried that...
Did not work.

Could it be because octopus is running as a service using the SYSTEM account?

**Comment by Franklin89** [comment]
I found the problem to be that the Octopus Tentacle was running under SYSTEM which would not let me use the signtool.exe

**Comment by kkaung** [comment]
This is happening to me also but I am using powershell.  I just did a normal `--releasify myApp.nupkg --no-msi`.  Then tried to sign the Setup.exe in `Releases` folder and got this error.

```
PS C:\DotNet\SkyWire.Pos> .\packages\squirrel.windows.1.7.8\tools\signtool.exe sign /a /f company.pfx /p mypassword Releases\Setup.exe
Done Adding Additional Store
SignTool Error: SignedCode::Sign returned error: 0x800700C1
        Either the file being signed or one of the DLL specified by /j switch is not a valid Win32 application.
SignTool Error: An error occurred while attempting to sign: Releases\Setup.exe

Number of errors: 1
```

**Comment by stuartjsmith** [comment]
I know this is almost three years old now, but I have the same problem as @kkaung ! Did you ever resolve this?

**Comment by kkaung** [comment]
> I know this is almost three years old now, but I have the same problem as @kkaung ! Did you ever resolve this?

@stuartjsmith we resolved this but I don't recall what we did.  This might have been a cert issue.  I can tell you that one of the issues we had was with our cert not imported on our AppVeyor vm instance.
