### ISSUE TITLE
Execute NGen after an update

### ISSUE THREAD

**Issue by Mzartek** [Squirrel/Squirrel.Windows#392]
Hello!

I started to use Squirrel for getting an update engine in my app, but currently i've got a problem.

When i install the application (i use my own installer with WiX), the installer use NGen to optimize the binary in order to get a faster launch. But when an update is downloaded and installed, the binary of the new package is not optimized, so the idea would be to use NGen right after the installation of the update. But the problem is that NGen needs admin rights and my app does not have this privilege. So i'm stuck at this point.

Someone have workaround?

Thanks for the help!

**Comment by paulcbetts** [comment]
You basically can't do this, NGen sucks :(

**Comment by shiftkey** [comment]
Maybe [some day](https://github.com/dotnet/coreclr/blob/master/src/inc/ngen.h) we'll have nice things...

**Comment by Mzartek** [comment]
Oh i'm so sad :(, and is there a way to use Squirrel in a Windows Service? In order to get admin rights? I didn't try but what do you think?

**Comment by paulcbetts** [comment]
Nope :(  That wrecks the entire proposition

**Comment by dealproc** [comment]
@Mzartek - this may get you started: http://www.codeproject.com/Articles/700435/Windows-service-auto-update-plugin-framework ... it's not squirrel.windows, but it may be a favorable alternative.

**Comment by paulcbetts** [comment]
Gonna close this since it's not possible

**Comment by ncoussemacq** [comment]
FYI, I just wrote a suggestion on UserVoice about this : http://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/9293115-ngen-should-be-able-to-produce-optimized-binaries
