### ISSUE TITLE
System.Net.Http.Formatting.dll being referenced without including it via Microsoft.AspNet.WebApi.Client package

### ISSUE THREAD

**Issue by bording** [Squirrel/Squirrel.Windows#393]
After updating to .99.2 I noticed that my project's bin folder suddenly had both System.Net.Http.Formatting.dll and Newtonsoft.Json.dll, which were never there before. I didn't see any new NuGet dependencies for the Squirrel package, so I was curious where they were coming from.

Looking at the MSBuild output, I'm seeing that they are being copied from:

`C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET MVC 4\Assemblies\System.Net.Http.Formatting.dll`

and

`C:\Program Files\Microsoft SDKs\Windows Azure\.NET SDK\v2.3\ref\Newtonsoft.Json.dll`

which seems super weird. I suppose everything is still working because it just happened to find those sitting in those folders.

Looks like #229 added a reference to System.Net.Http.Formatting.dll, but that isn't an assembly that is part of the .NET Framework. That PR should have included the assembly via the Microsoft.AspNet.WebApi.Client package.

However, I'm wondering if it would be better to change the code to not need it vs. introducing another dependency?

**Comment by BarryThePenguin** [comment]
I'd be happy to build a solution with WebClient instead.

Would also be good to write a test. @paulcbetts as the method relies on making a web request, do you have any guidance on writing a test for it?

**Comment by paulcbetts** [comment]
Can we just get rid of System.Net.Http.Formatting? I can't believe that HttpClient which is included in .NET requires an ASP.NET NuGet package in order to function

**Comment by shiftkey** [comment]
> I can't believe that HttpClient which is included in .NET requires an ASP.NET NuGet package in order to function

[I'm not seeing anything here that's critical](https://msdn.microsoft.com/en-us/library/system.net.http.formatting(v=vs.118).aspx) :fire::fire::fire::fire::fire::fire:

**Comment by BarryThePenguin** [comment]
```cs
var releases = await response.Content.ReadAsAsync<IEnumerable<Release>>();
```

`ReadAsAsync<T>` is an extension method in [System.Net.Http.Formatting](https://msdn.microsoft.com/en-us/library/system.net.http.httpcontentextensions.readasasync(v=vs.118).aspx)

**Comment by paulcbetts** [comment]
Oh cool, that's easy-peasy to replace, just do a `ReadAsStringAsync` followed by a JSON.NET call

**Comment by bording** [comment]
> I'm not seeing anything here that's critical :fire::fire::fire::fire::fire::fire:

System.Net.Http.Formatting.dll has a ton of stuff in it that fit into a lot of different namespaces, not just System.Net.Http.Formatting, like the above mentioned extension method.

**Comment by bording** [comment]
> Oh cool, that's easy-peasy to replace, just do a ReadAsStringAsync followed by a JSON.NET call

Is Json.NET already in Squirrel? Looking around in the project, I didn't see a direct reference to it.

**Comment by paulcbetts** [comment]
Oh, looks like we inline "SimpleJson" into Update.exe, probably have to push that down

**Comment by shiftkey** [comment]
@bording @BarryThePenguin you're right, I was just using the namespace as an example.

:thumbsup: to SimpleJson and :fire:ing the JSON.NET dependency.
