### ISSUE TITLE
Quick Start missing link to example package

### ISSUE THREAD

**Issue by appetere** [Squirrel/Squirrel.Windows#395]
[Getting started](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started.md) has the line, "Here's a good example package:" but no link to anything.

**Comment by janpieterz** [comment]
@appetere  I think the writer means the package displayed in the image below.

**Comment by appetere** [comment]
@janpieterz Thanks - can see from the history that the page was fixed up on the 17th August, including addressing this issue.  Will close the issue now.
