### ISSUE TITLE
Possibility of extending to Xamarin.Mac?

### ISSUE THREAD

**Issue by mteper** [Squirrel/Squirrel.Windows#398]
A fair bit of Squirrel.Window is understandably Windows-specific, but some isn't. @paulcbetts, what do you think, is this even worth contemplating? What would be involved?

**Comment by BarryThePenguin** [comment]
I've had the same thought in relation to [SparkleShare](https://github.com/hbons/SparkleShare)

**Comment by paulcbetts** [comment]
It seems like it would be far easier to use Squirrel.Mac, no?

**Comment by BarryThePenguin** [comment]
Even for a .Net/Mono application?

**Comment by paulcbetts** [comment]
afaik Squirrel.Mac doesn't care what language your app is written in, it'd probably be easier to just run Squirrel.Mac through Objective Sharpie and generate a binding

**Comment by mteper** [comment]
I'd have to take another look. The readme made is sound like S.M had to be integrated (source level) into your project.

**Comment by shiftkey** [comment]
> The readme made is sound like S.M had to be integrated (source level) into your project.

There's plenty of Electron apps for macOS that use Squirrel.Mac, so I don't believe this is a requirement.
