### ISSUE TITLE
Rename a shortcut

### ISSUE THREAD

**Issue by ChaseFlorell** [Squirrel/Squirrel.Windows#399]
I'm looking at the `CreateShortcutsForExecutable` and it doesn't have an option to name the shortcut. I notice that the Shortcut name is the same as the exe name, but I'm hoping to be able to change it per environment.

MyApp.exe

 - (dev shortcut) MyApp - Dev
 - (qual shortcut) MyApp - Qual
 - (prod shortcut) MyApp

Is there an easy way to do this with the stuff built into Squirrel now? Since I'm super lazy, what's the preferred approach to achieving this?

**Comment by agostinocinelli** [comment]
Same problem here, what about a new parameter in UpdateManager:CreateShortcutsForExecutable()?

**Comment by paulcbetts** [comment]
I think you probably want to do this by-hand yourself, it should be pretty easy to call CreateShortcutsForExecutable then rename it

**Comment by ChaseFlorell** [comment]
@paulcbetts does Squirrel have hooks into the shortcut locations, or do I have to try and figure those out manually?

**Comment by paulcbetts** [comment]
@ChaseFlorell Gotta figure them out yourself though if you look at the Squirrel source it's not so bad

**Comment by ChaseFlorell** [comment]
Yeah, I was thinking it would be nice to have an overload on `CreateShortcutsForExecutable`

**Comment by ChaseFlorell** [comment]
@paulcbetts would you be willing to re-open this and give a little guidance on how you envision it being implemented? I'd be interested on working on it and submitting a PR. This is definitely a need in our Continuous Delivery pipeline.

**Comment by paulcbetts** [comment]
@ChaseFlorell I would instead have a new method `GetShortcutsForExecutable` that has an identical signature but instead of doing something, returns the ShellLink object that it *would* create, which means you can edit it and commit it yourself

**Comment by StillLearnin** [comment]
Any updates on this? I could use it as well.

**Comment by paulcbetts** [comment]
Ah sorry, this has been shipped for awhile now, check out https://github.com/Squirrel/Squirrel.Windows/blob/aea7552c392e6fa8f49fa2a0733060e6c8342bc0/src/Squirrel/UpdateManager.ApplyReleases.cs#L153

**Comment by Slion** [comment]
Why not use the title as specified in the NuGet package to name the shortcut?
