### ISSUE TITLE
Rename Update.exe

### ISSUE THREAD

**Issue by jhofker** [Squirrel/Squirrel.Windows#400]
On Windows (8, 8.1, and 10), hitting Start and typing `update` should really probably list Windows' own update control panel first. 

![image](https://cloud.githubusercontent.com/assets/812787/8964072/1993a688-35e9-11e5-81eb-a7329e782076.png)

Manually changing `Update.exe` to `SquirrelUpdate.exe` on an installed app seems to "fix" the issue with search.

![image](https://cloud.githubusercontent.com/assets/812787/8964113/5299de20-35e9-11e5-9faa-159ec6108e31.png)

[Twitter conversation](https://twitter.com/paulcbetts/status/626434854733901824) :smiley:

**Comment by davidruhmann** [comment]
:+1: Looking forward to a permanent change rather than manually fixing this annoyance.

**Comment by paulcbetts** [comment]
This will fix the search issue but is 100% guaranteed to break updates and probably the app too. This bug is most likely a WontFix, too much opportunity to break stuff and cause compatibility issues, sorry.

**Comment by jhofker** [comment]
I should note that, for anyone coming across this in the future, renaming `Update.exe` "fixes" the issue, but breaks updating in the app that was using. Change at your own risk, etc.

**Comment by davidruhmann** [comment]
It is sad that this will not be addressed.  However, I do have a method of fixing this that does not require renaming the file.

1. Create a text file in the same directory as _Update.exe_ and name it `whatever you want.bat`.
2. Paste __`@"%~dp0Update.exe" %*`__ into the .bat file.
3. Modify the shortcut files created by the applications to use the script rather than _Update.exe_.

Now when typing "update" in Windows search, the application shortcuts do not appear.

**Comment by paulcbetts** [comment]
@davidruhmann This definitely will also break updates and all the things that the other fix will

**Comment by davidruhmann** [comment]
@paulcbetts How will changing the Start Menu shortcut (Code.lnk for example) and adding a batch file break updating?  Nothing else is modified, so if this breaks updating then there is something severely broken with Squirrel.  Squirrel itself should not care if it is called by command line, shortcut file, or batch script.

**Comment by paulcbetts** [comment]
@davidruhmann I spent three full years of my life writing this, and you just rolled in a day ago with your Hot Take. Maybe you could humor me that I know what I'm talking about?
