### ISSUE TITLE
Why doesn't launching the setup.exe cause the application to start, if the application was already installed and at the same version?

### ISSUE THREAD

**Issue by sickboy** [Squirrel/Squirrel.Windows#406]
1. Install the software clean, find that the software starts.
2. Stop the software
3. Try installing the software again, find that nothing happens

**Comment by Pinpickle** [comment]
When running an installer, the version check has only caused problems for me. For me, it would make sense if the installer installed over whatever application was currently installed.

This would make testing a whole lot more straightforward, the installer behaviour more predictable, and would solve #145 and #93 and would go some of the way to fixing #366.

**Comment by paulcbetts** [comment]
> Why doesn't launching the setup.exe cause the application to start, if the application was already installed and at the same version?

This is a bug, though tbh the behavior we're going to is going to just pave the entire local app dir instead

**Comment by paulcbetts** [comment]
Fixed in master
