### ISSUE TITLE
Is it possible to deploy VSTO project using Squirrel?

### ISSUE THREAD

**Issue by anantakrishna** [Squirrel/Squirrel.Windows#409]

**Comment by paulcbetts** [comment]
Nope! You could probably write a bunch of code to make it work but it's definitely not built in

**Comment by anantakrishna** [comment]
Thanks for an instant reply!

**Comment by IntegerMan** [comment]
This feller has done it, but it's probably best to stick with ClickOnce: https://github.com/Squirrel/Squirrel.Windows/issues/534
