### ISSUE TITLE
File names are URI escaped.

### ISSUE THREAD

**Issue by Ran-Intendu** [Squirrel/Squirrel.Windows#414]
"File Name" is installed as "File%20Name"

**Comment by paulcbetts** [comment]
Which file names?

**Comment by Ran-Intendu** [comment]
A file which is included in the nuget package we create.
Specifically, I have a file called "unity default resources" which is being extracted as "unity%20default%20resources".

**Comment by paulcbetts** [comment]
Probably related to https://github.com/Squirrel/Squirrel.Windows/pull/394/files

**Comment by duanyao** [comment]
Nuget expects entry names in .nupkg file %-escaped, so if you found "unity%20default%20resources" in the .nupkg file or extract it with a zip tool, it is normal. After installaton with Squirrel, the file names should be unescaped (If not, it must be a bug).

**Comment by Ran-Intendu** [comment]
Well, it is a bug.

When I open the nuget package through 7zip, I can see that the file is %-encoded.
When I open the nuget package through NuGet Package Explorer, the file is decoded (without %).
Finally, after installation with Squirrel, the file remains escaped --> Bug.

**Comment by paulcbetts** [comment]
I think this is a combination of @duanyao's change and my change that rips NuGet out of the extraction code.

**Comment by hfcorriez** [comment]
+1

**Comment by hankbao** [comment]
Same here.

**Comment by hankbao** [comment]
Hi @paulcbetts. Do you have any ETA for the fix of this issue?

**Comment by jbeshir** [comment]
Got bit by the same problem here. Now I know about it I can at least change things to avoid spaces in names as a workaround. Interestingly enough doesn't seem to happen for @ symbols, just spaces. Maybe it just doesn't consider that symbol as something needing escaping.

**Comment by ruisebastiao** [comment]
+1

**Comment by yuanyinchun** [comment]
+1

**Comment by geary** [comment]
I posted some code to [work around this](https://github.com/Squirrel/Squirrel.Windows/issues/544#issuecomment-172672313) in the other issue a few weeks ago. It may be helpful for anyone who runs into this.

**Comment by kumarharsh** [comment]
I am also running into the same bug, but it's because I've named my own app with spaces in the name.  The app exe now as a `%20` in it's name. Everything works correctly, but it does look ugly !

**Comment by Thieum** [comment]
@shiftkey fixed by #650 , this can be closed.

**Comment by bddckr** [comment]
I don't believe #650 fixed this (completely): #1266 was opened two years after that PR was merged and I can still observe the issue on Squirrel 1.8.0.

I noted the same in https://github.com/Squirrel/Squirrel.Windows/issues/1266#issuecomment-495487426 to prevent that one from getting closed without a resolution.

**Comment by shiftkey** [comment]
@bddckr does #1266 cover the outstanding problem as you see it? If so, I'm happy to use that issue to track that problem.

If not, please open a fresh issue with details about your setup and the problem you are seeing.

**Comment by Thieum** [comment]
@shiftkey @bddckr see also #1141 - I think they are related with each other. I could be wrong, but I think the timeline of this, is that it was fixed for the previous compression technology, and it came back when we moved from sharpziplib to sharpcompress.

**Comment by bddckr** [comment]
#1266 works, perhaps we could change the title to ensure other users have an easier time finding that issue then moving forward?

#1141 definitely sounds like it's related. I wonder if that one really only is restricted to executable file names as mentioned in that issue. If it's not just executables I'm confident this should be the same issue we're looking at.

**Comment by paulrahme** [comment]
A workaround for this "filename with spaces" issue is to use an old version of NuGet. As per this thread:
[https://stackoverflow.com/questions/51404465/octopus-download-package-error-part-uri-is-not-valid-per-rules-defined-in-the-o/52439110#52439110](url), we tried using 2.8.6 to create the .nupkg and Squirrel.exe worked fine with it, no longer giving the "Part URI..." error.
