### ISSUE TITLE
Documentation for how to fetch the current version and changlog via the Squirrel API

### ISSUE THREAD

**Issue by moser96** [Squirrel/Squirrel.Windows#417]
I want to know where do I get the **ReleaseEntry for the CurrentlyInstalledVersion** which is mentioned at the following documentation:
https://github.com/Squirrel/Squirrel.Windows/blob/master/specs/ClientImplementation.md#client-side-api

I have no plan where do I get this object, can anybody tell me this? I'll add it to the documentation when I found the answer!

thx

**Comment by Thieum** [comment]
@moser96 the updatemanager is now documented [here](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/update-manager.md) with the info you are requesting.

@shiftkey this can be closed, as the doc has changed and contains the info requested.
