### ISSUE TITLE
Does Squirrel.Windows Allow Query String Information to Be Passed In?

### ISSUE THREAD

**Issue by bbunderson** [Squirrel/Squirrel.Windows#418]
We are looking for a real replacement for ClickOnce, but our main use of ClickOnce is to launch from a web page and pass in query string parameters. We can then read these query string parameters in our ClickOnce app to use to retrieve information, etc.

Info on how it is done with ClickOnce below.
https://msdn.microsoft.com/en-us/library/ms172242.aspx

**Comment by paulcbetts** [comment]
No, unfortunately the only way you can do that is by cheating and building part of the installer into the operating system, sorry :(
