### ISSUE TITLE
Server-side implementation questions

### ISSUE THREAD

**Issue by SamyPesse** [Squirrel/Squirrel.Windows#421]
First of all, sorry for the long message and my english.

I'm working on adding Squirrel.Windows auto-update support to [Nuts](https://github.com/GitbookIO/nuts) (https://github.com/GitbookIO/nuts/pull/5).

After reading the documentation and specs, I still have a few questions about the auto-update process.
##### 1. `-delta.nupkg` or `-full.nupkg`? (:white_check_mark: answered in first comment)

Does Squirrel.Windows requires `-delta.nupkg` or can it update the application using only the `-full.nupkg`?

Basically, it easier for us to start by building and releasing only the  `-full.nupkg`, then our `RELEASES` will contain only one line, like:

```
27085B8258F3AC391344BEF728CAAA4575CF23F3 gitbook-editor-4.0.0-full.nupkg 46682474
```

Will it block the update process (If Squirrel.Windows requires the `-delta.nupkg`) ?
##### 2. Server side routes and `Update.exe --update <url>` process?

I'm not sure I perfectly understood what `Update.exe --update <url>` will exactly do to update the application.

From what I understood:
1. Desktop application run  `Update.exe --update http://myserver.com/update`
2. `Update.exe` will make an HTTP GET to `http://myserver.com/update/RELEASES` to download the `RELEASES` file.
3. It will compare the SHA of the current application with the last line of the `RELEASES` file to determine if it needs to update
4. If the SHAs are different, it will download the file from `http://myserver.com/update/gitbook-editor-4.0.0-full.nupkg` (Related to the first question)
5. Update the local application using this file
6. Restart the application
##### 3. Channels and pre-version?

[Nuts](https://github.com/GitbookIO/nuts) has been designed to work with Semver versions and to serve alternate channels (like `alpha` or `beta`) according to the pre-release part of the tag.

NuGet and Squirrel.Windows doesn't fit well with pre-release tags, that's why I designed in Nuts (https://github.com/GitbookIO/nuts/pull/5) the update url to contains the current application version:

```
http://downloads.myapp.com/update/win32/:version
```

Squirrel.Mac requires to pass the version as a parameter to send a `200` or `204` status code, but Squirrel.Windows doesn't have the same logic ([For example in Atom](https://github.com/atom/atom/blob/a6f31ed79192cba8f1509a819fd2689e3f050c93/src/browser/auto-update-manager.coffee#L19-L24)).

It looks like the server requires to send a `RELEASES` with all versions or at least the latest one.

Will it be a "good practice" to include the version in update url for `Update.exe` ?

Passing the version as a parameter, will make it possible for the server to serve `alpha`/`beta` releases only to users using these channels.
##### 4. 64bits?

It looks like Atom is released only as a 32bits application, Do you have any plan for releasing it as a 64bits ? If yes, what differences will it brings to the update process?

From my understanding, the update url will need to contain infos to signal the architecture (Something like `http://myserver.com/update/64` and `http://myserver.com/update/32`), so that it can serve the correct `RELEASES` and `.nupkg` files.

**Comment by SamyPesse** [comment]
I found the answer to my first question: `delta.nupkg` are optionals ([UpdateManager.ApplyReleases.cs#L273](https://github.com/Squirrel/Squirrel.Windows/blob/58c10baf4d2d4ed5c924ae699c8c2d8e93052dc7/src/Squirrel/UpdateManager.ApplyReleases.cs#L273) and [UpdateInfo.cs#L76](https://github.com/Squirrel/Squirrel.Windows/blob/0d1250aa6f0c25fe22e92add78af327d1277d97d/src/Squirrel/UpdateInfo.cs#L76))

After running some tests, it looks like pre-release (like `1.0.0-alpha.1`) are causing a lot of troubles with NuGet/Squirrel.Window.
Since NuGet requires a version format like `x.y.z`, the `RELEASES` for `1.0.0-alpha.1`, `1.0.0-alpha.2`, `1.0.0` will contain the same filename (`myapp-1.0.0-full.nupkg`); and Squirrel.Window is using the filename to compare versions ([UpdateInfo.cs#L70](https://github.com/Squirrel/Squirrel.Windows/blob/0d1250aa6f0c25fe22e92add78af327d1277d97d/src/Squirrel/UpdateInfo.cs#L70))
So an update on a pre-release will be ignored, right?

It looks a solution will be to "force" update if the `sha` of the package changed (or event just the `size`). But it will give more responsibility to the server (just like `Squirrel.Mac` is doing with the `update` endpoint and 200/204 status code), which is maybe not wanted by design.

**Comment by paulcbetts** [comment]
Squirrel.Mac and Squirrel.Windows have two very different philosophies about how updates should work, and I think you're coming at it from the Mac side.

Squirrel.Windows has been designed explicitly to not require a complicated update server, in Squirrel.Windows many of the decisions are made on the client side - things like, which version to choose, and which channel to update from. 

> I'm not sure I perfectly understood what Update.exe --update <url> will exactly do to update the application.

I think this is part of your confusion, here's how it works:

1. Desktop application run  `Update.exe --update http://myserver.com/update`
2. `Update.exe` will make an HTTP GET to `http://myserver.com/update/RELEASES` to download the `RELEASES` file.
3. It will compare the *VERSION* of the current application with the last line of the `RELEASES` file to determine if it needs to update
4. If the *VERSION* is higher, it will download the file from `http://myserver.com/update/gitbook-editor-4.0.0-full.nupkg`, and use the *SHA1* to check its integrity

Squirrel.Windows compares versions to determine which update to choose, not SHA1s. This is different than Squirrel.Mac. Because Squirrel.Windows compares versions, it can make decisions on how to get from point A to point B - i.e. if it's less bandwidth to download several deltas, it will do that instead of downloading a single full package.

> Passing the version as a parameter, will make it possible for the server to serve alpha/beta releases only to users using these channels.

You can make this happen, this is a feature I intended to add at some point (I would add it as a query parameter though). 

> It looks like Atom is released only as a 32bits application, Do you have any plan for releasing it as a 64bits ? If yes, what differences will it brings to the update process?

This is on the Atom team to decide what to do. In other apps, the client simply chooses a different URL for checking for updates

**Comment by SamyPesse** [comment]
Thanks @paulcbetts for your answer!

Both philosophies (Squirrel.Mac and Squirrel.Windows) make sense, it'll probably be a good idea to add a note about differences with Squirrel.Mac in the documentation.

I still have a last question: Since NuGet/Squirrel.Windows requires versions to have the format `x.y.z', multiple semver versions will have the same reduced tag name:

- `1.0.0` -> `1.0.0`
- `1.0.0-alpha.1` -> `1.0.0`
- `1.0.0-alpha.6` -> `1.0.0`

If the application is running version `1.0.0-alpha.1` and version `1.0.0-alpha.2` is available, it will make the HTTP request to `RELEASES` and get something like:

```
27085B8258F3AC391344BEF728CAAA4575CF23F3 myapp-1.0.0-full.nupkg 46682474
```

And it will ignore the update (since versions from filenames are equal).

I'm trying to find a server side solution to make pre-release work by serving a `RELEASES` like (even if the NuGet package contains the reduced version `1.0.0`):

```
27085B8258F3AC391344BEF728CAAA4575CF23F3 myapp-1.0.0-alpha.1-full.nupkg 46682474

or

27085B8258F3AC391344BEF728CAAA4575CF23F3 myapp-1.0.0.14-full.nupkg 46682474
```

It looks like it can handle correctly version like `1.0.0.10` ([ReleaseExtensions.cs](https://github.com/Squirrel/Squirrel.Windows/blob/0d1250aa6f0c25fe22e92add78af327d1277d97d/src/Squirrel/ReleaseExtensions.cs).

Will it work for the all process ? or is it going to cause trouble during the update ?

**Comment by thughes** [comment]
@paulcbetts I also found this explanation useful. Is it something that could be added to the squirrel windows docs? I'm coming into the squirrel world from electron, where all the documentation currently only describes the squirrel mac server behavior: http://electron.atom.io/docs/v0.31.0/api/auto-updater/

Any plans on unifying squirrel mac and windows behavior? (Personally I like the "text file you can host on S3" approach that squirrel windows uses)

**Comment by paulcbetts** [comment]
> Any plans on unifying squirrel mac and windows behavior? (Personally I like the "text file you can host on S3" approach that squirrel windows uses)

Nope, gotta convince the Squirrel.Mac people :(

**Comment by Thieum** [comment]
@SamyPesse regarding your last question, semver is not fully supported, but you can track this particular issue in #1394
@shiftkey all the original questions have been answered, this can be closed.
