### ISSUE TITLE
Installation of .net 4.5 sliently fails if free disk space is not enough

### ISSUE THREAD

**Issue by duanyao** [Squirrel/Squirrel.Windows#426]
Steps to reproduce:
- Setup a fresh Windows 7 virtual machine (64bit tested), confirm that only .net 3.5.x installed. Make sure the free space of system partition is less than 3GB.
- Try to run atom editor installer (1.0.9 32bit tested) in it.

What happened:

A dialog poped up asking whether to install .net 4.5, confirmed. The .net 4.5 web installer was downloaded and ran, and "Extracting files" dialogs poped up and disappeared latter. However after that, nothing happened, .net 4.5 was not installed, and no logs can be found, even after reboot.

<del>If manually download .net 4.5 web installer (http://go.microsoft.com/fwlink/?LinkId=397707) and run it, .net 4.5 is able to be installed.</del>

Update:

It turns out that this failure is not the problem of windows 7 or the .net 4.5 installer, but the deficient free space of system partition. Intalling .net 4.5 on a fresh windows 7 box requires > 3GB space; if not available, `NDP452-KB2901954-Web.exe /passive` exits with code 5100 (means "The user's computer does not meet system requirements") (https://msdn.microsoft.com/en-us/library/ee942965%28v=vs.110%29.aspx#return_codes).

However, it seems that squirrel does not report errors of .net 4.5 installer to users, which may cause confusion. Can this be improved?

**Comment by duanyao** [comment]
It seems the problem is that .net 4.5 web installer doesn't work in passive or quiet mode in my win7 box. If I run `NDP452-KB2901954-Web.exe /passive` or `NDP452-KB2901954-Web.exe /q`, the installer also sliently quit after "Extracting files". If I simply run `NDP452-KB2901954-Web.exe`, it pops up a dialog asking for confirmation of some "SUPPLEMENTAL LICENSE TERMS" (see the picture, it is in Chinese). I suspect this dialog is reason why passive or quiet installation not work -- users can't confirm it.

![default](https://cloud.githubusercontent.com/assets/1684137/9596941/69c023c2-50ae-11e5-9deb-2749cb2e2f1f.PNG)

**Comment by jhg-tgu** [comment]
I have same bug but with more of 3GB of free space on system partition. With /silent and without this.

**Comment by gojanpaolo** [comment]
@shiftkey close in favor of #1476 ?
