### ISSUE TITLE
"Allow shortcuts to be created with arguments" in release notes

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#440]
In this https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.0.0  releases note you write
"Allow shortcuts to be created with arguments"

Is this the fix for #293?

**Comment by ricardopolo** [comment]
@paulcbetts any comment?

**Comment by paulcbetts** [comment]
No, this just lets you create shortcuts with arguments, it doesn't let you get the original setup arguments
