### ISSUE TITLE
GitHubUpdateManager doesn't look in Releases by default

### ISSUE THREAD

**Issue by amweiss** [Squirrel/Squirrel.Windows#442]
GitHubUpdateManager just looks in the root of the repo for RELEASES which by default is put into Releases.  Should the default update functionality be updated to match the default releasify?

**Comment by amweiss** [comment]
@BarryThePenguin thoughts?

**Comment by BarryThePenguin** [comment]
I need to actually document it properly, but I'll try and explain.

The GitHubUpdateManager only uses the myuser/myrepo part (PathAndQuery) of the 'root' url. It uses GitHub's api to query releases and find the latest release.

Squirrels query https://api.github.com/repos/Squirrel/Squirrel.Windows/releases

Then it uses the `html_url` from the latest release as the Releases folder, replacing tag for download which is where the assets are.

Squirrels latest release folder is https://github.com/Squirrel/Squirrel.Windows/releases/download/1.0.2
The asset is https://github.com/Squirrel/Squirrel.Windows/releases/download/1.0.2/Squirrel.Windows-1.0.2.zip

This is where Squirrel would then find `RELEASES`.

The only downside to doing this is that the diff updates Squirrel performs will only work from one version to the next. I don't think it will allow versions to be skipped, so then it will just fetch the latest installer anyway.

Hope that helps, let me know if I misunderstood. Happy to discuss changes too!

**Comment by amweiss** [comment]
So I setup this:
```c#
UpdateManager.GitHubUpdateManager("https://github.com/amweiss/vigilant-cupcake")
```
and the URL it tried to hit was:
https://github.com/amweiss/vigilant-cupcake/releases/download/v1.0.5615.25295/RELEASES?id=vigilantcupcake&localVersion=1.0.5735.17492&arch=amd64

Are you saying I need to supply a zip asset to the release and not just use the code tag?

**Comment by BarryThePenguin** [comment]
The release should contain everything squirrel generates for a release
* The RELEASES file
* The full installer package for your application
* Any delta packages generated by the release process

**Comment by amweiss** [comment]
Got it, needed to use assets attached to the release, not just the code tag directly.

I got to this error now, which appears to be related to #441 
```
IEnableLogger: Failed to invoke post-install: System.IO.FileNotFoundException: Could not load file or assembly 'NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'NuGet.Squirrel, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null'
```
