### ISSUE TITLE
Question: Messagebox when installation ends.

### ISSUE THREAD

**Issue by ghiboz** [Squirrel/Squirrel.Windows#444]
I like squirrel, but my users wish a message that indicates that the installation is finished without problems...
where I can put a simple
```csharp
MessageBox.Show("Installation completed.");
```

thanks!

**Comment by paulcbetts** [comment]
@ghiboz We're probably not going to add this directly, but this is easy to add to your `squirrel-firstrun` handler and from a user perspective it'll have the same effect

**Comment by ghiboz** [comment]
thanks, i'm modifying a bit squirrel to try some other things... maybe is more simply add a line somewhere
