### ISSUE TITLE
Allow prerelease strings in package version numbers

### ISSUE THREAD

**Issue by maxbrunsfeld** [Squirrel/Squirrel.Windows#449]
We'd like to use versions like `1.1.0-beta.3` in our app. Currently, this doesn't work because Squirrel uses the prerelease field in the version number for `delta` and `full`.

**Comment by nathansobo** [comment]
> and old clients MUST be able to upgrade

For our beta channel, we'll have users download a new installer. For our stable channel, we'll continue to use un-suffixed release names. So it seems like there will be continuity where it's needed unless I'm missing something.

**Comment by paulcbetts** [comment]
> So it seems like there will be continuity where it's needed unless I'm missing something.

That works for Atom, but what about other people? I'm very, very reticent to ship features that you need to know a "special trick" in order to not get broken

**Comment by paulcbetts** [comment]
![](http://cl.ly/image/0S2l322J3v3Y/Atom_-_Slack_2015-09-28_14-44-08.png)

I have no idea how many places in the code rely on being able to use the prerelease tag for delta vs full, which is why this change is terrifying. You'll for sure have to update `ReleaseEntry`, then do basically an audit of the code looking for other places that care about delta vs full, or try to parse the release file name in any way.

**Comment by paulcbetts** [comment]
I told this to @maxbrunsfeld, but I think there is actually a better way to do beta channels / releases that doesn't involve the `-beta` tag (The current proposal involves massively changing Squirrel and very possibly breaking / stranding users, without any user-visible benefit).

The better way to do this is (we'll say here we have a 'beta' and 'stable' release channel):

1. Every build of Atom that gets released gets a real version number (i.e. 1.1.2)
1. The Beta version of the RELEASES file gets every version number
1. Certain releases get Promoted to the Stable channel - this involves simply copying the nupkg files over and adding a line to Stable's RELEASED entry

This means you can promote releases to Stable without making a new version number or build, you just copy some files. It also means that version numbers are monotonically increasing across channels, which is easier to understand.

**Comment by nathansobo** [comment]
I really prefer the self-describing nature of our current plan. It is also monotonic, and additionally you can immediately determine from the version number alone what stage of the release pipeline the release is associated with and what version it will graduate to in the next phase of the pipeline. I don't want to have to consult a table to determine if a version is a beta.

**Comment by thedaniel** [comment]
This also seems like it would exacerbate our issue with not being able to increment a component of a version number over 255 on windows, especially if we have 2-3 channels. If we had infinite time and labor I'd suggest it's time to cut a new major version of Squirrel that actually uses the prerelease field for prerelease... but we don't.

**Comment by thedaniel** [comment]
Could we just treat atom-beta like a separate app entirely, with its own RELEASES and generated packages, etc? Rather than atom 1.5.0-beta, we'd have atom-beta 1.5.0

**Comment by nathansobo** [comment]
Can we do that just for Windows?

**Comment by paulcbetts** [comment]
> Could we just treat atom-beta like a separate app entirely, with its own RELEASES and generated packages, etc? 

Yeah, you can definitely do that too without any changes to Squirrel (in fact, you need to do this if you want both stable Atom and beta Atom to be installable at the same time).

**Comment by maxbrunsfeld** [comment]
Doing that doesn't remove the need to use the prerelease field though, because we still want to be able to release `1.2.3-beta.1`, `1.2.3-beta.2`, etc.

**Comment by paulcbetts** [comment]
Assumedly you could come up with a mechanical scheme to translate beta releases to digit-based ones i.e. (`1.2.3-beta.1 => 1.1.99.1`, like how GNOME sets up prereleases)

**Comment by nathansobo** [comment]
@thedaniel Do you think we could we re-interpret `atom 1.2.0.beta.5` to `atom-beta 1.2.5` for requests from squirrel for windows, but otherwise leave our releases the same?

**Comment by thedaniel** [comment]
For sure, I think to be viable any sort of hacky workaround would have to be contained within atom.io or our build scripts.

**Comment by paulcbetts** [comment]
@thedaniel Generating the `RELEASES` file dynamically was designed to be drop-dead simple to do, it should be p. easy to do this in atom.io if you had to
