### ISSUE TITLE
Missing update.exe

### ISSUE THREAD

**Issue by tom2zip** [Squirrel/Squirrel.Windows#451]
I downloaded the zip file from the releases (Squirrel.Windows-1.0.2.zip) and got the following files: rcedit.exe
Setup.exe
signtool.exe
Squirrel.com
Squirrel.exe
SyncReleases.exe

I was following a tutorial found here: http://www.mylifeforthecode.com/creating-a-windows-distribution-of-an-electron-app-using-squirrel/

The tutorial talks about using update.exe which doesn't seem to come with the zip file. Where do I find this update.exe file? Any help would be appreciated, thanks

**Comment by paulcbetts** [comment]
Squirrel.exe gets renamed to update.exe when you create a package. The `grunt-electron-installer` npm package is currently the recommended way to do this, though if you're using `electron-packager` you probably aren't using Grunt. You could steal the code though!
