### ISSUE TITLE
Certify an Squirrel based setup

### ISSUE THREAD

**Issue by InnovaTex** [Squirrel/Squirrel.Windows#452]
We are trying to certify an application with an setup based on Squirrel. It looks like the certification tool (WACK) cannot find the shortcuts created by the setup, and therefore cannot complete the certification process.

Did anyone ever managed to get the application completely through the wack test tool? We are trying to but we cannot get passed the following error:
- The don’t block reboot test detected the following errors: No new shortcuts were identified.

We tried all kinds parameters for machine-wide installation but it cannot get passed this error. Any ideas?

**Comment by paulcbetts** [comment]
When setting up WACK, you need to select "Per-user installation" - I've only tried this once, but it worked when I did this

**Comment by paulcbetts** [comment]
Reopen if this doesn't work!

**Comment by InnovaTex** [comment]
Yes we select that option, and that solves a problem when it complains about , but it does not work unfortunally.

Halfway the test the following message appears:
---------------------------
Windows App Certification Kit
---------------------------
Testing cannot continue unless an application is successfully installed, including a discoverable shortcut and an entry in add/remove programs.
---------------------------

And in the report in the end it sais failed because of: •The don’t block reboot test detected the following errors: No new shortcuts were identified.

We tried to make a change in the way shortcuts are created, changing Environment.SpecialFolder.DesktopDirectory to Environment.SpecialFolder.CommonDesktopDirectory but then we get an UnauthorizedException while running the setup, don't know where that is coming from yet.

**Comment by paulcbetts** [comment]
Well, are you creating a shortcut?

**Comment by InnovaTex** [comment]
Hi, yes we are using the default settings that creates shortcuts on desktop and startmenu.

It is simple to test:
- Download virtualbox
- Download windows 10 virtual machine from https://dev.modern.ie/
- Install the windows 10 sdk
- run the certification toolkit on an squirrel setup, and indeed select for current users as option.

Verify that this test fails.

**Comment by paulcbetts** [comment]
Dunno, sounds like a WACK bug

**Comment by InnovaTex** [comment]
Hi, I will submit the issue to microsoft support. I let you know if it leads to anything

**Comment by paulcbetts** [comment]
@InnovaTex Is there a reason you care about WACK? There's really not any practical benefit to do so - for Desktop apps, you essentially only get a "marketing page" in the Windows store with a link, it's not really worth the time imho. You'd do far better spending this time working on a great landing page for your app on just a website with its own domain

**Comment by InnovaTex** [comment]
Hi, The company I work for is a Gold Certified (ISV) partner for microsoft, to keep the gold partnership it is vital to have an certified windows app. The parnership is important because of marketing ofcourse and also gives us large discounts for the MSDN subscriptions we need.

**Comment by john-griffin** [comment]
Also encountering the shortcut error when running the installer against WACK. Our reason for running WACK is to help increase our SmartScreen Application Reputation as advised here http://stackoverflow.com/a/28359323/3904603

**Comment by paulcbetts** [comment]
Does WACK produce a log anywhere? Can someone upload it?

**Comment by john-griffin** [comment]
Here is the output from the `appcert.exe` command

```
Note: Test application type - Desktop.
Beginning execution of task Modify fault tolerant heap.
Beginning execution of task Modify status of the TAEF service.
Task Modify fault tolerant heap execution result was success.
Task Modify status of the TAEF service execution result was success.
Beginning execution of task Registry key inventory.
Task Registry key inventory execution result was success.
Beginning execution of task Program inventory.
Task Program inventory execution result was success.
Beginning execution of task Digital signing.
Beginning execution of task Do not load services and drivers in safe mode.
Task Digital signing execution result was failure.
Task Do not load services and drivers in safe mode execution result was success.
Beginning execution of task Proper OS version checking.
Beginning execution of task Multi user enable.
Task Multi user enable execution result was success.
Task Proper OS version checking execution result was success.
Beginning execution of task Do not force an immediate reboot during installation.
Task Do not force an immediate reboot during installation execution result was success.
Beginning execution of task Modify Program Compatibility Assistant service.
Task Modify Program Compatibility Assistant service execution result was success.
Beginning execution of task User mode hooking using AppInit_DLLs.
Beginning execution of task Crashes and hangs.
Task User mode hooking using AppInit_DLLs execution result was success.
Task Crashes and hangs execution result was success.
Beginning execution of task Process install trace files.
Beginning execution of task Modify local Windows Error Reporting settings.
Task Modify local Windows Error Reporting settings execution result was success.
Task Process install trace files execution result was success.
Beginning execution of task Program inventory.
Task Program inventory execution result was success.
Beginning execution of task Process install trace files.
Task Process install trace files execution result was success.
Beginning execution of task Installed programs.
Task Installed programs execution result was success.
Beginning execution of task Dependency information.
Beginning execution of task Proper OS version checking.
Task Proper OS version checking execution result was success.
Task Dependency information execution result was success.
Beginning execution of task Process install trace files.
The application failed to install under a higher version of Windows. Windows App Certification Kit will now retry installing the application under different settings.
Task Process install trace files execution result was success.
Beginning execution of task Program inventory.
Task Program inventory execution result was success.
Beginning execution of task Process install trace files.
Task Process install trace files execution result was success.
Beginning execution of task Installed programs.
Task Installed programs execution result was failure.

Testing cannot continue unless an application is successfully installed, including a discoverable shortcut and an entry in add/remove programs.
```

It does not generate the report xml because WACK fails to complete.

**Comment by paulcbetts** [comment]
You could try running Procmon to catch where it's trying to find the shortcut. However, to be honest, signing your application with a cert then waiting a few days will make Smartscreen go away (because you'll build up a reputation)

**Comment by john-griffin** [comment]
Thanks. Nothing is jumping out on Procmon so I'll give it a few days.

**Comment by dcposch** [comment]
We're running into this exact bug in WebTorrent.

```
Testing cannot continue unless an application is successfully installed, including a discoverable shortcut and an entry in add/remove programs.
```

We verified that it creates an entry in Add or Remove Programs, a Start Menu shortcut, and a desktop shortcut.

I think WACK doesn't recognize those because the shortcuts point to a different executable than the one being tested: we're testing the installer, but shortcuts point to the installed binary.

**Comment by paulcbetts** [comment]
Why do you want to get certified for WACK?

**Comment by feross** [comment]
@paulcbetts We don't. Just using it as a sanity check / linter.

**Comment by paulcbetts** [comment]
WACK is pretty dated and never really was geared for desktop apps, its goal was always more for Universal Apps, I would forget about it. If there's some setup code you want me to check I totally can

**Comment by paulcbetts** [comment]
Squirrel has pretty stable / hard API guarantees, if a Squirrel update breaks you we'd consider that a bug

**Comment by hlevring** [comment]
I think MS is now starting to drive harder to get regular desktop apps in the store. We considering to change our updater/ Installer framework and its important for us that we have store compatibility.....is there any updates on this ? If not I will get some folks to try it out and report back.

**Comment by paulcbetts** [comment]
MS is trying to convince people to use Project Centennial, which _actually_ puts your app in the store (like with an AppX manifest and everything). If you do that, the Store handles updates / installs and you don't need Squirrel
