### ISSUE TITLE
AbandonedMutexException

### ISSUE THREAD

**Issue by kc0isg** [Squirrel/Squirrel.Windows#453]
Some of the client machines that squirrel is deploying to are getting the following error:
 ```
An unhandled exception of type 'System.Threading.AbandonedMutexException' occurred in Squirrel.dll

Additional information: Leaked a Mutex!
```

I looked at the source and this exception is thrown in the SingleGlobalInstance deconstructor but I cannot figure out why it is getting thrown.  There are no errors in the SquirrelSetup.log and it only happenes on the client machines, not my development machine.  Any suggestions for debugging this?

**Comment by paulcbetts** [comment]
I'm not sure either, it sounds as if maybe >1 Update process is running concurrently?

**Comment by kc0isg** [comment]
It turns out that is was because I forgot to dispose UpdateManager.  Some of the clients were getting errors when closing the application saying that UpdateManager was not getting disposed.  Strangely when I created a VM to debug this issue it didn't have either of these errors.

Thanks for the help.
