### ISSUE TITLE
Can I use this with VB.Net

### ISSUE THREAD

**Issue by UVLabs** [Squirrel/Squirrel.Windows#460]
Can I use this to create a VB.NET application...At least clickonce has tonssss of VIDEOS on how to create your package. C'mon guys...us junior devs need a little extra push...I want to use your product but I have absolutely no clue how to start. Yes i did read the start up guide....but theres still alot missing...what exactly do we download from github?...can someone make a video on how to set this up? You would have my and im sure alotttt of other devs eternal gratitude.

**Comment by paulcbetts** [comment]
Yep! You can definitely use it with VB.NET. The only Squirrel video at the moment is https://channel9.msdn.com/Events/dotnetConf/2015/Squirrel-for-Windows-installing-NET-apps-the-way-it-should-be
