### ISSUE TITLE
Antivirus Randomly Quarantines updater.exe etc

### ISSUE THREAD

**Issue by UVLabs** [Squirrel/Squirrel.Windows#461]
I was getting a whole bunch of errors at times when trying to stall the program...update...and even uninstall (btw I noticed that uninstalling the app through programs and features doesnt do a CLEAN uninstall, I still had an updater.exe and a .dead file inside the app folder in local)

I turned off my antivirus for a while and so far...things seem a little better...Im using AVAST, how could I prevent this from happening...I plan to distribute my app as opensource...I cant be telling lay users to set exceptions in their antivirus...

![capture](https://cloud.githubusercontent.com/assets/10324144/10409732/bd895da2-6ef9-11e5-90ca-a9c044f0fb0e.PNG)
![capture2](https://cloud.githubusercontent.com/assets/10324144/10409734/c325dbfa-6ef9-11e5-8aa3-c57d63f4c748.PNG)

**Comment by paulcbetts** [comment]
You need to get a code signing certificate and sign your installer
