### ISSUE TITLE
Installer required reboot after installation and opens installation directory on boot up. 

### ISSUE THREAD

**Issue by sguergachi** [Squirrel/Squirrel.Windows#462]
A user who Installed our application through Squirrel let us know that the installer required a reboot following the installation and then every reboot since the installation the installation directory would automatically open up upon launch. 

The user was using a Windows Explorer replacement called Xplorer2. Likely the culprit. 

The painful thing is that after uninstalling our app, Xplorer apparently still automatically launched. Suggesting some registry change that wasn't reversed after uninstalling.

Any help where to start with solving this would be super appreciated. Thanks.

**Comment by paulcbetts** [comment]
Squirrel itself doesn't set any registry entries except for the uninstall key - maybe your app set a key in an install hook?

**Comment by sguergachi** [comment]
Seems to be due to a shortcut to the install folder put into the startup folder. The user was able to fix this. Don't know why Squirrel would behave this way though.


- Sammy Guergahchi

**Comment by paulcbetts** [comment]
There's no code in Squirrel that does this. Reopen if you get more info!
