### ISSUE TITLE
GitHub hosted releases don't update across nonconcurrent versions

### ISSUE THREAD

**Issue by stajs** [Squirrel/Squirrel.Windows#465]
Okay, I'm still wrapping my head around the GitHub hosted releases, so feel free to correct me. I've whipped up a reproducing repo here if you want to try and reproduce it yourself, or check that I haven't made a bad assumption on something.

https://github.com/stajs/SquirrelHub/releases

The relevant releases are v2, v3, v4. This is a bit hard to explain so bear with me. I'm going to work backwards here as I think it shows it better.

# Step 0
All releases are marked as "stable", i.e. not "prerelease".

# Step 1 - v4 (latest)

0. Ensure `SquirrelHub` is not installed.
0. Install `Setup-SquirrelHub-4.0.0.exe`
0. The check for update shows it is already on the latest version:<br />![image](https://cloud.githubusercontent.com/assets/2253814/10424238/1b9159ea-712a-11e5-873e-ab045c0cf4c8.png)

_Note:_ `IsCanary` is a flag I was using to check prereleases, ignore it for this discussion.

# Step 2 - v3 updates to v4

0. Ensure `SquirrelHub` is not installed.
0. Install `Setup-SquirrelHub-3.0.0.exe`
0. The check for update finds v4 and updates:<br />![image](https://cloud.githubusercontent.com/assets/2253814/10424360/1ccf658a-712b-11e5-9577-c4f9fec2154c.png)
0. Restart to verify on v4.

# Step 3 - v2 updates to v3

0. Ensure `SquirrelHub` is not installed.
0. Ensure v4 is marked as prerelease, so that v2 only tries to update to v3.
0. Install `Setup-SquirrelHub-2.0.0.exe`
0. The check for update finds v3 and updates:<br />![image](https://cloud.githubusercontent.com/assets/2253814/10424451/c2658934-712b-11e5-81c2-6a6780213e3b.png)
0. Restart to verify on v3.

# Step 4 - v2 fails to update to v4

0. Ensure `SquirrelHub` is not installed.
0. Ensure v4 is not marked as prerelease, so that v2 tries to update to v4.
0. Install `Setup-SquirrelHub-2.0.0.exe`
0. The check for update finds v4 and fails:<br />![image](https://cloud.githubusercontent.com/assets/2253814/10424547/666c125a-712c-11e5-8eef-e88a93822920.png)

# Summary
0. Updates to concurrent releases work: v2 > v3 > v4.
0. Updates to nonconcurrent releases fail: v2 > v4.

Apart from changing `UpdateManager` to `GitHubUpdateManager`, I was using the same updating code with non-GitHub-hosted releases previously. Nonconcurrent releases were applied fine so I expected GitHub hosted releases to behave the same way.

**Comment by stajs** [comment]
For a different project, I have just verified that updating across nonconcurrent releases works fine with the older `UpdateManager`.

I'm wondering if I need to take more responsibility with `GitHubUpdateManager` and progressively apply each release myself. This would be a bit of change from what I was used to; I expected Squirrel to make the decision of applying the deltas if it was quicker than applying the full package. Can I just check that?

Given intermediate i.e. v2 > v3 > v4, and you start on v2, when checking for updates what should Squirrel do:

0. Apply v3-delta then v4-delta always?
0. Apply just v4-full always?
0. Either of the above, depending on what is least to download.

I thought 3., but just checking the assumption.

**Comment by paulcbetts** [comment]
Normally Squirrel just does this for you (and does what you describe with idea 3, where bandwidth makes the decision), it sounds like GitHubUpdateManager is falling over a bit

**Comment by BarryThePenguin** [comment]
GitHubUpdateManager makes a few assumptions that are different to Squirrels regular update process

- The repoUrl passed into the factory is used to find all GitHub releases
- The latest GitHub release is then found, taking into account prereleases
- The url for the latest release is then used to build the latestReleaseUrl
- The latestReleaseUrl is what points to the assets folder for the latest release
- The assets folder should contain the Setup.exe, Project-full.nupkg, Project-delta.nupkg and the RELEASES file
- The RELEASES file should only contain the ReleaseEntrys for the _latest_ release

If you remove the other releases from your RELEASE file

```
89D9DD4531718518F71C01D80FF4676CB8170A06 SquirrelHub-4.0.0-delta.nupkg 6013
D905BFD2ECE700C679C6382AF6B3998DA90F94E7 SquirrelHub-4.0.0-full.nupkg 692642
```

Then updates should be able to skip versions. The major downside to this is delta updates will only work for concurrent versions. GitHubUpdateManager cannot currently be used to update with delta packages across multiple releases

**Comment by stajs** [comment]
@BarryThePenguin Awesome, thanks for that information!

I tried updating each RELEASES file to just have the single pair of updates.

v2 RELEASES

```
09CEDCCD816EEEBC04999FDAE5BA9DA1DB744A5D SquirrelHub-2.0.0-delta.nupkg 7092
34F8D0E588135D5F10F157369C8F16E431F0BA35 SquirrelHub-2.0.0-full.nupkg 692551
```

v3 RELEASES

```
A80B9B85DFF3E4F44FA815B935E239D391AA8BAC SquirrelHub-3.0.0-delta.nupkg 6557
65104E1B4AF78751A3D9358BF1A334F2A3D042FD SquirrelHub-3.0.0-full.nupkg 692648
```

v4 RELEASES

```
89D9DD4531718518F71C01D80FF4676CB8170A06 SquirrelHub-4.0.0-delta.nupkg 6013
D905BFD2ECE700C679C6382AF6B3998DA90F94E7 SquirrelHub-4.0.0-full.nupkg 692642
```

Updating from v3 > v4 works still. Updating from v2 > v4 fails with a different exception:

![image](https://cloud.githubusercontent.com/assets/2253814/10441566/eecee92c-71a6-11e5-83ff-cf1b32f41197.png)

Probably shouldn't be looking to apply a diff in this situation? I'll try going one step further and remove the -deltas from RELEASES. Hopefully that will force it to do the full update instead.

**Comment by BarryThePenguin** [comment]
Yeah, v2 > v4 shouldn't attempt a diff as I doubt it has all the information required

**Comment by stajs** [comment]
Success! Removing the -deltas from RELEASES works for v2 > v4 (and v3 > v4 still works):

![image](https://cloud.githubusercontent.com/assets/2253814/10441880/3249c070-71aa-11e5-80f1-5ee9c0fa93b6.png)

A bit sad that deltas aren't supported, but as long as it's working. A future feature request perhaps...?

**Comment by BarryThePenguin** [comment]
Yeah, absolutely. Happy to review/advise on any pull requests

[My current implementation for SparkleShare](https://github.com/BarryThePenguin/SparkleShare)

**Comment by stajs** [comment]
Would be good to see how you are using GitHubUpdateManager for comparison. Do you have a link? I tried searching your repo but came up empty.

**Comment by BarryThePenguin** [comment]
It's [SparkleUpdater.cs](https://github.com/BarryThePenguin/SparkleShare/blob/squirrel-updates/SparkleShare/Windows/SparkleUpdater.cs) in the squirrel-updates branch.

There's an [appvoyer.yml](https://github.com/BarryThePenguin/SparkleShare/blob/squirrel-updates/appveyor.yml) too that does the build and release. The build process I got from [HangfireIO](https://github.com/HangfireIO/Hangfire)
