### ISSUE TITLE
Any documentation about Sync Releases feature?

### ISSUE THREAD

**Issue by ricardopolo** [Squirrel/Squirrel.Windows#473]
Could find anything in docs..

Whats the purpose?

**Comment by CrazyOrange** [comment]
opts = new OptionSet() {
                    "Usage: SyncReleases.exe command [OPTS]",
                    "Builds a Releases directory from releases on GitHub",
                    "",
                    "Options:",
                    { "h|?|help", "Display Help and exit", _ => {} },
                    { "r=|releaseDir=", "Path to a release directory to download to", v => releaseDir = v},
                    { "u=|url=", "When pointing to GitHub, use the URL to the repository root page, else point to an existing remote Releases folder", v => repoUrl = v},
                    { "t=|token=", "The OAuth token to use as login credentials", v => token = v},
                };

**Comment by mufid** [comment]
Just in case someone wandering from Google Search (like me), it is here: https://github.com/Squirrel/Squirrel.Windows/blob/master/src/SyncReleases/Program.cs
