### ISSUE TITLE
DeltaCompressionDotNet error

### ISSUE THREAD

**Issue by bxxx** [Squirrel/Squirrel.Windows#476]
I have this error on install. Some package does not support .NET 4. Github page of that package says:
```DeltaCompressionDotNet targets the .NET Framework 2.0, but if you're lucky enough to be using the .NET Framework 4.5 then you should prefer MsDeltaCompression over PatchApiCompression where possible.```
What should I do?

PM> Install-Package squirrel.windows
Attempting to gather dependencies information for package 'squirrel.windows.1.1.2' with respect to project 'stp_scan', targeting '.NETFramework,Version=v4.0'
Attempting to resolve dependencies for package 'squirrel.windows.1.1.2' with DependencyBehavior 'Lowest'
Resolving actions to install package 'squirrel.windows.1.1.2'
Resolved actions to install package 'squirrel.windows.1.1.2'
Install failed. Rolling back...
Package 'DeltaCompressionDotNet 1.0.0' does not exist in project 'stp_scan'
Package 'DeltaCompressionDotNet 1.0.0' does not exist in folder 'F:\Work\stp\scanner\stp_scan\packages'
Install-Package : Could not install package 'DeltaCompressionDotNet 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does 
not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package squirrel.windows
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

Quick question. Can Squirrel work under Linux with Mono?

**Comment by paulcbetts** [comment]
> Some package does not support .NET 4.

I think that NuGet is getting confused with the error here. However, your project must be *.NET 4.5* or higher, .NET 4.0 isn't supported
