### ISSUE TITLE
Missing Shortcut (.lnk) Icon after Updates

### ISSUE THREAD

**Issue by bradleach** [Squirrel/Squirrel.Windows#477]
I've got a problem with my app "losing" its desktop shortcut icon after two subsequent updates (it is fine on initial install, and for one update later). We were running Squirrel 1.0.3, but I've upgraded to 1.1.2 and continue to see the problem.

By "losing", I mean it shows up as follows:
![shortcut-missing-icon](https://cloud.githubusercontent.com/assets/108573/10871922/afb525a0-8149-11e5-84de-ffb7544c09f7.png)

I believe the app icon should be updated as we are Squirrel Aware, and when our app starts up, we make a call to:

    using (var manager = new UpdateManager(UpdateUrl))
    {
      SquirrelAwareApp.HandleEvents(
        onInitialInstall: _ => manager.CreateShortcutForThisExe(),
        onAppUpdate: _ => manager.CreateShortcutForThisExe(),
        onAppUninstall: _ => manager.RemoveShortcutForThisExe());
    }

The only "weird" thing I see is in the properties for the .lnk file, the "Starts In" folder is set to the original folders location. e.g. say our first version is "0.1.0.5", but now we're running "0.1.0.7", the link Starts In is set to "%localappdata%/myprog/app-0.1.0.5", which no longer exists, as we only have "app-0.1.0.6" and "app-0.1.0.7" folders.

Any help would be appreciated!

**Comment by molster** [comment]
I have also experienced this from time to time.

**Comment by janpieterz** [comment]
I'm experiencing this with both Atom and Slack as well.

**Comment by mavenius** [comment]
Is this maybe just a user issue (not end-user, but dev using Squirrel?)

There is an optional icon (i=|icon) parameter that can be passed to Update.exe (which is what links point to.) Setting this for Slack fixes the issue for me. I think Slack, etc. should probably be setting this, but if I am correct, it should probably be called out better in the documentation.

**Comment by abakaa** [comment]
I`m experiencing this as well.
Is there any update on this? 
Anyone?

**Comment by paulcbetts** [comment]
This is fixed in the latest version
