### ISSUE TITLE
Update has stopped working

### ISSUE THREAD

**Issue by CallumCarmicheal** [Squirrel/Squirrel.Windows#482]
I have installed Slack then a week later i went to install Atom Text Editor but every attempt i got `Update has stopped working` once i had closed it, it asked to show a log and the problem was
DirectoryNotFound `AppData\Local\slack\packages\RELEASE`. 

I had to uninstall slack to see if it would work - (I uninstalled via Update.exe) I uninstalled perfectly fine but one uninstalled the slack installer started to mess-up and show the same error but this time it does not even get near logging. I had tried another Squirrel driven application called AvoCode and still the same problem but does not ask if i want to see the log.

I had attempted to install it 

OS: Windows 7 64Bit.

**Comment by Inzanit** [comment]
Without logs or some decent repro steps, this might have been an artifact of an old build of Squirrel. Four years on, can probably be closed @shiftkey

**Comment by shiftkey** [comment]
Good point @Inzanit.

@CallumCarmicheal if you can reproduce this issue against the latest version of Squirrel.Windows please open a fresh issue with details.
