### ISSUE TITLE
What are the options for the `shortcut-locations`?

### ISSUE THREAD

**Issue by lipis** [Squirrel/Squirrel.Windows#490]
In the help it says the following about `--shortcut-locations`:

> Comma-separated string of shortcut locations, e.g. 'Desktop,StartMenu'

and I know that it works for `Startup` as well, but is there somewhere a full list of supported locations?

**Comment by paulcbetts** [comment]
Yeah, any Enum in https://github.com/Squirrel/Squirrel.Windows/blob/2cc6bfe3c51d0cd0a56511deb8bdab8172aed409/src/Squirrel/IUpdateManager.cs#L17 will work

**Comment by lipis** [comment]
Thanks.

**Comment by wexman** [comment]
Is there an option for not creating a shortcut at all?

**Comment by bddckr** [comment]
@wexman I may be wrong here but if you use `SquirrelAwareApp.HandleEvents` and just don't create the shortcuts in response to those it works for me AFAICS.

**Comment by wexman** [comment]
Thanks, i will try that!


Am 19. März 2018 6:34:25 nachm. schrieb Christopher-Marcel Böddecker 
<notifications@github.com>:
