### ISSUE TITLE
Setup and Updates doesn't run smoothly

### ISSUE THREAD

**Issue by vicentedealencar** [Squirrel/Squirrel.Windows#494]
Hi, I am trying to use squirrel on a electron to make a autoupdatable app.

I am using grunt-electron-installer outputing the releases to a `updates` folder, and serving as static via `http-server` for development. Looking at `http-server` output I can see it gets hit by the grunt task on new version releases, and the folder looks ok with the .nupkgs, .msi, and RELEASES.

I run the projectSetup.msi to install it on my machine, only thing I noticed is the `project Installer` folder on the `Program Files`, with the project.exe inside. and a new entry on `Control Panel\Programs\Programs and Features` `project Machine-Wide Installer`. I Expected to see `AppData/Local/project`, but it is not there yet, what am I missing?

Moving on, I run the `Program Files/project Installer/project.exe`, and it is installed ok adding the Desktop shortcut, whitch points to `Update.exe --processStart project.exe`. It looks nice, but the autoupdating is not happening, only way it happens is by calling `Update.exe --update=url` (same url on remoteReleases in the Gruntfile). I am not sure where the autoupdate is triggered. Maybe I am missing something on the way the squirrel events are handled, because I just pasted the snippet at https://github.com/atom/grunt-electron-installer#handling-squirrel-events

**Comment by paulcbetts** [comment]
> and serving as static via http-server for development

You don't need to do that, instead of a URL, just pass the file path to your updates 

> I Expected to see AppData/Local/project, but it is not there yet, what am I missing?

The MSI is for installation via Group Policy, not intended for users to install the app. Use the EXE instead.

> It looks nice, but the autoupdating is not happening, only way it happens is by calling Update.exe --update=url (same url on remoteReleases in the Gruntfile

You need to use the `auto-updater` module to trigger updates, or you can just manually spawn Update.exe yourself

**Comment by vicentedealencar** [comment]
This was really helpful, thanks!

Now there is this other weird thing going on... the Desktop shurtcut is not being customized

![image](https://cloud.githubusercontent.com/assets/1762868/11203986/f148baca-8ce0-11e5-9604-aa1be658dc40.png)

and after few tries (changing the name of the app to make fresh install), this is what I see trying to install a new app with unique name. (notice the extra d on app`d`datable)

![image](https://cloud.githubusercontent.com/assets/1762868/11204028/6492801a-8ce1-11e5-86dc-8b976e18f7cc.png)

This is the [repo](https://github.com/vicentedealencar/electron-boilerplate/tree/master/boilerplate) working on

**Comment by vicentedealencar** [comment]
Actually the Desktop issue is related to missing parameters passed to electron-packager:
`--icon`
`--version-string.ProductName=ortooff0`
