### ISSUE TITLE
How can I catch the error when installing a new instance when the app is already running?

### ISSUE THREAD

**Issue by lipis** [Squirrel/Squirrel.Windows#495]
If the app is already running and I'm trying to install the latest/same version I'm getting the following error.

![screen shot 2015-11-16 at 11 10 31](https://cloud.githubusercontent.com/assets/125676/11179346/036116d2-8c53-11e5-9b15-aefea64a3a5b.png)

Is there any way to catch this or maybe automatically close the currently running version in order to install the new one?

**Comment by dbruning** [comment]
My users do this all the time too. Would be great to notice the app already running (semaphore? process name?) and switch to it.

**Comment by lipis** [comment]
We actually might want to close it and install the newest one, than just switching to it..

**Comment by dbruning** [comment]
For my use case, I wouldn't want to close the running instance to install a newer one. The running instance will already will be doing its own periodic checks for updates, so for me it's just guarding against users who think "the way I start this app is to run this setup.exe on the desktop".

**Comment by lipis** [comment]
That could also work actually.. :dancer:

**Comment by py09mb** [comment]
This would be nice :+1:

**Comment by dabcoder** [comment]
Same above error was reported when the app was NOT previously running, on a fresh (and first) install. Just FYI.

**Comment by lipis** [comment]
Related #317

**Comment by paulcbetts** [comment]
Fixed!

**Comment by lipis** [comment]
@paulcbetts thanks!
