### ISSUE TITLE
Possible to display animated gif earlier in install process?

### ISSUE THREAD

**Issue by bitrocket** [Squirrel/Squirrel.Windows#500]
First up - great project - thanks for building it & especially building it open-source.

My app's setup.exe is 44MB. The time from when a user double-clicks the setup.exe, to when they see something happen, can be ~10s on a slower machine, which means in practice that they tend to run it twice, thinking nothing happened on the first click. I think running the installer twice is the cause of some issues I'm seeing.

I added a nice animated gif, hoping that would prevent the users from running the installer twice. What actually happens though is that the animated gif only flashes up briefly (if at all) before the app actually starts. I think this is because most of the setup time is extracting those ~44MB worth of resources, which happens inside setup.exe. By the time update.exe is invoked (and starts its 4 second timer before showing the animated gif window), there's not much left to do, and so the app usually starts upbefore the 4 seconds has elapsed from that point.

Is there any way the animated gif display could be moved inside setup.exe, rather than update.exe? Perhaps include the animated gif as a second resource in setup.exe, and extract that first & pop it up onscreen while the main resource is being extracted? It would also be great to be able to control the 4s timeout - I think I'd prefer to have it popup straight away, although I understand the reason for the 4s delay.

**Comment by paulcbetts** [comment]
This was the original design but trying to show an Animated GIF with MFC is a shitshow nightmare so I gave up.

**Comment by dbruning** [comment]
Ah right. What about keeping just update.exe and the loading gif in separate resources, and shelling out to update.exe early on with a commandline parameter telling it just to show the loading gif?
(The original issue was me logged in as the wrong account btw)
