### ISSUE TITLE
doesn't replace setup icon properly

### ISSUE THREAD

**Issue by plrthink** [Squirrel/Squirrel.Windows#503]
I'm using grunt-electron-installer to generate a windows installer, which troubles me is the generated installer's icon doesn't changed in file explorer, but when clicking the file to show details, the correct icon is shown in popup menu.

 
![default](https://cloud.githubusercontent.com/assets/2429369/11361144/1a939ba8-92c6-11e5-94cd-32d0b01207b5.PNG)

**Comment by danielchalmers** [comment]
This is probably caused by Windows caching icons.

**Comment by plrthink** [comment]
Yeah, after rooting it does change the icon.
