### ISSUE TITLE
'setup.exe --machine' doesn't create a Run entry in the registry

### ISSUE THREAD

**Issue by ProvGeorgeDAlessio** [Squirrel/Squirrel.Windows#504]
Running Setup.exe --machine does create the SquirrelMachineInstalls with our <OurApp.exe> but it doesn't add any new value to the Run registry subkey.
We are using VS2013 in Windows 8.1 64-bit and Squirrel 1.2.1. I assume that is supposed to be run by any administrator (but not GPO) right?
Thanks

**Comment by paulcbetts** [comment]
Are you checking under Wow6432Node?

**Comment by ProvGeorgeDAlessio** [comment]
You are right. Looking in the wrong place. Silly me. Thanks
