### ISSUE TITLE
Missing Upgrade table in MSI

### ISSUE THREAD

**Issue by chucker** [Squirrel/Squirrel.Windows#507]
I have a simple Squirrel-built console application (.NET 4.5, C#; nothing fancy other than requiring elevation), and `--releasify` nicely makes me an MSI file. I've been trying to deploy that using Group Policy. This works neither on Windows Server 2012 nor R2.

At first, I get "Software Installation was unable to read the MSI file <file>. The following error was encountered: SQL query syntax invalid or unsupported." in event log. Following a comment from http://eventid.net/display-eventid-107-source-Software%20Installation-eventno-4452-phase-1.htm, I tried adding an empty Upgrade table. This, however, produces an invalid MSI file according to Orca's validation. It does change group policy's error message to a more generic "There is no software installation data object in the Active Directory" (googling that yields various file permission problems, which is presumably a red herring).

So, I'm *guessing* something needs to be added to the Upgrade table. Squirrel appears to use WiX to build the MSI; is there some parameter I need to add to `--releasify` to make this work?

(Squirrel is added using the squirrel.windows NuGet package, version 1.2.1.)

**Comment by paulcbetts** [comment]
We've never seen this error before - there shouldn't be upgrade information in the MSI table since we're actually using MSI as a hack to get Squirrel on the box

**Comment by Jaykah** [comment]
Do we have to ship Setup.exe with the MSI somehow? My Setup.msi is 148kb and the Setup.exe is 63+mb.

Also, does the MSI function the same way in terms of updates?

**Comment by paulcbetts** [comment]
@Jaykah Your Setup.exe should be included in the MSI, that's definitely what's going wrong here

**Comment by pdoh00** [comment]
I am having a similar problem with 1 of my machine wide application installers.  I am using squirrel to install 2 separate applications.  One of the apps' .msi works fine and is a bit bigger than its Setup.exe.  The other one does not work and the .msi is 148kb.  One thing to note is that if I releasify by hand on my local machine it seems to build the installer fine, but when it is done on my TeamCity build it creates the 148kb msi

**Comment by cmdel** [comment]
@pdoh00 Can I ask; how do you have it set up in TeamCity to do the *releasify*? Any screenshots of the steps would be greatly appreciated. Thanks!

**Comment by pdoh00** [comment]
@cmdel Sorry I can't be more help.  It seems to have _magically_ fixed itself.  My .msi's are building OK now.  Here is my script though. Simple as can be I think.

```
Build Step 1
--releasify "CineDetect.%dep.CineDetect_CineDetectMaster.Version.Full%.nupkg"
```

```
Build Step 2
ren .\Releases\setup.exe CineDetectSetup.exe
ren .\Releases\setup.msi CineDetectSetup.msi
```

I tried to go back in my TeamCity history to mid May, but my settings must have cleaned it out.  Sorry.  If I end up reproducing it I will be sure to collect more data and post it here.

**Comment by paulcbetts** [comment]
We did it!
