### ISSUE TITLE
MSI based installation fails

### ISSUE THREAD

**Issue by knutt** [Squirrel/Squirrel.Windows#508]
We are trying to use the msi file generated by Squirrel. The msi file seems to run ok without error, and installs a file named \<ApplicationPackageName\>.exe in folder "c:\program files(x86)\\\<ApplicationName> Installer". When run, this file displays the following error message:
"This is a dummy setup.exe. If you are seeing this, your build did not correctly replace the IDR_UPDATE_ZIP resource.
Command line: '--install . ' "

So, my question is: How do I correctly replace the IDR_UPDATE_ZIP resource?

**Comment by paulcbetts** [comment]
Does your normal Setup.exe run without error?

**Comment by knutt** [comment]
Yes, the setup.exe built by Squirrel is fine. No problem there.

**Comment by paulcbetts** [comment]
Huh, really? That is quite odd. Can you share the log file that gets generated when you run --releasify?

**Comment by knutt** [comment]
Please find the log file attached. (Renamed the file to ...txt to allow it to be attached)
[SquirrelSetup.log.txt](https://github.com/Squirrel/Squirrel.Windows/files/50546/SquirrelSetup.log.txt)

**Comment by skaryshev** [comment]
I checked out 1.2.1 and got the same issue. The problem is template.wxs points to stub (bootstrapper) setup.exe in the same directory. I patched my template.wxs with hardcoded path to target setup.exe and the issue gone.

**Comment by paulcbetts** [comment]
@skaryshev Sure, but the template is copied to releases where the Setup.exe is supposed to be already filled out

**Comment by skaryshev** [comment]
Right, but I think  ".\Setup.exe" path in template.wxs->setup.wsx is relative to candle.exe which is in squirrel.exe working directory.

**Comment by knutt** [comment]
Thanks,

I changed the setup.exe path in template.wsx to: Source="../../../../Release/Setup.exe". Problem solved for now.

**Comment by paulcbetts** [comment]
@skaryshev Can you make a PR to this effect?

**Comment by skaryshev** [comment]
Cant push local branch to github:
`git push origin skaryshev_msi_fix`
`remote: Permission to squirrel/squirrel.windows.git denied to skaryshev`

**Comment by paulcbetts** [comment]
@skaryshev In this case, you need to hit the fork button and push to your fork of Squirrel.Windows, then send a PR from the website - here's a good guide: http://stackoverflow.com/questions/14680711/how-to-do-a-github-pull-request
