### ISSUE TITLE
Where to put release notes in a electron app?

### ISSUE THREAD

**Issue by plrthink** [Squirrel/Squirrel.Windows#510]
I am coming from grunt-electron-installer and I just wonder how can I attach a release note to a update? It seems like I should put that in a .nuspec file, is it right? If so, how can I put that in a electorn app?

**Comment by paulcbetts** [comment]
While Squirrel has release notes support, it's not well-supported, especially for non-C# apps. tbh, I'd just have a static HTML page with notes and throw that in a `webview` tag.

**Comment by plrthink** [comment]
@paulcbetts Thanks for your advice but I don't get it. You say a statci HTML page with notes but where it come from?

**Comment by paulcbetts** [comment]
You write it, independent of Squirrel
