### ISSUE TITLE
multiple release channels?

### ISSUE THREAD

**Issue by dennismi** [Squirrel/Squirrel.Windows#511]
Hey

Is there anybody who got multiple release channels working with 1.2.1? 

I am having difficulty seeing how it is possible without the app knows too much about the process.

How does the setup handle that there exists multiple packages in one location? 

//dennismi

**Comment by dennismi** [comment]
anyone? 
For now i solved it with 3 different nuspec files, three different install locations, and the app knows where to look for updates...

But i'm thinking there must be a better way?

**Comment by dealproc** [comment]
It's been questioned many times... the way it's recommended would be to provide a separate folder / subdirectory for each channel.

e.g. 
http://yoursite.com/releases/public
http://yoursite.com/releases/rc
http://yoursite.com/releases/QA
...

Within each store, you host the `RELEASES` file, then provide the *.nupkg s as necessary.

**Comment by paulcbetts** [comment]
@dealproc has the right idea!

**Comment by dennismi** [comment]
that would imply the app knows which channel it comes from? or implicitly knows from install point.

This also implies that any one user only can have 1 channel installed at a time...

My extra requirement was that you should be able to have multiple channels installed at a time. 

A little section in the docs couldn't hurt :)

**Comment by DanielRivers** [comment]
I also would like to know how to install multiple channels at one time.  This would solve a few of my problems.

**Comment by paulcbetts** [comment]
> I also would like to know how to install multiple channels at one time. This would solve a few of my problems.

This isn't possible, sorry :(   You'll have to change the package name if you want this

**Comment by DanielRivers** [comment]
> This isn't possible, sorry :( You'll have to change the package name if you want this

Ok, thanks, I see this is listed in the goals of Squirrel, is there a roadmap for this?  Possibly a parameter to releasify or property to a squirrel aware app?

**Comment by paulcbetts** [comment]
> Ok, thanks, I see this is listed in the goals of Squirrel, is there a roadmap for this? Possibly a parameter to releasify or property to a squirrel aware app?

Multiple release channels are already implemented, you just can't install >1 of them at a time on the same user account, that feature is not planned
