### ISSUE TITLE
Squirrel on terminal servers (e. g. Citrix)

### ISSUE THREAD

**Issue by djanknecht** [Squirrel/Squirrel.Windows#512]
Hi @all, any good idea how to handle updates on a terminal server environment with published applications? 

The major problem is the fixed link to the executable (update.exe or the squirrel aware application) that is stored in the terminal server configuration. Changing the shortcuts during the update process only affects the shortcuts in the user scope. That will lead to a broken linkt as soon as the old version is deleted.

So seems like some kind of fixed location of the executable is needed.

Anyone handled this problem yet?

Regards,

Dirk

**Comment by paulcbetts** [comment]
afaik, the way to deploy to a Terminal Server environment is via the MSI file, every user will get their own copy and everything should work
