### ISSUE TITLE
Register DLL on install

### ISSUE THREAD

**Issue by acidhax** [Squirrel/Squirrel.Windows#513]
Is it possible to register a DLL under the current system, in UAC mode?

edit:

Typo

**Comment by paulcbetts** [comment]
What's UAT mode

**Comment by acidhax** [comment]
Administrator mode

**Comment by paulcbetts** [comment]
Aha! No, its not possible - Squirrel apps are per-user. If all you want to do is register a COM component, you can do this via writing to HKCU/Classes, or look into Registration-Free COM
