### ISSUE TITLE
FileDownloader isn't visible enough.

### ISSUE THREAD

**Issue by plinehan** [Squirrel/Squirrel.Windows#514]
3dc9456e2a8b195d30de86376d84032d23edb3a5 allows one to specify a custom WebClient, but the FileDownloader class isn't visible enough.

**Comment by paulcbetts** [comment]
@plinehan Send me a PR to change the visibility

**Comment by plinehan** [comment]
https://github.com/Squirrel/Squirrel.Windows/pull/516
