### ISSUE TITLE
GitHubUpdateManager overhaul worth it?

### ISSUE THREAD

**Issue by amweiss** [Squirrel/Squirrel.Windows#515]
I recently switched over to GitHubUpdateManager and I really like the overall idea.  However, my current gripe is that is each release has more and more files.  Is it worth building out a way to just grab the full and delta for each release and then build up the URLs for old versions from the old releases?  I can probably start looking into it unless someone has a specific reason not too or a different plan.

**Comment by amweiss** [comment]
Sorry, @BarryThePenguin thoughts?

**Comment by stajs** [comment]
Last I looked, `GitHubUpdateManager` didn't support updating (applying deltas) across nonconcurrent versions (see #465), so you shouldn't have "more and more files" each release: just include the current delta and full package.

I'd be happy to see it support updating nonconcurrent versions, e.g. build out the list of previous deltas.

**Comment by amweiss** [comment]
@stajs it looks like your solution (https://github.com/Squirrel/Squirrel.Windows/issues/465#issuecomment-147552534) was to just remove the -delta files, correct?  If so, do you just need
```
D905BFD2ECE700C679C6382AF6B3998DA90F94E7 SquirrelHub-4.0.0-full.nupkg 692642
```
in your RELEASES?  That certainly would cleanup GitHub but would force all upgrades to be full which for this small app isn't really a problem.

**Comment by BarryThePenguin** [comment]
@amweiss you should be able to keep that line plus what ever the latest delta.

I'd be happy to see multiple delta's working too. At the time, the current implementation was simpler and it kept the Github releases light. Currently it's just a wrapper around the regular UpdateManager to handle locating releases on Github. Anything more would require modification of Squirrel core...

**Comment by stajs** [comment]
@amweiss Correct. Each RELEASES file lists only the full version package forcing full upgrades:

https://github.com/stajs/SquirrelHub/releases/download/v2/RELEASES
https://github.com/stajs/SquirrelHub/releases/download/v3/RELEASES
https://github.com/stajs/SquirrelHub/releases/download/v4/RELEASES

Correction: I said "just include the current delta and full package", I meant just the current full package only.

**Comment by stajs** [comment]
Clarification to my correction! :dizzy_face:

I resorted to forcing full upgrades, because it was the only way to support upgrades across nonconcurrent versions (v2 > v4). You _can_ include delta packages in your RELEASES from **just** the previous version and it works (v2 > v3 or v3 > v4). What doesn't work is having your v4 RELEASES having deltas from v2 > v3 > v4.

**Comment by amweiss** [comment]
Works for me, closing this out then.
