### ISSUE TITLE
Server Feed URL

### ISSUE THREAD

**Issue by rissem** [Squirrel/Squirrel.Windows#517]
I'm confused about how to implement the server side of the Squirrel Windows auto updater.

I came across "TODO about URL shit" on [the docs](https://github.com/Squirrel/Squirrel.Windows/blob/master/specs/Implementation.md#production--server-side) Maybe that's related? :-)

A simple example of the kind of HTTP request and response I could expect to see would be super helpful. I'm also happy to help out a bit with the docs if someone can point me in the right direction. Thanks!

**Comment by paulcbetts** [comment]
The only thing you do is take the Releases folder and put that up on a static file host site

**Comment by Thieum** [comment]
@rissem there is a section about Distributing in [the docs](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/readme.md) that shows how to use different ways to implement the server side of Squirrel.

@shiftkey this can be closed.
