### ISSUE TITLE
Request: Make RootAppDirectory as an option to Squirrel.exe

### ISSUE THREAD

**Issue by juturu** [Squirrel/Squirrel.Windows#518]
In Squirrel.Windows/src/Update/Program.cs, can the RootAppDirectory be bubbled up as an option to Squirrel.exe?

**Comment by paulcbetts** [comment]
I'm not sure what this would mean

**Comment by juturu** [comment]
I'm looking into changing the install location from %appdata%\Foo\Foo.exe to %appdata%\<Bar>\Foo\Foo.exe. Using Squirrel.exe i don't see a way to do this. Just looking into the code, i felt bubbling the RootAppDirectory as an option will help do that. Are there any implications due to this?

**Comment by juturu** [comment]
@paulcbetts can you please take a look at this?

**Comment by paulcbetts** [comment]
Sorry, this assumption is very built into lots of different parts of the library and is dangerous to change.
