### ISSUE TITLE
Per-machine installer downgrades application upgraded by silent install.

### ISSUE THREAD

**Issue by skaryshev** [Squirrel/Squirrel.Windows#523]
Found in 1.2.2. Steps to reproduce:
1. Install application version 1 by  per-machine installer
2. Build new release version 2 
3. Run application to let silent install upgrade to version 2
4. Logout. Login. Find application downgraded to version 1 (by per-machine installer I guess)

**Comment by dythim** [comment]
I've had the same issue.  Is there a suggested workaround?

**Comment by paulcbetts** [comment]
Hm, I'm not seeing this. Does this happen with the MSI file?

**Comment by skaryshev** [comment]
I releasify version 1 of App. Install MSI and  re-login. Now App v1 is installed by per-machine install. 
I releasify version 2 of App and  run App. Now App v2 is installed by silent install.
I re-login and and the per-machine installer runs and installs App v1 again.

**Comment by paulcbetts** [comment]
Hm, I just did exactly that with Slack and it worked. Did you change your NuGet Package ID in an update or something crazy?

**Comment by skaryshev** [comment]
I am looking through the code and MachineInstaller::ShouldSilentInstall should take care of my case and prevent install if  C:\Users\Username\AppData\Local\$pkgName\packages dir exists. Will rebuild and try again and rebuild debug and try again....

**Comment by skaryshev** [comment]
I think I found something:
src/Setup/MachineInstaller.cpp in `bool MachineInstaller::ShouldSilentInstall()` on line 140
installFolder is like C:\Users\Username\AppData\Local\\\$pkgName\packages
Note double backslash before pkgName. Because
`CString pkgName = CString(ourFile + fullPath.ReverseFind(L'\\'));` 
returns a leading backslash and
`wcscat(installFolder, L"\\");` on line 135 adds another backslash.
 Anyway MachineInstaller::ShouldSilentInstall() does not work for me as expected and returns true when we're already installed.

**Comment by skaryshev** [comment]
Found it! My problem was a dot in my package ID. I soon as I changed Package.Name to Package_Name the issue was resolved even with double backslash still in the path.
Thank you.

**Comment by SlySven** [comment]
> Found it! My problem was a dot in my package ID. I soon as I changed Package.Name to Package_Name the issue was resolved even with double backslash still in the path. Thank you.

Hang on - this is exactly the opposite of what the `nuget` documentation says: https://learn.microsoft.com/en-us/nuget/create-packages/creating-a-package#choose-a-unique-package-identifier-and-setting-the-version-number where it says to use '.' rather than '-' or '_' to separate components!

**Comment by caesay** [comment]
There are bugs in Squirrel when using dots or dashes in the package ID. Since this is no longer maintained, your best bet is to stick to underscores or find a different library.
