### ISSUE TITLE
unzip.h does not handle zero-length files

### ISSUE THREAD

**Issue by wjk** [Squirrel/Squirrel.Windows#526]
I was trying to use `unzip.h` as included in this library to extract a ZIP file for [my project](https://github.com/wjk/ChocolateyInstaller), only to find that this unzipping code cannot handle ZIP archives with zero-length files in it (such as the one I am working with). The unzipping library used here cannot distinguish between a legitimate zero-length file and an error condition. Is there any workaround? Thanks!

**Comment by paulcbetts** [comment]
Why will the embedded Zip include any zero-length files? Or are you trying to use unzip.h in your own project?

**Comment by wjk** [comment]
I am trying to use `unzip.h` in my own project, where zero-length files are used as a signal to another process (that I did not write). However, I was able to workaround the issue by checking the `ZIPENTRY::unc_size`, and seeing if the file is genuinely zero-length before returning an error.

**Comment by paulcbetts** [comment]
:sparkle:
