### ISSUE TITLE
No shortcuts created when executable name contains dot

### ISSUE THREAD

**Issue by JVimes** [Squirrel/Squirrel.Windows#530]
When my executable name contains a dot, no shortcuts are created. No error reported in SquirrelSetup.log. I have a single exe that is _not_ Squirrel-Aware.

**Comment by Lakritzator** [comment]
Some time ago I tried Squirrel.Windows and had a lot of problems, today I gave it another go thinking most issues might be solved by now.

Still couldn't get it working, whatever I tried.... there was no shortcut and the application also wasn't started.

Luckily I found this issue, and tried to use an executable without a dot in it.
Maybe there is a good reason for it, as long as there is no fix it would really help if this is documented somewhere.

@JVimes Thanks for reporting this, without your issue I would probably still be trying to make it work.

**Comment by Lakritzator** [comment]
Added a pull-request #536 for the documentation, just in case..

**Comment by JVimes** [comment]
Glad it helped! ☺ I lost hours to this, myself. Definitely needs to be documented until fixed.

**Comment by dennismi** [comment]
I have an _SquirrelAware App_ that contains dots in the exe and it is working fine.

**Comment by raybooysen** [comment]
This also causes issues elsewhere.  An app, for example, titled Foo.Bar.Baz, will have the folder in the user's profile created as Foo.  Additionally, no shortcuts are created.

**Comment by raybooysen** [comment]
Heavily related to #609

**Comment by Thieum** [comment]
@shiftkey duplicates #283 , this can be closed.
