### ISSUE TITLE
List of binaries to add to deployment

### ISSUE THREAD

**Issue by skaryshev** [Squirrel/Squirrel.Windows#531]
Getting Started page still reads  "Make sure to include Squirrel.dll and its dependencies too!" in "BETA: Some hacky notes that will go away soon" section.

Could you please confirm that we need to add all the following binaries to our application deployment.

DeltaCompressionDotNet.dll
DeltaCompressionDotNet.MsDelta.dll
ICSharpCode.SharpZipLib.dll
Microsoft.Data.Edm.dll
Microsoft.Data.OData.dll
Microsoft.Data.Services.Client.dll
Microsoft.Web.XmlTransform.dll
Mono.Cecil.dll
NuGet.Squirrel.dll
Splat.dll
Squirrel.dll
System.Spatial.dll

Thank you.

**Comment by paulcbetts** [comment]
I'm pretty sure those all get ILMerged

**Comment by skaryshev** [comment]
Sounds like I am missing something. There is no Squirrel.dll in the release package (https://github.com/Squirrel/Squirrel.Windows/releases/download/1.2.2/Squirrel.Windows-1.2.2.zip). So I rebuilt Squirrel.dll from source code in Visual Studio. And both Release and Debug do not ILMerge anything for me. Only CLBuild does ILMerge but on Update project. Could you please help me to get ILMerge'd Squirrel.dll?

**Comment by paulcbetts** [comment]
@skaryshev For C# projects, you should use the NuGet package, the release zip file is for non-C# projects

**Comment by skaryshev** [comment]
OK. I run `Install-Package squirrel.windows` and get 1.2.1 version of Squirrel.dll with size of 218K, which does not look like ILMerge'd either plus two more dlls. Also I am looking to build a signed version of the dll to link with my application. Any help to build up-to-date release quality version for Windows from the source code would be great ;).  
Thanks.

**Comment by skaryshev** [comment]
I see I need to add all 12 binaries to my deployment any way. Either directly or ILMerge them into one blob.
Thank you.
