### ISSUE TITLE
VSTO and Squirrel

### ISSUE THREAD

**Issue by aneeff** [Squirrel/Squirrel.Windows#534]
Hi,

I was able to use Squirrel installer with VSTO (I have a library that does all the registry entries for VSTO). basically the commandline install, update all works. but the SquirrelAwareApp events doesnt seems to be working.

below is my code:

        private void ThisAddIn_Startup(object sender, System.EventArgs e)
        {
            const string updateUrl = "E:\vstoupdate";
            const string ProductName = "MyRibbon";

           //Update and Install
            Task.Run(async () =>
                {

                    using (var mgr = new UpdateManager(updateUrl, ProductName))
                    {
                        SquirrelAwareApp.HandleEvents(onAppUpdate: v => UpdateRegistry(),
                                                    onInitialInstall: v => UpdateRegistry(),
                                                    onAppUninstall: v => Uninstall());
                        var updateInfo = await mgr.CheckForUpdate();
                        if (updateInfo.CurrentlyInstalledVersion.SHA1 != updateInfo.FutureReleaseEntry.SHA1)
                        {
                           var res= await mgr.UpdateApp();

                            MessageBox.Show($"release updated to {res.Version.Version.ToString()}");
                        }
                        mgr.Dispose();
                    }
                });

        }

The pacakge doesn't contain an exe though... could that be a problem. i've marked my assembly as SquirrelawareApp too.

**Comment by paulcbetts** [comment]
Only EXEs are scanned for Squirrel Awareness. You need to include a dummy EXE that will do your setup config stuff for you

**Comment by DavidHooper** [comment]
@aneeff do you have any resources available on how you used Squirell for VSTO installations?

**Comment by frederikstonge** [comment]
> @aneeff do you have any resources available on how you used Squirell for VSTO installations?

https://github.com/frederikstonge/sobeys-excel-addin

I managed to do it by having an external console app that is SquirrelAware, and the add-in calls that console app with a Process.Start.
