### ISSUE TITLE
Reference implementation of building Releases folder, can use in Quick Start?

### ISSUE THREAD

**Issue by JVimes** [Squirrel/Squirrel.Windows#540]
Building the Releases folder is awkward, which makes it hard to learn Squirrel. Ideally, a new user would hit Build and the Releases folder would pop out. A reference implementation of this would help them learn and get going right away.

I wrote [such a thing](https://github.com/JVimes/SquirrelProject) and if it passes review then I think linking to it from Quick Start would be valuable. Or including it there, somehow. Highlights:
- Try out the full install/update process right away, no config required (see readme).
- Readme explains how the Releases folder is built, and about this particular implementation.
- Build doesn't break on new versions of Squirrel.Windows and NuGet.CommandLine packages.
- It grabs some of the .nuspec metadata from Assembly Info (avoids duplicating values).
- Build works from msbuild.exe as well as Visual Studio.

If admins like my idea, then I just need my implementation code-reviewed and we can figure out the best way to include it in the docs and/or distribute it (project template, NuGet install, etc.).

**Comment by Thieum** [comment]
@JVimes The documentation now explains what gets created in the [Releases folder](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/2-packaging.md#releasify-output). If you think something should be added, please send a PR referencing this issue. If you feel like it's complete, you can close this issue.

**Comment by JVimes** [comment]
I'll close this one, as it's so old I have no idea if it's accurate. Thanks for the docs update.
