### ISSUE TITLE
Squirrel does not create installer in the releaseDir when executed from powershell

### ISSUE THREAD

**Issue by backpacked** [Squirrel/Squirrel.Windows#543]
When running the squirrel command from powershell, it does not create the installer in the releaseDir and also ignores --no-msi parameter.

Sample Script:
$buildDir = 'D:\builds'
$squirrelExe = join-path $buildDir 'tools/squirrel/squirrel.exe'
$releaseDir = 'D:\Releases\QA'
$nugetPackFile = join-path $buildDir 'App.5.0.5840.28508.nupkg'
if ((test-path $nugetPackFile) -and (test-path $squirrelExe)) {
    & $squirrelExe '--releasify' $nugetPackFile '--no-msi --releaseDir' $releaseDir
    }

Squirrel creates a Releases folder in the buildDir and places the installer there which is incomplete. Refer #542

**Comment by backpacked** [comment]
Fixed this issue. It is the way powershell handles arguments. I wish life was a simple as in bash but no.

If someone is interested:

Changes:
$buildDir = 'D:\builds'
$squirrelExe = join-path $buildDir 'tools/squirrel/squirrel.exe'
$releaseDir = 'D:\Releases\QA' #can also be '\\SERVERNAME\Releases\QA'

$nugetPackFile = 'App.5.0.5840.28508.nupkg'
if ((test-path $nugetPackFile) -and (test-path $squirrelExe)) {
    $squirrelArg1 = '--releasify=' + $nugetPackFile
    $squirrelArg2 = '--releaseDir=' + $releaseDir 
    & $squirrelExe $squirrelArg1 $squirrelArg2 '--no-msi'
}

**Comment by pltaylor** [comment]
@backpacked I'm running into this same issue.  I have tried your posted solution to no avail....do you have any further thoughts on this?

**Comment by backpacked** [comment]
@pltaylor can you post your code sample? Thanks.

**Comment by pltaylor** [comment]
@backpacked I actually asked a question over on stackoverflow and I got some good powershell advice but nothing that has solved my problem w/ squirrel.  My code and the suggestions can be found over at the [Stackoverflow Question](http://stackoverflow.com/questions/42147180/squirrel-powershell-file-is-not-creating-the-setup-exe/42147940#42147940)  I can post it here too if you would like but am trying to keep as much in one place as possible.

**Comment by backpacked** [comment]
I had a brief look at your code. Looks like your nugget file variable is not resolved. Try to use join-path.

For posterity it'd be nice to have the code posted here so that others don't have to jump out.

**Comment by pltaylor** [comment]
@backpacked Are you referring to $nugetPackFile?  It is dumping out ".\MyApp\MyApp.17.210.1.nupkg' in the log of the Team Services Build server.  My current code is 

Write-Host "Current Path  $env:Agent_BuildDirectory"
Write-Host "Build Number  $env:Build_BuildNumber"
$squirrel = Get-Item (Join-Path $env:BUILD_SOURCESDIRECTORY "packages\squirrel.windows.*\tools\Squirrel.exe") | select -First 1 -Expand FullName
$releaseDir = '.\Releases'
$nugetPackFile = ".\MyApp\MyApp.$env:Build_BuildNumber.nupkg"
Write-Host $squirrel
Write-Host $nugetPackFile

if((Test-Path $nugetPackFile) -and (Test-Path $squirrel)) {
    $squirrelArg1 = "--releasify=`"$nugetPackFile`""
    $squirrelArg2 = "--releaseDir=`"$releaseDir`""
    & $squirrel $squirrelArg1 $squirrelArg2 
}

**Comment by pltaylor** [comment]
@backpacked It appears with a little more googling I have been able to answer my question.  I found the answer [here ](https://github.com/Squirrel/Squirrel.Windows/issues/489)  w/ the '| Write-Output' option at the end.  My current code that works is as follows

Write-Host "Current Path  $env:Agent_BuildDirectory"
Write-Host "Build Number  $env:Build_BuildNumber"

$squirrel = Get-Item (Join-Path $env:BUILD_SOURCESDIRECTORY "packages\squirrel.windows.*\tools\Squirrel.exe") | %{
    if ($_ -match '.*\\squirrel\.windows\.(?<Major>\d+)\.(?<Minor>\d+)\.(?<Build>\d+)\\tools\\Squirrel\.exe') {
        (new-object -TypeName PSObject -Property $matches)
    }
} | sort @{e={$_.Major};a=0}, @{e={$_.Minor};a=0}, @{e={$_.Build};a=0} | select -First 1 -ExpandProperty '0'

Set-Alias Squirrel $squirrel

$releaseDir = '.\Releases'
$nugetPackFile = ".\HMSSim\HmsSim.$env:Build_BuildNumber.nupkg"
Write-Host $squirrel
Write-Host $nugetPackFile

if((Test-Path $nugetPackFile) -and (Test-Path $squirrel)) {
    Squirrel --releasify $nugetPackFile --releaseDir $releaseDir | Write-Output
}

**Comment by jguett** [comment]
Not a squirrel issue but I tried using line continuations for my script and which seemed to cause newlines in the corresponding arguments. The new line resulted in the release dir not getting parsed correctly.

start-process squirrel.exe `
-ArgumentList `
"--releasify=${pkg} `
--releaseDir=${release_dir} `
-l 'Desktop' `
-i ${icon} `
-setupIcon ${icon} `
-g ${splash}" `
-Wait

Once I collapsed it to a single line it worked fine.
