### ISSUE TITLE
Please add documentation for remove shortcut

### ISSUE THREAD

**Issue by provkristian** [Squirrel/Squirrel.Windows#546]
Could someone please add documentation for remove shortcut?

From looking at source and trial and error I found this to work:
C:\Users\youruser\AppData\Local\YourApp>Update.exe --removeShortcut=yourapp.exe

It seems like it should be much easier for new folks though.  Thanks.

**Comment by provkristian** [comment]
I probably should add for context that one of our use cases is to install an app and have it launch at startup.  So, we don't need desktop shortcuts and it seemed a bit much to add custom code just to remove shortcuts since the default setup.exe works for what we need.

I'm thinking for now that I'll just use powershell to run the installer (run by IS dept) and then let powershell call update.exe to remove the extra desktop shortcuts.  Thanks.

**Comment by paulcbetts** [comment]
@provkristian If you make your app Squirrel-aware, you can choose to not create desktop shortcuts. If your app is a C# app, this is only an extra ~10 lines of code

**Comment by provkristian** [comment]
@paulcbetts Thanks for the reply!  We'll consider that.

**Comment by provkristian** [comment]
Thanks again @paulcbetts .  I was able to use SquirrelAwareApp.HandleEvents() with no arguments and then in our CI where we run squirrel via powershell we just run:
.\packages\squirrel.windows.1.2.1\tools\Squirrel.exe --shortcut-locations='Startup' --releasify $package.name

Cheers.
