### ISSUE TITLE
No uninstall?

### ISSUE THREAD

**Issue by JakeGinnivan** [Squirrel/Squirrel.Windows#547]
I am not clear on the default behavior so the answer may just be I have to make my app squirrel aware, but is the default behavior *not* to add an entry into Programs and Features? I couldn't see anything in the docs.

Possibly related exception:

```
2016-01-08 10:15:13> ApplyReleasesImpl: Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
   at Squirrel.UpdateManager.ApplyReleasesImpl.<unshimOurselves>b__13_0(RegistryView view)
```

**Comment by paulcbetts** [comment]
The default behavior is to write an entry, you don't have to write it yourself. Not sure why it's not getting written

**Comment by JakeGinnivan** [comment]
Inside `HKEY_CURRENT_USER\Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags` I have no `Layers` key. That is causing the NullReferenceException

Am looking into why that would be, but more thoughts welcome

**Comment by paulcbetts** [comment]
@JakeGinnivan Don't worry about the AppCompat error, it's just a warning

**Comment by JakeGinnivan** [comment]
Pebkac! 

Had a empty `<title>` attribute in the nuspec

**Comment by JakeGinnivan** [comment]
Gonna submit a PR to the docs specifying the default behavior

**Comment by paulcbetts** [comment]
I'd take a PR to instead fail releasify
