### ISSUE TITLE
Squirrel update causes 401 on server with both Anonymous and Windows Authentication enabled

### ISSUE THREAD

**Issue by scionwest** [Squirrel/Squirrel.Windows#550]
I have published the squirrel `releasify` output to our webserver running IIS 8. The webserver has the MIME types enabled like described in the [Microsoft IIS docs](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/microsoft-iis.md). We've tried setting the MIME types on the server itself, and within the repository directory for the `releasify` output. The MVC project and server both use Windows Authentication for our internal website. When I use

    using (var updateManager = new UpdateManager("http://MyApp/Downloads", "MyApp"))
    {
        UpdateInfo updateInfo = await updateManager.CheckForUpdate();
    }

I receive a 401 status code which throws an exception. The /downloads folder is a virtual folder that points to a directory outside of the website itself. I'm able to navigate to `http://MyApp/Downloads/RELEASES` and download the file via Chrome or IE. Not sure why Squirrel wouldn't be authorized, unless it's missing credential info.

![failure](https://cloud.githubusercontent.com/assets/1865693/12275594/2da246fc-b92e-11e5-95f1-90b741e01e5a.PNG)

I've browsed the docs and don't see anything that screams to me i'm messing something up. Is there something I'm missing?

**Comment by paulcbetts** [comment]
No idea if we support NTLM Auth. This looks like an internal / LOB app - any reason not to just use a network share?

**Comment by scionwest** [comment]
It is an internal LOB app. I'm learning from other peoples misfortunes and trying to future proof myself a bit. We've had a couple other apps were their servers were replaced but the apps pointed to the server name for the update point. When the servers were discontinued, the app updater broke and they had to manually apply updates to several hundred machines. 

We already have a website for our LOB app, to download, get training etc. I wanted to mask the update process behind the domain name so we can change servers when ever and not worry about breaking the apps update process.

Worse case scenario is we can deploy to a file share. In the end, I'm trying to protect against poor coordination and planning on our side of the fence. I'd like to say we'd always plan for everything, but i'd rather play it safe.

**Comment by scionwest** [comment]
I see you have an IFileDownloader interface, could I implement my own to handle the request and pass along NTLM auth?

**Comment by paulcbetts** [comment]
Fair enough - in that case since you have control of the IIS Server, I'd just disable Windows Auth for the update folder

**Comment by scionwest** [comment]
I had Anonymous authentication enabled for the directory under IIS, but just realized that I had Anonymous Users denied under the .NET Authorization Rules in the IIS configuration. I created a rule that allowed it for that one folder, for GET verbs only. This seemed to solve my issue.
