### ISSUE TITLE
How does install path get calculated

### ISSUE THREAD

**Issue by JakeGinnivan** [Squirrel/Squirrel.Windows#552]
I am extending the docs around the naming of everything, docs include what info is pulled from the nuspec but things like `AssemblyProduct` take over in certain scenarios (shortcut names).

I want to change the install location from `%appdata%\Local\MyApp` to `%appdata%\Local\MyApp.Development` and can't figure out where MyApp is coming from.. it isn't the nuspec or the package name?

I've been looking through the source but i'm not that familiar and can't see it :( I will be submitting a PR with docs updates once I know this

**Comment by paulcbetts** [comment]
It's the NuSpec package ID

**Comment by JakeGinnivan** [comment]
Dashes ok? :P

**Comment by paulcbetts** [comment]
:+1:

**Comment by JakeGinnivan** [comment]
Thanks, PR submitted

**Comment by robertohuertasm** [comment]
It seems that dashes are causing issues too. I've been testing it and it causes the installation path to be cut: if your package Id is `myapp-staging` the installation path will be trucated to %appdata%\Local\myapp` causing issues if you have also `myapp-production` and so on.

**Comment by robertohuertasm** [comment]
See [ReleaseEntry.cs#68](https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/src/Squirrel/ReleaseEntry.cs#L68). Here is where the name of the folder package name is created and all dashes and dots are removed!!

Then, [here](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Update/Program.cs#L202) the `PackageName` property is used to build the installation path.

**Comment by robertohuertasm** [comment]
Is there a particular reason to remove the dashes?
