### ISSUE TITLE
How to release both x64 and ia32 versions

### ISSUE THREAD

**Issue by Kamahl19** [Squirrel/Squirrel.Windows#554]
Hi,

I need to release both 32bit and 64bit versions for Windows, however I am not really sure how to name and upload assets to github release.

I have /installers/ folder with 2 folders /win32-x64/ and /win32-ia32/ . Both these folders contain RELEASE, setup.exe and nupkg files.

I guess I can rename nupkg and and setup.exe files to include the platform (app-x64.nupkg, setup-x64.exe and app-ia32.nupkg, setup-ia32.exe). But what should I do with the RELEASES file? Can I simply concat RELEASES files into 2 and upload just that? 

Thanks for help

**Comment by paulcbetts** [comment]
You should just upload both folders to two separate URLs, you don't concat the RELEASES file. Have the client change the URL based on the architecture
