### ISSUE TITLE
Issue + fix proposal for shortcuts on Desktop

### ISSUE THREAD

**Issue by hcd** [Squirrel/Squirrel.Windows#557]
Hello,
We have an issue with "overwriting" shortcut links on the desktop. This is because we created different squirrel apps from the same build (which thus have the same "Application name" embedded in the EXE).
The problem is as follow : when our app is build, the outputted dropfolder is used to created different Squirrel apps for different environments with each a different squirrel package name, eg an APP_DEV, APP_UAT, APP_PRD. This works fine, until a user installs two packages side by side. They are correctly installed, but they overwrite each others shortcut on the desktop. I've looked into the Squirrel code, and in the ApplyReleasesImpl.linkTargetForVersionInfo , the possible names for the product are evaluated. These names all come somehow from the executable (from the ProductName, FileDescription, Filename..) 
Wouldn't it be possible to pass the wanted shortcutName to the RemoveShortcut & CreateShortcutMethods from within the application ? This way, the name can be decided at runtime e.g read from a config file. 
In the code it would only take a few lines, and not break any existing code. All it would take is add an optional argument "shortcutName"  to the Remove&CreateShortcut methods, pass this to the "linkTargetForVersionInfo" and put it as first in the posibleProductNames array.

That way, in our app, in the squirrel HandleEvents onAppUpdate and onAppUninstall, we can call 
                        _updateManager.CreateShortcutForThisExe(title);
                        _updateManager.RemoveShortcutForThisExe(title);
where "title" obviously comes from a config file or so, which differs per environment. So we have shortcuts "App name - DEV" , "App name - TST" , instead of just 1 shortcut "App name"

I hope this all makes sense and is feasible to add to this great product :)

Kind regards,
Sven.

**Comment by paulcbetts** [comment]
In this case, I would instead call https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.cs#L119 to get the ShellLink files we _would_ have saved, edit the name, then call "Save" on them
