### ISSUE TITLE
Icon in nuspec causes error in installation

### ISSUE THREAD

**Issue by stefanolson** [Squirrel/Squirrel.Windows#56]
if you add an icon to the nuspec file, e.g:
<iconUrl>http://localhost.fiddler:55910/testinst/icon.ico</iconUrl>
Then when set up runs it says there was an error during installation. You can see via fiddler that the icon is actually retrieved. If the URL is on localhost, then the setup log file is 0 bytes.  If it is on another machine then you get the error log without actually seeing what the error is.

**Comment by Thieum** [comment]
@stefanolson is it an issue you still experience in the latest version of Squirrel?

**Comment by stefanolson** [comment]
Is now installing, haven't been able to verify if the icon is working. But a bit more testing to do on that first but happy to close this one and open a new one if there are icon issues because is now a different issue.
