### ISSUE TITLE
Is there an option to not Launch MyApp after install?

### ISSUE THREAD

**Issue by provkristian** [Squirrel/Squirrel.Windows#560]
I was reading the help for update.exe and the help at install-process.md but have a question.  Is there an option to not Launch MyApp after install?  Thanks.

**Comment by paulcbetts** [comment]
The initial install gets the `--squirrel-firstrun` parameter, so you can see it and exit

**Comment by provkristian** [comment]
Ah, okay. Thanks.

**Comment by provkristian** [comment]
So, something like this then?
                                        SquirrelAwareApp.HandleEvents(
                                            null,
                                            null,
                                            null,
                                            onFirstRun: () => Process.GetCurrentProcess().Kill());

Unfortunately, the use case that we have is not a simple one.  We have an app that is supposed to run at startup after we do a machine install using our own shortcut.  We're using setup.exe --machine since the .msi has a bug.  Thanks.
