### ISSUE TITLE
Mono.Cecil question

### ISSUE THREAD

**Issue by skaryshev** [Squirrel/Squirrel.Windows#566]
One and the only place we currently using Mono.Cecil API is
`SquirrelAwareExecutableDetector.GetAssemblySquirrelAwareVersion`
This method may be easy re-implemented using regular System.Reflection calls. (I tried it and the tests passed with new implementation).
If we are not planning wider utilization of Mono.Cecil API in the future, we can eliminate this dependency entirely.

**Comment by paulcbetts** [comment]
The problem with trying to use Reflection is that you have to load the assembly, which means that it will try to load all of its children into your process, which has been Highly Problematic in the past (the original version of Squirrel would implement hooks as C# classes, and it was a disaster)

**Comment by skaryshev** [comment]
Well, to my surprise, according to MSDN https://msdn.microsoft.com/en-us/library/ms172331%28v=vs.110%29.aspx there is a way to load assembly without dependencies. It sounds like `Assembly.ReflectionOnlyLoadFrom`  loads assembly not into AppDomain but to isolated reflection-only context. Do you think it worth to try?

**Comment by paulcbetts** [comment]
@skaryshev Mayyyybe? We can try it I guess.

**Comment by skaryshev** [comment]
I am trying 'Assembly.ReflectionOnlyLoadFrom' now. One of the tests is failing
`SquirrelAwareExecutableDetectorTests.SquirrelAwareViaAssemblyAttribute' that one where the test is probing its own assembly for Squirrel awareness. I guess 'Assembly.ReflectionOnlyLoadFrom' does not allow loading assembly which is already in AppDomain. The rest of the tests are passing. How important for us is this particular test case? If it is important we can query AppDomain first to get already loaded assembly.

**Comment by skaryshev** [comment]
PR submitted for further discussion https://github.com/Squirrel/Squirrel.Windows/pull/567
