### ISSUE TITLE
Release binaries for `1.2.3`

### ISSUE THREAD

**Issue by unindented** [Squirrel/Squirrel.Windows#570]
Any chance of getting the latest `1.2.3` binaries on GitHub? Or should I be getting them from somewhere else?

**Comment by Thieum** [comment]
You can get those from nuget: https://www.nuget.org/packages/squirrel.windows/
It's a zip, and has the same content as the binaries zip:

![SquirrelZip](http://s11.postimg.org/p8q3oy3jn/Squirrel_Zip.png)

**Comment by unindented** [comment]
Ah awesome, thank you @Thieum!

**Comment by Thieum** [comment]
@shiftkey the binaries are available through the nuget package as suggested in https://github.com/Squirrel/Squirrel.Windows/issues/570#issuecomment-175683117 , otherwise the source is available [there](https://github.com/Squirrel/Squirrel.Windows/releases/tag/1.2.3). This can be closed.
