### ISSUE TITLE
How do I check if the app is installed via Squirrel?

### ISSUE THREAD

**Issue by JonasDralle** [Squirrel/Squirrel.Windows#574]
I want to distribute my app as Squirrel edition and Standalone edition (the standalone wont be able to update)

How can I find out weather an app is installed via Squirrel or not?
My current method of determining isn't very good especially becaue you guys just used System.Execption instead of something like NonSquirrelInstallationException

            UpdateManager updateManager;

            try
            {
                updateManager = new UpdateManager("https://company.com/software/releases");
            }
            catch (Exception exe)
            {
                if (exe.Message.Contains("Update.exe not found"))
                {
                    //This isn't an squirrel installed app
                    return;
                }

                //throw everything else
                throw exe;
            }

**Comment by JonasDralle** [comment]
If you don't have a good solution I would like it if you could implement one

**Comment by paulcbetts** [comment]
```cs
var assembly = Assembly.GetEntryAssembly();
var updateDotExe = Path.Combine(Path.GetDirectoryName(assembly.Location), '..', 'Update.exe');
var isInstalled = File.Exists(updateDotExe);
```

**Comment by JonasDralle** [comment]
oh thank you

**Comment by quasarea** [comment]
It looks like this does the job:

    var updates = await updateManager.CheckForUpdate();
    if (updates.CurrentlyInstalledVersion == null) { 
      //Seems like this is not a squirrel installation, running within VisualStudio perhaps?
      MessageBox.Show("Unknown current version - possibly application was not installed correctly");
    } else if (updates.ReleasesToApply.Any()) {
      //Squirrel installation with updates to apply
      await updateManager.DownloadReleases(updates.ReleasesToApply);
      await updateManager.ApplyReleases(updates);
      await updateManager.UpdateApp();
    }

**Comment by GregWilliamBryant** [comment]
> It looks like this does the job:
> 
> ```
> var updates = await updateManager.CheckForUpdate();
> if (updates.CurrentlyInstalledVersion == null) { 
>   //Seems like this is not a squirrel installation, running within VisualStudio perhaps?
>   MessageBox.Show("Unknown current version - possibly application was not installed correctly");
> } else if (updates.ReleasesToApply.Any()) {
>   //Squirrel installation with updates to apply
>   await updateManager.DownloadReleases(updates.ReleasesToApply);
>   await updateManager.ApplyReleases(updates);
>   await updateManager.UpdateApp();
> }
> ```

This is a more reliable way to check, although both are problematic as update.exe can be present if the application is not installed  (for example running in visual studio).  Although update.exe is present, other dependent files are not (for example the releases file) if not 'installed'.
