### ISSUE TITLE
Install causes symantec to quarantine

### ISSUE THREAD

**Issue by dasjestyr** [Squirrel/Squirrel.Windows#576]
Symantec reports SONAR.RogueAV!gen14 again update.exe and quarantines it causing install to fail and symantec forces me to restart my computer.

**Comment by provkristian** [comment]
We've seen this too.  You might need to have your organization create an exception.

**Comment by paulcbetts** [comment]
Sign your application and this will most likely go away. Also, uninstall Symantec forever and ever

**Comment by dasjestyr** [comment]
I can't just have the corporation add an exception like this and I definitely just cant tell them to ditch symantec, as much as I'd like them to. Unfortunately, I just won't be able to use this solution.

**Comment by paulcbetts** [comment]
Sign the application?
