### ISSUE TITLE
SquirrelTemp takes up a lot of space

### ISSUE THREAD

**Issue by threecleartones** [Squirrel/Squirrel.Windows#577]
Sorry if this is an Atom issue and not a Squirrel issue, but I was going through my WinDirStat results and found the following directory:

\AppData\Local\SquirrelTemp

which currently has 8 directories in it called tempa, tempb, tempc, etc. through temph. All told they're currently taking up 718 megs of space. Each one has (in addition to various other files/dirs) a file called "atom.nuspec" so this may be an Atom question, but my question is: can I delete these temp directories to reclaim disk space?

thanks!

**Comment by paulcbetts** [comment]
Not sure why these are piling up, but yeah, it is 100% safe to delete that entire directory

**Comment by threecleartones** [comment]
awesome thanks!

**Comment by ChathuraGH** [comment]
I had the same problem, sub folders contain multiple copies of atom.exe.
It was 786MB and 26,576 files and 9167 folders. Even long after I uninstalled atom. I am deleting this folder now.
