### ISSUE TITLE
ICSharpCode.SharpZipLib.dll as a dependency

### ISSUE THREAD

**Issue by MatthewSteeples** [Squirrel/Squirrel.Windows#583]
Is there a reason that SharpZipLib is included as it's own reference in the NuGet package and not a dependent package? We already depend on this library in our app, so having a second instance of it with a different publickeytoken is going to be problematic

It looks like it's possibly been recompiled to target .net 4, but that shouldn't be necessary as you can use v2 dlls in v4 apps

**Comment by paulcbetts** [comment]
Yes, it's a patched version, I can't remember what the patch is though

**Comment by MatthewSteeples** [comment]
Thanks for that. It looks like some changes were made around tar files. I considered relying on the version that you were shipping for our zip functionality instead of the other NuGet package, but in the end decided to depend on the ZipArchive class in the framework itself (as we don't need anything fancy, and the only reason we used that library in the first place was because this app used to be a .net 2.0 app)
