### ISSUE TITLE
Squirrel package manager

### ISSUE THREAD

**Issue by tenacious** [Squirrel/Squirrel.Windows#585]
if anyone is interested i've made this utility , similar to Nuget Package Manager, but thinked for Squirrel.

App Workflow :

1. **Update Application Version .**  the package version is extracted from exe file , you don't need to set this value manually

2. **Create Squirrel Package** . In similar way you do with Nuget Package Manager, just drag the file you want into window. No need to create lib/net45 folder.

3. **Upload installer files** . Set connection details one time . At now only on Amazon S3

4. **Decide to upload only the updated files or do complete setup upload** . 

Source Code at : [https://github.com/tenacious/Auto.Squirrel](https://github.com/tenacious/Auto.Squirrel)

**Comment by stajs** [comment]
Great idea!

**Comment by paulcbetts** [comment]
This is great!

**Comment by tenacious** [comment]
Hi Paul, it's not clear to me , i just started using squirrel, i know only basic stuff..

Anyway another main feature to add could be **adding prerequisites to installer** .
From gui you have a list of available prerequisites, similar to clickonce.

The approach i have in mind to install prerequisites is **leverage on Chocolatey** , so you can just send command to cmd console. 

For example if you need *Visual C++ Redistributable 2010* , programatically send to console  
```
choco install vcredist2010
```
In my opinion the best place to add this in code, is where Setup.exe detect and install .NET 4.5 if missing.

Could be an idea ?

**Comment by paulcbetts** [comment]
@tenacious I'm not as excited about that one - most of those require UAC elevation, and the only one you really need at the moment is .NET 4.6 if you depend on it, and we've got a better proposal to solve that.

(PS: Starting with at least VS2013, you can just ship the VC++ Redist DLLs in your app, no need to ask users to install a separate package system-wide)

**Comment by tenacious** [comment]
@paulcbetts Yes, you are right, also another down side can be the fact you have to visualize the powershell on screen to install packages..
