### ISSUE TITLE
Problem with multi user machine

### ISSUE THREAD

**Issue by teocomi** [Squirrel/Squirrel.Windows#586]
An app with a Squirrel installer is not working on machines with multiple users (while it works correctly on single user machines):

- user A logs into the machine and installs the apps, it works fine
- user A logs out and then in again and the squirrel files are gone (Update.exe) but the app-X.X.X folder is still there
- another user B has the Update.exe in his localappdata folder but he never run the squirrel installer

Anyone else having the same issue? Any possible way to avoid it?

**Comment by paulcbetts** [comment]
This sounds like Antivirus

**Comment by teocomi** [comment]
@paulcbetts I've checked the log and found I had erroneously put a registry key with the --install flag to autostart the app, it was conflicting with the running app and partly deleting its files.

It could be helpful having Squirrel to check for any running instance before attempting installing an app. 

Thanks

`2016-02-04 15:39:59> Program: Starting Squirrel Updater: --install . --checkInstall --silent
2016-02-04 15:39:59> Program: Starting install, writing to D:\Users\myuser\AppData\Local\SquirrelTemp
2016-02-04 15:39:59> Program: About to install to: D:\Users\myuser\AppData\Local\MyApp
2016-02-04 15:39:59> Program: Install path D:\Users\myuser\AppData\Local\MyApp already exists, burning it to the ground
2016-02-04 15:39:59> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.`

**Comment by paulcbetts** [comment]
> It could be helpful having Squirrel to check for any running instance before attempting installing an app.

The problem is that if you do this and users have a corrupted / messed up install, they can never reinstall - Squirrel install needs to be able to work even when the apps are in an invalid state / don't respond correctly. Instead we'll probably end up killing all of the processes belonging to the package
