### ISSUE TITLE
Two previous versions of the installed app remain in AppData Local after update.

### ISSUE THREAD

**Issue by MarkAJones** [Squirrel/Squirrel.Windows#589]
Initially the Folder in AppData will have 
- app-xxx (folder)
- packages (folder)
- App.ico
- Update.exe

If the application detects an update and downloads it, a new app-yyy folder is created
(as app-xxx is in use)

When the application is relaunched it will run from app-yyy (as expected)
but app-xxx remains

Later when app-zzz is updated, the app-xxx will be removed, but not app-yyy

I guess the suggestion is that Update.exe should remove the previous version when it starts running from the new folder, so there is only more than one while the update rollover is occurring.

Currently it looks like the download process tries to clean up, what it can, but not the startup process.

**Comment by paulcbetts** [comment]
Yep, this is by-design, we always have two versions of the app

**Comment by mafer31** [comment]
The updates are made but my application does not run with the latest version, can you help me please?

**Comment by vnikiti** [comment]
> 
> 
> The updates are made but my application does not run with the latest version, can you help me please?

I am running into the same issue

**Comment by RareScrap** [comment]
> Yep, this is by-design, we always have two versions of the app, the current and previous ones

I have two questions about this behavior:
1) What is the reason of keeping the previous version?
2) Can the previous version be safely removed by my app logic?
