### ISSUE TITLE
releasify - icon

### ISSUE THREAD

**Issue by tenacious** [Squirrel/Squirrel.Windows#592]
**I'm trying to customize desktop shortcut name and icon.**

Looking at the [code](https://github.com/Squirrel/Squirrel.Windows/blob/c86d3d0f19418d9f31d244f9c1d96d25a9c0dfb6/src/Update/Program.cs) this should be possible : 

```
{ "i=|icon", "Path to an ICO file that will be used for icon shortcuts", v => icon = v},
{ "setupIcon=", "Path to an ICO file that will be used for the Setup executable's icon", v => setupIcon = v},
```

My releasify command become : 

```
 -releasify C:\<path-to>\\NCWOP.2.0.0.31.nupkg -releaseDir C:\<path-to>\Releases\ -icon C:\Users\User\Documents\Visual Studio 2015\Projects\ECam\ECAM_Installer\Custom\appIcon.ico
```

The local path to icon is correct . I can't get it work also with -setupIcon parameter.

![icon_path](https://cloud.githubusercontent.com/assets/1358065/12866267/b413ce10-ccc8-11e5-93fa-38852478d392.png)

Also is possible pick the shortcut name from linked application exe ?

**Comment by dannylindquist** [comment]
I just ran into the same problem and got it to work with this..
`Squirrel --releasify .\App1.0.0.nupkg --setupIcon D:\path\to\icon\Icon.ico`
I do recommend the documentation be a bit more clear on how this tag is to be used.

**Comment by tenacious** [comment]
thanks Danny, i'll check if i can this things works.

2016-03-11 0:52 GMT+01:00 danny <notifications@github.com>:

**Comment by cprcrack** [comment]
Cannot get it to work, the icon of the exe file is always the following:

![screenshot](https://cloud.githubusercontent.com/assets/650925/25490570/88f6efbe-2b6d-11e7-8bcf-291cc1746c95.png)

**Comment by dannylindquist** [comment]
@cprcrack I am running windows 10 and am still having success. Would you mind providing the full command you are running. It may be easier to diagnose if I could see it.

**Comment by cprcrack** [comment]
@dannylindquist I am using the following in .csproj:

`squirrel --releasify $(OutDir)AdaptiveTaskbar.$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3)).nupkg --no-msi --setupIcon icon64.ico`

But guess what, I rebooted Windows and now it works, so it probably was something that was cached.

**Comment by Robbos** [comment]
@cprcrack I also didn't see the icon change because of the Windows icon cache.
You can clear it using Windows Run (Win + R).
`ie4uinit.exe -ClearIconCache`
Then restart explorer.exe.

**Comment by Thieum** [comment]
@tenacious considering your [last comment](https://github.com/Squirrel/Squirrel.Windows/issues/592#issuecomment-195229770), is it an issue you are still experiencing? if not, you can close this issue.
