### ISSUE TITLE
Does Squirrel needs previous release to build next one?

### ISSUE THREAD

**Issue by tbitowt** [Squirrel/Squirrel.Windows#593]
Hello

I have one problem with building squirrel releases:

While building release it looks like it needs all previous releases to build next one. How does it work?

Do I really need to keep all `*.nupkg` items in my repository to have a history of it? Or can I just build new version and copy only `*-full.nupkg` , new `*.exe` file and a simple line from RELEASES and attach it to my ftp server?

**Comment by geary** [comment]
The reason for keeping the previous releases is to allow Squirrel to build delta update files. Delta updates can be *much* smaller than a full update, but Squirrel has to have a copy of the previous release to build a delta update.

If you don't care about delta updates, you don't need the previous release files - you can just do as you described - but you'll be missing out on a major benefit of using Squirrel. Every one of your updates will be a full update.

Where you keep the previous release files is up to you - in your repository, in an S3 bucket or the like, or whatever.

**Comment by shiftkey** [comment]
Seconding what @geary said here.

Previous releases are required to support delta packages, and delta packages can save your users (and your infrastructure) on bandwidth costs. Highly recommended.
