### ISSUE TITLE
Cannot read from Settings file.

### ISSUE THREAD

**Issue by sharok** [Squirrel/Squirrel.Windows#594]
I have installed application builded by Squirrel. But my program crashed when I make some action. In the windows logs I found the following:
```
System.NullReferenceException
   in BestApp.Winapp.Configuration.BestAppSettings.get_AccessTokenExpiredAt()
```

It cannot read from Settings file.
When I run app from Visual Studio all works fine. I used ClickOnce before and all worked fine also.

Where is a problem?

**Comment by paulcbetts** [comment]
Settings files don't work with Squirrel, you'll have to use something else

**Comment by sharok** [comment]
We use it a lot. Ok. Thanks.
