### ISSUE TITLE
Couldn't acquire lock, is another instance running.

### ISSUE THREAD

**Issue by ArcadeRenegade** [Squirrel/Squirrel.Windows#599]
Hi again,

One of my users is getting this error when trying to run Setup.exe

https://i.imgur.com/jUNGoMK.png

Couldn't acquire lock, is another instance running.

From the call stack it looks like it is occuring during UpdateManager.CheckForUpdate

Any idea why this is occurring? I dove into another thread regarding this but it was way over my head.

For context, this is the code for the update check:

```
try
{
    using (UpdateManager _manager = new UpdateManager(ConfigurationManager.AppSettings["CurrentReleaseURL"]))
    {
        UpdateInfo _update = await _manager.CheckForUpdate();

        if (_update.ReleasesToApply.Any())
        {
            Version _newVersion = _update.ReleasesToApply.OrderByDescending(r => r.Version).First().Version.Version;

            Update _updateWindow = new Update();
            _updateWindow.Show();

            await _manager.UpdateApp((p) => _updateWindow.SetProgress(p));

            _updateWindow.Close();

            string _newExePath = Utilities.Paths.Exe(_newVersion);

            if (Framework.Settings.Instance.RunAtStartup)
            {
                Utilities.Startup.EnableStartupTask(_newExePath);
            }

            Process.Start(_newExePath);

            Shutdown();
        }
        else if (showInfo)
        {
            MessageBox.Show(Constants.Generic.UPDATEMSG, Constants.Generic.PROGRAMNAME, MessageBoxButton.OK, MessageBoxImage.Information, MessageBoxResult.OK, MessageBoxOptions.DefaultDesktopOnly);
        }
    }
}
catch (WebException)
{
    if (showInfo)
    {
        MessageBox.Show(Constants.Generic.UPDATEERROR, Constants.Generic.UPDATEERRORTITLE, MessageBoxButton.OK, MessageBoxImage.Error, MessageBoxResult.OK, MessageBoxOptions.DefaultDesktopOnly);
    }
}
```

Edit: Correction, it installed correctly. This error still occurs when he runs my app though.

Edit2: For more context, the update occurs in my WPF app during my override App.OnStartup() after base.OnStartup(). Perhaps I should do the update later on in the app or delay it?

**Comment by gojanpaolo** [comment]
@ArcadeRenegade are you still experiencing this issue with the latest version of Squirrel?

**Comment by ArcadeRenegade** [comment]
I haven't tested the latest version of Squirrel, sorry.

**Comment by shiftkey** [comment]
Closing this out due to incomplete information about the issue.

> Perhaps I should do the update later on in the app or delay it?

Side note: I wouldn't check for updates at launch - the user has more important things to do than deal with them (or even be held up by these checks).
