### ISSUE TITLE
What are the requirements for Update.exe --update=https:// to work?

### ISSUE THREAD

**Issue by demetris-manikas** [Squirrel/Squirrel.Windows#618]
I am getting a "Could not create SSL/TLS secure channel." error when trying to use autoUpdates.

I suspect that some requirements concerning https are not met by our server since
when i run Update.exe --update="https://google.com" I get a 404 expected error but 
Update.exe --update="https://myserver.com" gives me the above mentioned error.

**Comment by paulcbetts** [comment]
Sounds like your certificate is invalid maybe?

**Comment by demetris-manikas** [comment]
You can see for yourself that this is not the case by visiting
 https://www.ssllabs.com/ssltest/analyze.html?d=crypho.com&hideResults=on

**Comment by paulcbetts** [comment]
Hm, you might have to debug into Update.exe and poke around a bit.

**Comment by demetris-manikas** [comment]
Well after searching a bit I found out that I had to enable TLS.1 and TLS1.1 for the update to work..
Allowing  only TLS1.2 on server doesn't seem to be supported.

**Comment by paulcbetts** [comment]
Fixed in https://github.com/Squirrel/Squirrel.Windows/commit/b464b41bb243380c5acad82f3336ff7c9b1e4cb3

**Comment by reach2deep** [comment]
@demetris-manikas I have same issue. are you using your own domain to update or using the Github update manager?

**Comment by demetris-manikas** [comment]
I use my own domain to update. But this issue seems to have been resolved a month now. 
Are you using one of the releases that include the fix?

**Comment by reach2deep** [comment]
Thanks for the reply @demetris-manikas . i have few doubts, when we use our own domain, **do we need to host any files in our IIS** to check the version like below, because its looking for the below path to get the version information, but there is nothing like that in server.  Can you give me some guidance to setup the update server methods in IIS please

http://10.10.1.120/Builds/RELEASES?id=SME&localVersion=16.8.9&arch=amd64

**Comment by demetris-manikas** [comment]
@reach2deep You will need to have a server app that parses the info from the request decides whether an update exists based on client version and arch and serve the proper RELEASES content.

**Comment by reach2deep** [comment]
@demetris-manikas  yes, as you said am looking for server app.  is server app source is also in this repository? do i want to write my own?

**Comment by demetris-manikas** [comment]
@reach2deep  You have to write your own or use one of the following that the autoUpdater module suggests: nuts, electron-release-server, squirrel-updates-server.

**Comment by paulcbetts** [comment]
Pull over, you don't need a server In General to use Squirrel.Windows. Only if you want this non-standard "Server decides version to serve up" behavior. You can just use S3 or any other static file host

**Comment by reach2deep** [comment]
@paulcbetts, @demetris-manikas  yes, my requirement is simple like you said, looking for static file hosting, where Squirrel will just download like specifying local folder path(D://myApp). i tried the [Hosting on IIS](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/microsoft-iis.md) . it doesn't work,

This is my IIS folder strructure with the webconfig as specified. but no luck, do i miss anything ?? Please advise

[IIS Folder structure](https://s31.postimg.org/cd88nkyvv/squi.png)

**Comment by reach2deep** [comment]
@demetris-manikas  please see my above comment and correct me if am wrong

**Comment by demetris-manikas** [comment]
I guess @paulcbetts  can help you with the static file hosting. I am no expert on the matter. Cheers
