### ISSUE TITLE
Use DNX instead of having .Net 4.5 dependency?

### ISSUE THREAD

**Issue by aplex** [Squirrel/Squirrel.Windows#619]
Are there any plans to use DNX for Squirrel? This will make the installer a stand-alone application and remove dependency on .Net 4.5 installation (because a smaller version of.Net will be bundled with the installer). 

This will help using Squirrel on plain Windows 7, which is still the most popular version of Windows. Currently people have to wait for .Net installation to complete, even if the app is not dotnet-based (like electron apps). Also they need admin permissions to complete .Net installation.

Additional benefit of migrating to DNX will be the ability to run the same, or very similar, version of Squirrel on Windows, Mac and Linux hosts.

**Comment by flagbug** [comment]
We would need a GUI toolkit that works with DNX for displaying the animated GIF at the beginning. Is there such a thing?

**Comment by dealproc** [comment]
is https://github.com/perspex/perspex (i think) there yet?  If not, may be interesting to observe and see what is possible.

**Comment by flagbug** [comment]
I think Perspex is just using the native GUI on each platform, i.e WPF on Windows, which still requires the full .NET Framework

**Comment by paulcbetts** [comment]
It sounds like a massive amount of work to support a platform that is 6 years old. While it would be cool to see it work, it's almost certainly more trouble than it's worth.
