### ISSUE TITLE
msi not working with group policy

### ISSUE THREAD

**Issue by dannylindquist** [Squirrel/Squirrel.Windows#624]
I am running into a problem when using Group Policy to deploy using the msi generated by Squirrel. It appears that I can add the msi as a new package in group policy, but it disappears shortly after. Is there a fix for this.

Our use case is such that we want all the software to be installed for everyone in the office without anyone having to go run the setup.exe file themselves.

What are my options here?

**Comment by lehne** [comment]
@dannylindquist did you solve this? I'm getting the same issue...

**Comment by dannylindquist** [comment]
I abandoned my efforts after nobody got back to me on it. Sorry.. Though I'll reopen and see if someone could help out with this.

**Comment by paulcbetts** [comment]
What do you mean by "it disappears"?

**Comment by dannylindquist** [comment]
@paulcbetts After attempting it again just now, I didn't have any problems, but we have moved away from using group policy with our squirrel applications. @lehne you will have to give a better description of what you are experiencing.

**Comment by lehne** [comment]
It looks like it adds to the group policy but then when I close that policy and reopen it, the file is gone. Perhaps my nuspec is wrong? The regular installer works great.

**Comment by Thieum** [comment]
@shiftkey initial issue was resolved, this can be closed.
@lehne if you still experience any issue with the latest version of Squirrel, please open a new issue that describes the problematic behavior.
