### ISSUE TITLE
Couldn't rewrite shim RegKey, most likely no apps are shimmed:

### ISSUE THREAD

**Issue by prabathsl** [Squirrel/Squirrel.Windows#628]
Couldn't rewrite shim RegKey, most likely no apps are shimmed: System.NullReferenceException: Object reference not set to an instance of an object.
at Squirrel.UpdateManager.ApplyReleasesImpl.b__f5(RegistryView view)

And i Haven't any tag with empty in nugspec

**Comment by paulcbetts** [comment]
Don't worry about this, it's just a warning

**Comment by ankurdeshmukh87** [comment]
Is it really just a warning? It is blocking me from installing the Atom editor
