### ISSUE TITLE
get a release not before downloading update 

### ISSUE THREAD

**Issue by reguez** [Squirrel/Squirrel.Windows#629]
hello isnt a good idea to get the release notes to the user before making the update ?

**Comment by wesleywesley** [comment]
yes, thats how it should be :-)

**Comment by shiftkey** [comment]
While the examples show the simple path of "just update the app" there is an advanced flow if you want to check for updates and show the release notes:

```c#
using (var manager = new UpdateManager("https://server.com/updates/my-cool-app"))
{
    var updateInfo = await manager.CheckForUpdate();
    if (updateInfo != null)
    {
        var releaseNotes = updateInfo.FetchReleaseNotes();
        // TODO: display something to the user
    }
}
```

The rest of the flow is outlined here:

https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/update-manager.md#advanced-updating
