### ISSUE TITLE
A simple way to package an app

### ISSUE THREAD

**Issue by poma** [Squirrel/Squirrel.Windows#630]
I'm not sure why documentation recommends things like OctoPack and Auto.Squirrel when packaging can be easily integrated directly into build process using only nuget and squirrel. Just define a build target in .csproj file:

``` xml
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
  <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
    <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo"/>
  </GetAssemblyIdentity>
  <Exec Command="nuget pack MyApp.nuspec -Version %(myAssemblyInfo.Version) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
  <Exec Command="squirrel --releasify $(OutDir)MyApp.%(myAssemblyInfo.Version).nupkg" />
</Target>
```

this will generate a nuget package from .nuspec file setting version from AssemblyInfo.cs and place it in OutDir (by default `bin\Release`). Then it will generate release files from it.

Here is an example .nuget file for myApp:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  <metadata>
    <id>MyApp</id>
    <!-- version will be replaced by MSBuild -->
    <version>0.0.0.0</version>
    <title>title</title>
    <authors>authors</authors>
    <description>description</description>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <copyright>Copyright 2016</copyright>
    <dependencies />
  </metadata>
  <files>
    <file src="*.*" target="lib\net45\" exclude="*.pdb;*.nupkg;*.vshost.*"/>
  </files>
</package>
```

Solution needs to have `nuget.exe` available for example by installing `NuGet.CommandLine` package. And also it suffers from this bug when sometimes NuGet packages are not loaded properly and throws `nuget/squirrel is not recogized (9009)` errors.

> you may simply need to restart Visual Studio so the Package Manager Console will have loaded all the package tools

Other than that I think it's the simplest solution that fits most simple apps and should be recommended in Getting Started tutorial. I'm not sure whether including `nuget.exe` in squirrel package is a good practice but it could eliminate an additional dependency on `NuGet.CommandLine` and make MSBuild integration work out of the box.

**Comment by kenbailey** [comment]
@poma, thanks for the description of the steps. I've created some initial docs you can checkout on my [docs-vs-package branch](https://github.com/kenbailey/Squirrel.Windows/blob/doc-vs-packing/docs/using/visual-studio-packaging.md). Feel free to submit a PR based on it or send me comments of any updates and I will submit a PR. 

My initial thought is to keep the Package Manager GUI on the getting started and simply provide a quick link to this approach. 

Thanks again!

**Comment by HalidCisse** [comment]
Tried this method run into these issues :
`EXEC : warning : 204 issue(s) found with package 'myApp'.
8>   (TaskId:177)
8>  Issue: Assembly outside lib folder. (TaskId:177)
8>  Description: The assembly 'af\Humanizer.resources.dll' is not inside the 'lib' folder and hence it won't be added as 
8>  reference when the package is installed into a project. (TaskId:177)
8>  Solution: Move it into the 'lib' folder if it should be referenced. (TaskId:177)
8>   (TaskId:177)`

`Done executing task "Exec". (TaskId:177)
8>Task "Exec" (TaskId:178)
8>  Task Parameter:Command=squirrel --releasify bin\Release\myApp.1.0.0.0.nupkg --no-msi (TaskId:178)
8>  squirrel --releasify bin\Release\myApp.1.0.0.0.nupkg --no-msi (TaskId:178)
8>C:\projects\myApp.csproj(1815,5): error MSB3073: The command "squirrel --r
8>eleasify bin\Release\myApp.1.0.0.0.nupkg --no-msi" exited with code -1.
8>Done executing task "Exec" -- FAILED. (TaskId:178)
8>Done building target "AfterBuild" in project "myApp.csproj" -- FAILED.: (TargetId:261)`

**Comment by mbulava** [comment]
Using this approach I keep getting error:
5>  'squirrel' is not recognized as an internal or external command,
5>  operable program or batch file.

I've restarted VS serveral times, and the end goal is to get this to work on my Build server...  Any ideas Suggestions?

**Comment by HalidCisse** [comment]
it never worked for me too

**Comment by poma** [comment]
Probably because Visual Studio can't find squirrel.exe or nuget.exe. If you have corresponding NuGet packages installed VS will load paths after you open Package Manager Console window. Otherwise just use full paths to exe files.

**Comment by cburman01** [comment]
@Poma This was a great idea. Thanks!

**Comment by agostinocinelli** [comment]
My 2 Cents:
Add
 ```
<files>
    <file src="*.*" target="lib\net45\" exclude="*.pdb;*.nupkg;*.vshost.*"/>
    <file src="**\*.*" target="lib\net45\" exclude="*.pdb;*.nupkg;*.vshost.*"/>
  </files>
```
to include all subfolder recursively.
It would be nice adding it in docs
[https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/visual-studio-packaging.md](url)

**Comment by celeron533** [comment]
I restarted the VS several times but still got nuget 9009 error.
After re-installed the NuGet Package Manager in VS, it works. :thumbsup:

**Comment by poma** [comment]
@celeron533 probably you didn't open Package Manager Console after restarting VS to scan for executable tools. I've made a pull request #830 that clarifies how to avoid that error but it is still pending.

**Comment by pdinnissen** [comment]
Version 1.5 breaks this.  The Revision needs to be stripped from the Version string:
`$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3))`
(credit to http://stackoverflow.com/a/32855014)
Or better yet maybe there's a way to use the AssemblyInformationalVersion instead since that's what typically used by nuget by default?

**Comment by Yitzchok** [comment]
In order to find squirrel.exe you can use [MSBuild Transforms](https://msdn.microsoft.com/en-us/library/ms171476(v=vs.80).aspx)

Example see **@(squirrelPackage->'%(fullpath)')**
```
<ItemGroup>
   <SquirrelPackage Include="..\..\packages\squirrel.windows.*\tools\Squirrel.exe" />
</ItemGroup>


<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
  <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
    <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo"/>
  </GetAssemblyIdentity>
  <Exec Command="nuget pack MyApp.nuspec -Version %(myAssemblyInfo.Version) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
  <Exec Command="@(squirrelPackage->'%(fullpath)') --releasify $(OutDir)MyApp.%(myAssemblyInfo.Version).nupkg" />
</Target>
```

**Comment by poma** [comment]
Nice! Can you make a pull request?

**Comment by agostinocinelli** [comment]
I'm facing another problem:
When I run "squirrel --releasify XYZ.nupkg" in PackageManagerConsole, output files are generated in (SolutionFolder)/Released
When VS runs the same command in the .csproj, the files are generated in (SolutionFolder)/(MainProjectFolder)/Releases

How can i specify output dir? Am I missing smt?

**Comment by markfox1** [comment]
@poma's solution, with some additions from the conversation here, very nearly works for me. I'm working in VB, so there are some slight differences, but it basically works. I agree with @agostinocinelli that it seems a little off-putting to have the Releases folder showing up under the project folder and not the solution folder. I'd like to better understand the implications for multi-project solutions.

Anyways, here is what worked for me:

```
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo"/>
    </GetAssemblyIdentity>
    <Exec command="..\packages\Nuget.CommandLine.3.5.0\tools\nuget pack SquirrelTest.nuspec -Version %(myAssemblyInfo.Version) -Properties Configuration=Release" />
    <Exec Command="..\packages\squirrel.windows.1.5.2\tools\squirrel --releasify SquirrelTest.$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3)).nupkg" />
</Target>
```

I don't like having the versions of squirrel and Nuget in the Exec, but @Yitzchok's solution didn't work because of spaces in one of the parent directories containing this code.

**Comment by markfox1** [comment]
@agostinocinelli, the only thing you are missing to get Squirrel to output to another directory is the documentation for the Squirrel [command-line arguments](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/squirrel-command-line.md).

**Comment by markfox1** [comment]
I've tweaked this to the point where I'm very nearly happy. Spaces aren't a problem in full paths if they are properly quoted with `&quot;`. Keep in mind that I'm working in VB, but the only difference I'm seeing is one less `..` in the paths. This is what I have now:

```
<ItemGroup>
  <NugetPackage Include="..\packages\Nuget.CommandLine.*\tools\NuGet.exe" />
</ItemGroup>
<ItemGroup>
  <SquirrelPackage Include="..\packages\squirrel.windows.*\tools\Squirrel.exe" />
</ItemGroup>
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
  <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
    <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo"/>
  </GetAssemblyIdentity>
  <Exec Command="&quot;@(NugetPackage->'%(fullpath)')&quot; pack SquirrelTest.nuspec -Version %(myAssemblyInfo.Version) -Properties Configuration=Release" />
  <Exec Command="&quot;@(SquirrelPackage->'%(fullpath)')&quot; --releasify SquirrelTest.$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3)).nupkg --releaseDir=../Releases " />
</Target>
```

The only thing I don't like is using the AfterBuild target, which executes after every build, but it is as simple as changing the target to, say, Package, and executing MSBuild from the command-line with Package as the target.

**Comment by PHeonix25** [comment]
Hey guys, there was a formatting issue in the docs, which I've fixed with #1012 

In addition, I'd like to share what I ended up with (that combines a lot of the solutions above) for the next person that comes along:

```
<ItemGroup>
    <NuGetCommandLine Include="..\packages\NuGet.CommandLine.*\tools\nuget.exe" />
    <Squirrel Include="..\packages\Squirrel.Windows.*\tools\squirrel.exe" />
  </ItemGroup>
  <Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
    <!-- Add some nice errors for the next person that comes along -->
    <Error Condition="!Exists(@(NuGetCommandLine->'%(FullPath)'))" Text="You are trying to use the Nuget.CommandLine package, but it is not installed. Please install NuGet.CommandLine from the Package Manager." />
    <Error Condition="!Exists(@(Squirrel->'%(FullPath)'))" Text="You are trying to use the Squirrel.Windows package, but it is not installed. Please install Squirrel.Windows from the Package Manager." />
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="assemblyInfo" />
    </GetAssemblyIdentity>
    <Exec Command="@(NuGetCommandLine->'%(FullPath)') pack MYAPPLICATION.nuspec -Version %(assemblyInfo.Version) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
    <Exec Command="@(Squirrel->'%(FullPath)') --releasify $(OutDir)MYAPPLICATION.$([System.Version]::Parse(%(assemblyInfo.Version)).ToString(3)).nupkg" />
  </Target>
```
Please note (again, for the next guy) you'll need to replace the *two* `MYAPPLICATION` mentions above.

Hope this helps someone.

**Comment by poma** [comment]
Why not replace MYAPPLICATION with a macro such as `$(TargetName)`

**Comment by PHeonix25** [comment]
@poma - for me (due to the way the project has grown over time), it's because they are different. 
For others following along later, that might be a much nicer solution indeed. Thanks.

**Comment by markfox1** [comment]
@PHeonix25 You'll want to put '&quot;'s around the first part of the Command parameter to the Exec. Like I did above.

Also, on my system, specifying the OutputDirectory and Basepath break the NuGet Exec, as does the $(OutDir) in the Squirrel Exec.

The error messages are welcome though, and already saved us a bunch of fiddling this morning.

**Comment by poma** [comment]
Created a pull request #1120 that includes all suggestions above, please review

**Comment by awbacker** [comment]
Reviewing that PR as well, but its been months so.. in the meantime, this is what I ended up with in order to get a well-enough functioning `AfterBuild` target in my primary project (`My.App` here).  Builds fine from the solution level with `msbuild MyApp.sln /p:..release..`

Maybe this would work as a slightly more understandable doc until the PR is in?  It certainly helps with the props set like that (esp. releaseDir)

```
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
        <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo"/>
    </GetAssemblyIdentity>
    <PropertyGroup>
        <NuGetExe>..\packages\NuGet.CommandLine.4.3.0\tools\NuGet.exe</NuGetExe>
        <SquirrelExe>..\packages\squirrel.windows.1.7.8\tools\squirrel.exe</SquirrelExe>
        <SemVerNumber>$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3))</SemVerNumber>
        <NuSpecFile>MyApp.nuspec</NuSpecFile>
        <ReleaseDir>..\Releases\</ReleaseDir>
        <!-- extra optional params for squirrel. can be empty -->
        <SquirrelParams>--icon Images\favicon.ico --setupIcon Images\favicon.ico</SquirrelParams>
    </PropertyGroup>
    <!-- build nupkg into the project local bin\Release\ directory temporarily -->
    <Exec Command="$(NuGetExe) pack $(NuSpecFile) -Version $(SemVerNumber) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
    <!-- squirrelify into the release dir (usually at solution level.  change the property above for a different location -->
    <Exec Command="$(SquirrelExe) --no-msi --releasify $(OutDir)MyApp.$(SemVerNumber).nupkg --releaseDir=$(ReleaseDir) $(SquirrelParams)" />
</Target>
```

`SolutionDir\My.App\MyApp.nuspec`
```
- same as example
- uses src="**\*.*" instead of *.* for
```

**Comment by poma** [comment]
Your solution looks much cleaner. If we merge it with suggestions above result will look like:

```
<Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
        <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo"/>
    </GetAssemblyIdentity>
    <PropertyGroup>
        <NuGetExe>..\packages\NuGet.CommandLine.*\tools\nuget.exe</NuGetExe>
        <SquirrelExe>..\packages\Squirrel.Windows.*\tools\squirrel.exe</SquirrelExe>
        <SemVerNumber>$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3))</SemVerNumber>
        <ReleaseDir>..\Releases\</ReleaseDir>
        <!-- extra optional params for squirrel. can be empty -->
        <SquirrelParams>--no-msi</SquirrelParams>
    </PropertyGroup>
    <!-- Add some nice errors for the next person that comes along -->
    <Error Condition="!Exists(@(NuGetExe->'%(FullPath)'))" Text="You are trying to use the NuGet.CommandLine package, but it is not installed. Please install NuGet.CommandLine from the Package Manager." />
    <Error Condition="!Exists(@(SquirrelExe->'%(FullPath)'))" Text="You are trying to use the Squirrel.Windows package, but it is not installed. Please install Squirrel.Windows from the Package Manager." />
    <!-- build nupkg into the project local bin\Release\ directory temporarily -->
    <Exec Command="&quot;@(NuGetExe->'%(FullPath)')&quot; pack $(TargetName).nuspec -Version $(SemVerNumber) -OutputDirectory $(OutDir) -BasePath $(OutDir)" />
    <!-- squirrelify into the release dir (usually at solution level. Change the property above for a different location -->
    <Exec Command="&quot;@(SquirrelExe->'%(FullPath)')&quot; --releasify $(OutDir)MyApp.$(SemVerNumber).nupkg --releaseDir=$(ReleaseDir) $(SquirrelParams)" />
</Target>
```

And there is also question about `@(NuGetExe->'%(FullPath)')` vs `%(NuGetExe.FullPath)` as suggested in push request. I've just taken my expression from the suggestion above and it worked, and I'm not sure what's the difference between two. Since we use `*` instead of version we need to test if this will work if there are multiple versions of `NuGet.CommandLine` package installed.

**Comment by awbacker** [comment]
@poma I actually integrated your changes from that PR into what I am using locally.  The error messages were super helpful, a very good idea.  I had no idea you could do that with the `*` in the property, and used it too, ending up with basically what you have.  I can't think that you'd have or want to have 2 different versions of nuget.commandline installed, but I'm sure it could happen.  I wonder what order it picks them in with * ;)

Also, I couldn't get the `"!Exists(@(NuGetExe->'%(FullPath)'))"` style to work, only the dotted notation (`!Exists(%(NuGetExe.FullPath))`) worked.  I'm on VS2017 & msbuild 15.4.x so perhaps thats why.

**Comment by poma** [comment]
A few more improvements:

* I've found in MSBuild docs that `ItemGoup` can be included in `Target` starting with .NET Framework 3.5
* When included this way it doesn't need `InProject` tag
* `@(NuGetExe->'%(FullPath)')` doesn't work with multiple packages installed but `%(NuGetExe.FullPath)` does. It get the lowest version though

Result:

```xml
  <Target Name="AfterBuild" Condition=" '$(Configuration)' == 'Release'">
    <GetAssemblyIdentity AssemblyFiles="$(TargetPath)">
      <Output TaskParameter="Assemblies" ItemName="myAssemblyInfo" />
    </GetAssemblyIdentity>
    <ItemGroup>
      <!-- If your .NET version is <3.5 and you get build error, move this ItemGroup outside of Target -->
      <NuGetExe Include="..\packages\NuGet.CommandLine.*\tools\nuget.exe" />
      <SquirrelExe Include="..\packages\Squirrel.Windows.*\tools\squirrel.exe" />
    </ItemGroup>
    <PropertyGroup>
      <SemVerNumber>$([System.Version]::Parse(%(myAssemblyInfo.Version)).ToString(3))</SemVerNumber>
      <ReleaseDir>..\Releases\</ReleaseDir>
      <!-- extra optional params for squirrel. can be empty -->
      <SquirrelParams>--no-msi</SquirrelParams>
    </PropertyGroup>
    <!-- Add some nice errors for the next person that comes along -->
    <Error Condition="!Exists(%(NuGetExe.FullPath))" Text="You are trying to use the NuGet.CommandLine package, but it is not installed. Please install NuGet.CommandLine from the Package Manager." />
    <Error Condition="!Exists(%(SquirrelExe.FullPath))" Text="You are trying to use the Squirrel.Windows package, but it is not installed. Please install Squirrel.Windows from the Package Manager." />
    <!-- build nupkg into the project local bin\Release\ directory temporarily -->
    <Exec Command='"%(NuGetExe.FullPath)" pack $(TargetName).nuspec -Version $(SemVerNumber) -OutputDirectory $(OutDir) -BasePath $(OutDir)' />
    <!-- squirrelify into the release dir (usually at solution level. Change the property above for a different location -->
    <Exec Command='"%(SquirrelExe.FullPath)" --releasify $(OutDir)MyApp.$(SemVerNumber).nupkg --releaseDir=$(ReleaseDir) $(SquirrelParams)' />
  </Target>
```

**Comment by jrlilly** [comment]
@poma not sure if where this is all at, but it would be nice to remove the one final reference to MyApp in the squirrel exec and replace with TargetName :)

**Comment by MrBjorn** [comment]
Very nice post! Excellent. 

I got a problem though with last changes. This worked:

  <Exec Command="nuget pack MyApp.nuspec -Version %(myAssemblyInfo.Version) -Properties Configuration=Release -OutputDirectory $(OutDir) -BasePath $(OutDir)" />


But not this more general way, mention in the end:

      <NuGetExe Include="..\packages\NuGet.CommandLine.*\tools\nuget.exe" />

    <Exec Command='"%(NuGetExe.FullPath)" pack $(TargetName).nuspec -Version $(SemVerNumber) -OutputDirectory $(OutDir) -BasePath $(OutDir)' />

this reports also an error:

    <Error Condition="!Exists(%(NuGetExe.FullPath))" Text="You are trying to use the NuGet.CommandLine package, but it is not installed. Please install NuGet.CommandLine from the Package Manager." />


I have Visual Studio 2017, 15.5.7 and Nuget Command Line is installed, it worked running as usual. but would be good have this more general solution.

anyone knows what can be wrong?

**Comment by poma** [comment]
It is fixed in the new PR #1120

**Comment by Thieum** [comment]
@shiftkey the original issue was solved by a merged PR. The other points are in an ongoing one and could be tracked in #1120. This can be closed if we want to track this in the PR.

**Comment by shiftkey** [comment]
Closing this out in favour of the PR #1120
