### ISSUE TITLE
How to dispose GitHubUpdateManager?

### ISSUE THREAD

**Issue by poma** [Squirrel/Squirrel.Windows#633]
I'm using it like this:

``` csharp
using (var mgr = await UpdateManager.GitHubUpdateManager(Settings.UpdateRepository)) {
    await mgr.UpdateApp();
}
```

But if app is closed shortly before starting (like in first few seconds) it throws AbandonedMutexException. Probably because UpdateManager is not properly disposed. Am I doing something wrong? If i remove first await like in docs my app just hangs on the second await call.

**Comment by d0narnbl1tz** [comment]
look at my [issue ](https://github.com/Squirrel/Squirrel.Windows/issues/639), i used a way to dispose it.

**Comment by shiftkey** [comment]
I'm not 100% sure of this, but this feels like the app being closed while it's trying to update:

> Every example I've found of this is user error, you're checking for updates but closing the app before it completes. **This is a bug in your app - killing the app while updates are applying is bad**.
> https://github.com/Squirrel/Squirrel.Windows/issues/587#issuecomment-325423449

https://github.com/Squirrel/Squirrel.Windows/issues/587#issuecomment-387799204 shows a way to guard against this.
