### ISSUE TITLE
Using await in Main() method

### ISSUE THREAD

**Issue by joshiji** [Squirrel/Squirrel.Windows#640]
Hi,

I was trying to follow the documentation. [Integration Page](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/getting-started/1-integrating.md) page suggests to put the following snippet into the Main function:

```
using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
{
    await mgr.UpdateApp();
}
```

But, for this the Main function needs to be async and which is not being allowed by compiler. So, am I missing something here or is there a different way to achieve it?

Best Regards,
Santosh

**Comment by d0narnbl1tz** [comment]
you can call an async function from your main function ;)

**Comment by santoshkumarjoshi** [comment]
Thanks @d0narnbl1tz . It helps. Do we need the document to say so. Because I think many people may be naive just like me.

**Comment by FrenchBen** [comment]
Circling back on this - when I add the above and call `Update()` in main, I get:
```
Error	CS0708	'Update': cannot declare instance members in a static class	MyApp	C:\Projects\MyApp\Program.cs
```

n00bie in c# :(

**Comment by santoshkumarjoshi** [comment]
Did you miss making the `Update` a `static` method? Note static keyword
below.

async static void update()
{
    using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
      {
         await mgr.UpdateApp();
      }
}


Best Regards,
Santosh
electroBucket <http://www.electrobucket.com/>
+91-855-365-4729
+91-879-286-2194

**Comment by FrenchBen** [comment]
yup that was it - thanks!

**Comment by dsplaisted** [comment]
So I'm gathering that the recommended practice is to have an `async void` update method that you call from `Main()`.  That way the update will happen in the background while your app runs.  This wasn't at all clear to me from the documentation though, it would really help to have this more spelled out.

**Comment by shiftkey** [comment]
> But, for this the Main function needs to be async and which is not being allowed by compiler. 

This is now allowed as part of [C# 7.2](https://blogs.msdn.microsoft.com/mazhou/2017/05/30/c-7-series-part-2-async-main/) and I've opened #1475 to close this out...
