### ISSUE TITLE
Setup.exe Error

### ISSUE THREAD

**Issue by manbeardgames** [Squirrel/Squirrel.Windows#645]
The first releasify I performed, the Setup.exe works as expected when distributing it to users.  However, each subsequent releaseify that is performed, the Setup.exe throws the following error when run.  

```
This is a dummy update.exe.  If you are seeing this, your build did not correctly replace the IDR_UPDATE_ZIP resource.

Command line --instal
```

![Imgur](http://i.imgur.com/J5PDud5.png)

Users are however able to install the first release and have the application update to the newest version. They just can't use the Setup.exe from the newest version if they are a new user

This is using Squirell.Windows verions 1.2.5 in Visual Studio installed via Nuget Package Manager.

**Comment by the-dansan** [comment]
Cf. #671

**Comment by CrazyOrange** [comment]
Make sure you have the "WriteZipToSetup.exe" in your Squirrel folder.

**Comment by the-dansan** [comment]
@CrazyOrange definitely not the issue in the case of #671. @dartvalince , can you post the log that is being generated during --releasify?

**Comment by dartvalince** [comment]
Believe this is it. This is the SquirrelSetup.log

http://pastebin.com/wdn47END

**Comment by the-dansan** [comment]
From the log file (looks fairly similar to mine from #671):

> 2016-03-27 05:56:25> Program: Building embedded zip file for Setup.exe
2016-03-27 05:56:26> Program: Failed to update Setup.exe with new Zip file: System.Exception: Failed to write Zip to Setup.exe!
 Setup: C:\Users\Dart\Documents\GitHub\DiscerningEye\DiscerningEye\0.1.2.x\DiscerningEye\DiscerningEye\Releases\Setup.exe, Zip: C:\Users\Dart\AppData\Local\Temp\tmp1C93.tmp
Starting to read in Zip file!
Updating Resource!
Finished!
Failed to update resource
Usage: WriteZipToSetup [Setup.exe template] [Zip File]
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi

**Comment by lukywong** [comment]
meet same issue

**Comment by paulcbetts** [comment]
Are you using Antivirus? This is probably blocking us from being able to edit Setup.exe.

**Comment by lukywong** [comment]
@paulcbetts no, not even install, i don't know why, but after a system reboot, it works like a charm, thank you.

**Comment by weeger** [comment]
Same issue... after about 5 releases succeed, same error, no Antivirus, nothing in the SquirrelSetup.log, unpacked app works.

**Comment by weeger** [comment]
Solved. I just moved out my project the sh script that launches compiling. It seems that it creates a loop slowing down the process (it takes about 15mn to complete), then creates a corrupted exe file who throw the "dummy update.exe" error.

**Comment by Thieum** [comment]
@manbeardgames is it an issue you are still experiencing with the latest version of Squirrel?

**Comment by manbeardgames** [comment]
@Thieum Unfortunately, I'm unable to answer that as the project that I was originally using Squirrel for is not longer being managed and hasn't for some time.

**Comment by shiftkey** [comment]
@manbeardgames thanks for following up. I'm going to close this out as we lack the information to proceed. If anyone else feels they are still dealing with this problem, please open a fresh issue and fill out the template to help us investigate.
