### ISSUE TITLE
Files of running version are deleted - example workflow needed?

### ISSUE THREAD

**Issue by dannylindquist** [Squirrel/Squirrel.Windows#646]
In the case where you release multiple versions, say 1.0.22 and 1.0.23 while a user is running 1.0.21. If the app periodically updates more than once while open, the files of the current version for the user (1.0.21) are deleted causing the program to be useless until its restarted.

This is more a question of workflow more than anything. When is the best time to apply updates so the user doesn't notice it happening, but also avoiding having squirrel clean up the files which are still being use??

**Comment by gajagt** [comment]
We're hitting the same issue. We wrote some code to detect .dead files in the folder and notify users that they have to restart.

Can the number of versions that are retained be configured? I'd prefer if the exe is attempted to be deleted first. If that's locked, the cleanup should be deferred. 

We end up throttling how often we update because of this issue.

**Comment by paulcbetts** [comment]
It can't be configured but I think that we should up it by one. The problem is, the more you have, the more users start to whine about "SQUIRREL EATING MY DISK SPACE, IT NEVER DELETES OLD VERSIONS!!!!1111"

**Comment by gajagt** [comment]
What about doing the exe check that I suggested? I think most users will appreciate their running instance not getting wiped, especially if the app has some state that needs to be pushed remotely. In our electron app, html/js files get wiped so the page that helps users save their state can also not be rendered.

**Comment by paulcbetts** [comment]
It's probably doable, can you submit a PR @gajagt? Very similar code is already in the library to search the process list for modules in a certain directory

**Comment by gajagt** [comment]
Sure, will try to get something out this week.
