### ISSUE TITLE
Running installer twice causes error

### ISSUE THREAD

**Issue by rmcshane** [Squirrel/Squirrel.Windows#652]
I used Squirrel.Windows to create an installer for an app built with Electron.  I noticed that if a user runs the installer after they've already installed the application, and _while_ it's still running, the process halts on an exception.  If the user runs the installer while the application is _not_ running, the installer removes the current install and successfully installs the application again.  I'm not sure if this is a Squirrel issue or an Electron issue.

The exception:
Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\user\AppData\Local\testapp\app-0.1.1\ffmpeg.dll' is denied

After this happens the user cannot run the app because Update.exe has already been removed from the app folder in local app data.  Also removing the app from the Control Panel will fail because Windows cannot find Update.exe.

**Comment by paulcbetts** [comment]
This is fixed in the latest version of Squirrel by killing off your app automatically
