### ISSUE TITLE
How to change the background color of the icon in the Start Menu?

### ISSUE THREAD

**Issue by lipis** [Squirrel/Squirrel.Windows#653]
Can we have the same background color as Chrome has instead of the blue?

![wrong color](https://cloud.githubusercontent.com/assets/125676/14335878/f75902e2-fc5e-11e5-8c16-ea59d195e9eb.png)

**Comment by paulcbetts** [comment]
afaik the background color is set by Explorer, not by applications (it's your "accent color"). You can try making your icon a full square?

**Comment by lipis** [comment]
Thanks. We'll try that.
