### ISSUE TITLE
What's the proper format for the title icon?

### ISSUE THREAD

**Issue by lipis** [Squirrel/Squirrel.Windows#654]
Here is how it looks like on some Windows 7..
![icon windows 7](https://cloud.githubusercontent.com/assets/125676/14335974/f1b78ca4-fc5f-11e5-8b8a-20fbcad1a4c0.png)

and here is the `.ico` file that we are providing with all the different sizes.. are we missing any size in particular?! Or maybe we have too many.. :D

<img width="616" alt="screen shot 2016-04-07 at 01 28 44" src="https://cloud.githubusercontent.com/assets/125676/14335997/1aa8aa1c-fc60-11e5-9b05-ffa8791a27b0.png">

**Comment by paulcbetts** [comment]
This is an Electron bug, on Windows 7 you need to set the EXE's icon, and _not_ set the `BrowserWindow` icon at all

**Comment by lipis** [comment]
you're right.. sorry for that.

**Comment by paulcbetts** [comment]
No worries!

**Comment by lipis** [comment]
Shall I file it there as is or that's the provided solution?

**Comment by lipis** [comment]
Wasn't using the `icon` in the `BrowserWindow` https://github.com/electron/electron/issues/5062 :)
