### ISSUE TITLE
[USER] I don't want crap in AppData

### ISSUE THREAD

**Issue by tjmonk15** [Squirrel/Squirrel.Windows#655]
I'm not just a user, but a Dev. I have enough crap on my C:, and I don't need any old app that uses this framework installing itself (WITHOUT PERMISSION) in my AppData.

How are you planning on supporting users like me?

**Comment by paulcbetts** [comment]
ohai, Squirrel doesn't install things without your permission, only when you explicitly click on a Setup.exe file.

It sounds like you're worried about disk space, and the good news is, every Squirrel app is completely portable, you can move it wherever you want, then `mklink` it in:

```sh
robocopy /MIR %LocalAppData%\Atom  E:\SquirrelApps\Atom  ## Or whatever
mklink /D %LocalAppData%\Atom E:\SquirrelApps\Atom
```

Bingo bango, your app isn't on C: and you still get updates and everything works great

**Comment by tjmonk15** [comment]
Every "Installer" for windows provides several chances to abort (at any point along the line.) So, "You opened the file, you obviously gave your permission" isn't really an answer.

About your mklink "solution" you

1) Forgot to include that that solution only works when you open the command prompt in admin mode.
2) Failed to make me want to use anything that uses your library.

Unfortunately, for me (and others), I (we) have no way of knowing if an app uses your library unles we do some digging. As fare as I'm concerned your library does nothing more than allow app devs to "hoodwink" users (compared to what they are used to) to allow apps (or malware) to be installed and run on startup.

**Comment by paulcbetts** [comment]
Unfortunately Squirrel will never change this behavior. Sorry!

**Comment by tjmonk15** [comment]
So you understand that you are breaking "standards" that Windows Users as used to (and expect) and what? Can't be held responsible for abuse?

**Comment by BarryThePenguin** [comment]
If developers can build an app using Squirrel, they could provide a 'portable' version too. That portable version can be included in any directory on any drive.

**Comment by tjmonk15** [comment]
@BarryThePenguin And how does that help/protect users in any way?

**Comment by paulcbetts** [comment]
@tjmonk15 I'm not super interested in debating this. Squirrel works the way it does. I'm sorry that it doesn't match up with your expectations. When you run a Squirrel Installer, its *sole* goal is to open the app the user asked to install, as soon as possible. 

Opening the app as soon as possible is literally the _only_ thing a Squirrel installer will ever ever do. No dialogs, no questions.

The good news is, uninstalling Squirrel apps is just as fast, and just as easy!

**Comment by tjmonk15** [comment]
@paulcbetts So you want Squirrel to be an app launcher and not an installer?

**Comment by gsn1074** [comment]
Squirrel is garbage; I hope postman stops using it.

**Comment by bddckr** [comment]
If you have an issue with specific software talk to the creator of that software. Don't try to make the maintainers of the tooling that software uses to change something. That won't even end up in the software you have issues with anyway as it means that creator needs to update it first.

@shiftkey Seems like this is a perfect issue to lock.
