### ISSUE TITLE
Uninstall one SquirrelAware CefSharp app, others crash.

### ISSUE THREAD

**Issue by Layoric** [Squirrel/Squirrel.Windows#662]
When creating a SquirrelAware app, I noticed when I uninstalled it GitHub for Windows would crash.

Testing this with multiple SquirrelAware apps, I can crash separate applications by uninstall other SquirrelAware apps.

I think it comes down to [this here](https://github.com/Squirrel/Squirrel.Windows/blob/8674e343fa30b7970a40a80b98eedec37330a5f3/src/Squirrel/UpdateManager.ApplyReleases.cs#L128).

``` Csharp
// NB: Some people attempt to uninstall apps while 
// they're still running. I cannot even.
var toKill = allApps
    .SelectMany(x => Process.GetProcessesByName(x.Name.Replace(".exe", "")))
    .ToList();
```

and more specifically [this](https://github.com/Squirrel/Squirrel.Windows/blob/9de260cb6b614234511d57723738f1be2ed25476/src/Squirrel/SquirrelAwareExecutableDetector.cs#L16)
``` CSharp
var di = new DirectoryInfo(directory);

return di.EnumerateFiles()
    .Where(x => x.Name.EndsWith(".exe", StringComparison.OrdinalIgnoreCase))
    .Select(x => x.FullName)
    .Where(x => (GetPESquirrelAwareVersion(x) ?? -1) >= minimumVersion)
    .ToList();
```

I could be reading this wrong, but basically it's looking for all `exe` files in the app install directory and nuking any (and all) running instances of any found exe files, matching by name. This causes a problem when multiple application are going to be using `CefSharp.BrowserSubprocess.exe` for example.

Shouldn't this process only care for the main executable that is being uninstalled rather than killing any and all running instances matching a name of an exe in the install directory?

Any help is appreciated! :+1:

**Comment by paulcbetts** [comment]
Oops, it looks like we're still killing processes the old way in a few places, can you port this code to the new way that we build in https://github.com/Squirrel/Squirrel.Windows/pull/590? Thanks!

**Comment by Layoric** [comment]
You mean like [`KillAllProcessesBelongingToPackage`](https://github.com/Squirrel/Squirrel.Windows/blob/9de260cb6b614234511d57723738f1be2ed25476/src/Squirrel/UpdateManager.InstallHelpers.cs#L106)?

Or another? I don't think the above method will have the desired effect since:

``` CSharp
// Never kill our own EXE
if (ourExePath != null && x.Item1.Equals(ourExePath, StringComparison.OrdinalIgnoreCase)) return false;
```

**Comment by shiftkey** [comment]
> When creating a SquirrelAware app, I noticed when I uninstalled it GitHub for Windows would crash.

![](http://i.giphy.com/CDJo4EgHwbaPS.gif)

> when multiple application are going to be using `CefSharp.BrowserSubprocess.exe` for example

Ah, yes. That explains it...

![](https://cloud.githubusercontent.com/assets/359239/14517745/54525eb2-0254-11e6-9501-8fe7acb958f7.gif)

**Comment by paulcbetts** [comment]
@Layoric Correct - that method reads the full path to the EXE's main module, which means it won't affect any other software on the system

**Comment by Layoric** [comment]
@paulcbetts Ahhh right, my mistake `ourExe` = `Update.exe`/`Squirrel.exe` not the application using Squirrel itself. :+1:

**Comment by jcpc91** [comment]
Squirrel is creating an link access in start menu from cefsharp.browsersubprocess.exe file.
how can avoid this?

**Comment by paulcbetts** [comment]
@jcpc91 Read the instructions about handling Squirrel Events in your app
