### ISSUE TITLE
V1.4.0 does not support .net 4.0 projects

### ISSUE THREAD

**Issue by jordyvaneijk** [Squirrel/Squirrel.Windows#674]
After trying to install Squirrel.Windows 1.4.0 on a WPF application targeting .net 4.0 I get the following exception

> Could not install package 'DeltaCompressionDotNet 1.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Is there a possibility to have it on a .net 4.0 framework?

Thanks in advance

**Comment by paulcbetts** [comment]
Not possible, sorry

**Comment by jordyvaneijk** [comment]
Then my next question, is there a version that is supporting .net 4.0?

**Comment by paulcbetts** [comment]
No, you need .Net 4.5

**Comment by jordyvaneijk** [comment]
Maybe it's a handy thing to put it somewhere in the Documentation for upcomming users that the minimal supported framework version is .net 4.5 because I can't find it. And i think there will be others trying this too.

**Comment by jordyvaneijk** [comment]
I see that DeltaCompressionDotNet v1.1.0-rc1 and the 2.0.0-rc1 versions are both .net 4 (i think even .net 2.0) compatible Is there the possibility you can update Squirrel to one of these 2 versions
