### ISSUE TITLE
Nuget and Squirrel Server

### ISSUE THREAD

**Issue by FrenchBen** [Squirrel/Squirrel.Windows#678]
It seems that the behavior between all platform are completely different. 
The windows packaging can use Nuget but does not respect at all the format declared within OSX and the older Server code. 

As a reminder, this is what's in the README:
https://github.com/Squirrel/Squirrel.Mac#update-json-format
```
{
    "url": "http://mycompany.com/myapp/releases/myrelease",
    "name": "My Release Name",
    "notes": "Theses are some release notes innit",
    "pub_date": "2013-09-18T12:29:53+01:00"
}
```

Why so many different formats? What's the idea behind yet-again re-creating a file structure that doesn't seem to be compatible with the rest of your repos? (blame docs?)
![lost...](http://s2.quickmeme.com/img/72/723f54b0b433ea20c75af23136e84c5b166284ddbcabfe865014b7c4ce9c257e.jpg)

**Comment by paulcbetts** [comment]
> It seems that the behavior between all platform are completely different.  The windows packaging can use Nuget but does not respect at all the format declared within OSX and the older Server code.

Correct. Squirrel.Windows and Squirrel.Mac are completely different, the name is only shared because they accomplish a similar goal

**Comment by FrenchBen** [comment]
Doesn't that completely defeat the purpose of having a cross-platform updater? 

Also I saw a mention of 'Channels' in the Squirrel.Windows docs, yet no true info on how this is to be setup - Could you expand on that?

**Comment by paulcbetts** [comment]
It's not a cross-platform updater

**Comment by FrenchBen** [comment]
Would mind explaining what prompted the change of something nice like the original Mac + Squirrel server to this rather independent Nuget packaging system?

**Comment by paulcbetts** [comment]
> Also I saw a mention of 'Channels' in the Squirrel.Windows docs, yet no true info on how this is to be setup - Could you expand on that?

Sure - Squirrel.Windows is mostly client-driven, so it means that setting up different update channels (i.e. "Beta" vs "Production") is super easy - you can just host them at different folders on the update server, which can just be S3 / Blob Storage / anything that can serve up static HTTP

**Comment by paulcbetts** [comment]
> Would mind explaining what prompted the change of something nice like the original Mac + Squirrel server to this rather independent Nuget packaging system?

Because requiring every developer to set up a "Squirrel Server" is stupid, they should be able to host updates on S3. So I built a thing that did that, instead of how Squirrel.Mac works!

**Comment by FrenchBen** [comment]
I see - how does one make the Windows create/update channels using the current process?
