### ISSUE TITLE
latest behaviour

### ISSUE THREAD

**Issue by abunet** [Squirrel/Squirrel.Windows#681]
HI, 
I'd like the following update naming convention: 
have always the folder with the latest version named *-latest
have the second-last version named with his version

Suppose to have an application called MyApp that is fist deployed at version 1.0.0 
and then need to be updated at 1.1.0

I'd like the following behaviour:

(folders at first install. version 1.0.0)
MyApp
update.exe
   MyApp-latest

(folders updated at version 1.1.0)
MyApp
update.exe
   MyApp-1.0.0
   MyApp-latest
 

is it possibile to achieve this? How I have to create the package and the manifest?
Regards
Marco

**Comment by paulcbetts** [comment]
This isn't possible, sorry.
