### ISSUE TITLE
squirrel Update.exe --uninstall fail to uninstall package

### ISSUE THREAD

**Issue by lfern** [Squirrel/Squirrel.Windows#684]
We have developed an electron application with autoupdate ussing electron-windows-installer. I don't have any problem before, but today we have generate a new installer and I get this error when doing Updater.exe --uninstall:

`2016-05-09 21:36:32> Program: Starting Squirrel Updater: --install .
2016-05-09 21:36:32> Program: Starting install, writing to C:\Users\luis\AppData\Local\SquirrelTemp
2016-05-09 21:36:32> Program: About to install to: C:\Users\luis\AppData\Local\TractisPki
2016-05-09 21:36:32> Program: Install path C:\Users\luis\AppData\Local\TractisPki already exists, burning it to the ground
2016-05-09 21:36:32> Unhandled exception: System.AggregateException: Se han producido uno o varios errores. ---> System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Squirrel.UnsafeUtility.<>c__DisplayClass2.<EnumerateProcesses>b__0(Int32 i)
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en Squirrel.UnsafeUtility.EnumerateProcesses()
   en Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   en Squirrel.Update.Program.<Install>d__38.MoveNext()
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   en System.Threading.Tasks.Task.Wait()
   en Squirrel.Update.Program.executeCommandLine(String[] args)
   en Squirrel.Update.Program.main(String[] args)
---> (Nº de excepción interna 0) System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Squirrel.UnsafeUtility.<>c__DisplayClass2.<EnumerateProcesses>b__0(Int32 i)
   en System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   en System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   en System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   en Squirrel.UnsafeUtility.EnumerateProcesses()
   en Squirrel.UpdateManager.InstallHelperImpl.KillAllProcessesBelongingToPackage()
   en Squirrel.Update.Program.<Install>d__38.MoveNext()<---
`

Please, could you help us? We can't find any information about this error.

Thanks

**Comment by lfern** [comment]
Hi,

I have just reboot my computer, and now it works. I think the problem could be here:

https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/Utility.cs#L677

I think the out length parameter is used as number of processes but in the documentation of function EnumProcesses I find:

> To determine how many processes were enumerated, divide the pBytesReturned value by sizeof(DWORD). There is no indication given when the buffer is too small to store all process identifiers. Therefore, if pBytesReturned equals cb, consider retrying the call with a larger array.

So if the number of processes is high (more than 2048/sizeof(DWORD)) you will go out of the bounds of the int[2048]

**Comment by michael-kindtner** [comment]
Subscribe, same sporadically here. Whenever a user has many programs open and starts setup, it fails.

**Comment by markmcdowell** [comment]
Just had this in 1.7.8 so the bug still exists.

**Comment by NicolasDorier** [comment]
Same problem (2019, 3 years after this report) anybody actually using this?

**Comment by evan-gravitate** [comment]
+4 years.  Same problem every time I'm forced to update Slack.  Wow, closing a bunch of unrelated programs does seem to work.  I don't think any of the ones I closed were even electron apps, but I closed chrome(most tabs), notepad, Rider, Websorm, and Excel for what it's worth.  Best guess is that it choked on 35 chrome.exe's.  :-)

**Comment by anaisbetts** [comment]
All these comments and nobody thought to just make the number bigger?

**Comment by evan-gravitate** [comment]
Could this be included in a release so I can bug Slack about upgrading to it?

**Comment by SlySven** [comment]
Also - for those getting `squirrel.windows` via `nuget install squirrel.windows -ExcludeVersion` the version there is even older than the `master` branch - it notes that is was last updated in 2020 https://www.nuget.org/packages/squirrel.windows/ !
