### ISSUE TITLE
some error!

### ISSUE THREAD

**Issue by gggin** [Squirrel/Squirrel.Windows#689]
and there no icon pin in desktop toolbar

2016-05-11 13:20:15> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\GGGin\AppData\Local\corn\packages\.betaId”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   在 System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   在 System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   在 System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   在 Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2016-05-11 13:20:15> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: 未能找到路径“C:\Users\GGGin\AppData\Local\corn\packages\RELEASES”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   在 Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()

**Comment by paulcbetts** [comment]
I think your NuGet package is malformed or doing odd things

**Comment by gggin** [comment]
I just use electron-builder and use electron-squirrel-event then no thing.
 can you help me in some way?

**Comment by rogeru** [comment]
I am having the exact same issue (on Windows 8)
    "electron-builder": "3.22.0",
    "electron-prebuilt": "1.0.2"

After the build, the output folder is "win" instead of "win64" even though the build output is:
 Removing dist\win and dist\win-unpacked
 Packaging app for platform win32 x64 using electron v1.0.2

It used to work before with an older electron-builder version. I'll try to see when it was still working.

**Comment by paulcbetts** [comment]
Electron-builder has forked basically every package, I can't really support it, sorry. Please file bugs there instead.

**Comment by rogeru** [comment]
Seems this was my problem as well: [402](https://github.com/electron-userland/electron-builder/issues/402)
Supposed to be fixed with 3.24
