### ISSUE TITLE
[question] Where to define installation path / Subdirectories

### ISSUE THREAD

**Issue by bergziege** [Squirrel/Squirrel.Windows#696]
Hi,
since its not mentioned in the FAQ nor I found anything in the issues I hope someone could help me out with this.

1st question: Where can I set the installation path to be used by squirrel? As an example: When running the app I want to tell to install in c:/portable or have no dependencies on a directory at all, so that I can take the app, copy it to an usb stick and updating still works.

2nd question: Is there any support for subdirectories. Given I have some config files in a "config" subfolder of my application (or dlls in "lib" folder). How to deploy them?

Greeting,
bergziege

**Comment by paulcbetts** [comment]
You can't set the installation directory. As to subdirectories, they Just Work, just put the directory structure you want in your Nupkg

**Comment by DRSDavidSoft** [comment]
#1002.
