### ISSUE TITLE
setup.exe is always compiled with the latest nupkg

### ISSUE THREAD

**Issue by hcd** [Squirrel/Squirrel.Windows#697]
Hello,

we're using Squirrel for deployment of our application in different environments (DEV, TST, UAT, PRD) - these environments have their own application Id so as far as squirrel is concerned, they are different applications.
The squirrel releasifying is built into our build/release process and work well, unless we want to build a "hotfix" on a previous version. The packaging of the NuPkg with a version number smaller than the "latest version" works, but during the "Squirrel --releasify", the resulting setup.exe gets made with the latest version that is in the RELEASES file (although the intended version is correctly inserted in the releases file.
Let me clarify with an example.
Imagine we have a version history of our application as follows.
1.0.0
1.0.1
1.1.0
1.2.0
But we want to hotfix 1.1.0 to 1.1.1. We provide a correct nupkg with the 1.1.1 in the nuspec file and start the releasify. The -full and -delta packages for 1.1.1 are correctly created (deltafied from 1.1.0 - which is correct) and the entries in the RELEASES file are inserted at the correct place (not just appended at the end).
But the setup.exe is then created with the 1.2.0 nupkg as payload. This should be the 1.1.1 !
(we've pinpointed this to lines 390=> 410 in Program.cs)

(note: We're fully aware that doing such "hotfixes" messes up the delta-checksums of later releases, but it's an unusual situation and we have a fallback that will install the -full if errors occurred. Nevertheless, the setup.exe should contain the correct -previous- nupkg)

Kind regards,
Sven.

**Comment by paulcbetts** [comment]
Squirrel just isn't designed for this scenario, sorry - it tries really, really, really hard to always make users on the latest version, you can't do like servicing branches or hotfixes.

If you want to try to do it anyways, I would manually edit the RELEASES file before running Releasify (or better yet, write a program to do it for you, since the RELEASES file is very very easy to parse)
