### ISSUE TITLE
Update.exe Should Support TLS 1.2

### ISSUE THREAD

**Issue by throwaway2348** [Squirrel/Squirrel.Windows#702]
Update.exe doesn't appear to support TLS 1.2 (see #618). Older TLS versions have known security vulnerabilities. Update.exe should support TLS 1.2

**Comment by paulcbetts** [comment]
Looks like this is possible via a configuration change: http://stackoverflow.com/questions/4137106/are-there-net-implementation-of-tls-1-2

Can you submit a PR to this effect?

**Comment by throwaway2348** [comment]
Sorry. I don't have familiarity with Squirrel or its code base. (I'm here after trying out the WhatsApp windows desktop client and investigating why it was checking for updates over TLS 1.0).

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/commit/b464b41bb243380c5acad82f3336ff7c9b1e4cb3
