### ISSUE TITLE
print info about the update process to stdout for no C# apps

### ISSUE THREAD

**Issue by mbsanchez** [Squirrel/Squirrel.Windows#703]
I have a C++ app (Qt app), I have created the installer using 'squirrel --releasify', also, the app was marked as Squirrel Aware though the .rc file.

All is good, the app is installed, and squirrel is sending events to it. I'm starting the update process thought a child process (QProcess) using the update.exe, the command is: 

`
..\update.exe --update=myrepo
`

I'm using a pipe to the child-process (update.exe) to receive some informations about the update process, but I only receive the next data:
"11"
"\r\n"
"22"
"\r\n"
"33"
"\r\n"
"66"
"\r\n"
"69"
"\r\n"
"76"
"\r\n"
"82"
"\r\n"
"91"
"\r\n"
"92"
"\r\n"
"94"
"\r\n"
"99"
"\r\n"

This appears to be the update progress, but when there is not update available, it receives the same info. What about if the update.exe tool sends some message about the update process? something like:
update found or not new updates
downloading update
update sucess

In this case, non c# apps can know when the update process is executed sucessfully, etc. Squirrel events are good to execute some installer tasks (like add/remove shortcuts), but it starts another process, I want to receive the update progress in the same process that launches the update.exe tool. Also, you can add another option to the update tool, something like:

`..\update.exe --checkUpdate=myrepo`

This command will say whether or not there is an update available. so I can inform the user about it and start the update process.

**Comment by paulcbetts** [comment]
The very last line is a JSON blob indicating what happened, maybe you're not getting that bit in your app?

**Comment by mbsanchez** [comment]
No, I only receive those numbers through the pipe (11, 22, 33, ..., 99). Also I have executed ´update.exe --update=my repo´ in the Windows Command Prompt, and i don't receive any output in the console.

**Comment by mbsanchez** [comment]
I'm doing a lot of test, and I have noticed that: `..\update.exe --download=myrepo` prints to stdout this data: `"{\"currentVersion\":\"0.1.48\",\"futureVersion\":\"0.1.49\",\"releasesToApply\":[{\"version\":\"0.1.49\",\"releaseNotes\":\"\"}]}\r\n"`

however `..\update.exe --update=myrepo` only prints the numbers described above `(11, 22, 33, .., 99).` Can you change the code so the --update prints more relevant info to stdout?

**Comment by paulcbetts** [comment]
@mbsanchez Sure, can you submit a PR to this effect?

**Comment by mbsanchez** [comment]
Sure, I can do that.

**Comment by Thieum** [comment]
@shiftkey fixed by #716 , this can be closed.
