### ISSUE TITLE
Electron app can't seem to download releases file with query parameters

### ISSUE THREAD

**Issue by simonporter007** [Squirrel/Squirrel.Windows#705]
I fully preload this with the idea that i'm probably doing something wrong on my side. I've had a look through all the open and closed issues but can't really seem to find anything that helps. In fact I saw a closed issue that sounded like my issue but it's been resolved, so i'm at a loss.

I've built an elecotron app and bundled it for release with electron-builder project. This gave me the full-nupkg and .exe files. I've then uploaded these to the electron-release-server which gives me the URL structure to follow.

I've then set up the squirrel events in my app and have set the feedURL to match the URL of my electron-release-server. When I install and run my app, it installes successfully but according to the SquirrelSetup.log:

```
2016-05-24 20:45:24> Program: Starting Squirrel Updater: --download http://example.com:1337/update/win64/0.2.0/stable
2016-05-24 20:45:24> Program: Fetching update information, downloading from http://example.com:1337/update/win64/0.2.0/stable
2016-05-24 20:45:24> CheckForUpdateImpl: Using existing staging user ID: 7479c3e3-cf74-5a57-9a6a-5ab84a435532
2016-05-24 20:45:24> CheckForUpdateImpl: Downloading RELEASES file from http://example.com:1337/update/win64/0.2.0/stable
2016-05-24 20:45:24> FileDownloader: Downloading url: http://example.com:1337/update/win64/0.2.0/stable/RELEASES?id=bb&localVersion=0.2.0&arch=amd64
2016-05-24 20:45:24> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Filename can either be an absolute HTTP[s] URL, *or* a file name
```

I am not sure where this issue is coming form but I think this is the Squirrel code generating the URL and then trying to parse it? From a quick read of the code here (I know nothing about C#) it looks like the filename param is being parsed and checking for illegal characters (which would contain a ?) and as the URL uses query strings, it invalidates it and throws an error.

I guess the real question is, have I misconfigured something so that it causes Squirrel to send the query parameters onto the URL rather than just accessing it directly?

**Comment by simonporter007** [comment]
Further searching the squirrel.windows code I can't understand where the query parameters are coming from:

```
if (Utility.IsHttpUrl(updateUrlOrPath)) {
                    if (updateUrlOrPath.EndsWith("/")) {
                        updateUrlOrPath = updateUrlOrPath.Substring(0, updateUrlOrPath.Length - 1);
                    }
                    this.Log().Info("Downloading RELEASES file from {0}", updateUrlOrPath);
                    int retries = 3;
                retry:
                    try {
                        var data = await urlDownloader.DownloadUrl(String.Format("{0}/{1}", updateUrlOrPath, "RELEASES"));
                        releaseFile = Encoding.UTF8.GetString(data);
```
and then:
```
public async Task<byte[]> DownloadUrl(string url)
        {
            var wc = Utility.CreateWebClient();
            var failedUrl = default(string);
        retry:
            try {
                this.Log().Info("Downloading url: " + failedUrl ?? url);
```

**Comment by paulcbetts** [comment]
@simonporter007 This is probably electron-release-server generating bogus RELEASE files, can you curl the RELEASES file and share it?

**Comment by simonporter007** [comment]
I can access the URL with and without the query params in the browser, which is probably expected. The contents of the RELEASES file at that URL is:

> 16C212981118451F3433BEF66F7A176DC015B2F9 /download/0.2.0/bb-dev-0.2.0-full.nupkg 59456226

**Comment by paulcbetts** [comment]
> Filename can either be an absolute HTTP[s] URL, *or* a file name

:smoking: :gun:

**Comment by paulcbetts** [comment]
You actually don't have to use a "release server" at all with Squirrel for Windows, just take the output of electron-builder and put it on S3 or anywhere that serves static files. Easy peasy!  You can even test updates by using just a path to a folder instead of a HTTP server

**Comment by simonporter007** [comment]
Think you're right. Pointing it to a local directory doesn't produce any errors. Didn't realise you could static host them (or maybe I did but didn't put two and two together). In which case, balls to the release server! Thanks, I guess I'll carry on that route and close this off. 

(Though it's still a mystery to me where the query params where coming from!)

**Comment by paulcbetts** [comment]
The query params are actually provided by Squirrel itself so that people who are using an "update server" have extra info to go on
