### ISSUE TITLE
Basic intergration not working WPF

### ISSUE THREAD

**Issue by jordyvaneijk** [Squirrel/Squirrel.Windows#706]
I'm following allong with the basic intergration for an application that i'm building but it seems to be nothing is working. I just added Squirrel.Windows nuget package with all its dependencies to my net45 project. Packageing and releasify are working.

Added the code 
`using (var mgr = new UpdateManager(@"C:\Projects\DataManagement\Releases"))
            {
                var ri = mgr.UpdateApp().Result;
            }`
But when i run my applicaiton it will hang on the line `var ri = mgr.UpdateApp().Result;` and not throwing any errors, I also tried to do it with a Url on IIS with having the right Web.config in place but this is also not making a request. If i look with Fiddler nothing to see. Can someone point me in the right direction?

My application is a WPF application and the code is used inside the OnStartup in App.xaml.cs using VS2015

**Comment by ganeskg** [comment]
Hello @jordyvaneijk,

I am getting the same problem. The method UpdateManager.UpdateApp() seems to be never completed and does not give any error. Have you resolved your above problem, if yes please let me know how.

Regards
Ganesan
