### ISSUE TITLE
Strong Named Assemblies

### ISSUE THREAD

**Issue by sys27** [Squirrel/Squirrel.Windows#711]
I have a signed assembly and cannot use yours (Could not load file or assembly 'Squirrel, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required).

Do you have Strong Named Assemblies or can I sign your dlls with my key?

**Comment by paulcbetts** [comment]
Sorry, Strong Naming negatively impacts Open Source - I recommend you stop signing assemblies, or as an alternative, I can provide SN binaries for a fee: http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets/

**Comment by joelweiss** [comment]
Try using [Strong Namer](https://github.com/dsplaisted/strongnamer) to sign Squirrel during the build process.
