### ISSUE TITLE
How to change the default install dir via squirrel.windows?

### ISSUE THREAD

**Issue by my891008** [Squirrel/Squirrel.Windows#712]
these days, i'm studying on the electron app, i use the "electron-winstaller" to create the setup installer. But the install dir is "C://user/administrator/Appdata/local/appname", I want to change the default dir and   built the install UI. How to do these?

**Comment by paulcbetts** [comment]
It's not possible, sorry!

**Comment by wesleywesley** [comment]
will you accept pull requests to make it possible?

**Comment by paulcbetts** [comment]
@wesleywesley No, sorry, installing to LocalAppData is part of how Squirrel can do background updates without UAC dialogs
