### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by wesleywesley** [Squirrel/Squirrel.Windows#720]
Is it not possible to have encrypted updates? Similar to how sparkle for mac does it; 

"Supports traditional Sparkle DSA signatures"

**Comment by paulcbetts** [comment]
Squirrel relies on HTTPS to provide secure transport for updates, we don't attempt to create our own security model for them

**Comment by wesleywesley** [comment]
But that's not a replacement. Someone could break into the server and place other update files. However, if there were DSA signatures, he'd have to have those too (which are only on the local machine, normally). So it gives extra security.
