### ISSUE TITLE
Give user choice to install update now or not

### ISSUE THREAD

**Issue by wesleywesley** [Squirrel/Squirrel.Windows#721]
Is it possible to give the user the choice to install the update? There are cases where this silent auto-update behavior is not wanted.

**Comment by paulcbetts** [comment]
Yep, Squirrel places the update timing / UI / etc totally in the hands of the developer, it's just a method that is called. You can check for updates, prompt the user, then initiate the update, you're definitely not forced to do automatic updates

**Comment by wesleywesley** [comment]
yes, installation I can choose. But the update is automatically downloaded, is it not? Or did I read the docs wrong? And if I don't install it at that occassion, will it be-redownloaded, or is the file cached somewhere?

**Comment by paulcbetts** [comment]
For Squirrel directly, you can check for updates without downloading. Electron may always download, but not apply, and the file should be cached locally

**Comment by paulcbetts** [comment]
It would probably be a good PR to give users that option thoguh
