### ISSUE TITLE
Release build failing due to projects missing ILRepack nuget package reference.

### ISSUE THREAD

**Issue by JimiC** [Squirrel/Squirrel.Windows#722]
The projects `SyncReleases` and `Update` are missing a nuget package reference to `ILRepack` causing them to fail on `Release` build.

**Comment by shiftkey** [comment]
@JimiC why do we need to add `ILRepack`? These are solution-level packages and unless something is changing that MSBuild parameter it's not clear to me how this is breaking.

https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/SyncReleases/SyncReleases.csproj#L84

Can you elaborate more about what's breaking on your side?

**Comment by JimiC** [comment]
Thanks for reminding me about this issue. I have abandoned the project I wanted to package with `Squirrel` and `Squirrel` altogether.

**Comment by JimiC** [comment]
Just for the fun of it, line 84 in `SyncReleases` states that the builder should use `ILRepack.exe` from the `packages` folder but the `packages` do not include the said package. Thus even when doing `nuget restore` no `ILRepack` gets downloaded so the builder fails because it can not find the executable.

My PR just included that package reference. I'm not sure if you get that package in another way through.

**Comment by shiftkey** [comment]
> My PR just included that package reference. I'm not sure if you get that package in another way through.

Yeah, I'm just curious why this appears to be the only report about it. I'll keep an eye out for others, but at least there's one potential solution here if we have others who have encountered it...
