### ISSUE TITLE
Specify Executables that should be in start menu and desktop

### ISSUE THREAD

**Issue by cwoolum** [Squirrel/Squirrel.Windows#726]
I am deploying an application that relies on CefSharp. The package is created successfully but the installer puts a CefSharp icon on my desktop and in the start menu. Is there any way to prevent this?

**Comment by paulcbetts** [comment]
Yep - follow the steps at https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md and this should stop happening
