### ISSUE TITLE
update url on a network storage

### ISSUE THREAD

**Issue by Schrims** [Squirrel/Squirrel.Windows#730]
hi guys,
i got squirrel working on my local file system and now i want to store the release files on a network storage. I tried to use '\\ip-address\folder\releases' as a url but it isn't working - so the question is what url should i use to get it working on a network storage?

**Comment by Schrims** [comment]
any thoughts?

**Comment by paulcbetts** [comment]
UNC paths start with two slashes

**Comment by pablopedrosa** [comment]
Hi there, did you find a solution?, I got stuck in mgr.CheckForUpdate();. . . the UNC path is correct.

**Comment by soraryu** [comment]
Since this one was closed without resolution I opened a new one : #1175
