### ISSUE TITLE
Is it possible to have the exe always in the same folder?

### ISSUE THREAD

**Issue by Edddy** [Squirrel/Squirrel.Windows#733]
I have an app that must run with windows (It adds itself to `SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run` if the user agrees to do it), so I need the current version to stay in the same folder.

Is it possible with Squirrel?

**Comment by paulcbetts** [comment]
Use the "Startup" shortcut type and use that instead, it'll automatically write out something that works with all versions

**Comment by Edddy** [comment]
Perfect. Thanks!
