### ISSUE TITLE
Determining the installation location for an app

### ISSUE THREAD

**Issue by veleek** [Squirrel/Squirrel.Windows#736]
I have an app that's installed and updated using Squirrel.  I would like to automatically do the installation and launching via a powershell script so that I can easily provide it to my team members.

In this case, the installer I have doesn't point to the most recent version so whenever I launch it using the installer I have (via the script) it doesn't launch the most recent version.  Is there anyway using the squirrel installer I can tell it to launch whatever version in installed or at least point me to the installation location?

**Comment by tomuxmon** [comment]
We could append "path" system environment variable. Can squirrel installer require (like MSI) launch under elevated permissions?

**Comment by paulcbetts** [comment]
Squirrel apps already install and launch automatically when you double click them? If you want to do something like "Launch whatever the latest version of X.exe is", mimic what the shortcuts do:

```
%LocalAppData%\MyApp\Update.exe --processStart myApp.exe
```

> We could append "path" system environment variable. Can squirrel installer require (like MSI) launch under elevated permissions?

Nope, though you could use the per-user PATH

**Comment by veleek** [comment]
@paulcbetts That's exactly what I was looking for.  Thanks!
