### ISSUE TITLE
Version.dll hijacking on Windows 7

### ISSUE THREAD

**Issue by bardospeter** [Squirrel/Squirrel.Windows#738]
I've tested our squirrel installer on several machines. It seems that for some reason on windows 7 version.dll can be hijacked.

**Comment by AnderssonPeter** [comment]
If you want this fixed maybe you should explain the problem more in depth, and how you managed to hijack it?

**Comment by shiftkey** [comment]
We have the ability to control this, see #1444 for a related example, but it looks like this issue didn't get a follow up about how `version.dll` could be hijacked so I'm going to close this out for now.
