### ISSUE TITLE
How to rename the desktop shortcut.?

### ISSUE THREAD

**Issue by reach2deep** [Squirrel/Squirrel.Windows#742]
HI

How to rename the desktop Shortcut??

By default it creates the desktop shortcut name same as Assembly name. how to rename it ?

Thanks in advance

**Comment by jackjwilliams** [comment]
I would love to know how to do this as well. With the ability to support multiple channels, it would be nice to be able to have side-by-side shortcuts (Beta, Prod).

**Comment by agostinocinelli** [comment]
+1 here.
ApplyReleasesImpl.CreateShortcutsForExecutable() should have an extra parameter:
    public enum ShortcutName
    {
        VersionInfoProductName,
        PackageTitle,
        VersionInfoFileDescription,
        VersionInfoFileName
    }

**Comment by agostinocinelli** [comment]
I tried to do it by myself, but I cannot make it work.

**Comment by richkeenan** [comment]
Has anyone got any info on this?

**Comment by sstorie** [comment]
There is (now) documentation on how the shortcut name is determined - https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/naming.md#shortcut-name

**Comment by Thieum** [comment]
@reach2deep @shiftkey this can be closed, the original issue is now adressed in the doc.
