### ISSUE TITLE
Do i miss anything when update url is HTTP

### ISSUE THREAD

**Issue by reach2deep** [Squirrel/Squirrel.Windows#744]
Hi,

i made a installer, all work well, when its local network path, when i update the remote path ,it throwing 404 not found exception. i noticed some query params in the url while debugging. do i need to add any script in IIS to process the query string? 

http://XXX//MyApp/Releases/RELEASES?id=MyApp&localVersion=16.8.9&arch=amd64

**Comment by mzmousa** [comment]
What server are you using to for your update URL's? I recommend [Nuts](https://github.com/GitbookIO/nuts).

**Comment by reach2deep** [comment]
@mzmousa am using IIS server, is it possible to use static file hosting. Nuts looks more advanced, i just want to download from remote server. is there anyway?

**Comment by mzmousa** [comment]
> is it possible to use static file hosting

You mean, you just want to host your files on any server at all to test your app's functionality? I like to use [http-server](https://www.npmjs.com/package/http-server) for that. Just `npm install -g http-server` then start it up in any directory by doing `http-server -p 8081` (8081 can be replaced with any other valid port number). Now if you're using that to test, make sure that setting your `autoUpdater` feedURL looks something like this:
```
var os = require('os');
var electron = require('electron');
var platform = os.platform() + '_' + os.arch(),
version = electron.app.getVersion();
var feedURL = 'http://localhost:8081'
autoUpdater.setFeedURL('http://localhost:8081' + '/' + platform + '/' + version);
autoUpdater.checkForUpdates();
```

Of course, when you have a real server, your `feedURL` will be `http://xxx'
> Nuts looks more advanced

Nuts is simple, not very advanced, but you to host a real server somewhere to use it (I recommend [IBM's Bluemix](https://console.ng.bluemix.net/registration/). All it does is host your Github releases on a server that is query-able by your update and download URL's.

**Comment by paulcbetts** [comment]
Yes, Squirrel.Windows was explicitly designed so that dumb static file hosts like S3 can be used, the query parameters are strictly optional

**Comment by reach2deep** [comment]
@paulcbetts @mzmousa  Thanks for the message

How the static file hosting works? Am hosting in the IIS of my own server( Windows server 2012)

requirement is simple. Squirrel works perfect when its a local location path(D://myApp). i tried to  place the folder in IIS . it doesn't work,

This is my IIS folder strructure with the webconfig as specified. but no luck, do i miss anything ?? Please advise

[Click to view the IIS Folder structure](https://s31.postimg.io/cd88nkyvv/squi.png)

**Comment by InteXX** [comment]
@paulcbetts — How can I get this working on IIS with an .ASHX file? I've posted more detail [here](https://github.com/Squirrel/Squirrel.Windows/issues/1219).

**Comment by InteXX** [comment]
@paulcbetts — Merry Christmas  :-)

**Comment by nSwann09** [comment]
I had the same issue.

On IIS create a web.config file in the directory with the RELEASES file containing the following and it will allow the file to be viewed/downloaded

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<staticContent>
             <mimeMap fileExtension="." mimeType="text/plain" />
         </staticContent>
	</system.webServer>
</configuration>`

**Comment by Thieum** [comment]
@InteXX There is now a doc about [hosting on IIS](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/microsoft-iis.md). If this doc helps you out, you can close this issue.

**Comment by InteXX** [comment]
@Thieum 

Excellent, thank you. This is right on time.

**Comment by Thieum** [comment]
@shiftkey this can be closed.
