### ISSUE TITLE
Installation icon wrong colors?

### ISSUE THREAD

**Issue by AnderssonPeter** [Squirrel/Squirrel.Windows#745]
In my `*.nuspec` I added the following row `<iconUrl>http://domain/Icon.png</iconUrl>` then I packed and releasyfied my program.
After installing it the icon got used in `Programs And Features` but it mangled the image totally.
[Orginal](http://i.imgur.com/jK848Q4.png)
[After installation](http://i.imgur.com/hb0wp16.png)

Why on earth did it mangle the image? and how do I fix it, the specification for nuspec files told me to point it at a `.png` that is 64x64 with transparent background and that is what I did.

Also when is this Icon fetched? (at packaging time or installation time?)

**Comment by paulcbetts** [comment]
Use an ICO file

**Comment by AnderssonPeter** [comment]
@paulcbetts ok ill try that but `When is this Icon fetched? (at packaging time or installation time?)`.

**Comment by paulcbetts** [comment]
Installation time

**Comment by AnderssonPeter** [comment]
Thanks!
