### ISSUE TITLE
Remove old shortcut after renaming

### ISSUE THREAD

**Issue by dougludlow** [Squirrel/Squirrel.Windows#748]
Hey, I have a situation where we renamed renamed the company in our electron app and so a start menu shortcut was created in a separate folder and left the old ones orphaned. What's a good way to go about removing the old folder/shortcut in the start menu?

**Comment by damieng** [comment]
You probably want to write some custom code using the Squirrel Events to clean up the old icons;

https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md

**Comment by shiftkey** [comment]
Seconding the suggestion from Damien here.

There's also docs for non-C# apps that is helpful for Electron apps to know what events to hook: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md
