### ISSUE TITLE
Using Squirrel on a .Net 4.0 project

### ISSUE THREAD

**Issue by iamthefaker** [Squirrel/Squirrel.Windows#75]
When I:
PM> Install-Package squirrel.windows

Amongst other things, I get:
Install failed. Rolling back...
Install-Package : Could not install package 'Splat 1.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Thinking I could use the binaries from the releases section instead, but isn't this still going to be a problem?

**Comment by JohnThomson** [comment]
I can live with it not working on XP, but it would be nice to get a better message when someone tries. See #282.

**Comment by Petoj87** [comment]
"It's like ClickOnce but Works™" dosent hold true, ClickOnce actually works on XP but Squirrle does not?

**Comment by paulcbetts** [comment]
Nope! It doesn't

**Comment by Petoj87** [comment]
@paulcbetts sure it does we have been using it for 4 years, i would not say its flawless and the best product ever but it installs and updates our software,

Now if it was flawless i would not be here, but it works at one place where Squirrle does not.
But the question i have is this still on the post 1.0 todo or is it scrapped?

**Comment by paulcbetts** [comment]
4.0 is even deader than it was 12mo ago. Closed!

**Comment by mikkoviitala** [comment]
Deadier or not, as of 2017, corporate clients are still not willing to drop XP support from their requirements.

**Comment by pavel-kudishin** [comment]
Any news on .net framework 4.0 support?

**Comment by paulcbetts** [comment]
@pavel-kudishin 🙃🙃🙃🙃🙃🙃🙃🙃

**Comment by ghuntley** [comment]
@mikkoviitala and @pavel-kudishin 

![image](https://user-images.githubusercontent.com/127353/31691382-abe87856-b3e1-11e7-8764-ebf56e52f530.png)

**Comment by mikkoviitala** [comment]
@ghuntley spent a day on it. Dropped because of reasons.
