### ISSUE TITLE
Take advantage of Install.ps1 execution when installing package

### ISSUE THREAD

**Issue by martin0** [Squirrel/Squirrel.Windows#750]
Hi,
As per [here](http://docs.nuget.org/create/creating-and-publishing-a-package#automatically-running-powershell-scripts-during-package-installation-and-removal) I am exploring executing a powershell script when the package is installed.
I created a simple Install.ps1, and installed the package via squirrel. I couldn't see any sign the powershell script had run. Is this perhaps only applicable when nugget is run within a Visual Studio environment?
I also tried to debug the behaviour as per [this](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/debugging-installs.md) I tried the command 
Update.exe --squirrel-install 1.0.0 (with my version number)
The response I got was
Usage: Squirrel.exe command [OPTS] .....
implying squirrel had not been invoked correctly by Update.exe

Is this the best place to ask such questions? Apologies if not, I couldn't find anywhere else.

Thanks for any help forthcoming
Martin

**Comment by paulcbetts** [comment]
You should use Squirrel Hooks to do that instead
