### ISSUE TITLE
HandleEvents not working on WPF applicaton except onFirstRun

### ISSUE THREAD

**Issue by MarcoMedrano** [Squirrel/Squirrel.Windows#752]
Hi, I used squirrel before for console application and other events were working. Now I am doing a WPF application and tried the **Startup** event, constructor and static constructor, but it is not working. My app does not need elevated permissions, neither I did something around that.
**onAppUninstall** is not working as well.

I updated to last version of squirrel 1.4.0 and cleaned my app from %appdata%.
My code `SquirrelAwareApp.HandleEvents` is not wrapped on `using (var mgr = UpdateManager...` but using it did not work neither.

**Comment by paulcbetts** [comment]
Do you have the Assembly attribute you need?

**Comment by MarcoMedrano** [comment]
Yep I have this
`[assembly: AssemblyVersion("1.0.3")]
[assembly: AssemblyFileVersion("1.0.3")]`

on AssemblyInfo.cs

**Comment by paulcbetts** [comment]
No, the SquirrelAppAware assembly attribute

**Comment by MarcoMedrano** [comment]
Heck forgot to add that, now all events are working (could not test yet `onAppUpdate` ).
Thanks for your fast help! and sorry it was my fault.

**Comment by paulcbetts** [comment]
No worries :)
