### ISSUE TITLE
command line options and build questions

### ISSUE THREAD

**Issue by martin0** [Squirrel/Squirrel.Windows#753]
Thanks for answering my questions yesterday Paul.

I need to be able to run the setup program and pass a parameter that will end up influencing how my software runs. I saw in the source code for squirrel.windows v1.3 file Update\program.cs that there is a command option process-start-args. It's not clear to me the syntax I need to use for this option. In addition, although I have squirrel v1.3 installed via nuget and powershell in visual studio, when I run squirrel --help, it doesn't show that option.
I want to be able to run setup.exe -a="name=value" and have "name-value" end up in the shortcut generated to run my program (and for it to be used the first time the program is run).

I also find that when I build Squirrel from the source code, I don't get the Squirrel.Windows nupkg file. Nor do I get Squirrel.exe which is present in the tools directory of the package in visual studio.

Can you offer advice/help on those two questions?
Many thanks
Martin

**Comment by elmahdibenhadda** [comment]
Same question : How can we passe argument to Setup.exe then get them back when the application is lunched after Setup finish .... ??
When the application has finished installing you can use : 

` Update.exe --processStart MyExe --process-start-args "arg1 arg2 arg3" .`

**Comment by shiftkey** [comment]
> I want to be able to run setup.exe -a="name=value" and have "name-value" end up in the shortcut generated to run my program (and for it to be used the first time the program is run).

Merging this one into the older issue #293, as ` --process-start-args ` is only for use with `Update.exe`.
