### ISSUE TITLE
RELEASES format

### ISSUE THREAD

**Issue by astoilkov** [Squirrel/Squirrel.Windows#756]
I have a RELEASES file. I want to change theformat. Can I do this without breaking something?

I am not sure if this is a specific format I should follow `{appName}-{appVersion}-{type}.nupkg` or I can change it to use my own format: `{appName}.nupkg`

```
﻿44DED8FF2CEA4949E7B33C4525B47F223497BBE0 Caret-1.3.4-full.nupkg 48577749
```

**Comment by shiftkey** [comment]
As we talked about in #125 we don't have plans to extend or change the `RELEASES` format, because of backwards-compatibility risks with existing clients and applications that don't know how to handle new/different fields.
