### ISSUE TITLE
How can I create an uninstall shortcut in the start menu?

### ISSUE THREAD

**Issue by zhouce** [Squirrel/Squirrel.Windows#759]
I know the Update.exe is the uninstaller entry. But how can I create an uninstall shortcut in the start menu?
Thanks!

**Comment by sanqianpiao** [comment]
@zhouce I have the same question

**Comment by Andrew-Hanlon** [comment]
Guys, this is open source code. Look at how the [application shortcuts are created](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.ApplyReleases.cs) and how the [uninstaller entry is created](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.InstallHelpers.cs)... mix and match.

**Comment by zhouce** [comment]
@Andrew-Hanlon Actually, I use squirrel in my Electron application.   Your answer gave me some idea. Thanks.

**Comment by damieng** [comment]
You can always uninstall the app from the uninstall add/remove app in Windows.

Putting an icon in the start menu is not only unnecessary but it clutters it and often interferes with people finding the built-in one when they type 'uninstall' into the start menu.  (As well as coming ahead of the system one often the Uninstall shortcuts don't even say what they will uninstall)

**Comment by MarshallOfSound** [comment]
@damieng I completely agree, this is no appropriate reason to add another shortcut to someones **start** menu to uninstall the app.  That is what Control Panel is for
