### ISSUE TITLE
Setup: If the install or the app launch fails, feedback should be given to the user

### ISSUE THREAD

**Issue by christianrondeau** [Squirrel/Squirrel.Windows#76]
I had a first run of user installs with my app, [GoToWindow](http://christianrondeau.github.io/GoToWindow/). It went ok for the most part, but I had some negative feedback.

One of them ran the installer, but nothing happened. The software was already installed, this is already logged as #69.

Another said that nothing happened. I'm not sure what the problem was exactly, and they couldn't find a `SquirrelSetup.log` file (I didn't push the issue).

I think that if for whatever reason something doesn't work, including:
- The setup itself
- Any of the app launches with `--squirrel-*` 
- If the first run returns within some time span with a non-zero exit code

a clear error message should be shown to the user, including an easy way to get the log file so they can send it back to the application developer.

Even better would be an optional "Send error log to the developer", using an email address from the `nupkg`, but I'm getting ahead of myself :)

I believe an error is frustrating, but so much less than no feedback at all.

**Comment by shiftkey** [comment]
Closing this out because I'm not sure what work here is left to do.
