### ISSUE TITLE
Squirrel.Windows 1.4.1 modifies directory structure. 

### ISSUE THREAD

**Issue by ruZZil** [Squirrel/Squirrel.Windows#765]
I have packaging an app using electron-winstaller (with grunt-electron-installer).

grunt-electron-installer:

  "dependencies": {
    "electron-winstaller": "^2.2.0"
  }

on a project based off https://github.com/chentsulin/electron-react-boilerplate

This solution has been working well for us. (Thanks!)

However, electron-winstaller just pulled Squirrel.Windows 1.4.1 - https://github.com/electron/windows-installer/pull/116

This causes some runtime errors for us, and I've found that the directory structure of our app has changed. 

Below is a diff from the output of find . command.

After manually moving the files back in place, the app works. 

Wether our directory structure is conventional or not, I'll work on figuring that out. However, I don't believe the installer should modify the structure, so your attention would be appreciated.

Thanks!

-Russ. 

Squirrel.Windows 1.4.1 (Doesnt work):
< ./lib
< ./lib/net45
< ./resources/app/node_modules/source-map-support/node_modules/source-map/array-set.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/base64-vlq.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/base64.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/binary-search.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/source-map-consumer.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/source-map-generator.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/source-node.js
< ./resources/app/node_modules/source-map-support/node_modules/source-map/util.js

Squirrel.Windows 1.4.0 (WORKS):
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/array-set.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/base64-vlq.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/base64.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/binary-search.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/source-map-consumer.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/source-map-generator.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/source-node.js
> ./resources/app/node_modules/source-map-support/node_modules/source-map/**lib/source-map**/util.js

**Comment by paulcbetts** [comment]
This is fixed in 1.4.2
