### ISSUE TITLE
Debugging Squirrel?

### ISSUE THREAD

**Issue by AnderssonPeter** [Squirrel/Squirrel.Windows#766]
When i try to create a new release i seem to get the issue described in https://github.com/Squirrel/Squirrel.Windows/issues/539

So i cloned the repo with visual studio 2015 community, but the Squirrel project is a `Class Library` and not a `Console Application`?

**Comment by AnderssonPeter** [comment]
I figured out how to debug with https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/contributing/vs-solution-overview.md please close this, and if possible please checkout https://github.com/Squirrel/Squirrel.Windows/issues/539

**Comment by Thieum** [comment]
@shiftkey this can be closed
