### ISSUE TITLE
SyncRemoteReleases does not pass along query parameters when requesting files

### ISSUE THREAD

**Issue by mbutters** [Squirrel/Squirrel.Windows#769]
While building an application using a populated releases file that contains urls with query string parameters, once the files are requested they do not contain the query parameters.  Example:

Release File contents:

`F137844DD5C32B49752131B05ZXXED0328 https://somedomain.com/somepath/files/filename-1.0.0-full.nupkg?release=5C9272399XA5DRD8369670`

Squirrel will request: https://somedomain.com/somepath/files/filename-1.0.0-full.nupkg (excluding the parameters)

The cause of this issue is: https://github.com/Squirrel/Squirrel.Windows/blob/master/src/SyncReleases/SyncImplementations.cs#L28

The URL is manually being built with the domain and file name and not including the query parameters.  The fix would be to also include the query parameters.

**Comment by mbutters** [comment]
Pull request has been created for this: https://github.com/Squirrel/Squirrel.Windows/pull/770

**Comment by Andrew-Hanlon** [comment]
Can I ask how you setup your nuspec/squirrel to get the domain name in the Releases file? This (along with your fix) would allow hosting on S3 with 'private' urls.

**Comment by mbutters** [comment]
Our releases file is remotely hosted and is generated once requested by our internal file list that we store in a database.  The domain name either can be generated on the fly (as the current domain) or can be placed statically.

**Comment by mbutters** [comment]
Also to add to this, it looks like the UpdateManager does pass along the query parameters:  https://github.com/Squirrel/Squirrel.Windows/blob/9de260cb6b614234511d57723738f1be2ed25476/src/Squirrel/UpdateManager.DownloadReleases.cs#L70  but the SyncImplementation does not.  We were wondering why there was a inconsistency between them and figured it was an oversight.

**Comment by Andrew-Hanlon** [comment]
Ah, interesting thanks for the additional info. So in fact I can already set this up just by manually adding the query parts to my Releases. Going to try it.

**Comment by Thieum** [comment]
@shiftkey PR fixing this issue has been merged, this can be closed.
