### ISSUE TITLE
Squirrel Console update Sample 

### ISSUE THREAD

**Issue by ghost** [Squirrel/Squirrel.Windows#772]
Hi,

Not sure if this is the right spot to post this but can any one tell me where I can find a sample console application made in c# that uses squirrel for updates.

**Comment by Keboo** [comment]
I posted a very simplistic code snippet on #1098

**Comment by di48l069** [comment]
@Keboo thanks

**Comment by gojanpaolo** [comment]
@shiftkey OP is a deleted account and question was answered so this can be closed
