### ISSUE TITLE
Using for service applications

### ISSUE THREAD

**Issue by DamianReeves** [Squirrel/Squirrel.Windows#777]
Most of the concepts in squirrel would work great for the deployment of our microservice applications, is there any reason we couldn't use the underlying update technology in a non-desktop application?

**Comment by dealproc** [comment]
I'd be interested in hearing your proposal, @DamianReeves, on how you see this being possible?  Squirrel.Windows has been authored to install and operate in the user context, whereas windows services are typically authored to be installed in the system/local service context instead.

**Comment by MattFellows** [comment]
I'm considering using squirrel as an installer for a .Net Core service, initially Windows but potentially other platforms in the future.  How much of a headache am I likely to get?

**Comment by lukeskinner** [comment]
Personally I wouldn't use Squirrel for this. The core of Squirrel is desktop applications, it has no support for elevating privileges required to install services on Windows. It's also going to try put the files for the services in the logged in users profile (appdata) which is not the place to be putting windows services.

Generally speaking you should also run your services on a user with the minimal security permissions required - this often means the user can't log into Windows... so how do you run the installer then?

You would have to fork Squirrel and comment out so much code that you would be better off using a more conventional solution to installing the windows service:

- [Wix](https://developingsoftware.com/wix-toolset-install-windows-service/) - Free
- [Advanced Installer](http://www.advancedinstaller.com/) - Paid

Also Squirrel has [no support for linux](https://github.com/Squirrel/Squirrel.Windows/issues/106) if that is the other platform you're referring to.

**Comment by paulcbetts** [comment]
Squirrel wouldn't be good for this, I would use a CD solution like Octopus Deploy (https://octopus.com/) instead
