### ISSUE TITLE
Missing binary .zip from latest releases

### ISSUE THREAD

**Issue by hvassbotn** [Squirrel/Squirrel.Windows#780]
The last two releases (1.4.1 and 1.4.2) does not have a link to the pre-compiled binaries zip, like the other releases do:

https://github.com/Squirrel/Squirrel.Windows/releases

Some of us would like to use Squirrel.Windows for non-dotnet projects and may even not have VS installed :-).

**Comment by paulcbetts** [comment]
Are you using Electron? I post these binaries to electron-winstaller

**Comment by paulcbetts** [comment]
But also, fair point regardless

**Comment by hvassbotn** [comment]
Hi Paul,

Thanks for the tip!

I'm not using Electron (which is a way of writing local apps using HTML5,
IIUC?), we're using Delphi to write a financial information and trading app
for Windows (see goinfront.com).

No hurry with the latest version, 1.4.0 should be fine for now :)

**Comment by paulcbetts** [comment]
Hit up https://github.com/electron/windows-installer/tree/master/vendor
