### ISSUE TITLE
Use with ASP.NET application?

### ISSUE THREAD

**Issue by mr-burnse** [Squirrel/Squirrel.Windows#782]
Can this project be used for auto-upgrading an ASP.NET web application and Windows service?  Most the content refers to desktop based applications.  Thanks!

**Comment by paulcbetts** [comment]
No, sorry

**Comment by kenbailey** [comment]
@mr-burnse, take a look at TeamCity (build server) and Octopus (automated web and windows service deployment). They are both commerical, but have a either a community edition or free for limited use options that have worked for us. And the tools are really nice.

**Comment by mr-burnse** [comment]
Thanks @kenbailey much appreciated!  Looks like it may be a good fit.
