### ISSUE TITLE
Installing to Roaming AppData instead of Local

### ISSUE THREAD

**Issue by DanielRivers** [Squirrel/Squirrel.Windows#785]
Can Squirrel install to the roaming profile instead of the local profile?

**Comment by paulcbetts** [comment]
No, Squirrel doesn't let you configure the installation location, sorry

**Comment by DanielRivers** [comment]
I understand not letting configure, issue being we have uses that switch desks a lot, so they use roaming appdata profile.  %appdata% points to their roaming.  Would be good if Squirrel used the %appdata% location instead of forcing local.  At present every time they move desks we have to reinstall.  This simple tweak would prevent this and also keep Squirrel as intended.

**Comment by paulcbetts** [comment]
Use the MSI and install the app for all users on your machines
