### ISSUE TITLE
Symantec Anti-Virus Squirrel Installer issue

### ISSUE THREAD

**Issue by SiddharthMalhotra** [Squirrel/Squirrel.Windows#786]
We have built our installer through squirrel installer. We generate the installer through a build loop. 
Contents of the build loop are as follows: 
1) We use a PowerShell script to change the environment of the app.config file of our project
2) We build the Nuget package through a Nuspec file, containing references to the dll's
3) Further, we use Squirrel to build the installer through the Nuget package generated above

For the DEV installer we do not face the antivirus pop-up. However for TEST and PROD environments we face the Symantec anti-virus problem. Please note that all of these installers are generated through the same build loop (DEV/TEST/PROD in the same order) and we change the environment though the PowerShell script mentioned in the first step. 

How can we avoid the antivirus pop-up issue on the TEST and PROD environments?

**Comment by paulcbetts** [comment]
Sign your installer and make sure you're using the very latest Squirrel.Windows which has some improvements to AV nonsense
