### ISSUE TITLE
File type association

### ISSUE THREAD

**Issue by Andrew-Hanlon** [Squirrel/Squirrel.Windows#788]
After searching through the repository, I was not able to find any previous discussions around associating a file extension with your squirrel-installed application. Before writing code, are there any existing biases/reasoning against implementing this in Squirrel? 

Since the command line for the shell/open registry entry should likely follow the same semantics as the shortcut target, I think it would be ideal to have two similar methods in Squirrel like Create/RemoveFileAssociation. 

Obviously there are some complexities and limitations (if the file type is already associated or has defaults) but otherwise it's a fairly straightforward local-user registry addition.

Happy to make a first pass pull-request if this feature is desirable.

**Comment by samirem** [comment]
Any news on this?

**Comment by JBamford1** [comment]
This would be a very useful implementation. It makes no sense that you can't make file associations to an installer.

**Comment by paulcbetts** [comment]
You don't need to add any additional code in Squirrel to do this, check out https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md

**Comment by JBamford1** [comment]
@paulcbetts Are there any examples on how to do this? I feel like the docs aren't clear enough on how to perform custom events.

**Comment by netroby** [comment]
Any example to show us how to deal with it ?thanks.

**Comment by lightlike** [comment]
I worked on a Workaround some using Registry some time ago. Maybe this might help.
https://github.com/Drachenhorn-Team/Drachenhorn/tree/master/Drachenhorn.Desktop/Resources

The code calling those Reg-Files is here:
https://github.com/Drachenhorn-Team/Drachenhorn/blob/master/Drachenhorn.Desktop/UserSettings/SquirrelManager.cs
