### ISSUE TITLE
Can Squirrel run PowerShell scripts during updates / installation like Nuget does?

### ISSUE THREAD

**Issue by provkristian** [Squirrel/Squirrel.Windows#790]
Can Squirrel run PowerShell scripts during updates / installation like Nuget does?  Thanks.

https://docs.nuget.org/create/creating-and-publishing-a-package#automatically-running-powershell-scripts-during-package-installation-and-removal

**Comment by provkristian** [comment]
I just did an experiment with some really simple PowerShell scripts and it appears that this does not work. I created a tools folder like the Nuget documentation suggests and included an Init.ps1, Install.ps1, and Uninstall.ps1.  So, I suppose that I answered my own question.  :)

**Comment by paulcbetts** [comment]
No, they don't work, you should use Squirrel Events instead

**Comment by provkristian** [comment]
Okay, thanks.
