### ISSUE TITLE
How can the user move to a previous version?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#796]
Hello,

Is it possible to give the user the ability to move to a previous version?

Thank you in advance.

**Comment by kneuvirth** [comment]
I have been trying to do this same thing. Any help would be appreciated.

**Comment by andymartinwork** [comment]
Have them uninstall the current version, and send them the installer for the old version?

**Comment by gojanpaolo** [comment]
@shiftkey duplicate of other rollback issues (#524, #964)

**Comment by Thieum** [comment]
@shiftkey @gojanpaolo the "original" downgrade issue is #145 Should we consolidate?

**Comment by gojanpaolo** [comment]
@Thieum yes. I think we should update the documentation and then close the two I mentioned above as those discusses the workarounds/strategies instead of having it built-in the library.

**Comment by shiftkey** [comment]
Closing this out in favour of #524
