### ISSUE TITLE
How to "Start the Application from Web or Network share"?

### ISSUE THREAD

**Issue by atverma** [Squirrel/Squirrel.Windows#797]
I want to use Squirrel.Windows however I am not able to find feature similar to ClickOnce feature - "Start the Application from Web or Network share". If I create a ClickOnce package I can use Mage.exe to control whether app needs to be installed on local system or in cache. Do we have anything similar to this in Squirrel.Windows? More details about ClickOnce feature is as below

This strategy is like the first, except the application behaves like a Web application. When the user clicks a link on a Web page (or double-clicks an icon on the file share), the application is started. When users close the application, it is no longer available on their local computer; nothing is added to the Start menu or Add or Remove Programs in Control Panel. Technically, the application is downloaded and installed to an application cache on the local computer, just as a Web application is downloaded to the Web cache. As with the Web cache, the files are eventually scavenged from the application cache. However, the perception of the user is that the application is being run from the Web or file share.
This strategy works best for applications that are used infrequently—for example, an employee-benefits tool that is typically run only one time each year.
To enable this deployment strategy in Visual Studio, click Do not install the application on the Install or Run From Web page of the Publish Wizard.
To enable this deployment strategy, manually, change the install tag in the deployment manifest. (Its value can be true or false. In Mage.exe, use the Online Only option in the Application Type list.)

**Comment by paulcbetts** [comment]
This doesn't exist in Squirrel, sorry
