### ISSUE TITLE
how to run the app on background (not showing windows) when windows start

### ISSUE THREAD

**Issue by wangxiexe** [Squirrel/Squirrel.Windows#799]
I am making my app run at Startup by doing:
  
      childProcess.execSync(path.join(app.getAppPath(), '../../../Update.exe') + ' --createShortcut=MyApp.exe -l=Desktop,StartMenu,Startup')

but when windows startup, my app just run as normally click on the app link and show a big window, what I want is for windows startup auto run, I want it run silently and stay on the tray 

Please advise. Thanks!

**Comment by dealproc** [comment]
That is outside the scope of squirrel.windows i believe.  There are a few articles on the web that discuss how to put your application into the windows system tray. 

Here's one from codeproject that discusses it. http://www.codeproject.com/Articles/290013/Formless-System-Tray-Application

HTH

**Comment by wangxiexe** [comment]
thanks dealproc, actually I noticed windows provided option for such feature

http://www.cnet.com/how-to/how-to-automatically-start-a-program-minimized-in-windows/

not sure if we can create startup link which will make app run as minimized. 

Thanks.

**Comment by wangxiexe** [comment]
and also I noticed there is a npm package

https://github.com/Teamwork/node-auto-launch/blob/master/src/AutoLaunchWindows.coffee

but seeems it does not work with latest squirrel

**Comment by wangxiexe** [comment]
used auto-launch with params passed into my app and I can control show or hide.

**Comment by Razzeee** [comment]
@wangxiexe 
can you post how exactly you've solved this? As it seems like the hidden param gets ignored/removed by squirrel somehow

**Comment by wangxiexe** [comment]
@Razzeee  

var appLauncher = new AutoLaunch({
    name: 'MyApp',
    isHidden: true
});

and appLauncher.enable() will append --hidden in the app launch call. 

can you see  hidden is there in the windows registery ? 

if yes, then you just simply hide the window like this： 

      if (process.argv[2] == '--hidden') {
        mainWindow.hide()
      }

**Comment by Razzeee** [comment]
Well my error seem to be caused by `auto-launch` not setting the parameters correctly.
As soon as I package the app into an exe via `windows-installer` it fails.
This PR should fix it https://github.com/Teamwork/node-auto-launch/pull/39 not sure if that will be accepted.
