### ISSUE TITLE
WriteZipToSetup.exe detected as virus by McAfee

### ISSUE THREAD

**Issue by pdinnissen** [Squirrel/Squirrel.Windows#800]
Every other antivirus is okay though according to https://www.virustotal.com/en/file/2b1b48420a1c1ed39a66dfb9ec29f0ff153dad5a9f592f27e6a6edc432de6d9a/analysis/
But McAfee (which is what is being used at my workplace) detects this file as 'Artemis!93D2D59A3747'.

Recommendations? Workarounds?

The file is being deleted as soon as it's downloaded, so Nuget throws and error and rolls back.

**Comment by paulcbetts** [comment]
Uninstall McAfee and update to Windows 10. Unfortunately, many of the tasks that installers do are very similar / identical to what malware does (a background updater and a trojan horse do all of the same things, it's just that the former has user consent), so we're always going to see some of these problems.

**Comment by pdinnissen** [comment]
I would love to do both those things but I don't have control over either of those items at my workplace.  Is there no way to sign the exe or something along those lines to avoid this detection?

**Comment by paulcbetts** [comment]
No, sorry

**Comment by pdinnissen** [comment]
Fair enough.  I'll see if my IT department can whitelist it or try to find a workaround (This library is too good not to).
