### ISSUE TITLE
Squirrel.Windows - Target Releases folder from FTP Server

### ISSUE THREAD

**Issue by CDAGaming** [Squirrel/Squirrel.Windows#805]
When I run either Setup.exe or Setup.msi, I get this in my file directory

The package has all files in it too
![2016-08-28 1](https://cloud.githubusercontent.com/assets/16328918/18035794/4d5d89ea-6d22-11e6-9f03-8f9654e8d70e.png)
![2016-08-28 2](https://cloud.githubusercontent.com/assets/16328918/18035796/4d63c198-6d22-11e6-9bd8-049e1a93d38a.png)
![2016-08-28 3](https://cloud.githubusercontent.com/assets/16328918/18035795/4d62e552-6d22-11e6-8862-5a0b9e79522b.png)

**Comment by paulcbetts** [comment]
Can you share a sample nupkg file?

**Comment by CDAGaming** [comment]
Update: Package now installs, but I now wish to point the target Releases folder to my FTP Server, Any tip on how to do this?

**Comment by paulcbetts** [comment]
FTP servers aren't supported, use HTTPS

**Comment by CDAGaming** [comment]
How, Can i have it target the directory through https? Sorry if it seems like a sumb question am very new to this

**Comment by CDAGaming** [comment]
CLOSING ISSUE -- Am Now utilizing github as update manager, Will post again if there are further issues, Thanks again @paulcbetts
