### ISSUE TITLE
Squirrel.Windows - Update Loop?!

### ISSUE THREAD

**Issue by CDAGaming** [Squirrel/Squirrel.Windows#808]
Well, Ive gotten every part of Squirrel.Windows working but when I try to launch my app it never opens,

It uses the GitHubUpdateManager with this:
![2016-08-29 3](https://cloud.githubusercontent.com/assets/16328918/18074520/d384496c-6e32-11e6-8f7c-bf894f775579.png)

It doesnt give any error, no log no anything

**Comment by floatas** [comment]
Issue is with incorrectly used async\await. Instead of them, start new thread, put update logic in it and don't wait for it to complete.
You can try something like this:
 ```
    Task.Run(async () =>
                {
                    await UpdateFunction();
                });
```

**Comment by CDAGaming** [comment]
Thanks
