### ISSUE TITLE
Update performance question

### ISSUE THREAD

**Issue by abakaa** [Squirrel/Squirrel.Windows#813]
Hello,

I have a 60mb size wpf application. Let's say a client did not use the application for a week.
If i'd deployed my application 10 times in this period of time, the update process would've taken way much longer than a normal single update would.

I guess squirrel downloads each delta and full package to 'packages' folder during the update, then removes them except the latest ones. Is this the expected behavior ?

How can i approach this problem and speed up things ?

Thanks.

**Comment by Andrew-Hanlon** [comment]
Squirrel compares the aggregate size of all of the intermediary delta packages against the full package size, and uses the smallest option. The worst case should be downloading the full 60mb application.

The code is found at the end of [UpdateInfo.Create](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateInfo.cs).

**Comment by Andrew-Hanlon** [comment]
It would be nice if there was an option to set a threshold size percentage when choosing the deltas versus the full package, as applying multiple small deltas that amount to 90% of the full package size is certainly much slower than downloading and applying a single full release.

**Comment by abakaa** [comment]
@Andrew-Hanlon Thanks for the info.

Upon further review, i don't think my problem is the size of the delta packages. Combining delta packages into full packages recursively takes time a lot i think. In my case, each full package (created from deltas recursively) adds to update duration by around 30 seconds. This means 300 seconds after 10 subsequent deployments. (Each delta package size is about 100 KB)

I check the updates on startup and restart after applying. This 5 minutes long update becomes a problem in this scenario.

I guess i will check for the updates after the application starts and silently apply it then show a message. In the mean time i will hope something doesn't break.

I'd be very happy to hear some other ways to handle this.

**Comment by Andrew-Hanlon** [comment]
One option would be to check for updates, and if the number of delta packages exceeds a desired threshold then re-perform the 'CheckForUpdate' specifying the 'ignoreDeltaUpdates' option. It's going to be a trade-off between download and apply times.

**Comment by paulcbetts** [comment]
Delta updates are designed to save bandwidth at the cost of CPU time. I think the solution to your problem is to not publish 10 updates in a week (probably because you've tied publishing to your CI server or sth)

**Comment by abakaa** [comment]
The 'ignoreDeltaUpdates' option may be the solution for me, in the meantime i will try to decrease the update frequency.

Thanks for the replies.

**Comment by hatton** [comment]
We have the same problem. What has worked on another of our products, produced with wix, is to do the diff from the product's major release. So you release 3.0 as a full install, then each minor release after that is a delta against 3.0, not yesterday's previous minor release. This seems like the best of both worlds. Since the bulk of most projects is the dependencies, and they are typically locked down for minor releases. So the deltas against the major release still end up being small, even though they span a larger range of versions.

I wish we could do that with Squirrel.

**Comment by abakaa** [comment]
That would be great if squirrel had this. Though i don't know if it is possible to implement this (maybe optional) behavior in the near future.

Thank you for the explanation.
