### ISSUE TITLE
Squirrel.Windows Question - GitHubUpdateManager

### ISSUE THREAD

**Issue by CDAGaming** [Squirrel/Squirrel.Windows#815]
I have a WPF PRogram that i plan to have two update channels:

Stable: Targets All Stable Releases or in Github, just called Releases
Beta: Tergets Pre-Release Github releases

Exactly how do i go about acomplishing this

**Comment by BarryThePenguin** [comment]
The only option here is the prerelease flag on the GitHubUpdateManager. Your app needs tobknow when to pass the flag through

**Comment by CDAGaming** [comment]
Can you show a code example of the flag being used?
