### ISSUE TITLE
Cannot locate resource 'mainwindow.xaml'

### ISSUE THREAD

**Issue by searope** [Squirrel/Squirrel.Windows#825]
Hello,

I'm testing out Squirrel to see if we can switch from ClickOnce to it. So I've created WPF app for the purpose. Brand new and empty WPF project runs just fine as expected. But once I add the NuGet package "squirrel.windows" and its 3 dependencies, I start getting exception with the message:

> An unhandled exception of type 'System.IO.IOException' occurred in PresentationFramework.dll
> Additional information: Cannot locate resource 'mainwindow.xaml'.

What could be wrong? I mean the only change to the new WPF project is the packages. I use VS2015 Enterprise with SP3.

**Comment by paulcbetts** [comment]
Probably using the wrong version of the .NET Framework, Squirrel.Windows is build against 4.5

**Comment by searope** [comment]
It seems the culprit was that I've named project **Squirrel**. Once I've changed **Default namespace** in the project properties to something else, I can start the project.

**Comment by stajs** [comment]
Seems a strange thing to fail on...

**Comment by MrAssembler0x00** [comment]
¿Do you verified that App.xaml file has StartupUri=" <NAME> .xaml"?
