### ISSUE TITLE
Switching between release channels?

### ISSUE THREAD

**Issue by searope** [Squirrel/Squirrel.Windows#826]
I have an app compiled slightly differently for different environments (say dev, staging and production) and I'm building them to different release folders. Say the builds have the same version.
Is it possible for the app to switch between channels and update to work with its corresponding environment? E.g. tree buttons in the app to update its bits from a corresponding channel?
I've tried to call UpdateApp() with UpdateManager pointing to different release folders and nothing happens, probably because all the apps share the same version,

**Comment by tankbob** [comment]
Isn't switching channels going to screw up the delta packages?

**Comment by paulcbetts** [comment]
@searope If all of your environments have equivalent versions this trick doesn't work, you have to have one single "timeline" of version numbers across all your environments

@tankbob It will, but then Squirrel.Windows will automatically retry with delta packages disabled
