### ISSUE TITLE
Squirrel.Windows - 0x75aedae8 in WPF Application

### ISSUE THREAD

**Issue by CDAGaming** [Squirrel/Squirrel.Windows#827]
MY Application is crashing and in a debugger i Downloaded this is the result before crashing:

![2016-09-13](https://cloud.githubusercontent.com/assets/16328918/18493310/79b497c6-79d5-11e6-8c33-ec7a8b3f78d9.png)

I hope you can help with this

**Comment by paulcbetts** [comment]
There is no information usable for this or anything to indicate this is Squirrel
