### ISSUE TITLE
'NuGet' could not be found

### ISSUE THREAD

**Issue by RickZeeland** [Squirrel/Squirrel.Windows#835]
After cloning from GitHub and trying to build the solution, I get errors like: 

> Error: The type or namespace name 'NuGet' could not be found (are you missing a using directive or an assembly reference?)

The following directory is empty:   C:\Git\Repos\Squirrel.Windows\vendor\nuget

I used VS2013:
- File - Open - Open from Source Control
- Team Explorer - connect plug symbol
- Clone
  https://github.com/Squirrel/Squirrel.Windows.git

Adding **NuGet.Core** with the package manager seems to help, now it builds.

**Comment by RickZeeland** [comment]
I see now it's better to follow the 'Getting Started Guide', that's a lot more simple !

**Comment by shiftkey** [comment]
This error is because the submodule in `vendor/nuget` was not initialized. To do this, just run this command at the root of the repository:

```
$ git submodule update --init
```
