### ISSUE TITLE
Checking for updates

### ISSUE THREAD

**Issue by SiddharthMalhotra** [Squirrel/Squirrel.Windows#837]
Hello, 

Here is a query that is really troubling us..  (For production installer) 

We are not sure if when checking for updates do all the delta and full nuget packages between say version 50 and version 100 need to be present in the same location folder or does only the delta of v100, full of v100 and RELEASES file which list up to version 100 enough when upgrading from v50 to v100? 

Also, is there a way to generate a single delta package between version 50 and version 100 so that we don't have to copy over all the delta, full packages in between? 

Thank you

**Comment by Andrew-Hanlon** [comment]
I do not believe there is a way to create an aggregate update package.

Squirrel will use the full package if the aggregate size of all of the delta packages is greater than the single full package. 

But, in the case where you potentially have a lot of small delta packages, I would recommend adding your own updater logic that uses the full package when over a certain threshold.

**Comment by SiddharthMalhotra** [comment]
Thank you Andrew. 

Do we have to copy over all the nuget packages (delta and full) between v50 and v100? 
Or will the nuget packages pointing to v100 suffice when upgrading from v50 to v100?

**Comment by paulcbetts** [comment]
You need to copy all of the delta packages, and the latest full package

**Comment by Thieum** [comment]
@shiftkey this has been answered, this can be closed.
