### ISSUE TITLE
Squirrel.Windows Question - Is imperative to use Visual Studio?

### ISSUE THREAD

**Issue by sinosoidal** [Squirrel/Squirrel.Windows#838]
Hi,

I use Qt to build my apps. I want to make use of Squirrel to provide an installer/updater to my windows app. Is imperative to use Visual Studio? Or can I integrate Squirrel without needing it? 

Thanks

**Comment by paulcbetts** [comment]
You don't have to use Visual Studio at all, just package your app as a NuGet package using either the command-line or GUI tools (NuGet Package Explorer), then run Squirrel --releasify.

**Comment by sinosoidal** [comment]
Paul, it might seam easy to you to understand the necessary steps as you have all the knowledge but for me it isn't. I have read the table of contents and there are many steps that I don't know how to complete them even if I had to use VS. I think the documentation is forgetting to contextualize the user explaining why they are doing such steps. I really want to try Squirrel but it is not being easy.

**Comment by macdew** [comment]
I'm in the same boat here - how do we invoke the updater from a C++ application, check for updates etc?

**Comment by paulcbetts** [comment]
> I'm in the same boat here - how do we invoke the updater from a C++ application, check for updates etc?

Invoke the `Update.exe` executable and parse its output / check the exit code. The super easy Get Started version is:

```sh
$GET_THE_DIRECTORY_MY_EXE_IS_RUNNING_IN/../update.exe --update https://myupdateserver.com/path/to/the/__folder__/containing/RELEASES
```

**Comment by macdew** [comment]
Ah, that's excellent.  Thank you for the info!
