### ISSUE TITLE
SquirrelAwareVersion events only

### ISSUE THREAD

**Issue by andreujuanc** [Squirrel/Squirrel.Windows#842]
Hello!

My application works just fine with Squirrel. Im just using UpdateApp. Just works.

But, i wanted to show a welcome screen, and didnt wanted to code it myself and since its already implemented here. So I added the assembly attribute and also handled SquirrelAwareApp HandleEvents(onFirstRun).

There are two issues that bugged me:

1. If I implement SquirrelAwareApp, the others stuff is not working, for example, setting icons, etc. So , Do I need to implement all these default stuff by myself just because i want to handle onFirstRun event?

2. Even if i implement those, somehow after getting the newer files it just gets restarted. 

**Is any simple way to get the events, without implementing all the update process by hand?**

Thanks!

**Comment by paulcbetts** [comment]
> If I implement SquirrelAwareApp, the others stuff is not working, for example, setting icons, etc. So , Do I need to implement all these default stuff by myself just because i want to handle onFirstRun event?

Correct

> Is any simple way to get the events, without implementing all the update process by hand?

Copy paste the default implementation

**Comment by andreujuanc** [comment]
Ok, will do. Thanks.!!
