### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by nullif** [Squirrel/Squirrel.Windows#847]
```
Unhandled exception: System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Squirrel.Update.Program.ProcessStart(String exeName, String arguments, Boolean shouldWait)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
```

**Comment by shiftkey** [comment]
@nullif I'm closing this out as there's missing information to troubleshoot this issue:

 - what version of Squirrel was used
 - what command and arguments were provided when running the program

In the current version of Squrirel there's a log message preceding this that is designed to capture this context:

https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/Update/Program.cs#L499-L504
 
If this is still reproducible on a more recent version of Squirrel, and you can help provide this context, please open a fresh issue.
