### ISSUE TITLE
Is there any guido to show how to integrarte Squirrel on a C++ Windows app not based on VC?

### ISSUE THREAD

**Issue by sinosoidal** [Squirrel/Squirrel.Windows#849]
Hi,

I have recentely found Squirrel but I'm just by reading the tutorial i'm not find a way of integrating it on my app. I developer on Windows via Qt + QtCreator. I don't use Visual Studio at all. 

Many of the steps are C# alike and Visual Studio dependent. Is there any example on how to integrate Squirrel without needing Visual Studio or C#? 

I was already able to build Squirrel for Windows. 

Regards,

Nuno

**Comment by paulcbetts** [comment]
Check out #838
