### ISSUE TITLE
Handle errors - How to - Best practices

### ISSUE THREAD

**Issue by andreujuanc** [Squirrel/Squirrel.Windows#856]
Hello, 

My project gets installed successfully but in some cases it has failed. 

I'm using out of the box Squirrel, without any change.

 1. First issue is about this log, what can be happening there, user tried normal and administrator to install it from zero: http://pastebin.com/rKrH66Su
 2. How to handle that error and others without using SquirrelAware? is it possible?
 3. Is there any example of good implementation of SquirrelAware in case of that being the only way?

Thanks

**Comment by paulcbetts** [comment]
This means the user locked down their LocalAppData somehow, there's not much you can do here :(  If you're not signing your installer, AV could be the culprit
