### ISSUE TITLE
SquirrelAware -> Runs last version while updating

### ISSUE THREAD

**Issue by andreujuanc** [Squirrel/Squirrel.Windows#857]
If I mark it as aware, while the app is updating it runs the last version and then close it.

Example: 
User has v1.1 and 1.0 on folders 
Server has v1.2

When user executes the app it loads 1.1 as it should, but while copying 1.2 it shows an instance of 1.0.

Maybe it also does that without the assembly attribute but is probably quickly or something. With the attribute it really shows the app 1 or 2 seconds before closing it.

Any way to prevent or hide this behaviour?

Is executing the previous version (1.0 in this example) right? or it should be executing 1.1?
Cheers

**Comment by andreujuanc** [comment]
Even if I move my HandleEvents to be the first thing to be executed, it also shows that. It's because in my code i need to wait until I get back from a web service the update path for the UpdateManager to use.

I still dont get the Idea of this projects. I read in ton of places that this is not all automated, right? its the developers' job to implement personalised behaviours. Right. no problem mate, but then why ApplyReleasesImpl is  internal? why do I need the UpdateManager to create shorcuts? 

Do i have to copy paste code just because is internal so I cant use directly? For example: `ApplyReleasesImpl.CreateShortcutsForExecutable`  

If this is a library for us to use, then give us the right tools, if its automated and "just works" then make so. But don't stay both ideas, because as you can see , there are lots of people confused out here.

In this case what you did was just to create extension methods to give us restricted access to classes, which I find not 'polite' if the idea of all this is to let us do our own implementations.

**Comment by paulcbetts** [comment]
> When user executes the app it loads 1.1 as it should, but while copying 1.2 it shows an instance of 1.0.

What does this mean, it "Shows an instance"?

**Comment by zbynek** [comment]
This help file suggests it's intentional that your obsolete .exe runs after install, with --squirrel-obsolete parameter
 https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events-non-cs.md

**Comment by Thieum** [comment]
@andreujuanc did @zbynek comment helped you out with your intial issue?

**Comment by andreujuanc** [comment]
@Thieum Hi, no. After 2017 i removed squirrel :( 
Thanks for the follow up. I forgot to close it after that.
