### ISSUE TITLE
Is it possible to distribute IIS Express?

### ISSUE THREAD

**Issue by UweKeim** [Squirrel/Squirrel.Windows#858]
Currently we are using NSIS to distribute a "local" website:

1. Install IIS Express (admin UAC) if not installed
1. Install my (Web Forms) application files into a local folder
1. Launch a helper application that:
    1. Starts IIS Express pointing to my application's folder
    1. Opens a browser to point to my local IIS URL

**My question:**

Can I use Squirrel to also install IIS Express if not installed?

I.e. I want to do the same as NSIS with Squirrel.

**Comment by paulcbetts** [comment]
Nope, sorry - anything that requires UAC is out the door.

**Comment by UweKeim** [comment]
Just to clarify: The readme.md states:

>  ….NET Framework friendly…

I thought that meant that you install .NET if it is not present.

Since this would mean UAC, I must be wrong, obviously.

Can you please tell me what you mean by saying Squirrel.Windows is ".NET Framework friendly"?
