### ISSUE TITLE
Prevent auto-start after install

### ISSUE THREAD

**Issue by omichelsen** [Squirrel/Squirrel.Windows#859]
I would like to be able to optionally prevent the auto-start after install. This is for testing purposes, so calling the installer with a switch or similar would be perfect.

I tried also tried passing switches through on '--squirrel-firstrun' but it doesn't seem to work.

Any suggestions would be greatly appreciated.

**Comment by paulcbetts** [comment]
The `--silent` switch will do exactly what you're going for

**Comment by zbynek** [comment]
When I do 
`..\Update.exe --silent --update <url>`
it downloads the update and starts the app. Is there a way to make Squirrel only download the update?

**Comment by omichelsen** [comment]
Thank you @paulcbetts that was exactly what I needed (our QE folks also says thanks 👍).
