### ISSUE TITLE
Update Issue :Error: Command failed: 4294967295

### ISSUE THREAD

**Issue by PreDeToR** [Squirrel/Squirrel.Windows#864]
Hi Guys

I seem to be having a really weird issue.
When I try and check for an update, I get the following error in the SquirrelSetup.log

> 2016-10-31 13:54:47> Program: Starting Squirrel Updater: --download http://6.apprelease.cointelvas.co.za/update/win32_x64/1.0.17
> 2016-10-31 13:54:47> Program: Fetching update information, downloading from http://6.apprelease.cointelvas.co.za/update/win32_x64/1.0.17
> 2016-10-31 13:54:47> CheckForUpdateImpl: Using existing staging user ID: b12e2c86-4c4c-592d-b2ba-c96701614f0f
> 2016-10-31 13:54:47> CheckForUpdateImpl: Downloading RELEASES file from http://6.apprelease.cointelvas.co.za/update/win32_x64/1.0.17
> 2016-10-31 13:54:47> FileDownloader: Downloading url: http://6.apprelease.cointelvas.co.za/update/win32_x64/1.0.17/RELEASES?id=JustFlicks&localVersion=1.0.17&arch=amd64
> 2016-10-31 13:54:47> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Filename can either be an absolute HTTP[s] URL, *or* a file name
>    at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Squirrel.ReleaseEntry.ParseReleaseFileAndApplyStaging(String fileContents, Nullable`1 userToken)
>    at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Update.Program.<Download>d__7.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at Squirrel.Update.Program.executeCommandLine(String[] args)
>    at Squirrel.Update.Program.main(String[] args)
> ---> (Inner Exception #0) System.Exception: Filename can either be an absolute HTTP[s] URL, *or* a file name
>    at Squirrel.ReleaseEntry.ParseReleaseEntry(String entry)
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
>    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
>    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
>    at Squirrel.ReleaseEntry.ParseReleaseFileAndApplyStaging(String fileContents, Nullable`1 userToken)
>    at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Squirrel.Update.Program.<Download>d__7.MoveNext()<---
> 

If I download the file manually (http://6.apprelease.cointelvas.co.za/update/win32_x64/1.0.17/RELEASES?id=JustFlicks&localVersion=1.0.17&arch=amd64) 
The content is : 2AF81BA3B42AEA7758B2527DCF3488CBF95B05B1 /download/1.0.17/windows_64/JustFlicks-1.0.17-full.nupkg 58702054

For some reason it always shows the above error in the log files no matter if there is an update or not.

Any Ideas how to fix this?

**Comment by paulcbetts** [comment]
It says right there in the error message,

> Filename can either be an absolute HTTP[s] URL, or a file name

`/download/1.0.17/windows_64/JustFlicks-1.0.17-full.nupkg` is neither of these two things.
