### ISSUE TITLE
Throwing Exceptions in object Finalizers 

### ISSUE THREAD

**Issue by cburman01** [Squirrel/Squirrel.Windows#871]
There are two instances in code where an overridden destructor is throwing an excpetion.  

Case 1: 
https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.cs#L258
```
~UpdateManager()
        {
            if (updateLock != null && !exiting) {
                throw new Exception("You must dispose UpdateManager!");
            }
        }
```

The Problem is there are some scenarios where the destructor runs, but Dispose hasn't been called.

This can easily be tested with the following code: 

>    using (var updateMgr = new UpdateManager("\\path"))
>             {
>                 var updates = await updateMgr.CheckForUpdate();
>                 // Sleep to simulate more work being done 
>                 Thread.Sleep(30000);
>             }

While the thread is sleeping, close the application and squirrel will throw an AbandonedMutexException. 

See: https://msdn.microsoft.com/en-us/library/system.object.finalize(v=vs.110).aspx

> If Finalize or an override of Finalize throws an exception, and the runtime is not hosted by an application that overrides the default policy, the runtime terminates the process and no active try/finally blocks or finalizers are executed. This behavior ensures process integrity if the finalizer cannot free or destroy resources.

Additionally, 
Even if Dipose is called by the consumer, no call `GC.SuppressFinalize(this);` is made and the destructor block is run. (This wont always mean an exception, but there is no need to run the finalizer if Dispose is called from the consumer. 

Anyways...The destructors are basically doing nothing but throwing an exception if the objects hasnt been disposed..But the destructor should attempt to dispose to account for dispose not being called by the consumer (for reasons like above code sample).  

I did find an instance where this destructor is implemented correctly: 
https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/ShellFile.cs#L473

@paulcbetts What are your thoughts? 

Edit Update Line number and added snippet.

**Comment by 2moveit** [comment]
I had the same issue in our app and you test code narrows it down.
I browsed throuh the squirrel code and found this [https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.cs#L169](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/Squirrel/UpdateManager.cs#L169)

**Comment by cburman01** [comment]
@2moveit Yes that Dispose can be used on the updateLock. But I think Its the throw exception on the finalizer. Throwing an exception within a finailzier is always unrecoverable.

http://stackoverflow.com/questions/20358401/throwing-exception-in-finalizer-to-enforce-dispose-calls
There is a nice SO post you can read. Links to the same article in my main post here.

**Comment by cburman01** [comment]
Since this is 5 months old :) Paging @paulcbetts   Any input?

**Comment by paulcbetts** [comment]
This is by-design, it's trying to tell you that you're doing something wrong

**Comment by 2moveit** [comment]
Hi @paulcbetts can you give me a hint in the right direction what I'm doing wrong, please?
I'm using the code from Step 1 Integrating page.
```
using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
{
    await mgr.UpdateApp();
}
```
As this was blocking the start of the UI I started it as a Task for a better UX. I think this is fine, isn't it?
When I start the App and close it immediately when I see the UI then it does throws the mutex exception. The problem is that in production I cannot start the app anymore.
@cburman01 code just reproduce this behaviour by using the CheckForUpdate method and Thread.Sleep so that you can close the app and get the same error.
I'm trying and searching a couple of days now so I would really appreciate some help. Do I miss anything? 
Thx a lot

**Comment by cburman01** [comment]
A call to gc.waitforpendingfinalizers can be used as a workaround. 

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Kai <notifications@github.com> Date: 3/21/17  2:45 PM  (GMT-06:00) To: "Squirrel/Squirrel.Windows" <Squirrel.Windows@noreply.github.com> Cc: cburman01 <cburman01@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [Squirrel/Squirrel.Windows] Throwing Exceptions in object Finalizers (#871) 
Hi @paulcbetts can you give me a hint in the right direction what I'm doing wrong, please?

I'm using the code from Step 1 Integrating page.
using (var mgr = new UpdateManager("C:\\Projects\\MyApp\\Releases"))
{
    await mgr.UpdateApp();
}

As this was blocking the start of the UI I started it as a Task for a better UX. I think this is fine, isn't it?

When I start the App and close it immediately when I see the UI then it does throws the mutex exception. The problem is that in production I cannot start the app anymore.

@cburman01 code just reproduce this behaviour by using the CheckForUpdate method and Thread.Sleep so that you can close the app and get the same error.

I'm trying and searching a couple of days now so I would really appreciate some help. Do I miss anything?

Thx a lot

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Squirrel/Squirrel.Windows","title":"Squirrel/Squirrel.Windows","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Squirrel/Squirrel.Windows"}},"updates":{"snippets":[{"icon":"PERSON","message":"@2moveit in #871: Hi @paulcbetts can you give me a hint in the right direction what I'm doing wrong, please?\r\nI'm using the code from Step 1 Integrating page.\r\n```\r\nusing (var mgr = new UpdateManager(\"C:\\\\Projects\\\\MyApp\\\\Releases\"))\r\n{\r\n    await mgr.UpdateApp();\r\n}\r\n```\r\nAs this was blocking the start of the UI I started it as a Task for a better UX. I think this is fine, isn't it?\r\nWhen I start the App and close it immediately when I see the UI then it does throws the mutex exception. The problem is that in production I cannot start the app anymore.\r\n@cburman01 code just reproduce this behaviour by using the CheckForUpdate method and Thread.Sleep so that you can close the app and get the same error.\r\nI'm trying and searching a couple of days now so I would really appreciate some help. Do I miss anything? \r\nThx a lot"}],"action":{"name":"View Issue","url":"https://github.com/Squirrel/Squirrel.Windows/issues/871#issuecomment-288196426"}}}

**Comment by cburman01** [comment]
Yes, but in C++ this is not a problem. It becomes a problem in .NET because exceptions thrown in finalizers are application terminating. I don't think squirrel should be making the decision on whether our application terminate unexpectedly.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Paul Betts <notifications@github.com> Date: 3/21/17  1:32 PM  (GMT-06:00) To: "Squirrel/Squirrel.Windows" <Squirrel.Windows@noreply.github.com> Cc: cburman01 <cburman01@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Squirrel/Squirrel.Windows] Throwing Exceptions in object Finalizers (#871) 
This is by-design, it's trying to tell you that you're doing something wrong

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Squirrel/Squirrel.Windows","title":"Squirrel/Squirrel.Windows","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Squirrel/Squirrel.Windows"}},"updates":{"snippets":[{"icon":"PERSON","message":"@paulcbetts in #871: This is by-design, it's trying to tell you that you're doing something wrong"}],"action":{"name":"View Issue","url":"https://github.com/Squirrel/Squirrel.Windows/issues/871#issuecomment-288176261"}}}

**Comment by 2moveit** [comment]
> A call to gc.waitforpendingfinalizers can be used as a workaround. 

I tried it in different placed but it did not work. But I found a workaround that seems to work for me.
I tried to dispose the UpdateManager in a finally block manually instead by the using statement. I noticed that it's not beeing called if I exit the app (the main thread).
```
        private UpdateManager mgr;
        private void UpdateApp()
        {
            Task.Run(async () =>
            {
                mgr = new UpdateManager(path);
                try
                {
                    await mgr.UpdateApp();
                }
                finally
                {
                    mgr.Dispose();
                }
            });
        }
```
So I dispose it in the OnExit overload and now I do not get any errors anymore. Now trying it in production.
```
        protected override void OnExit(ExitEventArgs e)
        {
            base.OnExit(e);
            mgr?.Dispose();
        }
```
