### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by featuresnap** [Squirrel/Squirrel.Windows#873]
When using Squirrel Releasify, is there a method of specifying a timestamp url for use when the installer is being digitally signed?

**Comment by ralsu091** [comment]
You can include **/t** {url} when passing -n
For more info:
[https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/docs/using/application-signing.md](url)
