### ISSUE TITLE
McAffee prevents files being installed

### ISSUE THREAD

**Issue by PhilJenson** [Squirrel/Squirrel.Windows#885]
It seems that McAffee prevents an installation form completing, even if running the setup as an Administrator. Some files are installed but I am seeing the setup fail with "System.IO.IOException: Access to the path 'ru' is denied" in the Squirrel log. Disable mcAffee and this installation works fine.

I can't ask customers to disabled virus protection before installing. Is there another solution?

**Comment by celeron533** [comment]
It seem some of your developed program not the Squirrel itself triggered the antivirus.
Maybe you could submit it to McAfee to told them it is a false alarm.

**Comment by hvassbotn** [comment]
https://github.com/Squirrel/Squirrel.Windows/issues/698

**Comment by paulcbetts** [comment]
Sign your application
