### ISSUE TITLE
Regarding Code Style

### ISSUE THREAD

**Issue by Andrew-Hanlon** [Squirrel/Squirrel.Windows#891]
Is there a specific code style in use within this code base? For example is there a resharper (or similar) convention that can be applied?

I want to ensure that pull requests adhere to the codebase, and don't propagate style-only changes.

Thanks.

**Comment by paulcbetts** [comment]
I planned to blog on how to write One True C# Style at some point but never got around to it. Just try your best to match what's there and I'll fix up the rest

**Comment by Andrew-Hanlon** [comment]
Hah -  I'll do my best; though I must admit it is very jarring – Calling it the _'One True C# Style'_ is like calling math rock the _'one true musical genre'_... :wink: Cheers!
