### ISSUE TITLE
Possibility to have multiple shortcuts

### ISSUE THREAD

**Issue by jordyvaneijk** [Squirrel/Squirrel.Windows#893]
Is there the possibility to have multiple shortcuts in your startmenu. I would like to have the normal shortcut to the Update.exe but i also want a shortcut to the update.exe with some extra arguments so i can have something like a Safe Mode

**Comment by shiftkey** [comment]
I'd recommend using the `SquirrelAwareApp` hooks and add code to register your own shortcut:

https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/custom-squirrel-events.md#using-the-squirrelawareapp-helper

You can learn a bit about how Squirrel creates the default shortcuts if you want to emulate it with your own shortcut:

https://github.com/Squirrel/Squirrel.Windows/blob/de5baa93a134ac24fd5bf9172d3e457ac27e0b7a/src/Squirrel/UpdateManager.ApplyReleases.cs#L194
