### ISSUE TITLE
Multiple exe files in installation folder

### ISSUE THREAD

**Issue by filippobottega** [Squirrel/Squirrel.Windows#894]
Hello,
  my application has 3 exe files in installation folder. I have tried to create a squirrel installation but when I run Setup.exe, 3 shortcuts are created and all 3 exe are executed. 
  How can I create only one shortcut and run only one application at the end of the install process?

  Best regards,
    Filippo Bottega.

**Comment by YoCsusuOld** [comment]
I have this mistake in Squirrel.windows 1.5.0, but if I look build Nuget, I see in this : _ExecutionStub.exe (2 files). If i delete this in nuget and launch debug no create some .exe
I have no solution to solve this.

**Comment by YoCsusu** [comment]
I have this mistake in Squirrel.windows 1.5.0, but if I look build Nuget, I see in this : _ExecutionStub.exe (2 files). If i delete this in nuget and launch debug no create some .exe
I have no solution to solve this.

**Comment by chromworks** [comment]
I got the same issue. Is it impossible?

**Comment by paulcbetts** [comment]
Hi please read https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/docs/using/custom-squirrel-events.md

**Comment by Mario-Eis** [comment]
I read the article and call SquirrelAwareApp like

```
SquirrelAwareApp.HandleEvents(
    onInitialInstall: v => updater.CreateShortcutForThisExe(),
    onAppUpdate: v => updater.CreateShortcutForThisExe(),
    onAppUninstall: v => updater.RemoveShortcutForThisExe()
);
```

Unfortunately I still do get multiple EXE shortcuts on my desktop.

Used version is 1.5.1
