### ISSUE TITLE
Do I need to restart the application after applying updates?

### ISSUE THREAD

**Issue by chris-colima** [Squirrel/Squirrel.Windows#895]
Hi,

I found the file [goals.md](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/goals.md) that states: 
* Updates should be able to be applied while the application is running.
* At no time should the user ever be forced to stop what he or she is doing.

So I tried installing the updates and letting the user decide when to restart the application. But when working with the application after applying the update, e.g. opening another window, I get a System.IO.FileNotFoundException for an assembly referenced by the application. 

Otherwise, everything works fine. The new version is started when using the link in the Startmenu.

Is it possible to have a working application after applying updates or do I need to restart first?

**Comment by TyBarthel** [comment]
You will have to restart.  You can see in your %appdata%\local\<yourappname> the new folder for the new version which contains your binaries.  Compare that to your running program by checking the location using something like task manager and you'll see it's running in a different directory than your updated version.

**Comment by chris-colima** [comment]
Thanks for your reply. I am aware that I have to restart the application in order to use the updated version. But is it still possible to delay the restart after applying the update and let the user decide when to restart?

**Comment by TyBarthel** [comment]
Oh yeah, you can delay the restart until whenever.  There's nothing forcing you to restart right away.  I'm not sure why you received the error you did, but I'm willing to guess it's independent of Squirrel.

**Comment by chris-colima** [comment]
Thank you for this statement that encouraged me to try finding the cause of this exception. I found out that the update process deletes the assembly in question from the folder of the currently running version. (Also, it creates the .dead file in the same folder.)

As a result, when calling a method using this assembly in the application after updating, it will throw the FileNotFoundException while .NET is trying to load it into memory.

I can prevent this Exception by calling this method before starting the update in order to load the assembly in memory. This time, the assembly will not deleted from the current application's folder by the updater.

So I guess the question is: How can I prevent Squirrel from deleting any files from the current version's folder until the application is restarted?

**Comment by gojanpaolo** [comment]
@chris-colima Squirrel doesn't delete the current version's folder (and the immediately previous version). See docs https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/update-process.md#update-process

>6. Previous Version Clean-up - on the next startup of MyApp, all but current and immediately previous version of your app are deleted as part of clean up (e.g., after updating to app-1.0.5, app-1.0.4 will remain, but app-1.0.3 and before will be deleted - see issue #589)

Please let us know if you have any other questions or if we could close this issue :)

**Comment by shiftkey** [comment]
@gojanpaolo @chris-colima closing this out as by-design, but if you encounter something strange in this area please open a fresh issue and fill out the template.
