### ISSUE TITLE
Version number in the Control Panel does not change after an update

### ISSUE THREAD

**Issue by chris-colima** [Squirrel/Squirrel.Windows#896]
Hi,

is there a way to change the version number of the application that is displayed in the "Programs and Features" control panel to the new version after an update has been applied? Currently, it always shows the version number of the initial release.

**Comment by Thieum** [comment]
@shiftkey works fine with the current version, this can be closed.

**Comment by TiagoBrazSantos** [comment]
I have the same problem in version 1.9.1.0. I am using "ApplyReleases" to apply the update, the application itself is successfully updated but the version that is displayed in Control Panel is still the same.
