### ISSUE TITLE
Join the Squirrel Chat Room

### ISSUE THREAD

**Issue by anaisbetts** [Squirrel/Squirrel.Windows#9]
If you're interested in Squirrel.Windows.Next and want to get involved, the best way is via joining our Slack room on the topic:

![](http://cl.ly/image/2z2m1v3B032y/content#png)
### Getting In

Email paul@paulbetts.org with the Email address you'd like to join up with and I can send you an invite

**Comment by jweinstein** [comment]
Is this channel still active? Wagon engineers would love to join!

**Comment by shiftkey** [comment]
@anaisbetts is this still a thing? I think I've still got the admin bit to be able to invite people, and I think this could be a bit more prominent in the repository to help bring peeps together...

**Comment by peters** [comment]
@shiftkey I have a cross-platform drop in replacement of squirrel that supports Windows and Linux. It has offline and a web installer as well. It uses myget (any nuget server v2/v3) is supported. This way you never have to store any packages locally. It also supports channels in the same way chrome does (think Canary etc). I have been planning to open source it for a while but haven’t had the time to write up the docs. If you want to contribute that I will release it under the MIT license.

**Comment by peters** [comment]
Oh btw, its production ready as its used commercially in our company products.

**Comment by shiftkey** [comment]
@peters for the moment I'd like to focus on Squirrel.Windows because there's a lot of existing usage of it that depends on ongoing maintenance work.

**Comment by peters** [comment]
@shiftkey That’s fair!  ☺️ But if you find the time let me know because feature wise its basically a clone except its written from scratch and has 400+ unit tests.

**Comment by windwalker1963** [comment]
Been a ham radio inthuseth sense 13 years. Began the PC years later no I usually try to incorporate those hobbies in consideration of the other @times.hope to chat later with u guys. Thank u windwalker_sc@yahoo.com kd4azb don

**Comment by windwalker1963** [comment]
Hello!! Is their anybody out thare??🤔

**Comment by robmen** [comment]
With the advent of GitHub Discussions, we have a public forum that is also internet searchable. Feel free to discuss Squirrel there.
