### ISSUE TITLE
No hook to run custom script during Uninstall operation

### ISSUE THREAD

**Issue by ferzkopp** [Squirrel/Squirrel.Windows#901]
It is often necessary to clean up registry settings or files created by an application during an uninstall. Currently Squirrel documentation does not mention uninstall, and as far as I can tell from the code there does not seem to be an option for such an operation.

Feature request: enable specifying a command (cmd line) to run during uninstall.

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/14d6dc1599676a9d83daba60e73507d12b73164d/src/Squirrel/SquirrelAwareApp.cs#L44

It's a hook just like the other operations
