### ISSUE TITLE
Signing fails when using Squirrel called from deploy.ps1 out of Octopus Deploy

### ISSUE THREAD

**Issue by Franklin89** [Squirrel/Squirrel.Windows#903]
I am creating a Squirrel installer from Octopus Deploy in the deploy.ps1. Everything is working great. I added the _-n_ parameter with all the required things as shown in the wiki. When running the script my self it works but when called from Octopus Deploy I get the following error:

`System.AggregateException: One or more errors occurred. ---> System.Exception: Failed to sign, command invoked was: 'C:\OctopusTentacle\Applications\Test\Tridoo.Client\1.5.0-automate-deploym0026\tools\Squirrel\signtool.exe sign /a /f C:\Temp\PersonalCodeSigningCertificate.pfx /p ******** /fd sha256 /tr http://timestamp.digicert.com /td sha256`

Any Idea what the problem could be?

**Comment by jackjwilliams** [comment]
Are you using the Squirrel.exe --releasify command? What is the exact command you are using? Here is an excerpt from my deploy.ps1 (note, it is using poshBAR's Exec):

``` powershell
# invoke the releasification
    Exec {
        Squirrel.exe --releasify "$currentDir\website\MyClient$environment.$version.nupkg" `
                     -r "$appFilePath\$environment\Releases" `
                     -setupIcon "$currentDir\website\MyClient.ico" `
                     -icon "$currentDir\website\MyClient.ico" `
                     -n "/a /f $currentDir\$($es.certificates.codeSigning.name).pfx /p $($es.certificates.codeSigning.password)"
    } -retry 2
```

**Comment by Franklin89** [comment]
@jackjwilliams Thanks for getting back to me.

My call to _Squirrel.exe_ looks just the same as yours. I then changed the _logon user_ for the Octopus Tentacle service from _SYSTEM_ to local _Administrator_ and now it works. But I don't really like having my Services running under Administrator so I need to figure something out there.

Any hint from your side? What user are you using?

**Comment by rgl** [comment]
@Franklin89 do you realize that SYSTEM has more privileges than Administrator?

**Comment by jackjwilliams** [comment]
Also, it looks like it's a signing issue, my bet would be on some junk in either your private, public or password field in one of your environments.xml. Maybe you didn't copy/paste the public / private key in correctly (or you hit "enter" when pasting). I wouldn't think it's a service user issue.

**Comment by Franklin89** [comment]
@rgl Yeah I know that thanks...still dont like my services running with the _Administrator_ account.

@jackjwilliams True, it does look like a singing issue. Evironments.xml? That sounds like _poshBAR_ and not like squirrel.windows...I am not using _poshBAR_

But since this is a signing issue and not really a squirrel.windows issue I will close this...

Thanks for the help...

**Comment by jackjwilliams** [comment]
Oh yes, sorry that is poshBAR specific. Look closer at how you are building your certs.
