### ISSUE TITLE
How to start Squirrel-powered app from command line?

### ISSUE THREAD

**Issue by borekb** [Squirrel/Squirrel.Windows#906]
I'm using an Electron app, [Caret](https://caret.io/), that is installed and updated using Squirrel. I'd like to open it from the command line (and automate this by saving it into a batch file) but I can't figure out how to do it without the knowledge of a specific version.

Their installer creates a taskbar icon with this:

```
C:\Users\Borek\AppData\Local\Caret\Update.exe --processStart Caret.exe
```

However, that works only thanks to this being in "start in":

```
C:\Users\Borek\AppData\Local\Caret\app-1.11.3
```

![image](https://cloud.githubusercontent.com/assets/101152/21296288/a14f5706-c568-11e6-8910-5d817532aa44.png)

I cannot afford to hardcode the application version into the batch file, and running `C:\Users\Borek\AppData\Local\Caret\Update.exe --processStart Caret.exe` from a folder other than the specific version number does nothing.

How can I start a Squirrel-powered app from command line, from any working directory?

**Comment by paulcbetts** [comment]
Hm, "start in" shouldn't matter, are you sure that this is the case?

**Comment by borekb** [comment]
You're right, it was because the content of my batch file was cached.

So is this the correct way to call Squirrelized app, instead of plan `Caret.exe file.md`?

```
"%localappdata%\Caret\Update.exe" --processStart Caret.exe --process-start-args file.md
```

**Comment by paulcbetts** [comment]
Once Caret updates their Squirrel.Windows it'll just be `"%localappdata%\Caret\Caret.exe`, but your args work too

**Comment by borekb** [comment]
Oh, I'm not familiar with Squirrel at all but if I could call Caret just like any other app, that would be great. This `Update.exe --processStart Caret.exe` felt a bit weird.

I'll point the developers here. Thank you!
