### ISSUE TITLE
Atom like windows installer using Squirrel.Windows.

### ISSUE THREAD

**Issue by abuhenasobuj** [Squirrel/Squirrel.Windows#907]
Does anyone here to help me integrate [Atom](https://github.com/atom/atom) like windows installer for my existing C# project with Visual Studio.
I followed simple doc to integrate Squirrel Installer but can't get exact result what I want.

I'll be glad if anyone from here tech me to create an windows installer same as Atom installer for Windows with Auto Update.

**Comment by Franklin89** [comment]
What problems are you running into?

**Comment by abuhenasobuj** [comment]
Hello @Franklin89, 
Thanks for your reply.

**Do you have any best example that used Squirrel.Windows framework?** With server-side auto update, Install processing splash screen like Atom etc. 
![screenshot_2016 12 20_18h24m57s_002](https://cloud.githubusercontent.com/assets/16954436/21350503/dbfa535e-c6e1-11e6-9b13-7a19be48a830.png)

**Comment by Franklin89** [comment]
@abuhenasobuj Go check out these two blog posts: [Post 1](https://gregorsuttie.com/2015/04/27/squirrel-replace-clickonce-the-easy-way/) from @gsuttie and [Post 2](https://chaseflorell.github.io/devops/2015/08/07/deploying-squirrel.windows-apps-with-octopus-deploy/) from @ChaseFlorell

They should help you get started. The Splahscreen is nothing more than a GIF that can be added as a parameter to the releasify process...

**Comment by abuhenasobuj** [comment]
@Franklin89 Sir, thanks again.
I think @gsuttie post easy to understand. Will try soon to implement this thing. 

**What's the parameter to show an GIF during installation?**

**Comment by abuhenasobuj** [comment]
I releasify a setup file. But when I double click `setup.exe` I got this error message screen.
![screenshot_2016 12 20_20h52m02s_006](https://cloud.githubusercontent.com/assets/16954436/21355047/bcab91a6-c6f6-11e6-8d81-2ee8d145eda6.png)

**Comment by Franklin89** [comment]
Then i suppose something went wrong during the packaging.

Make sure your application files are inside _lib/net45_ of the nuspec.

**Comment by abuhenasobuj** [comment]
It was my wrong, I used different squirrel version instead my `package` > `squirrel.windows`.

**Can I show an GIF file during installation process in small apps?**

**Comment by Franklin89** [comment]
I dont think that is possible. And why block the user?

The splash screen is there in case your installer takes a long time to install. So why block the user with a splash screen for 10 seconds before installing? By then the user could already use your app.

Having a small simple app and installing it in seconds is the best thing you can get :-)

**Comment by Thieum** [comment]
@shiftkey original question has been answered, this can be closed.
