### ISSUE TITLE
'Squirrel.UpdateManager.GitHubUpdateManager' is not defined.

### ISSUE THREAD

**Issue by chromworks** [Squirrel/Squirrel.Windows#909]
Local update works perfectly for my VB project.
But I cannot use GibHubUpdateManager with this error. Tested on both VS2015 and VS2017. Same error.

   BC30002	Type 'Squirrel.UpdateManager.GitHubUpdateManager' is not defined.

Can anyone know how to around this problem?

**Comment by chromworks** [comment]
It seems all methods in UpdateManager are not visible when VB project. Only 'Release' class is visible.
I suspect it's been never tested with VB.net. 
I wonder if anyone can confirm....

**Comment by shiftkey** [comment]
This crude example builds for me on VS2017:

```vb
Imports Squirrel

Module Module1

    Sub Main()
        Update().Wait()
    End Sub

    Async Function Update() As Task
        Using manager = Await UpdateManager.GitHubUpdateManager("https://github.com/shiftkey/my-cool-app")
            Await manager.UpdateApp()
        End Using
    End Function

End Module
```

**Comment by coderocks** [comment]
It compiles but it throws at runtime:
This exception was originally thrown at this call stack:
	Microsoft.VisualBasic.CompilerServices.Symbols.Container.GetMembers(ref string, bool)
	Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateGet(object, System.Type, string, object[], string[], System.Type[], bool[])
	Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(object, System.Type, string, object[], string[], System.Type[], bool[])
    Dispatch.My.MyApplication.ApplicationUpdater() in ApplicationEvents.vb
