### ISSUE TITLE
GitHub Update Manager not Working

### ISSUE THREAD

**Issue by TonyValenti** [Squirrel/Squirrel.Windows#911]
Hi All,
I'm trying to make an my appp update from GitHub but I'm getting errors.  The code I'm using is:
````
                using (var UpdateManager = Squirrel.UpdateManager.GitHubUpdateManager("https://github.com/TonyValenti/Clio.WebDav")) {

                    using (var res = UpdateManager.Result)
                    {

                        var UpdateNeeded = res.CheckForUpdate().Result;
                       

                    }
                }

````

When "UpdateNeeded" gets called, I get the following exception:
"The request was aborted: The connection was closed unexpectedly."

Using Fiddler, I see that the following URLs are being queried:
This URL returns correctly:
https://api.github.com/repos/TonyValenti/Clio.WebDav/releases

The following URLs are then queried four times each and each time they 404:
https://github.com/TonyValenti/Clio.WebDav/releases/download/1.1.6196.14495/RELEASES
https://github.com/tonyvalenti/clio.webdav/releases/download/1.1.6196.14495/releases

Is Squirrel using an old URL somewhere in the GitHub updater?

Please help!

Thanks!

**Comment by paulcbetts** [comment]
You didn't upload the RELEASES file

**Comment by TonyValenti** [comment]
Oh, I'm supposed to have an actual file called releases?

**Comment by paulcbetts** [comment]
Ya

**Comment by TonyValenti** [comment]
Is there a sample GitHub app that I can look at so I can figure out the format of this file and stuff?

**Comment by paulcbetts** [comment]
The file is created when you do --releasify, you just have to upload it

**Comment by TonyValenti** [comment]
squirrel --releasify=C:\Users\Administrator\SOURCE\Repos\Clio.WebDav\Clio.WebDav.Windows\bin\Clio.WebDav.Windows.1.0.0.0.Release.x86.nupkg

squirrel : System.ArgumentException: '86' is not a valid version string.

Am I doing something wrong here?

**Comment by TonyValenti** [comment]
I'm using the "CreateNewNugetPackage" script btw.

**Comment by ralsu091** [comment]
try 
`squirrel --releasify=C:\Users\Administrator\SOURCE\Repos\Clio.WebDav\Clio.WebDav.Windows\bin\Clio.WebDav.Windows.1.0.0.nupkg`

**Comment by bbougot** [comment]
Same thing here. Every files inside Releases folder have been uploaded to a new release of a private Github repository, and I get "The request was aborted: The connection was closed unexpectedly." from DownloadFile method inside FileDownloader class. 
The url is https://github.com/blacknut/waterfall/releases/download/1.0.1.0/RELEASES?id=Blacknut&localVersion=1.0.1.0&arch=amd64.
My managed is constructed as follow 

```
using (var mgr = await UpdateManager.GitHubUpdateManager(Constants.GithubRepositoryUrl,
                    accessToken: Constants.GithubAccessToken))
{
}
```

with GithubAccessToken an access token which have "repo" authorization.

**Comment by stajs** [comment]
From memory, the access token was only used to avoid GitHub API rate limits when checking for updates. I don't think it was ever tested for private repo access. The 404 is GitHubs way of saying you are unauthenticated.

**Comment by paulcbetts** [comment]
@ruromgar You cannot use Squirrel to update against a private repo, correct. Either use S3 or create a repo `MyApp-Releases` for this purpose

**Comment by bddckr** [comment]
All files in the `Releases` directory. See the first step 4 here: https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/amazon-s3.md

**Comment by clauderoy790** [comment]
> @ruromgar You cannot use Squirrel to update against a private repo, correct. Either use S3 or create a repo `MyApp-Releases` for this purpose

I was having the same problem, working perfectly with a public repo but I'm going to implement your solution to create a repo with the release. That is so 5head, I would not have thought about that actually :D Thanks for your help and have an outstanding day :)
