### ISSUE TITLE
GitHubUpdateManager with No Network

### ISSUE THREAD

**Issue by TonyValenti** [Squirrel/Squirrel.Windows#913]
Hi All,
What is the correct way for me to handle installation processes and such when I am using the GitHubUpdateManager and no network is present.  Here's my code:
````
        public static UpdateManager CreateUpdateManager() {
            UpdateManager ret = null;
            try
            {
                ret = Squirrel.UpdateManager.GitHubUpdateManager("https://github.com/TonyValenti/Clio.WebDav").Result;
            } catch {

            }

            return ret;
        }
````
````
 public static class Installer {

        public static void Process() {
///My manager will be null sometimes!    
        using (var mgr = Updater.CreateUpdateManager())
            {

                // Note, in most of these scenarios, the app exits after this method
                // completes!
                SquirrelAwareApp.HandleEvents(
                  onInitialInstall: v => DoInitialInstall(mgr),
                  onAppUpdate: v => DoAppUpdate(mgr),
                  onAppUninstall: v => DoAppUninstall(mgr),
                  onFirstRun: () => { });
            }
        }
}
````

**Comment by imZEH** [comment]
Hello,

How about before running those code check the internet first.

Here some code to check the internet.

        [DllImport("wininet.dll")]
        private extern static bool InternetGetConnectedState(out int description, int reservedValue);

        public bool IsInternetAvailable()
        {
            int description;
            return InternetGetConnectedState(out description, 0);
        }


hope that might help you.

**Comment by shiftkey** [comment]
I think being defensive when instantiating the `UpdateManager` is the safest approach, as `GitHubUpdateManager` does invoke `HttpClient` (which might fail even if no network issue was detected by the user before doing this).
