### ISSUE TITLE
App crashes on startup if there were 4 groups of digits in assembly version

### ISSUE THREAD

**Issue by IgorVM** [Squirrel/Squirrel.Windows#917]
I used 1.0.0.0 in AssemblyVersion and in the name of nuget package. 
My app is installed successfully and can be executed from the version folder without any problem, updates work as expected.
But when I am trying to launch the app from the shortcut created by Squirrel it causes the app to launch the process and close it immediately and any window isn't shown.

Is it how it should work and only 3 groups of digits are allowed or is it a bug?

**Comment by joelweiss** [comment]
See #892

**Comment by shiftkey** [comment]
> Is it how it should work and only 3 groups of digits are allowed or is it a bug?

Closing this out as `wonfix` because semver doesn't support four groups of digits like this.
