### ISSUE TITLE
Couldn't write out staging user ID

### ISSUE THREAD

**Issue by Mario-Eis** [Squirrel/Squirrel.Windows#918]
Basically the installation seems fine and the application also starts up directly after the setup process. But afterwards, the created shortcuts on the desktop don't work. Also starting the EXE stubs from the local app directory don't start up the application. Just nothing seems to happen. No message at all. Starting up the application directly from inside the app-0.0.0.1 directory (bypassing the stub) works great. So there is no issue with the application itself.

The windows event log shows the following error for the application stub:

> Faulting application name: NativeAppHost.exe, version: 0.0.0.1, time stamp: 0x585040c7
> Faulting module name: NativeAppHost.exe, version: 0.0.0.1, time stamp: 0x585040c7
> Exception code: 0xc0000409
> Fault offset: 0x0000f686
> Faulting process id: 0x329c
> Faulting application start time: 0x01d268eb3e12339f
> Faulting application path: C:\Users\Mario\AppData\Local\ToolConfigurator\NativeAppHost.exe
> Faulting module path: C:\Users\Mario\AppData\Local\ToolConfigurator\NativeAppHost.exe
> Report Id: f1fc86db-1187-4a28-9889-78d7d65dbaf2
> Faulting package full name: 
> Faulting package-relative application ID: 

And the setup log holds the following information:

> 2017-01-07 14:53:23> Program: Starting Squirrel Updater: --install .
> 2017-01-07 14:53:23> Program: Starting install, writing to C:\Users\Mario\AppData\Local\SquirrelTemp
> 2017-01-07 14:53:23> Program: About to install to: C:\Users\Mario\AppData\Local\ToolConfigurator
> 2017-01-07 14:53:23> Program: Install path C:\Users\Mario\AppData\Local\ToolConfigurator already exists, burning it to the ground
> 2017-01-07 14:53:24> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Mario\AppData\Local\ToolConfigurator\packages\.betaId'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
>    at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
>    at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
>    at System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
>    at Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
> 2017-01-07 14:53:24> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Mario\AppData\Local\ToolConfigurator\packages\RELEASES'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
>    at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
> 2017-01-07 14:53:24> CheckForUpdateImpl: Reading RELEASES file from C:\Users\Mario\AppData\Local\SquirrelTemp
> 2017-01-07 14:53:24> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
> 2017-01-07 14:53:24> ApplyReleasesImpl: Writing files to app directory: C:\Users\Mario\AppData\Local\ToolConfigurator\app-0.0.0.1
> 2017-01-07 14:53:24> LogHost: Rigging execution stub for lib/net45/CefSharp.BrowserSubprocess_ExecutionStub.exe to C:\Users\Mario\AppData\Local\ToolConfigurator\CefSharp.BrowserSubprocess.exe
> 2017-01-07 14:53:24> LogHost: Rigging execution stub for lib/net45/NativeAppHost_ExecutionStub.exe to C:\Users\Mario\AppData\Local\ToolConfigurator\NativeAppHost.exe
> 2017-01-07 14:53:25> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\Mario\AppData\Local\ToolConfigurator\app-0.0.0.1\NativeAppHost.exe]
> 2017-01-07 14:53:25> ApplyReleasesImpl: Starting fixPinnedExecutables
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Creative Console Launcher.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Cygwin64 Terminal.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: IntelliJ IDEA 2016.3.1(64).lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Mozilla Firefox.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Remote Desktop Connection.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Skype.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: SourceTree.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: Visual Studio 2017 RC.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Examining Pin: VPN Access Manager.lnk
> 2017-01-07 14:53:25> ApplyReleasesImpl: Fixing up tray icons
> 2017-01-07 14:53:25> ApplyReleasesImpl: cleanDeadVersions: for version 0.0.0.1
> 2017-01-07 14:53:25> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-0.0.0.1

I tried to get rid of the "Couldn't write out staging user ID" problem. But I did not succeed. Disabled anti virus, cleared the temp directory, signed the application as stated in the docs, tried to run setup as administrator and in win8 compatibility mode. "Couldn't write out staging user ID" still there, application unable to start after the first initial run (only when bypassing the stub).

**Comment by Mario-Eis** [comment]
Update: The issue that the application wont start up when using the stub was related to https://github.com/Squirrel/Squirrel.Windows/issues/917
As the AssemblyVersion always gives 4 digit version numbers, there are issues when packaging the MsBuild target way. 

The "Couldn't write out staging user ID" sadly is still in my setup log.

**Comment by alexlee85** [comment]
I've also meet this problem.
not every machine happen this problem, some machine will happen this problem.

**Comment by lukeskinner** [comment]
Seeing the same error with 1.5.1 - Couldn't write out staging user ID, this user probably shouldn't get beta anything. Tested on 4 pcs and they all get the same error.

The versioned .exe in \AppData\Local\MyApp\app-1.0.1 also seems to be the stub instead of the application. Its 200kb and I'm expecting it to be 5MB. This also causes it find 0 squirrel enabled apps as the original .exe is not in the installation. 

I've tried following https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/debugging-installs.md on both Update.exe and on the app.exe but it doesn't do anything, presumably because the actual application .exe is not there.

I'll do some more digging, otherwise we will have to remain on 1.4.5.

**Comment by lukeskinner** [comment]
Debugging the code in ```UpdateManager.CheckForUpdates.cs```, at the end of the ```getOrCreateStagedUserId``` method. It does a ```File.WriteAllText(stagedUserIdFile, ret.ToString(), Encoding.UTF8);``` to create the \AppData\Local\iCRM\packages\.betaId file. 

At this point the packages folder does not exist. Adding in a call to create the packages directory fixes this, it finishes the install and the shortcuts all work. I'm not sure if that's a legitimate fix or just fixing a symptom of another problem.

**Comment by lukeskinner** [comment]
Found the real issue in our scenario, we have a duplicate .exe in a nested folder in the squirrel package. Squirrel ends up creating 2 stubs, one for the root level .exe and one for the nested .exe. The nested .exe stub is then placed into the app-x.x.x version folder causing the installation to only have stub .exes. 

Removing the nested duplicate .exe fixes the staging user ID error. Hopefully this helps others with this error. Maybe Squirrel could detect this during the releasify phase?

**Comment by simquad** [comment]
Thanks Luke; massively helpful tip and location to take a look at.

Resolved my issues.

**Comment by Thieum** [comment]
@shiftkey issue fixed, this can be closed.
