### ISSUE TITLE
Shorcut Target Is Wrong

### ISSUE THREAD

**Issue by leandroribeiro** [Squirrel/Squirrel.Windows#920]
Hey guys,

The shortcut target is wrong, instead of C:\Users\kbailey\AppData\Local\MyApp\Update.exe --processStart MyApp.exe is created C:\Users\kbailey\AppData\Local\MyApp\MyApp.exe.

Then this shortcut created doesnt works. =\

**Comment by aaababei** [comment]
This is intended. The behaviour was changed a while ago. More details in PR #868

**Comment by leandroribeiro** [comment]
Right, but after this change the shortcut doesn't works and crash my application before run it.

My temporary fix was to get back to 1.4.4 version.

**Comment by gregsdennis** [comment]
I may be experiencing this as well.  Please see [my question on SO](http://stackoverflow.com/questions/43128867/squirrel-app-throws-stackoverflowexception-exception-code-0xc0000409) and see if you're experiencing the same thing.

**Comment by gregsdennis** [comment]
Confirmed that reverting to v1.4.4 fixed the issue.

**Comment by PushOrigin** [comment]
Is there any resolution to this? I am migrating our app from 1.4.4 to 1.7.5 and when it updates the shortcut points to appname.exe in the root folder but the stub is never copied there. The appname_ExecutionStub.exe remains in the app-x.x.x directory. It appears that that is the only step that is  missed. If I copy and rename the execution stub the shortcut works fine.

If I uninstall and install the new version it works fine so it only appears to be a problem on updates. Am I missing something on upgrading Squirrel beyond 1.4.4? Or am I looking at reinstalling on each desktop?

**Comment by PhilJenson** [comment]
Please see #1075 for a solution

**Comment by Thieum** [comment]
@shiftkey duplicate of #1075 , which has more information than this issue. I would close this one in favor of #1075

**Comment by shiftkey** [comment]
Closing this out in favour of #1075
