### ISSUE TITLE
Stub crashes after extracting update

### ISSUE THREAD

**Issue by TimvdEijnden** [Squirrel/Squirrel.Windows#923]
Our electron app (build with electron-builder) downloads an update and extracts it. 
This happens in the background, but on Windows 7 the user get's a message about a crash. But it's actually the downloaded update that triggered the crash. The Electron app just keeps working, if I restart the application it's correctly updated. For example i've updated from version 1.3.1-demonl to version 1.3.2-demonl. We use the demonl for different environment and language, this way we can test our application with different environments stages of our website. 

This issue didn't exist when using Squirrel.Windows version 1.4.5 

We're using the following version:
* Squirrel.Windows: 1.5.1
* Electron: 1.4.13
* Electron Builder: 10.9.2 (we've also tried the latest version 11.2.1)

The following file crashed: **Gynzy Desktop NL_ExecutionStub.exe**

![crash](https://cloud.githubusercontent.com/assets/951290/21840027/56a210ba-d7db-11e6-8978-a78a81830125.png)

The files in crash details:
[WER4E30.tmp.appcompat.txt](https://github.com/Squirrel/Squirrel.Windows/files/698229/WER4E30.tmp.appcompat.txt)
[WER4E60.tmp.WERDataCollectionFailure.txt](https://github.com/Squirrel/Squirrel.Windows/files/698228/WER4E60.tmp.WERDataCollectionFailure.txt)
[WER78F.tmp.WERInternalMetadata.xml.txt](https://github.com/Squirrel/Squirrel.Windows/files/698236/WER78F.tmp.WERInternalMetadata.xml.txt)

**Comment by paulcbetts** [comment]
electron-builder isn't supported, sorry - can you reproduce this with electron-winstaller? electron-builder forks / replaces several Squirrel.Windows components

**Comment by paulcbetts** [comment]
Superficially, this does seem to work, if I rename `app-2.3.1` in Slack to `app-2.3.1-demonl`, the stub does run the executable, at least on Win10. There's nothing in the stub that is Win10-specific either, it's very boring Win32 C++ code

**Comment by TimvdEijnden** [comment]
Could you also try this on Windows 7 to see if that works?

**Comment by paulcbetts** [comment]
@TimvdEijnden No, but you could! Just install Slack then rename `%LocalAppData%\Slack\app-2.4.1` to `%LocalAppData%\Slack\app-2.4.1-demonl` and then try to run `%LocalAppData%\Slack\slack.exe`. If you get an Electron error, it worked

**Comment by develar** [comment]
@TimvdEijnden After https://github.com/Squirrel/Squirrel.Windows/issues/892#issuecomment-271810710 I think it is worth to provide directory listing of `%LocalAppData%\yourApp` on win 7 and 10.

**Comment by TimvdEijnden** [comment]
@paulcbetts 

I'll try that, but the issue occurs if there's a new version available and the nuget package is extracted. So i'll need slack 1.4.0. If I'll install that version then I will rename it to app-1.4.0-demonl and then update the app so see if the error occurs. But I can't find a older version of slack.


@develar Here's windows 7

```
C:\Users\IEUser\AppData\Local\gynzy_desktop_nl>dir
 Volume in drive C has no label.
 Volume Serial Number is E0CE-337D

 Directory of C:\Users\IEUser\AppData\Local\gynzy_desktop_nl

01/10/2017  02:26 PM    <DIR>          .
01/10/2017  02:26 PM    <DIR>          ..
01/10/2017  01:59 PM    <DIR>          app-1.3.1-demonl
01/10/2017  02:26 PM    <DIR>          app-1.3.2-demonl
01/10/2017  01:57 PM           110,173 app.ico
01/10/2017  02:26 PM    <DIR>          packages
01/10/2017  02:26 PM            13,783 SquirrelSetup.log
11/01/2016  08:13 AM         1,529,832 Update.exe
               3 File(s)      1,653,788 bytes
               5 Dir(s)  121,403,990,016 bytes free
```

And here's windows 10

```
C:\Users\Tony\AppData\Local\gynzy_desktop_nl>dir
Volume in drive C is BOOTCAMP
Volume Serial Number is 0AB6-45C0

Directory of C:\Users\Tony\AppData\Local\gynzy_desktop_nl

01/11/2017  10:22 AM    <DIR>          .
01/11/2017  10:22 AM    <DIR>          ..
01/11/2017  10:19 AM    <DIR>          app-1.3.1-demonl
01/11/2017  10:22 AM    <DIR>          app-1.3.2-demonl
01/11/2017  10:18 AM           110,173 app.ico
01/11/2017  10:22 AM           357,888 Gynzy Desktop NL.exe
01/11/2017  10:22 AM    <DIR>          packages
01/11/2017  10:22 AM             8,571 SquirrelSetup.log
01/10/2017  11:17 AM         1,532,904 Update.exe
              4 File(s)      2,009,536 bytes
              5 Dir(s)  24,422,522,880 bytes free
```

It seems the Gynzy Desktop NL.exe is missing in the Windows 7 version, perhaps because the process crashed?
