### ISSUE TITLE
Possible issue with version numbers being used in install directory

### ISSUE THREAD

**Issue by GeertvanHorrik** [Squirrel/Squirrel.Windows#93]
When I install this nuget version:

MyProduct-1.7.0-unstable0036-full.nupkg

That has NuGet version 1.7.0-unstable0036, it is installed as:

app-1.7.0

That menas that I can never update to a new version because it will also pick 1.7.0. Why is the -unstable0036 removed from the path?

**Comment by joaomoreno** [comment]
I would like to see this happen.

**Comment by DanPristupov** [comment]
Same here. I'd like to use prerelease numbers in Squirrel too.

**Comment by GeertvanHorrik** [comment]
Can you explain why you closed this one?

**Comment by paulcbetts** [comment]
@GeertvanHorrik Mostly to discourage the Me Toos

**Comment by joaomoreno** [comment]
That just discourages the support of the project.
