### ISSUE TITLE
bootstrapperEXE usage

### ISSUE THREAD

**Issue by ghost** [Squirrel/Squirrel.Windows#934]
I would like to create a custom bootstrapper to include .NET 4.5.2 Framework instead of downloading it.
Could I have some guide lines about creating custom bootstrapper?

**Comment by shiftkey** [comment]
I don't think we've got support for this, and I don't think it's planned, but you can currently indicate what framework version your app needs using the `--framework-version` parameter - this helps when apps work against later versions of .NET that the user might not have:

```
      --framework-version=VALUE
                             Set the required .NET framework version, e.g.
                               net461
```
