### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by muffmolch** [Squirrel/Squirrel.Windows#936]
I really like Squirrel. It simply makes isntallation and update purposes easy!

But since the version bumpto 1.5.0 and the problems with the 4 digit version numbers I would appreciate to have some  release notes :-)

**Comment by muffmolch** [comment]
Last days the updatig cycle ist about one minor release every five days, without any comments. I would really appreciate some notes (I even cannot see any big changes in the commit sections..)

**Comment by paulcbetts** [comment]
All of the release notes are in https://github.com/Squirrel/Squirrel.Windows/releases, where are you looking for them?

**Comment by muffmolch** [comment]
Sorry about that. I just didn't see that page (I'm just a poor mecurial user ;-) )
Perfect!
