### ISSUE TITLE
Uninstall Application

### ISSUE THREAD

**Issue by imZEH** [Squirrel/Squirrel.Windows#941]
I try to generate an installer using this command
"Squirrel --releasify filename.1.0.0.nupkg -g CHLOELoader.gif --no-msi"
it was generate three files namely (RELEASES, *.nupkg, Setup).
Try to install by running Setup, it looks fine but when try to uninstall the application it won't uninstall the application from Control panel. 

What should I do to remove it ?
Any help is much appreciated.

Thank you.

**Comment by siemandelc** [comment]
What was your solution to this issue?
