### ISSUE TITLE
ExecutableStubForExe and console app

### ISSUE THREAD

**Issue by CodeFunta** [Squirrel/Squirrel.Windows#945]
HI, it seems to be that for a install package with console app stubs are not created, so shortcuts are also broken. I've investigated the code and found that Releasify method use Utility.ExecutableUsesWin32Subsystem call (and inside code return subSystem == 2; /*IMAGE_SUBSYSTEM_WINDOWS_GUI*/) but for console app the subSystem == 3. So is it by design or bug? :)

**Comment by paulcbetts** [comment]
This is by-design, the executable stubs are Win32 Subsystem applications (you can only _either_ be a Win32 app or a console app, not both).

**Comment by CodeFunta** [comment]
Ok, thx for your comment

**Comment by sopelt** [comment]
I have an additional question related to this issue and #1098 .
@paulcbetts - is there any inherent/design reason why execution stubs are not generated for command line apps? In a project having two WPF apps as well as a command line app (for automating/scheduling tasks) we would love to have stubs for the command line EXE as well.

Has anyone else come forward with that use-case?

Is this something you would accept as a PR?

Thank you.

**Comment by paulcbetts** [comment]
@sopelt It's possible but I just didn't implement it yet since it was more of a pain in the ass (i.e. you need to pipe stdin/stdout properly). I would actually instead of using EXEs would try to create a `.cmd` stub that did the same thing

**Comment by sopelt** [comment]
Thank you for the swift reply @paulcbetts ... That sounds like a resonable approach. I wouldn't want to be the one implementing semver in batch/cmd though ;)
So I guess we could just use squirrel aware handlers and update/generate the cmd file on update ... or update.exe could do that lookup?

I will go ahead and see how generating the cmd in a squirrel event works out. Having this as an out of the box feature could still be nice though ... if there is demand for it.

**Comment by RonaldZaZ** [comment]
+1! 
At the moment I'm using a very very ugly workaround where I've written a stub myself, include it in a resource file, on update/install write the stub to the parent folder after doing some version checks.

I have a console app for the very same reason as @sopelt
