### ISSUE TITLE
Issues converting to using SemVer

### ISSUE THREAD

**Issue by DenisPitcher** [Squirrel/Squirrel.Windows#947]
I ran into an issue I thought worth documenting for others.

When trying to switch from traditional visual studio versioning to SemVer I ran into an issue.  I kept getting messages like these when trying to run squirrel --releasify

squirrel : System.ArgumentException: '0.1.0-ci.1228' is not a valid version string.
At line:1 char:1

I kept trying to change the version on my project to something simple like 0.1.0 and it still wouldn't work.

After digging through everything I could I realized that the prior failed nuget files had actually been written to the destination directory.  These files were being read as part of the releasify operation and failing regardless of what my current version was.

A fix is to delete these failed versions from the destination directory.

**Comment by nickelbob** [comment]
Hi @DenisPitcher,

I'm having the same issue and it's not clear what you mean by the "destination directory". Is that the releases folder? Do you know which files in particular?
