### ISSUE TITLE
Create multiple shortcuts for same executable

### ISSUE THREAD

**Issue by scionwest** [Squirrel/Squirrel.Windows#950]
I need to create multiple shortcuts for the same executable in my app. An example would be having the `App.exe` as a shortcut to run the app, and `App.exe --diagnostic` to run diagnostic stuff.

I #399 where you reference calling `GetShortcutsForExecutable` to create a custom `ShellLink` item, but I'm not sure what to do with that `ShellLink` once I've configured it. There aren't any methods that accept one. Do I have to reproduce all of the code in the `CreateShortcutsForExecutable` method? There are Types in use within that method that aren't exposed outside of the assembly for others to use (such as `Utility`). I'm trying to avoid bringing over a ton of your code into my project - I'll have to maintain changes between yours and mine then as bugs are found/fixed.

What is the guidance on this?

Thanks

**Comment by paulcbetts** [comment]
@scionwest Edit it the way you like, then call "Save" on it

**Comment by scionwest** [comment]
Thanks, I've not been able to try this yet but I will def try this approach and followup if i have any issues.
