### ISSUE TITLE
How to change update host without deleting settings file

### ISSUE THREAD

**Issue by JoshuaKrstic** [Squirrel/Squirrel.Windows#952]
I currently have an app that is having updating trouble because the squirrel settings.json file is not being updated. 

My old app pointed to an ip host for its updates. Squirrel had no problem fetching these updates. Along the line the server moved to a different IP address. How can I push a change to update the 'update host' property in the settings.json file? 

Is a manual delete of the file required to change update hosts?

**Comment by paulcbetts** [comment]
Squirrel.Windows doesn't have a settings.json, I'm not sure where you're finding this from
