### ISSUE TITLE
Support for FTP

### ISSUE THREAD

**Issue by floatas** [Squirrel/Squirrel.Windows#956]
There was an issue with FTP #805  with comment that FTP is not supported. Is there any specific reason why it's not supported\implemented ?

I slapped together FTP support in my branch.

I'm building installers on build server. Agents don't have previous builds, so I also added support to pull needed files (RELEASES, nupkg) from ftp/http in order to build delta packages.

So I'm not sure if I should invest time into code cleanup\refactoring, I could make a pull request.
 
Thanks,
Šarūnas

**Comment by baconbrad** [comment]
What would be an advantage of using FTP as the download endpoint opposed to HTTPS?

**Comment by paulcbetts** [comment]
FTP is not supported and won't be, sorry. Please please please use a secure protocol aka HTTPS for updates.
