### ISSUE TITLE
RELEASES File

### ISSUE THREAD

**Issue by imZEH** [Squirrel/Squirrel.Windows#958]
What is the purpse of RELEASE File ? 
Sorry newbie here

Is it possble when I have a new release clear all content inside the RELEASE file ang generate new one ?

Thank You.

**Comment by floatas** [comment]
1. When you releasify this file is used to get last full version, which is used to generate delta package for updates. If RELEASE file is missing during releasify only full installer will be created and RELEASE file will contain one row.

2. When you update, RELEASE file is used to find latest version files (either -delta.nupkg or -full.nupkg).

Before releasify, clean Release folder and new RELEASE file will be generated.

**Comment by imZEH** [comment]
Thank you. :) ok got it.

**Comment by paulcbetts** [comment]
The RELEASES file is a thing that Squirrel can read that's very small, in order to see if there are updates, without downloading the entire update

**Comment by DavidBrower** [comment]
@floatas 
> Before releasify, clean Release folder and new RELEASE file will be generated.

Do you mean delete the contents of the release directory before executing `squirrel --releasify`?
