### ISSUE TITLE
Delta patching fails when some deltas are missing.

### ISSUE THREAD

**Issue by peppy** [Squirrel/Squirrel.Windows#959]
I have written a deploy script which keeps the last five deltas, while removing all previous (it will be faster to manually patch in such cases).

Currently, if a user is more than `available deltas` behind, squirrel will still assume it can apply the deltas and then fail on application of the first one:

![image](https://cloud.githubusercontent.com/assets/191335/23149877/70a3f3b2-f832-11e6-874f-58433cfd6215.png)

My update code is currently run as such (pretty standard, i believe) using a `GitHubUpdateManager`:

```
var info = await updateManager.CheckForUpdate();
await updateManager.DownloadReleases(info.ReleasesToApply, (int p) => Schedule(() => n.Progress = p / 100f));
await updateManager.ApplyReleases(info, (int p) => Schedule(() => n.Progress = p / 100f));
```

You can see this happening in my [deployed build](https://github.com/ppy/osu/releases/download/v2017.213.0/install.exe). Note that I pushed the latest release with only one delta available just to help debug this problem.

I know I can "fix" this myself by modifying the ReleasesToApply list in my own code, but believe it may be better to gracefully handle this in squirrel itself (a hard crash isn't something we ever want to see in an update process. My proposed behaviour would be to fallback to the full download if *any* delta fails to apply.

**Comment by paulcbetts** [comment]
You should never see a hard crash due to delta updates, it will always fall back to the full download if deltas fail

**Comment by peppy** [comment]
As I said above, it isn't currently doing so. The exception being thrown (`Win32Exception`) is not being caught anywhere in the Squirrel call stack, so it ends up arriving at my user code.

async Task<ReleaseEntry> createFullPackagesFromDeltas(IEnumerable<ReleaseEntry> releasesToApply, ReleaseEntry currentVersion)
![image](https://cloud.githubusercontent.com/assets/191335/23150693/ad4ce23c-f838-11e6-8db9-6b0c7ce71c36.png)

This is where the exception rises to in the squirrel libraries (this is the function I am calling). Can you point me in the direction of the fallback code if I'm somehow missing it?

**Comment by paulcbetts** [comment]
https://github.com/Squirrel/Squirrel.Windows/blob/04cfe501cdde77e66bd3e26cc0f04f81da3a63fc/src/Update/Program.cs#L243

Looks like if you're calling it in your own code, you probably need to mimic this behavior

**Comment by peppy** [comment]
Aha, right. That's exactly what I've resorted to doing.

I would still propose for squirrel to throw custom exceptions in cases like this so a consumer that *is* calling the `ApplyReleases` method manually can be better informed as to what has gone wrong (something as general as `DeltaPatchingFailedException` would be a good start). Catching `Exception` is generally not a good idea after all.

Let me know if you agree with this direction and I'll look at PRing some changes.

**Comment by paulcbetts** [comment]
>  Catching Exception is generally not a good idea after all.

I disagree here, because literally for _any reason_, if delta patching fails, we want to retry with deltas disabled

**Comment by peppy** [comment]
Fair enough (although it did take me a while to figure what was going wrong due to the nondescript `Win32Exception`, so it may still be worth adding a custom exception *even if* yous till catch everything). 

Thanks for the help!
