### ISSUE TITLE
SquirrelAwareApp events do not trigger events when the application is enabled for UAC

### ISSUE THREAD

**Issue by nikhilsgadre** [Squirrel/Squirrel.Windows#960]
My Application (c#) requires to register a service during the installation time. So I added requestexecutionlevel in app.manifest. 
<requestedExecutionLevel  level="requireAdministrator" uiAccess="false" />

Depending on the application installation state I want to decide if a service needs to be installed or not. So I added following code in applaunch code. I do not these messagebox when the execution level is set to requireAdministrator, however if I turn the setting to asInvoker then these messagebox do show up. 

Any idea why this is happening and how to get pass this problem?

------------------------------------------------------------ 
SquirrelAwareApp.HandleEvents(
                    onAppUpdate: OnAppUpdate,
                    onAppUninstall: OnAppUninstall,
                    onInitialInstall: OnInitialInstall);

public static void OnAppUpdate(Version version)
        {
            // Could use this to do stuff here too.
            MessageBox.Show("OnAppUpdate do something");

        }

        public static void OnInitialInstall(Version version)
        {
            MessageBox.Show("OnInitialInstall do something");
        }

        public static void OnAppUninstall(Version version)
        {
            MessageBox.Show("uninstalling now do something");
        }
------------------------------------------------------------

**Comment by ralsu091** [comment]
I don't think the scope of Squirrel covers user elevation. See https://github.com/Squirrel/Squirrel.Windows/issues/20#issuecomment-56914508

**Comment by paulcbetts** [comment]
You cannot elevate in Squirrel.Windows installers, sorry!
