### ISSUE TITLE
Version ID Messed Up - WPF(VS2017 RC)

### ISSUE THREAD

**Issue by CDAGaming** [Squirrel/Squirrel.Windows#962]
I updated my app to V1.0.0.1(On accident and it gave me an error to fix it (Semver Version format) so i "fix" it by putting it on V1.1.0, but the error still shows up:

"Squirrel : System.Exception: Your package version is currently 1.0.0.1, which is *not* SemVer-compatible, 
change this to be a SemVer version number"

Both the Nugat Package and the vs project are on V1.1.0

**Comment by ngvanmy** [comment]
i have similar error, can you fixed it?

**Comment by CDAGaming** [comment]
Closing in 24 hours :)

**Comment by paulcbetts** [comment]
Remove the entry from the RELEASES file
