### ISSUE TITLE
Reference to Splat.1.6.2

### ISSUE THREAD

**Issue by MickaelRizzello** [Squirrel/Squirrel.Windows#970]
Hello,

I have an issue with visual studio when i try to add a new object as new datasource.  (by this way : https://msdn.microsoft.com/en-us/library/8s2t4x15.aspx).

When the wizard list all assembly from my project i  got "An unexpected error has occured."
"Error Message: Could not load file or assembly 'Splat, Version=1.6.20, Culture................."
I m not certain but the problem seems come from the fact you build Squirel with Splat version 1.6.2.0, but initially nuget took the version 2.0 of Splat when i have downloaded Squirrel.
I can fix the problem with downgrade the nuget Splat on my project to version 1.6.2.0 but is it possible to fix the problem with the next release?

Thanks.

**Comment by Thieum** [comment]
duplicate from #897 - requesting an update of splat from 1.6.2 to 2.0.0

**Comment by shiftkey** [comment]
Closing this out in favour of #897
