### ISSUE TITLE
SignTool password masking fails with special characters

### ISSUE THREAD

**Issue by markgould** [Squirrel/Squirrel.Windows#974]
The password masking implemented in #861 fails if the password contains a special character. 

For example a password of 1@234567 will show in the logs as ********@234567

**Comment by shiftkey** [comment]
@markgould I'd take a PR to improve this regex to capture anything that looks like text

https://github.com/Squirrel/Squirrel.Windows/blob/47de3b608269adb3a08ada732bf25d0148679ab5/src/Update/Program.cs#L621-L623
