### ISSUE TITLE
initial install fails as if it's already installed

### ISSUE THREAD

**Issue by userjeff3** [Squirrel/Squirrel.Windows#975]
The attached install log says the application already exists and so tries to "burn it to the ground" by deleting the directory, which then generates an "access denied" error. But that directory didn't exist when I started the install.
[SquirrelSetup.zip](https://github.com/Squirrel/Squirrel.Windows/files/856338/SquirrelSetup.zip)

**Comment by userjeff3** [comment]
I tripped across the problem myself. Releasify is being run from a TFS release task. For convenience, I was throwing all of the squirrel tools in with the application code being packaged. Separating the two into different artifacts solved it.

**Comment by Thieum** [comment]
@shiftkey problem solved, this can be closed.
