### ISSUE TITLE
Please help me with createShortcut option

### ISSUE THREAD

**Issue by haiduong87** [Squirrel/Squirrel.Windows#978]
Hi,
When I use this command:
PM> PATH_TO_SQUIRREL\squirrel --releasify BIN_PATH\MyApp.2.0.33404.nupkg --no-msi
It runs fine
But my solution has more than once exe file, so I try to use this command:
PM> PATH_TO_SQUIRREL\squirrel --releasify BIN_PATH\MyApp.2.0.33404.nupkg --no-msi --createShortcut  MyApp.exe
It gives me error: 
PATH_TO_SQUIRREL\squirrel : System.IO.DirectoryNotFoundException: Could not find a part of the path 'PATH_TO_SQUIRREL\packages\RELEASES'.

Please help me

Thanks a lot

**Comment by haiduong87** [comment]
Or please help me to create a setup file that will create shortcut for only one exe file in the package.
For example: my package contains 3 exe files: myApp.exe, myAppReport.exe, helper.exe. I want only myApp.exe will be created shortcut when setup on client machine.

**Comment by Thieum** [comment]
@haiduong87 consider making MyApp squirrel aware as documented [here](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/custom-squirrel-events.md) 

It this fixes your issue, you can close this.

**Comment by shiftkey** [comment]
Closing this out as `SquirrelAware` is the recommended way to get a shortcut for each executable after install.
