### ISSUE TITLE
install location truncated from nuspec ID

### ISSUE THREAD

**Issue by userjeff3** [Squirrel/Squirrel.Windows#994]
The MS package [spec](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#choosing-a-unique-package-identifier-and-setting-the-version-number) recommends using dot notation for the nuspec ID tag. But when I releasify (v. 1.5.2), the install location becomes "users/me/appdata/local/ABC" even though the ID is "ABC.QA". The workaround is to simply drop the ".". I hope this saves someone else the time it took me to debug.

**Comment by ralsu091** [comment]
This is mentioned in Squirrel docs:https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/naming.md

**Comment by schh** [comment]
Is this by design or is this getting fixed so folder install names supports dots?

**Comment by Thieum** [comment]
@shiftkey duplicates #283 , this can be closed.
