### ISSUE TITLE
What's the best way to make our Squirrel 1.5.2 application single-instance?

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#997]
Hello,

We're using Squirrel **1.5.2** and we're trying to make it single-instance. What's the best way to accomplish this?

Thanks in advance.

**Comment by Thieum** [comment]
@SissiKonsta did @JKSnd solution helped you? if so, you can close this issue.

**Comment by shiftkey** [comment]
Closing this out as this feature is outside the scope of Squirrel. Thanks for the suggested link @JKSnd!
