### ISSUE TITLE
Pinning in Squirrel 1.5.2 doesn't work as it should

### ISSUE THREAD

**Issue by SissiKonsta** [Squirrel/Squirrel.Windows#998]
Hello,

We're using Squirrel 1.5.2 and the pinning doesn't work as it should. After running the application, we pin the taskbar icon but it points to the .exe file that exists inside the version folder (e.g. inside the app-1.0.0 folder) and not the other one like the Desktop shortcut does. The pinning works only if we pin the application from the Start-up menu. How can we resolve this issue?

Thanks in advance.

**Comment by vgregor** [comment]
Same here. I can confirm  that version 1.5.2 has bug, as descibed by @SissiKonsta.

**Comment by SissiKonsta** [comment]
Is there any update regarding this issue? Please note that this is very important and urgent for us.

Thanks in advance.

**Comment by paulcbetts** [comment]
It's fine that the pin points to the interior version, Squirrel.Windows will fix up the pin shortcuts on upgrade

**Comment by SlavaChristin** [comment]
Paul, is that planned?
do you have another issue for tracking?

**Comment by paulcbetts** [comment]
No, it's already done

**Comment by markmcdowell** [comment]
I've been testing this and there does seem to be an issue.

Steps:
Run the application
Pin to the taskbar (from the icon in the taskbar)
Upgrade
You now get 2 icons (1 pinned and 1 running application)

Clicking the pinned icon does launch the new version but you always have 2 icons in the taskbar now.
