### ISSUE TITLE
which *.exe to launch specifically？How to mark a Squirrel-aware! 

### ISSUE THREAD

**Issue by wuscier** [Squirrel/Squirrel.Windows#999]
My setup.exe contains multiple *.exe. After I clicked setup.exe to install, it said installation has failed. But all the files have been copied to the AppData\Local folder successfully. It just didn't seem to know which exe to launch.

**Comment by lukeskinner** [comment]
When it says the installation has failed it should give you an option to view the log. Alternatively you can find the log at C:\Users\username\AppData\Local\SquirrelTemp\SquirrelSetup.log changing username to the users name. Go to the bottom of the log, and copy/paste the last install attempt here. The actual error should be in here.

Check out this page https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/custom-squirrel-events.md for more info on configuring which .exes startup automatically.
 
>When none of the apps in your package are "Squirrel-Aware", Squirrel does some things on your behalf to make your life easier, the primary one being that every EXE in your app package automatically gets a shortcut on both the Desktop and the Start Menu. Once you enable Squirrel events for even a single EXE file, you must do this yourself.

The above statement for shortcuts also applies to what .exes it will automatically launch.

**Comment by wuscier** [comment]
That's helpful. Thanks. I'll try make my app a "Squirrel-Aware". 👍  I think Squirrel is better than NSIS for me.

**Comment by Thieum** [comment]
@wuscier did the doc about custom squirrel events helped you fix your issue? If so, you can close the issue.

**Comment by Thieum** [comment]
@shiftkey question answered, this can be closed.
